Repository tangle-network/dapp, pull requests merged in 2022-09, with the labels that each got.

#539 New Typography Component
  packages/apps/package.json
  packages/apps/postcss.config.js
  packages/react-components/src/AppBar/AppBar.tsx
  packages/webb-ui-components/package.json
  packages/webb-ui-components/src/css/layer-base.css
  packages/webb-ui-components/src/css/layer-components.css
  packages/webb-ui-components/src/css/radix-ui.css
  packages/webb-ui-components/src/css/typography.css
  packages/webb-ui-components/src/fonts/BreezeSans-Bold.ttf
  packages/webb-ui-components/src/fonts/BreezeSans-Medium.ttf
  packages/webb-ui-components/src/fonts/BreezeSans-Regular.ttf
  packages/webb-ui-components/src/fonts/Cousine-Bold.ttf
  packages/webb-ui-components/src/fonts/Cousine-Regular.ttf
  packages/webb-ui-components/src/tailwind.css
  packages/webb-ui-components/src/typography/Typography/Typography.tsx
  packages/webb-ui-components/src/typography/Typography/index.ts
  packages/webb-ui-components/src/typography/index.ts
  packages/webb-ui-components/src/typography/types.d.ts
  packages/webb-ui-components/src/typography/utils/index.ts
  yarn.lock
Labels: approved ✅

#540 New Logo Component
  packages/react-components/src/Sidebar/index.tsx
  packages/webb-ui-components/src/components/Logo/Logo.tsx
  packages/webb-ui-components/src/components/Logo/index.ts
  packages/webb-ui-components/src/components/Logo/types.d.ts
  packages/webb-ui-components/src/components/index.ts
  packages/webb-ui-components/src/icons/create-icon.tsx
Labels: needs review 👓

#541 New Avatar Component
  packages/webb-ui-components/package.json
  packages/webb-ui-components/src/components/Avatar/Avatar.tsx
  packages/webb-ui-components/src/components/Avatar/index.ts
  packages/webb-ui-components/src/components/Avatar/types.d.ts
  packages/webb-ui-components/src/components/AvatarGroup/AvatarGroup.tsx
  packages/webb-ui-components/src/components/AvatarGroup/index.ts
  packages/webb-ui-components/src/components/AvatarGroup/types.d.ts
  packages/webb-ui-components/src/components/index.ts
  yarn.lock
Labels: needs review 👓

#543 New Button Component
  packages/apps/webpack.base.js
  packages/webb-ui-components/src/components/Avatar/types.d.ts
  packages/webb-ui-components/src/components/AvatarGroup/types.d.ts
  packages/webb-ui-components/src/components/Button/Button.tsx
  packages/webb-ui-components/src/components/Button/ButtonSpinner.tsx
  packages/webb-ui-components/src/components/Button/index.ts
  packages/webb-ui-components/src/components/Button/types.d.ts
  packages/webb-ui-components/src/components/Button/utils.ts
  packages/webb-ui-components/src/components/index.ts
  packages/webb-ui-components/src/icons/Spinner.tsx
  packages/webb-ui-components/src/icons/index.ts
  packages/webb-ui-components/src/icons/types.d.ts
  packages/webb-ui-components/src/types/index.d.ts
  packages/webb-ui-components/src/typography/types.d.ts
Labels: needs review 👓

#544 New Chip component
  packages/webb-ui-components/src/components/Chip/Chip.tsx
  packages/webb-ui-components/src/components/Chip/index.ts
  packages/webb-ui-components/src/components/Chip/types.d.ts
  packages/webb-ui-components/src/components/Chip/utils.ts
  packages/webb-ui-components/src/components/index.ts
  packages/webb-ui-components/src/types/index.d.ts
Labels: needs review 👓

#546 New Input Component
  packages/mixer/src/Mixer.tsx
  packages/webb-ui-components/src/components/Input/Input.tsx
  packages/webb-ui-components/src/components/Input/index.ts
  packages/webb-ui-components/src/components/Input/types.d.ts
  packages/webb-ui-components/src/components/index.ts
  packages/webb-ui-components/src/css/layer-base.css
Labels: needs review 👓

#535 Fetch fixtures from AWS instead of IPFS for Reliability
  package.json
  packages/api-providers/package.json
  packages/api-providers/src/chains/chain-id.enum.ts
  packages/api-providers/src/ipfs/evm/anchors.ts
  packages/api-providers/src/utils/storage.ts
  packages/api-providers/src/web3/vanchor-deposit.ts
  packages/api-providers/src/web3/vanchor-withdraw.ts
  packages/apps/package.json
  packages/apps/src/App.tsx
  packages/apps/src/configs/anchors/anchor-config.ts
  packages/apps/src/configs/chains/evm/index.ts
  packages/apps/src/configs/currencies/currency-config.ts
  packages/apps/webpack.base.js
  packages/apps/webpack.dev.js
  packages/mixer/package.json
  packages/page-mixer/package.json
  packages/react-components/package.json
  packages/react-environment/package.json
  packages/react-hooks/package.json
  packages/vbridge/package.json
  yarn.lock
Labels: needs review 👓

#547 New DropdownMenu component
  packages/mixer/src/Mixer.tsx
  packages/ui-components/src/styles/global.tsx
  packages/webb-ui-components/src/components/Button/Button.tsx
  packages/webb-ui-components/src/components/Button/types.d.ts
  packages/webb-ui-components/src/components/Button/use-button-props.ts
  packages/webb-ui-components/src/components/DropdownMenu/DropdownMenu.tsx
  packages/webb-ui-components/src/components/DropdownMenu/index.ts
  packages/webb-ui-components/src/components/DropdownMenu/types.d.ts
  packages/webb-ui-components/src/components/MenuItem/MenuItem.tsx
  packages/webb-ui-components/src/components/MenuItem/index.ts
  packages/webb-ui-components/src/components/MenuItem/types.d.ts
  packages/webb-ui-components/src/components/index.ts
  packages/webb-ui-components/src/icons/CheckboxFill.tsx
  packages/webb-ui-components/src/icons/Filter.tsx
Labels: wip 🚧

#549 New `Slider` Component
  packages/mixer/src/Mixer.tsx
  packages/ui-components/src/styles/global.tsx
  packages/webb-ui-components/package.json
  packages/webb-ui-components/src/components/Slider/Slider.tsx
  packages/webb-ui-components/src/components/Slider/index.ts
  packages/webb-ui-components/src/components/Slider/types.d.ts
  packages/webb-ui-components/src/components/index.ts
  yarn.lock
Labels: needs review 👓

#552 Add `Tooltip` Component
  packages/mixer/src/Mixer.tsx
  packages/webb-ui-components/package.json
  packages/webb-ui-components/src/components/Button/utils.ts
  packages/webb-ui-components/src/components/Chip/Chip.tsx
  packages/webb-ui-components/src/components/Tooltip/Tooltip.tsx
  packages/webb-ui-components/src/components/Tooltip/index.ts
  packages/webb-ui-components/src/components/Tooltip/types.d.ts
  packages/webb-ui-components/src/components/index.ts
  yarn.lock
Labels: needs review 👓

#553 New `Progress` component
  packages/mixer/src/Mixer.tsx
  packages/webb-ui-components/package.json
  packages/webb-ui-components/src/components/Progress/Progress.tsx
  packages/webb-ui-components/src/components/Progress/index.ts
  packages/webb-ui-components/src/components/Progress/types.d.ts
  packages/webb-ui-components/src/components/Tooltip/Tooltip.tsx
  packages/webb-ui-components/src/components/index.ts
  yarn.lock
Labels: needs changes 🔧, needs review 👓

#542 Integrate Graphql API for stats page
  .graphqlconfig
  codegen.yml
  graphql.schema.json
  package.json
  packages/api-providers/package.json
  packages/api-providers/src/abstracts/relayer/types.ts
  packages/api-providers/src/contracts/wrappers/webb-vanchor.ts
  packages/api-providers/src/polkadot/vanchor-deposit.ts
  packages/api-providers/src/polkadot/vanchor-withdraw.ts
  packages/api-providers/src/utils/retry-promise.ts
  packages/api-providers/src/web3/vanchor-withdraw.ts
  packages/apps/package.json
  packages/mixer/package.json
  packages/page-claims/package.json
  packages/page-crowdloan/package.json
  packages/page-governance/package.json
  packages/page-governance/src/ProposalDetail/VotersTable/VotersTable.tsx
  packages/page-mixer/package.json
  packages/page-statistics/package.json
  packages/page-statistics/src/AuthoritiesData.tsx
  packages/page-statistics/src/DKGStatistics/DKGStatistics.tsx
  packages/page-statistics/src/generated/graphql.tsx
  packages/page-statistics/src/gql/proposal-counters.graphql
  packages/page-statistics/src/gql/proposals.graphql
  packages/page-statistics/src/gql/public-keys.graphql
  packages/page-statistics/src/gql/sessions.graphql
  packages/page-statistics/src/index.tsx
  packages/react-components/package.json
  packages/react-environment/package.json
  packages/react-hooks/package.json
  packages/ui-components/package.json
  packages/ui-components/src/Inputs/NoteInput/MixerNoteInput.tsx
  packages/utils/src/retry-promise.ts
  packages/vbridge/package.json
  schema.graphql
  scripts/update-webb-tools-packages.js
  yarn.lock
Labels: needs review 👓

#557 Key Status Card Component
  packages/mixer/src/Mixer.tsx
  packages/webb-ui-components/package.json
  packages/webb-ui-components/src/components/Button/Button.tsx
  packages/webb-ui-components/src/components/Button/utils.ts
  packages/webb-ui-components/src/components/Card/Card.tsx
  packages/webb-ui-components/src/components/Card/index.ts
  packages/webb-ui-components/src/components/Card/types.d.ts
  packages/webb-ui-components/src/components/Chip/utils.ts
  packages/webb-ui-components/src/components/DropdownMenu/DropdownMenu.tsx
  packages/webb-ui-components/src/components/KeyStatusCard/KeyStatusCard.tsx
  packages/webb-ui-components/src/components/KeyStatusCard/index.ts
  packages/webb-ui-components/src/components/KeyStatusCard/types.d.ts
  packages/webb-ui-components/src/components/KeyStatusCard/useKeyStatusSeedData.ts
  packages/webb-ui-components/src/components/KeyValueWithButton/KeyValueWithButton.tsx
  packages/webb-ui-components/src/components/KeyValueWithButton/index.ts
  packages/webb-ui-components/src/components/KeyValueWithButton/types.d.ts
  packages/webb-ui-components/src/components/Label/Label.tsx
  packages/webb-ui-components/src/components/Label/index.ts
  packages/webb-ui-components/src/components/Label/types.d.ts
  packages/webb-ui-components/src/components/LabelWithValue/LabelWithValue.tsx
  packages/webb-ui-components/src/components/LabelWithValue/index.ts
  packages/webb-ui-components/src/components/LabelWithValue/types.d.ts
  packages/webb-ui-components/src/components/Progress/types.d.ts
  packages/webb-ui-components/src/components/TimeProgress/TimeProgress.tsx
  packages/webb-ui-components/src/components/TimeProgress/index.ts
  packages/webb-ui-components/src/components/TimeProgress/types.d.ts
  packages/webb-ui-components/src/components/TitleWithInfo/TitleWithInfo.tsx
  packages/webb-ui-components/src/components/TitleWithInfo/index.ts
  packages/webb-ui-components/src/components/TitleWithInfo/types.d.ts
  packages/webb-ui-components/src/components/Tooltip/Tooltip.tsx
  packages/webb-ui-components/src/components/Tooltip/types.d.ts
  packages/webb-ui-components/src/components/index.ts
  packages/webb-ui-components/src/css/layer-base.css
  packages/webb-ui-components/src/hooks/index.ts
  packages/webb-ui-components/src/hooks/useCopyable.ts
  packages/webb-ui-components/src/icons/InformationLine.tsx
  packages/webb-ui-components/src/typography/Typography/Typography.tsx
  packages/webb-ui-components/src/typography/utils/index.ts
  packages/webb-ui-components/src/utils/calculateDateProgress.ts
  packages/webb-ui-components/src/utils/formatDateToUtc.tsx
  packages/webb-ui-components/src/utils/index.ts
  packages/webb-ui-components/src/utils/shortenHex.ts
  yarn.lock
Labels: needs review 👓

#551 NoteAccount as separate page
  package.json
  packages/api-providers/package.json
  packages/api-providers/src/abstracts/anchor/vanchor-actions.ts
  packages/api-providers/src/abstracts/webb-provider.interface.ts
  packages/api-providers/src/contracts/wrappers/webb-vanchor.ts
  packages/api-providers/src/ipfs/evm/anchors.ts
  packages/api-providers/src/polkadot/mixer-deposit.ts
  packages/api-providers/src/polkadot/vanchor-actions.ts
  packages/api-providers/src/polkadot/vanchor-deposit.ts
  packages/api-providers/src/polkadot/vanchor-withdraw.ts
  packages/api-providers/src/polkadot/webb-provider.ts
  packages/api-providers/src/utils/retry-promise.ts
  packages/api-providers/src/web3/vanchor-actions.ts
  packages/api-providers/src/web3/vanchor-deposit.ts
  packages/api-providers/src/web3/vanchor-withdraw.ts
  packages/api-providers/src/web3/webb-provider.ts
  packages/apps/src/router-config.tsx
  packages/mixer/src/hooks/note/index.ts
  packages/page-note-account/README.md
  packages/page-note-account/package.json
  packages/page-note-account/src/index.tsx
  packages/react-components/src/AppBar/AppBar.tsx
  packages/react-components/src/NoteAccount/ChainNotesList.tsx
  packages/react-components/src/NoteAccount/NoteAccount.tsx
  packages/react-components/src/NoteAccount/NoteAccountButton.tsx
  packages/react-components/src/NoteAccount/NoteAccountDetails.tsx
  packages/react-components/src/NoteDisplay/ItemNoteDisplay.tsx
  packages/react-environment/src/WebbProvider.tsx
  packages/react-environment/src/webb-context/webb-context.ts
  packages/react-hooks/src/useNoteAccount.ts
  packages/ui-components/src/Inputs/MixerGroupSelect/MixerGroupSelect.tsx
  packages/vbridge/src/components/Deposit/Deposit.tsx
  tsconfig.paths.json
  yarn.lock
Labels: needs review 👓

#558 New Threshold and Key Card
  packages/mixer/src/Mixer.tsx
  packages/webb-ui-components/src/components/CopyWithTooltip/CopyWithTooltip.tsx
  packages/webb-ui-components/src/components/CopyWithTooltip/index.ts
  packages/webb-ui-components/src/components/CopyWithTooltip/types.d.ts
  packages/webb-ui-components/src/components/KeyCard/KeyCard.tsx
  packages/webb-ui-components/src/components/KeyCard/index.ts
  packages/webb-ui-components/src/components/KeyCard/types.d.ts
  packages/webb-ui-components/src/components/KeyStatusCard/KeyStatusCard.tsx
  packages/webb-ui-components/src/components/KeyValueWithButton/KeyValueWithButton.tsx
  packages/webb-ui-components/src/components/KeyValueWithButton/types.d.ts
  packages/webb-ui-components/src/components/NetworkThresholdsCard/NetworkThresholdsCard.tsx
  packages/webb-ui-components/src/components/NetworkThresholdsCard/index.ts
  packages/webb-ui-components/src/components/NetworkThresholdsCard/types.d.ts
  packages/webb-ui-components/src/components/NetworkThresholdsCard/useNetworkThresholdsSeedData.ts
  packages/webb-ui-components/src/components/TitleWithInfo/TitleWithInfo.tsx
  packages/webb-ui-components/src/components/TitleWithInfo/types.d.ts
  packages/webb-ui-components/src/components/index.ts
Labels: needs review 👓

#559 Add new `Table` and `Pagination` components
  packages/mixer/src/Mixer.tsx
  packages/webb-ui-components/package.json
  packages/webb-ui-components/src/components/AvatarGroup/AvatarGroup.tsx
  packages/webb-ui-components/src/components/KeyValueWithButton/KeyValueWithButton.tsx
  packages/webb-ui-components/src/components/KeyValueWithButton/types.d.ts
  packages/webb-ui-components/src/components/LabelWithValue/LabelWithValue.tsx
  packages/webb-ui-components/src/components/LabelWithValue/types.d.ts
  packages/webb-ui-components/src/components/Pagination/Pagination.tsx
  packages/webb-ui-components/src/components/Pagination/index.ts
  packages/webb-ui-components/src/components/Pagination/types.d.ts
  packages/webb-ui-components/src/components/Table/TData.tsx
  packages/webb-ui-components/src/components/Table/THeader.tsx
  packages/webb-ui-components/src/components/Table/Table.tsx
  packages/webb-ui-components/src/components/Table/index.ts
  packages/webb-ui-components/src/components/Table/types.d.ts
  packages/webb-ui-components/src/components/index.ts
  packages/webb-ui-components/src/containers/KeygenTable/KeygenTable.tsx
  packages/webb-ui-components/src/containers/KeygenTable/index.ts
  packages/webb-ui-components/src/containers/KeygenTable/types.d.ts
  packages/webb-ui-components/src/containers/index.ts
  packages/webb-ui-components/src/hooks/index.ts
  packages/webb-ui-components/src/hooks/useKeygenSeedData.ts
  packages/webb-ui-components/src/index.tsx
  packages/webb-ui-components/src/types/index.d.ts
  packages/webb-ui-components/src/utils/arrayFrom.ts
  packages/webb-ui-components/src/utils/getPaginationItems.ts
  packages/webb-ui-components/src/utils/index.ts
  packages/webb-ui-components/src/utils/range.ts
  yarn.lock
Labels: needs review 👓

#560 New `Filter` Component
  packages/webb-ui-components/package.json
  packages/webb-ui-components/src/components/CardTable/CardTable.tsx
  packages/webb-ui-components/src/components/CardTable/index.ts
  packages/webb-ui-components/src/components/CardTable/types.d.ts
  packages/webb-ui-components/src/components/Collapsible/Collapsible.tsx
  packages/webb-ui-components/src/components/Collapsible/CollapsibleButton.tsx
  packages/webb-ui-components/src/components/Collapsible/CollapsibleContent.tsx
  packages/webb-ui-components/src/components/Collapsible/index.ts
  packages/webb-ui-components/src/components/Collapsible/types.d.ts
  packages/webb-ui-components/src/components/Dropdown/Dropdown.tsx
  packages/webb-ui-components/src/components/Dropdown/DropdownBody.tsx
  packages/webb-ui-components/src/components/Dropdown/DropdownButton.tsx
  packages/webb-ui-components/src/components/Dropdown/index.ts
  packages/webb-ui-components/src/components/Dropdown/types.d.ts
  packages/webb-ui-components/src/components/DropdownMenu/DropdownMenu.tsx
  packages/webb-ui-components/src/components/Filter/Filter.tsx
  packages/webb-ui-components/src/components/Filter/index.ts
  packages/webb-ui-components/src/components/Filter/types.d.ts
  packages/webb-ui-components/src/components/Filter/utils.ts
  packages/webb-ui-components/src/components/Input/Input.tsx
  packages/webb-ui-components/src/components/Input/types.d.ts
  packages/webb-ui-components/src/components/Table/THeader.tsx
  packages/webb-ui-components/src/components/Table/Table.tsx
  packages/webb-ui-components/src/components/Table/types.d.ts
  packages/webb-ui-components/src/components/index.ts
  packages/webb-ui-components/src/containers/KeygenTable/KeygenTable.tsx
  packages/webb-ui-components/src/types/index.d.ts
  packages/webb-ui-components/src/utils/getPaginationItems.ts
  yarn.lock
Labels: needs review 👓

#563 Add New `TimeLine` Component
  packages/mixer/src/Mixer.tsx
  packages/webb-ui-components/src/components/KeyValueWithButton/KeyValueWithButton.tsx
  packages/webb-ui-components/src/components/KeyValueWithButton/types.d.ts
  packages/webb-ui-components/src/components/LabelWithValue/LabelWithValue.tsx
  packages/webb-ui-components/src/components/LabelWithValue/types.d.ts
  packages/webb-ui-components/src/components/TimeLine/TimeLine.tsx
  packages/webb-ui-components/src/components/TimeLine/TimeLineItem.tsx
  packages/webb-ui-components/src/components/TimeLine/index.ts
  packages/webb-ui-components/src/components/TimeLine/types.d.ts
  packages/webb-ui-components/src/components/index.ts
  packages/webb-ui-components/src/icons/ExternalLinkLine.tsx
  packages/webb-ui-components/src/icons/Spinner.tsx
Labels: needs review 👓

#561 Keys Stats API
  graphql.schema.json
  packages/page-statistics/README.md
  packages/page-statistics/src/AuthoritiesData.tsx
  packages/page-statistics/src/generated/graphql.tsx
  packages/page-statistics/src/gql/metadata.graphql
  packages/page-statistics/src/gql/proposals.graphql
  packages/page-statistics/src/gql/public-keys.graphql
  packages/page-statistics/src/gql/sessions.graphql
  packages/page-statistics/src/provider/DemoTable.tsx
  packages/page-statistics/src/provider/hooks/index.ts
  packages/page-statistics/src/provider/hooks/types.ts
  packages/page-statistics/src/provider/hooks/useAuthorities.ts
  packages/page-statistics/src/provider/hooks/useCurrentMetaData.ts
  packages/page-statistics/src/provider/hooks/useKeys.ts
  packages/page-statistics/src/provider/hooks/useProposal.ts
  schema.graphql
Labels: needs review 👓

#581 New Drawer Component
  packages/page-statistics/src/components/Footer/types.d.ts
  packages/page-statistics/src/components/Header/types.d.ts
  packages/page-statistics/src/containers/Layout/types.d.ts
  packages/webb-ui-components/package.json
  packages/webb-ui-components/src/components/Drawer/Drawer.tsx
  packages/webb-ui-components/src/components/Drawer/index.ts
  packages/webb-ui-components/src/components/Drawer/types.d.ts
  packages/webb-ui-components/src/components/Progress/Progress.tsx
  packages/webb-ui-components/src/components/index.ts
  packages/webb-ui-components/src/containers/KeygenTable/KeygenTable.tsx
  packages/webb-ui-components/src/css/layer-components.css
  tailwind.config.js
  yarn.lock
Labels: needs review 👓

#582 Key Detail Stats Page UI
  packages/page-statistics/package.json
  packages/page-statistics/src/containers/KeyDetail/KeyDetail.tsx
  packages/page-statistics/src/containers/KeyDetail/index.ts
  packages/page-statistics/src/containers/KeyDetail/types.d.ts
  packages/page-statistics/src/containers/KeygenTable/KeygenTable.tsx
  packages/page-statistics/src/containers/KeygenTable/index.ts
  packages/page-statistics/src/containers/KeygenTable/types.d.ts
  packages/page-statistics/src/containers/index.ts
  packages/page-statistics/src/hooks/index.ts
  packages/page-statistics/src/hooks/useAuthoritiesSeedData.ts
  packages/page-statistics/src/pages/Keys.tsx
  packages/page-statistics/webpack.config.js
  packages/webb-ui-components/src/components/AvatarGroup/AvatarGroup.tsx
  packages/webb-ui-components/src/components/Button/Button.tsx
  packages/webb-ui-components/src/components/Button/ButtonSpinner.tsx
  packages/webb-ui-components/src/components/Button/types.d.ts
  packages/webb-ui-components/src/components/Button/utils.ts
  packages/webb-ui-components/src/components/CardTable/CardTable.tsx
  packages/webb-ui-components/src/components/CardTable/types.d.ts
  packages/webb-ui-components/src/components/KeyCard/KeyCard.tsx
  packages/webb-ui-components/src/components/LabelWithValue/LabelWithValue.tsx
  packages/webb-ui-components/src/components/LabelWithValue/types.d.ts
  packages/webb-ui-components/src/components/Pagination/Pagination.tsx
  packages/webb-ui-components/src/components/Table/THeader.tsx
  packages/webb-ui-components/src/components/TimeLine/TimeLineItem.tsx
  packages/webb-ui-components/src/containers/index.ts
  packages/webb-ui-components/src/css/layer-components.css
  packages/webb-ui-components/src/icons/Close.tsx
  packages/webb-ui-components/src/types/index.d.ts
  packages/webb-ui-components/src/utils/index.ts
  packages/webb-ui-components/src/utils/range.ts
  packages/webb-ui-components/src/utils/shorttenString.ts
  yarn.lock
Labels: needs review 👓

#585 SubQuery timetamp
  packages/page-statistics/src/App.tsx
  packages/page-statistics/src/generated/graphql.tsx
  packages/page-statistics/src/gql/metadata.graphql
  packages/page-statistics/src/provider/hooks/useCurrentMetaData.ts
  packages/page-statistics/src/provider/stats-provider.tsx
Labels: needs review 👓

#604 chore: remove unused files
  packages/apps/src/sidebar-config.tsx
  packages/page-statistics/src/AuthoritiesData.tsx
  packages/page-statistics/src/DKGStatistics/DKGStatistics.tsx
  packages/page-statistics/src/DepositStatistics.tsx
  packages/page-statistics/src/RelayerStatistics.tsx
  packages/page-statistics/src/StatisticsOverview.tsx
  packages/page-statistics/src/WithdrawalStatistics.tsx
  packages/page-statistics/src/components/Footer/types.d.ts
  packages/page-statistics/src/components/Header/types.d.ts
  packages/page-statistics/src/containers/KeygenTable/types.d.ts
  packages/page-statistics/src/containers/Layout/types.d.ts
Labels: approved ✅

#586 Integrate SubQL API on Key Page
  packages/page-statistics/src/containers/KeyDetail/KeyDetail.tsx
  packages/page-statistics/src/containers/KeyDetail/types.d.ts
  packages/page-statistics/src/containers/KeyStatusCardContainer/KeyStatusCardContainer.tsx
  packages/page-statistics/src/containers/KeyStatusCardContainer/index.ts
  packages/page-statistics/src/containers/KeyStatusCardContainer/types.d.ts
  packages/page-statistics/src/containers/KeygenTable/KeygenTable.tsx
  packages/page-statistics/src/containers/index.ts
  packages/page-statistics/src/hooks/useAuthoritiesSeedData.ts
  packages/page-statistics/src/pages/KeyDetailDrawer.tsx
  packages/page-statistics/src/pages/KeyDetailPage.tsx
  packages/page-statistics/src/pages/Keys.tsx
  packages/page-statistics/src/provider/hooks/useAuthorities.ts
  packages/page-statistics/src/provider/hooks/useKeys.ts
  packages/page-statistics/src/routes/index.tsx
  packages/webb-ui-components/package.json
  packages/webb-ui-components/src/components/Avatar/Avatar.tsx
  packages/webb-ui-components/src/components/Avatar/types.d.ts
  packages/webb-ui-components/src/components/Avatar/utils.ts
  packages/webb-ui-components/src/components/AvatarGroup/AvatarGroup.tsx
  packages/webb-ui-components/src/components/KeyStatusCard/KeyStatusCard.tsx
  packages/webb-ui-components/src/components/KeyStatusCard/types.d.ts
  packages/webb-ui-components/src/components/KeyStatusCard/useKeyStatusSeedData.ts
  packages/webb-ui-components/src/components/Progress/Progress.tsx
  packages/webb-ui-components/src/components/Table/Table.tsx
  packages/webb-ui-components/src/components/Table/types.d.ts
  packages/webb-ui-components/src/components/TimeLine/TimeLineItem.tsx
  packages/webb-ui-components/src/components/Tooltip/Tooltip.tsx
  packages/webb-ui-components/src/hooks/useKeygenSeedData.ts
  packages/webb-ui-components/src/icons/Spinner.tsx
  packages/webb-ui-components/src/types/index.d.ts
  packages/webb-ui-components/src/utils/calculateDateProgress.ts
  yarn.lock
Labels: needs review 👓

#613 Authority Page UI
  packages/page-statistics/src/containers/AuthoritiesTable/AuthoritiesTable.tsx
  packages/page-statistics/src/containers/AuthoritiesTable/index.ts
  packages/page-statistics/src/containers/AuthoritiesTable/types.ts
  packages/page-statistics/src/containers/AuthorityDetail/AuthorityDetail.tsx
  packages/page-statistics/src/containers/AuthorityDetail/index.ts
  packages/page-statistics/src/containers/KeyDetail/KeyDetail.tsx
  packages/page-statistics/src/containers/KeygenTable/KeygenTable.tsx
  packages/page-statistics/src/containers/index.ts
  packages/page-statistics/src/pages/Authorities.tsx
  packages/page-statistics/src/pages/AuthorityDetailDrawer.tsx
  packages/page-statistics/src/pages/AuthorityDetailPage.tsx
  packages/page-statistics/src/pages/Proposals.tsx
  packages/page-statistics/src/provider/hooks/useAuthorities.ts
  packages/page-statistics/src/routes/index.tsx
  packages/page-statistics/src/utils/getChipColorByKeyType.ts
  packages/page-statistics/src/utils/index.ts
  packages/webb-ui-components/src/components/AvatarGroup/AvatarGroup.tsx
  packages/webb-ui-components/src/components/CardTable/CardTable.tsx
  packages/webb-ui-components/src/components/Stats/Stats.tsx
  packages/webb-ui-components/src/components/Stats/index.ts
  packages/webb-ui-components/src/components/Stats/types.d.ts
  packages/webb-ui-components/src/components/index.ts
  packages/webb-ui-components/src/icons/CheckboxBlankCircleLine.tsx
  packages/webb-ui-components/src/icons/Key.tsx
  packages/webb-ui-components/src/icons/Link.tsx
  packages/webb-ui-components/src/icons/Mail.tsx
  packages/webb-ui-components/src/icons/QRCode.tsx
Labels: needs review 👓

#610 Fix session and keys data
  .graphqlconfig
  codegen.yml
  packages/page-statistics/src/App.tsx
  packages/page-statistics/src/containers/KeygenTable/KeygenTable.tsx
  packages/page-statistics/src/generated/graphql.tsx
  packages/page-statistics/src/gql/sessions.graphql
  packages/page-statistics/src/provider/hooks/useKeys.ts
  packages/page-statistics/src/provider/stats-provider.tsx
  packages/webb-ui-components/src/components/Avatar/Avatar.tsx
  packages/webb-ui-components/src/components/Avatar/types.d.ts
  packages/webb-ui-components/src/components/KeyStatusCard/KeyStatusCard.tsx
Labels: needs review 👓

#615 Proposals stats UI integrations
  .graphqlconfig
  codegen.yml
  graphql.schema.json
  packages/page-statistics/src/App.tsx
  packages/page-statistics/src/containers/DonutChartContainer/DonutChartContainer.tsx
  packages/page-statistics/src/containers/KeyStatusCardContainer/types.d.ts
  packages/page-statistics/src/containers/ProposalDetail/ProposalDetail.tsx
  packages/page-statistics/src/containers/ProposalsTable/ProposalsTable.tsx
  packages/page-statistics/src/containers/ProposersTable/ProposersTable.tsx
  packages/page-statistics/src/generated/graphql.tsx
  packages/page-statistics/src/gql/fragments.graphql
  packages/page-statistics/src/gql/proposals.graphql
  packages/page-statistics/src/pages/Keys.tsx
  packages/page-statistics/src/pages/Proposals.tsx
  packages/page-statistics/src/provider/hooks/mappers/index.ts
  packages/page-statistics/src/provider/hooks/useKeys.ts
  packages/page-statistics/src/provider/hooks/useProposals.ts
  packages/page-statistics/src/provider/stats-provider.tsx
  schema.graphql
Labels: needs review 👓

#612 Remove global styles from dapp and api connection error handling
  packages/api-providers/src/abstracts/currency/orml-currency.ts
  packages/api-providers/src/abstracts/webb-provider.interface.ts
  packages/api-providers/src/ext-providers/polkadot/polkadot-provider.ts
  packages/api-providers/src/polkadot/chain-query.ts
  packages/api-providers/src/polkadot/mixer-deposit.ts
  packages/api-providers/src/polkadot/vanchor-actions.ts
  packages/api-providers/src/polkadot/webb-provider.ts
  packages/api-providers/src/web3/vanchor-deposit.ts
  packages/api-providers/src/web3/webb-provider.ts
  packages/apps/src/App.tsx
  packages/apps/src/configs/chains/evm/index.tsx
  packages/apps/src/configs/chains/substrate/index.tsx
  packages/apps/src/index.tsx
  packages/mixer/src/hooks/deposit/useDeposit.tsx
  packages/react-components/src/AppBar/ThemeSwitcher.tsx
  packages/react-environment/src/WebbProvider.tsx
  packages/react-hooks/src/currency/useCurrencies.tsx
Labels: needs review 👓

#617 Authorities History Page
  packages/page-statistics/src/pages/Authorities.tsx
  packages/page-statistics/src/pages/AuthoritiesHistory.tsx
  packages/page-statistics/src/routes/index.tsx
  packages/webb-ui-components/src/components/Dropdown/DropdownButton.tsx
  packages/webb-ui-components/src/components/MenuItem/MenuItem.tsx
Labels: needs review 👓
