Repository tangle-network/dapp, pull requests merged in 2022-06, with the labels that each got.

#407 Add tooltip for copy address button
  packages/bridge/package.json
  packages/bridge/src/components/DepositConfirm/DepositConfirm.tsx
  packages/mixer/package.json
  packages/mixer/src/components/Deposit/Deposit.tsx
  packages/mixer/src/components/DepositConfirm/DepositConfirm.tsx
  packages/react-components/package.json
  packages/react-hooks/package.json
  packages/react-hooks/src/index.ts
  packages/react-hooks/src/useCopyable.ts
  packages/ui-components/package.json
  packages/ui-components/src/Inputs/MixerGroupSelect/MixerGroupSelect.tsx
  packages/ui-components/src/Inputs/WalletSelect/WalletDetails.tsx
  packages/vbridge/package.json
  packages/vbridge/src/components/DepositConfirm/DepositConfirm.tsx
  yarn.lock
Labels: approved ✅

#415 Fix and remove logs / errors in browser console
  packages/apps/src/configs/logos/chains/ArbitrumLogo.tsx
  packages/mixer/src/hooks/note/index.ts
  packages/page-wrap-unwrap/src/index.tsx
  packages/react-components/src/InteractiveFeedbackView/DefaultErrorView.tsx
  packages/react-components/src/InteractiveFeedbackView/UnselectedNetworkView.tsx
  packages/react-environment/src/WebbProvider.tsx
  packages/react-environment/src/error/interactive-errors/extension-not-installed.tsx
  packages/react-hooks/src/currency/useNativeCurrencyBalance.tsx
  packages/react-hooks/src/useWallets.ts
  packages/ui-components/src/Inputs/AmountInput/AmountInput.tsx
  packages/ui-components/src/Inputs/ChainInput/ChainInput.tsx
  packages/ui-components/src/Inputs/WalletSelect/WalletSelect.tsx
  packages/ui-components/src/NetworkManger/NetworkManager.tsx
  packages/ui-components/src/Tabs/MixerTabs.tsx
  packages/ui-components/src/styling/themes/makeTheme.ts
Labels: needs review 👓

#416 Fix sync the display account with metamask account
  packages/api-providers/src/web3/webb-provider.ts
  packages/mixer/src/components/DepositConfirm/DepositConfirm.tsx
  packages/react-environment/src/WebbProvider.tsx
  packages/react-hooks/src/currency/useNativeCurrencyBalance.tsx
Labels: needs review 👓, bug 🪲

#418 Implement chain selection modal
  packages/bridge/src/components/Deposit/Deposit.tsx
  packages/bridge/src/components/Withdraw/Withdraw.tsx
  packages/react-components/src/AppBar/AppBar.tsx
  packages/react-components/src/BottomWalletSelection/BottomWalletSelection.tsx
  packages/react-components/src/InteractiveFeedbackView/UnselectedNetworkView.tsx
  packages/react-components/src/assets/WebbFullNameLogo.tsx
  packages/ui-components/src/Buttons/MixerButton.tsx
  packages/ui-components/src/Icon.tsx
  packages/ui-components/src/Inputs/ChainInput/ChainInput.tsx
  packages/ui-components/src/Inputs/ChainSelection/ChainSelection.tsx
  packages/ui-components/src/Inputs/TokenInput/TokenInput.tsx
  packages/ui-components/src/Modal/Modal.tsx
  packages/ui-components/src/NetworkManger/NetworkManager.tsx
  packages/ui-components/src/Tabs/MixerTabs.tsx
  packages/ui-components/src/assets/CloseIcon.tsx
  packages/ui-components/src/assets/SearchIcon.tsx
  packages/ui-components/src/misc/CircledArrowRight.tsx
  packages/ui-components/src/utils/responsive-utils/break-points.util.ts
  packages/ui-components/src/utils/responsive-utils/index.ts
  packages/ui-components/src/utils/responsive-utils/use-breakpoint.ts
Labels: needs changes 🔧, needs review 👓

#423 Token selection modal
  packages/api-providers/src/polkadot/anchor-api.ts
  packages/bridge/src/components/Deposit/Deposit.tsx
  packages/ui-components/src/Inputs/InputSection/InputSection.tsx
  packages/ui-components/src/Inputs/MixerGroupSelect/MixerGroupSelect.tsx
  packages/ui-components/src/Inputs/TokenInput/TokenInput.tsx
  packages/ui-components/src/Inputs/TokenSelection/TokenSelection.tsx
Labels: needs changes 🔧, needs review 👓

#426 Crowdloan page UI
  package.json
  packages/api-providers/src/abstracts/chain-query/index.ts
  packages/api-providers/src/abstracts/crowdloan/index.ts
  packages/api-providers/src/abstracts/currency/currency.ts
  packages/api-providers/src/abstracts/webb-provider.interface.ts
  packages/api-providers/src/chains/chain-utils.ts
  packages/api-providers/src/polkadot/chain-query.ts
  packages/api-providers/src/polkadot/crowdloan.ts
  packages/api-providers/src/polkadot/transaction.ts
  packages/api-providers/src/polkadot/webb-provider.ts
  packages/api-providers/src/types/currency-config.interface.ts
  packages/api-providers/src/web3/chain-query.ts
  packages/api-providers/src/web3/webb-provider.ts
  packages/apps/src/configs/currencies/currency-config.ts
  packages/apps/src/configs/logos/chains/KusamaLogo.tsx
  packages/apps/src/configs/logos/chains/PolkadotLogo.tsx
  packages/apps/src/configs/logos/chains/Polkadot_Token_PinkOnWhite.svg
  packages/apps/src/sidebar-config.tsx
  packages/page-crowdloan/src/CrowdloanInfo.tsx
  packages/page-crowdloan/src/hooks/useCrowdloan.ts
  packages/page-crowdloan/src/index.tsx
  packages/page-wrap-unwrap/src/index.tsx
  packages/react-components/src/Sidebar/Products.tsx
  yarn.lock
Labels: needs changes 🔧, needs review 👓

#427 Crowdloan confirmation modal UI
  packages/api-providers/src/polkadot/crowdloan.ts
  packages/page-crowdloan/package.json
  packages/page-crowdloan/src/ConfirmationModal.tsx
  packages/page-crowdloan/src/index.tsx
Labels: needs review 👓

#435 UI tasks
  packages/apps/public/index.html
  packages/apps/src/configs/chains/evm/index.ts
  packages/apps/src/configs/chains/substrate/index.ts
  packages/apps/src/configs/logos/Eth.tsx
  packages/apps/src/configs/logos/TelegramLogo.tsx
  packages/apps/src/configs/logos/chains/KusamaLogo.tsx
  packages/apps/src/configs/logos/chains/PolkadotLogo.tsx
  packages/apps/src/configs/logos/chains/Polkadot_Token_PinkOnWhite.svg
  packages/bridge/src/components/Deposit/Deposit.tsx
  packages/bridge/src/components/Withdraw/Withdraw.tsx
  packages/mixer/src/components/Deposit/Deposit.tsx
  packages/mixer/src/components/Withdraw/Withdraw.tsx
  packages/page-crowdloan/src/index.tsx
  packages/page-wrap-unwrap/src/index.tsx
  packages/react-components/src/AppBar/AppBar.tsx
  packages/react-components/src/AppBar/ThemeSwitcher.tsx
  packages/react-components/src/Sidebar/SocialPlatform.tsx
  packages/react-components/src/Sidebar/index.tsx
  packages/ui-components/src/Inputs/BalanceLabel/BalanceLabel.tsx
  packages/ui-components/src/Inputs/CheckBox/CheckBox.tsx
  packages/ui-components/src/Inputs/CheckBox/checkbox-props.ts
  packages/ui-components/src/Inputs/CheckBox/styled/CheckBoxText.tsx
  packages/ui-components/src/Inputs/CheckBox/styled/index.ts
  packages/ui-components/src/Inputs/InputTitle/InputTitle.tsx
  packages/ui-components/src/Inputs/RelayerButton/RelayerButton.tsx
  packages/ui-components/src/Inputs/RelayerButton/relayer-label-props.interface.ts
  packages/ui-components/src/Inputs/RelayerButton/styled/RelayerSettings.tsx
  packages/ui-components/src/Inputs/RelayerButton/styled/index.ts
  packages/ui-components/src/Inputs/TextLabel/TextLabel.tsx
  packages/ui-components/src/Inputs/WalletSelect/WalletSelect.tsx
  packages/ui-components/src/Inputs/shared/index.ts
  packages/ui-components/src/NetworkManger/NetworkManager.tsx
  packages/ui-components/src/assets/ArrowDownIcon.tsx
  packages/vbridge/src/components/Deposit/Deposit.tsx
  packages/vbridge/src/components/Withdraw/Withdraw.tsx
Labels: needs review 👓

#440 Inform user to switch to Kusama chain in Crowdloan page
  packages/page-crowdloan/src/hooks/useCrowdloan.ts
  packages/page-crowdloan/src/index.tsx
  packages/react-environment/src/WebbProvider.tsx
  packages/ui-components/src/Buttons/MixerButton.tsx
  packages/ui-components/src/NetworkManger/NetworkManager.tsx
Labels: approved ✅, needs review 👓

#425 Substrate VAnchor integration
  package.json
  packages/api-providers/package.json
  packages/api-providers/src/abstracts/anchor/anchor-api.ts
  packages/api-providers/src/abstracts/anchor/vanchor-deposit.ts
  packages/api-providers/src/abstracts/anchor/vanchor-withdraw.ts
  packages/api-providers/src/abstracts/currency/currency.ts
  packages/api-providers/src/abstracts/webb-provider.interface.ts
  packages/api-providers/src/contracts/wrappers/webb-vanchor.ts
  packages/api-providers/src/ext-providers/polkadot/polkadot-provider.ts
  packages/api-providers/src/ipfs/substrate/index.ts
  packages/api-providers/src/ipfs/substrate/vanchor.ts
  packages/api-providers/src/polkadot/mt-utils.ts
  packages/api-providers/src/polkadot/transaction.ts
  packages/api-providers/src/polkadot/vanchor-deposit.ts
  packages/api-providers/src/polkadot/vanchor-withdraw.ts
  packages/api-providers/src/web3/vanchor-deposit.ts
  packages/api-providers/src/web3/vanchor-withdraw.ts
  packages/api-providers/src/webb-error/webb-error.class.ts
  packages/apps/src/configs/anchors/anchor-config.ts
  packages/apps/src/configs/bridges/bridge-config.ts
  packages/bridge/package.json
  packages/mixer/package.json
  packages/mixer/src/hooks/note/index.ts
  packages/page-bridge/package.json
  packages/page-mixer/package.json
  packages/react-components/package.json
  packages/react-environment/package.json
  packages/react-hooks/package.json
  packages/vbridge/package.json
  packages/vbridge/src/components/DepositConfirm/DepositConfirm.tsx
  packages/vbridge/src/hooks/deposit/useBridgeDeposit.tsx
  packages/vbridge/src/hooks/withdraw/useWithdraw.tsx
  yarn.lock
Labels: approved ✅

#451 Improve UI components
  packages/react-components/src/Withdraw/WithdrawingModal.tsx
  packages/ui-components/package.json
  packages/ui-components/src/Chip/Chip.tsx
  packages/ui-components/src/Chip/index.ts
  packages/ui-components/src/Inputs/ChainInput/ChainInput.tsx
  packages/ui-components/src/Inputs/ChainSelection/ChainSelection.tsx
  packages/ui-components/src/Inputs/TokenInput/TokenInput.tsx
  packages/ui-components/src/Inputs/TokenSelection/TokenSelection.tsx
  packages/ui-components/src/Inputs/WalletSelect/WalletSelect.tsx
  packages/ui-components/src/Inputs/shared/ListEmpty/ListEmpty.tsx
  packages/ui-components/src/Inputs/shared/ListEmpty/index.ts
  packages/ui-components/src/Inputs/shared/ListEmpty/styled/ListEmptyWrapper.tsx
  packages/ui-components/src/Inputs/shared/ListEmpty/styled/index.ts
  packages/ui-components/src/Inputs/shared/index.ts
  packages/ui-components/src/Inputs/shared/styled/index.ts
  packages/ui-components/src/Inputs/shared/styled/selections-modal/CircleStatus.tsx
  packages/ui-components/src/Inputs/shared/styled/selections-modal/CloseHeaderButtonWrapper.tsx
  packages/ui-components/src/Inputs/shared/styled/selections-modal/ItemWrapper.tsx
  packages/ui-components/src/Inputs/shared/styled/selections-modal/ListWrapper.tsx
  packages/ui-components/src/Inputs/shared/styled/selections-modal/SearchIconWrapper.tsx
  packages/ui-components/src/Inputs/shared/styled/selections-modal/SearchWrapper.tsx
  packages/ui-components/src/Inputs/shared/styled/selections-modal/SelectionWrapper.tsx
  packages/ui-components/src/Inputs/shared/styled/selections-modal/index.ts
  packages/ui-components/src/Modal/Modal.tsx
  packages/ui-components/src/NetworkManger/NetworkManager.tsx
  packages/ui-components/src/NetworkManger/NetworkManagerIndicator.tsx
  packages/ui-components/src/index.ts
  packages/ui-components/src/utils/index.ts
  yarn.lock
Labels: needs review 👓

#450 Update VAnchor Withdraw UI
  packages/mixer/src/hooks/note/index.ts
  packages/ui-components/src/AlertCard/AlertCard.tsx
  packages/ui-components/src/AlertCard/icons/Error.tsx
  packages/ui-components/src/AlertCard/icons/Info.tsx
  packages/ui-components/src/AlertCard/icons/Success.tsx
  packages/ui-components/src/AlertCard/icons/Warning.tsx
  packages/ui-components/src/AlertCard/icons/index.tsx
  packages/ui-components/src/AlertCard/index.ts
  packages/ui-components/src/AlertCard/styled/AlertCardWrapper.tsx
  packages/ui-components/src/AlertCard/styled/IconWrapper.tsx
  packages/ui-components/src/AlertCard/styled/TextWrapper.tsx
  packages/ui-components/src/AlertCard/styled/index.ts
  packages/ui-components/src/AlertCard/types.ts
  packages/ui-components/src/Inputs/RelayerInput/RelayerInput.tsx
  packages/ui-components/src/Inputs/WalletSelect/WalletSelect.tsx
  packages/ui-components/src/index.ts
  packages/vbridge/src/components/NoteInput/NoteInput.tsx
  packages/vbridge/src/components/NoteInput/index.ts
  packages/vbridge/src/components/NoteInput/note-input-props.interface.ts
  packages/vbridge/src/components/NoteInput/styled/NoteInputContainer.tsx
  packages/vbridge/src/components/NoteInput/styled/NoteInputWrapper.tsx
  packages/vbridge/src/components/NoteInput/styled/index.ts
  packages/vbridge/src/components/Withdraw/Withdraw.tsx
  packages/vbridge/src/components/shared/styled/InformationItem.tsx
  packages/vbridge/src/components/shared/styled/Title.tsx
  packages/vbridge/src/components/shared/styled/Value.tsx
  packages/vbridge/src/components/shared/styled/index.ts
  packages/vbridge/src/hooks/index.ts
  packages/vbridge/src/hooks/withdraw/useWithdraw.tsx
Labels: needs review 👓
