Repository tangle-network/dapp, pull requests merged in 2022-10, with the labels that each got.

#623 Improve stats UI
  packages/page-statistics/src/components/Footer/Footer.tsx
  packages/page-statistics/src/constants/index.ts
  packages/page-statistics/src/containers/AuthoritiesTable/AuthoritiesTable.tsx
  packages/page-statistics/src/containers/KeyDetail/KeyDetail.tsx
  packages/page-statistics/src/containers/ProposalDetail/ProposalDetail.tsx
  packages/page-statistics/src/pages/Authorities.tsx
  packages/page-statistics/src/pages/Keys.tsx
  packages/page-statistics/src/provider/hooks/useAuthorities.ts
  packages/page-statistics/src/provider/hooks/useKeys.ts
  packages/page-statistics/src/provider/stats-provider.tsx
  packages/page-statistics/types/index.d.ts
  packages/webb-ui-components/src/components/Avatar/Avatar.tsx
  packages/webb-ui-components/src/components/Avatar/types.d.ts
  packages/webb-ui-components/src/components/Dropdown/DropdownBody.tsx
  packages/webb-ui-components/src/components/Dropdown/DropdownButton.tsx
  packages/webb-ui-components/src/components/DropdownMenu/DropdownMenu.tsx
  packages/webb-ui-components/src/components/Filter/Filter.tsx
  packages/webb-ui-components/src/components/Tabs/Tabs.tsx
  packages/webb-ui-components/src/icons/tokens/avax.svg
  packages/webb-ui-components/src/icons/tokens/default.svg
  packages/webb-ui-components/src/icons/tokens/dot.svg
  packages/webb-ui-components/src/icons/tokens/ksm.svg
  packages/webb-ui-components/src/icons/tokens/link.svg
  packages/webb-ui-components/src/icons/tokens/matic.svg
  packages/webb-ui-components/src/icons/tokens/one.svg
  packages/webb-ui-components/src/icons/tokens/usdc.svg
  packages/webb-ui-components/src/icons/tokens/webb.svg
  packages/webb-ui-components/src/icons/tokens/webb^2.svg
  packages/webb-ui-components/src/icons/tokens/webbdev.svg
  packages/webb-ui-components/src/icons/tokens/webbeth.svg
Labels: needs review 👓

#627 Iterative Improving Stats UI
  packages/page-statistics/src/components/Header/Header.tsx
  packages/page-statistics/src/containers/AuthoritiesTable/AuthoritiesTable.tsx
  packages/page-statistics/src/containers/AuthorityDetail/AuthorityDetail.tsx
  packages/page-statistics/src/containers/KeyDetail/KeyDetail.tsx
  packages/page-statistics/src/containers/KeygenTable/KeygenTable.tsx
  packages/page-statistics/src/containers/ProposalDetail/ProposalDetail.tsx
  packages/page-statistics/src/containers/ProposalsTable/ProposalsTable.tsx
  packages/page-statistics/src/containers/ProposersTable/ProposersTable.tsx
  packages/page-statistics/src/pages/Authorities.tsx
  packages/page-statistics/src/pages/AuthoritiesHistory.tsx
  packages/page-statistics/src/pages/Keys.tsx
  packages/page-statistics/src/pages/Proposals.tsx
  packages/page-statistics/src/provider/hooks/useKeys.ts
  packages/webb-ui-components/src/components/Button/Button.tsx
  packages/webb-ui-components/src/components/Button/types.d.ts
  packages/webb-ui-components/src/components/Button/utils.ts
  packages/webb-ui-components/src/components/Chip/Chip.tsx
  packages/webb-ui-components/src/components/Chip/utils.ts
  packages/webb-ui-components/src/components/Dropdown/DropdownButton.tsx
  packages/webb-ui-components/src/components/Filter/Filter.tsx
  packages/webb-ui-components/src/components/Input/Input.tsx
  packages/webb-ui-components/src/components/KeyCard/KeyCard.tsx
  packages/webb-ui-components/src/components/KeyStatusCard/KeyStatusCard.tsx
  packages/webb-ui-components/src/components/KeyValueWithButton/KeyValueWithButton.tsx
  packages/webb-ui-components/src/components/KeyValueWithButton/types.d.ts
  packages/webb-ui-components/src/components/LabelWithValue/LabelWithValue.tsx
  packages/webb-ui-components/src/components/LabelWithValue/types.d.ts
  packages/webb-ui-components/src/components/NetworkThresholdsCard/NetworkThresholdsCard.tsx
  packages/webb-ui-components/src/components/Pagination/Pagination.tsx
  packages/webb-ui-components/src/components/Slider/Slider.tsx
  packages/webb-ui-components/src/components/Table/TData.tsx
  packages/webb-ui-components/src/components/Tabs/Tabs.tsx
  packages/webb-ui-components/src/components/TimeLine/TimeLineItem.tsx
  packages/webb-ui-components/src/components/Tooltip/Tooltip.tsx
  packages/webb-ui-components/src/css/layer-components.css
  packages/webb-ui-components/src/types/index.d.ts
  packages/webb-ui-components/src/typography/Typography/Typography.tsx
  packages/webb-ui-components/src/typography/types.d.ts
  packages/webb-ui-components/src/typography/utils/index.ts
  packages/webb-ui-components/src/utils/formatDateToUtc.tsx
Labels: needs review 👓

#634 Switcher, Scrollbar and TokenSelector components
  packages/page-statistics/src/pages/ComponentsShowcase.tsx
  packages/page-statistics/src/routes/index.tsx
  packages/webb-ui-components/package.json
  packages/webb-ui-components/src/components/LabelWithValue/LabelWithValue.tsx
  packages/webb-ui-components/src/components/Stats/Stats.tsx
  packages/webb-ui-components/src/components/Switcher/Switcher.tsx
  packages/webb-ui-components/src/components/Switcher/index.ts
  packages/webb-ui-components/src/components/Switcher/types.d.ts
  packages/webb-ui-components/src/components/TokenSelector/TokenSelector.tsx
  packages/webb-ui-components/src/components/TokenSelector/index.ts
  packages/webb-ui-components/src/components/TokenSelector/types.d.ts
  packages/webb-ui-components/src/components/index.ts
  packages/webb-ui-components/src/css/layer-base.css
  tailwind.config.js
  yarn.lock
Labels: needs review 👓

#635 Input components of Bridge UI
  packages/page-statistics/src/containers/BridgeInputsShowCase/BridgeInputsShowCase.tsx
  packages/page-statistics/src/containers/BridgeInputsShowCase/index.ts
  packages/page-statistics/src/containers/BridgeInputsShowCase/types.ts
  packages/page-statistics/src/containers/index.ts
  packages/page-statistics/src/pages/ComponentsShowcase.tsx
  packages/webb-ui-components/src/components/Avatar/Avatar.tsx
  packages/webb-ui-components/src/components/BridgeInputs/AmountInput.tsx
  packages/webb-ui-components/src/components/BridgeInputs/ChainInput.tsx
  packages/webb-ui-components/src/components/BridgeInputs/CustomAmount.tsx
  packages/webb-ui-components/src/components/BridgeInputs/FixedAmount.tsx
  packages/webb-ui-components/src/components/BridgeInputs/InputWrapper.tsx
  packages/webb-ui-components/src/components/BridgeInputs/RecipientInput.tsx
  packages/webb-ui-components/src/components/BridgeInputs/RelayerInput.tsx
  packages/webb-ui-components/src/components/BridgeInputs/ShieldedAssetInput.tsx
  packages/webb-ui-components/src/components/BridgeInputs/TokenInput.tsx
  packages/webb-ui-components/src/components/BridgeInputs/index.ts
  packages/webb-ui-components/src/components/BridgeInputs/types.d.ts
  packages/webb-ui-components/src/components/Button/Button.tsx
  packages/webb-ui-components/src/components/Button/types.d.ts
  packages/webb-ui-components/src/components/Input/Input.tsx
  packages/webb-ui-components/src/components/Input/types.d.ts
  packages/webb-ui-components/src/components/TitleWithInfo/TitleWithInfo.tsx
  packages/webb-ui-components/src/components/TitleWithInfo/types.d.ts
  packages/webb-ui-components/src/components/index.ts
  packages/webb-ui-components/src/icons/TokenIcon.tsx
  packages/webb-ui-components/src/icons/tokens/eth.svg
  packages/webb-ui-components/src/icons/tokens/op.svg
Labels: needs review 👓

#638 List Card Components for the Bridge UI
  packages/page-statistics/src/containers/ListCardsShowcase/ListCardsShowcase.tsx
  packages/page-statistics/src/containers/ListCardsShowcase/index.ts
  packages/page-statistics/src/containers/index.ts
  packages/page-statistics/src/pages/ComponentsShowcase.tsx
  packages/webb-ui-components/package.json
  packages/webb-ui-components/src/assets/star-dark.png
  packages/webb-ui-components/src/assets/star.png
  packages/webb-ui-components/src/components/BridgeInputs/ShieldedAssetInput.tsx
  packages/webb-ui-components/src/components/BridgeInputs/TokenInput.tsx
  packages/webb-ui-components/src/components/Input/Input.tsx
  packages/webb-ui-components/src/components/Input/types.d.ts
  packages/webb-ui-components/src/components/ListCard/AssetListItem.tsx
  packages/webb-ui-components/src/components/ListCard/ChainListCard.tsx
  packages/webb-ui-components/src/components/ListCard/ListCardWrapper.tsx
  packages/webb-ui-components/src/components/ListCard/ListItem.tsx
  packages/webb-ui-components/src/components/ListCard/RelayerListCard.tsx
  packages/webb-ui-components/src/components/ListCard/TokenListCard.tsx
  packages/webb-ui-components/src/components/ListCard/WithdrawListCard.tsx
  packages/webb-ui-components/src/components/ListCard/WrapAssetListCard.tsx
  packages/webb-ui-components/src/components/ListCard/index.ts
  packages/webb-ui-components/src/components/ListCard/types.d.ts
  packages/webb-ui-components/src/components/ScrollArea/ScrollArea.tsx
  packages/webb-ui-components/src/components/ScrollArea/index.ts
  packages/webb-ui-components/src/components/ScrollArea/types.d.ts
  packages/webb-ui-components/src/components/TokenPair/TokenPair.tsx
  packages/webb-ui-components/src/components/TokenPair/index.ts
  packages/webb-ui-components/src/components/TokenPair/types.d.ts
  packages/webb-ui-components/src/components/index.ts
  packages/webb-ui-components/src/css/layer-base.css
  packages/webb-ui-components/src/icons/TokenIcon.tsx
  packages/webb-ui-components/src/icons/tokens/arbitrum.svg
  packages/webb-ui-components/src/icons/tokens/etc.svg
  packages/webb-ui-components/src/icons/tokens/near.svg
  packages/webb-ui-components/src/icons/tokens/one.svg
  packages/webb-ui-components/src/icons/tokens/weth.svg
  packages/webb-ui-components/src/utils/getRoundedAmountString.tsx
  packages/webb-ui-components/src/utils/index.ts
  yarn.lock
Labels: needs review 👓

#639 FEAT: adds storybook for component library documentation
  .github/workflows/deploy-storybook-docs.yml
  .gitignore
  packages/webb-ui-components/.storybook/main.js
  packages/webb-ui-components/.storybook/manager.js
  packages/webb-ui-components/.storybook/preview.js
  packages/webb-ui-components/.storybook/webbTheme.js
  packages/webb-ui-components/package.json
  packages/webb-ui-components/postcss.config.js
  packages/webb-ui-components/src/components/Divider/Divider.tsx
  packages/webb-ui-components/src/components/Pagination/Pagination.tsx
  packages/webb-ui-components/src/components/Switcher/Switcher.tsx
  packages/webb-ui-components/src/components/TimeLine/TimeLine.tsx
  packages/webb-ui-components/src/components/Tooltip/Tooltip.tsx
  packages/webb-ui-components/src/css/layer-base.css
  packages/webb-ui-components/src/stories/Introduction.stories.mdx
  packages/webb-ui-components/src/stories/assets/Logo.png
  packages/webb-ui-components/src/stories/assets/Logo.svg
  packages/webb-ui-components/src/stories/assets/code-brackets.svg
  packages/webb-ui-components/src/stories/assets/colors.svg
  packages/webb-ui-components/src/stories/assets/comments.svg
  packages/webb-ui-components/src/stories/assets/direction.svg
  packages/webb-ui-components/src/stories/assets/favicon.png
  packages/webb-ui-components/src/stories/assets/flow.svg
  packages/webb-ui-components/src/stories/assets/plugin.svg
  packages/webb-ui-components/src/stories/assets/repo.svg
  packages/webb-ui-components/src/stories/assets/stackalt.svg
  packages/webb-ui-components/src/stories/atoms/Logo.stories.jsx
  packages/webb-ui-components/src/stories/atoms/Typography.stories.jsx
  packages/webb-ui-components/src/stories/molecules/AmountInput.stories.jsx
  packages/webb-ui-components/src/stories/molecules/Avatar.stories.jsx
  packages/webb-ui-components/src/stories/molecules/Button.stories.jsx
  packages/webb-ui-components/src/stories/molecules/ChainInput.stories.jsx
  packages/webb-ui-components/src/stories/molecules/Checkbox.stories.jsx
  packages/webb-ui-components/src/stories/molecules/Chip.stories.jsx
  packages/webb-ui-components/src/stories/molecules/Divider.stories.tsx
  packages/webb-ui-components/src/stories/molecules/DropdownMenu.stories.jsx
  packages/webb-ui-components/src/stories/molecules/FixedAmount.stories.jsx
  packages/webb-ui-components/src/stories/molecules/Pagination.stories.jsx
  packages/webb-ui-components/src/stories/molecules/Slider.stories.jsx
  packages/webb-ui-components/src/stories/molecules/Switcher.stories.jsx
  packages/webb-ui-components/src/stories/molecules/Tabs.stories.jsx
  packages/webb-ui-components/src/stories/molecules/TimeProgress.stories.jsx
  packages/webb-ui-components/src/stories/molecules/Timeline.stories.jsx
  packages/webb-ui-components/src/stories/molecules/TokenInput.stories.jsx
  packages/webb-ui-components/src/stories/molecules/TokenSelector.stories.jsx
  packages/webb-ui-components/src/stories/molecules/Tooltip.stories.jsx
  packages/webb-ui-components/src/stories/organisms/KeyCard.stories.jsx
  packages/webb-ui-components/src/stories/organisms/KeyStatusCard.stories.jsx
  packages/webb-ui-components/tailwind.config.js
  yarn.lock
Labels: needs review 👓, ui-components, documentation 📓

#645 Fix keygen table filter
  packages/page-statistics/src/containers/KeygenTable/KeygenTable.tsx
  packages/page-statistics/src/provider/hooks/useKeys.ts
  packages/webb-ui-components/src/types/index.d.ts
Labels: needs changes 🔧, needs review 👓

#649 Ensure tables are sorted by latest
  .graphqlconfig
  graphql.schema.json
  packages/page-statistics/src/containers/AuthoritiesTable/AuthoritiesTable.tsx
  packages/page-statistics/src/generated/graphql.tsx
  packages/page-statistics/src/gql/authorites.graphql
  packages/page-statistics/src/provider/hooks/useAuthorities.ts
  schema.graphql
Labels: needs changes 🔧, needs review 👓

#655 Control Cards on the Bridge UI
  packages/page-statistics/src/pages/BridgeControlShowcase.tsx
  packages/page-statistics/src/routes/index.tsx
  packages/webb-ui-components/package.json
  packages/webb-ui-components/src/components/AmountMenu/AmountMenu.tsx
  packages/webb-ui-components/src/components/AmountMenu/index.ts
  packages/webb-ui-components/src/components/AmountMenu/types.d.ts
  packages/webb-ui-components/src/components/BridgeInputs/AmountInput.tsx
  packages/webb-ui-components/src/components/BridgeInputs/BridgeInputGroup.tsx
  packages/webb-ui-components/src/components/BridgeInputs/CustomAmount.tsx
  packages/webb-ui-components/src/components/BridgeInputs/FixedAmount.tsx
  packages/webb-ui-components/src/components/BridgeInputs/InfoItem.tsx
  packages/webb-ui-components/src/components/BridgeInputs/InputWrapper.tsx
  packages/webb-ui-components/src/components/BridgeInputs/RecipientInput.tsx
  packages/webb-ui-components/src/components/BridgeInputs/ShieldedAssetInput.tsx
  packages/webb-ui-components/src/components/BridgeInputs/TokenInput.tsx
  packages/webb-ui-components/src/components/BridgeInputs/index.ts
  packages/webb-ui-components/src/components/BridgeInputs/types.d.ts
  packages/webb-ui-components/src/components/Button/Button.tsx
  packages/webb-ui-components/src/components/Button/utils.ts
  packages/webb-ui-components/src/components/Popover/Popover.tsx
  packages/webb-ui-components/src/components/Popover/PopoverArrow.tsx
  packages/webb-ui-components/src/components/Popover/PopoverClose.tsx
  packages/webb-ui-components/src/components/Popover/PopoverContent.tsx
  packages/webb-ui-components/src/components/Popover/PopoverTrigger.tsx
  packages/webb-ui-components/src/components/Popover/index.ts
  packages/webb-ui-components/src/components/Popover/types.d.ts
  packages/webb-ui-components/src/components/TitleWithInfo/types.d.ts
  packages/webb-ui-components/src/components/Tooltip/Tooltip.tsx
  packages/webb-ui-components/src/components/index.ts
  packages/webb-ui-components/src/containers/DepositCard/DepositCard.tsx
  packages/webb-ui-components/src/containers/DepositCard/index.ts
  packages/webb-ui-components/src/containers/DepositCard/types.d.ts
  packages/webb-ui-components/src/containers/TransferCard/TransferCard.tsx
  packages/webb-ui-components/src/containers/TransferCard/index.ts
  packages/webb-ui-components/src/containers/TransferCard/types.d.ts
  packages/webb-ui-components/src/containers/WithdrawCard/WithdrawCard.tsx
  packages/webb-ui-components/src/containers/WithdrawCard/index.ts
  packages/webb-ui-components/src/containers/WithdrawCard/types.d.ts
  packages/webb-ui-components/src/containers/index.ts
  packages/webb-ui-components/src/css/layer-components.css
  yarn.lock
Labels: needs review 👓

#646 Implemented Filters for proposals and authorities tables
  graphql.schema.json
  packages/api-providers/__test__/utils/mock-config.ts
  packages/api-providers/src/types/abstracts.ts
  packages/apps/src/configs/chains/evm/index.tsx
  packages/apps/src/configs/chains/substrate/index.tsx
  packages/apps/src/configs/currencies/currency-config.ts
  packages/apps/src/configs/logos/Eth.tsx
  packages/apps/src/configs/logos/WebbWrappedLogo.tsx
  packages/apps/src/configs/logos/chains/ArbitrumLogo.tsx
  packages/apps/src/configs/logos/chains/GanacheLogo.tsx
  packages/apps/src/configs/logos/chains/KusamaLogo.tsx
  packages/apps/src/configs/logos/chains/OptimismLogo.tsx
  packages/apps/src/configs/logos/chains/PolkadotLogo.tsx
  packages/apps/src/configs/logos/chains/PolygonLogo.tsx
  packages/apps/src/configs/logos/chains/WebbLogo.tsx
  packages/page-statistics/src/containers/AuthoritiesTable/AuthoritiesTable.tsx
  packages/page-statistics/src/containers/Layout/Layout.tsx
  packages/page-statistics/src/containers/ProposalDetail/ProposalDetail.tsx
  packages/page-statistics/src/containers/ProposalsTable/ProposalsTable.tsx
  packages/page-statistics/src/generated/graphql.tsx
  packages/page-statistics/src/gql/authorites.graphql
  packages/page-statistics/src/gql/fragments.graphql
  packages/page-statistics/src/gql/metadata.graphql
  packages/page-statistics/src/gql/proposals.graphql
  packages/page-statistics/src/pages/Proposals.tsx
  packages/page-statistics/src/provider/hooks/mappers/index.ts
  packages/page-statistics/src/provider/hooks/useAuthorities.ts
  packages/page-statistics/src/provider/hooks/useKeys.ts
  packages/page-statistics/src/provider/hooks/useProposals.ts
  packages/webb-ui-components/src/components/CheckBox/Checkbox.tsx
  packages/webb-ui-components/src/components/CheckBoxMenu/CheckBoxMenu.tsx
  packages/webb-ui-components/src/components/CheckBoxMenu/CheckBoxMenuGroup.tsx
  packages/webb-ui-components/src/components/CheckBoxMenu/index.ts
  packages/webb-ui-components/src/components/CheckBoxMenu/types.d.ts
  packages/webb-ui-components/src/components/Filter/Filter.tsx
  packages/webb-ui-components/src/components/Filter/types.d.ts
  schema.graphql
Labels: needs changes 🔧, needs review 👓

#662 Add Wallet Connection Card
  package.json
  packages/page-statistics/src/hooks/useDonutColor.ts
  packages/page-statistics/src/pages/AuthoritiesHistory.tsx
  packages/page-statistics/types/index.d.ts
  packages/webb-ui-components/.storybook/main.js
  packages/webb-ui-components/package.json
  packages/webb-ui-components/src/components/BridgeInputs/InputWrapper.tsx
  packages/webb-ui-components/src/components/WalletConnectionCard/WalletConnectionCard.tsx
  packages/webb-ui-components/src/components/WalletConnectionCard/index.ts
  packages/webb-ui-components/src/components/WalletConnectionCard/types.d.ts
  packages/webb-ui-components/src/components/index.ts
  packages/webb-ui-components/src/containers/DepositCard/DepositCard.tsx
  packages/webb-ui-components/src/containers/TransferCard/TransferCard.tsx
  packages/webb-ui-components/src/containers/WithdrawCard/WithdrawCard.tsx
  packages/webb-ui-components/src/css/layer-base.css
  packages/webb-ui-components/src/icons/WalletLineIcon.tsx
  packages/webb-ui-components/src/icons/create-icon.tsx
  packages/webb-ui-components/src/icons/index.ts
  packages/webb-ui-components/src/icons/wallets/MetaMaskIcon.tsx
  packages/webb-ui-components/src/icons/wallets/PolkadotJsIcon.tsx
  packages/webb-ui-components/src/icons/wallets/SubWalletIcon.tsx
  packages/webb-ui-components/src/icons/wallets/TalismanIcon.tsx
  packages/webb-ui-components/src/icons/wallets/WalletConnectIcon.tsx
  packages/webb-ui-components/src/icons/wallets/index.ts
  packages/webb-ui-components/src/stories/templates/WalletConnectionCard.stories.jsx
  packages/webb-ui-components/src/tailwind.css
  packages/webb-ui-components/src/types/index.d.ts
  packages/webb-ui-components/src/typography/Typography/Typography.tsx
  packages/webb-ui-components/src/typography/utils/index.ts
  yarn.lock
Labels: needs review 👓

#664 Top Navigation Menu Component
  packages/page-statistics/src/components/Header/Header.tsx
  packages/webb-ui-components/src/components/NagivationMenu/NavigationMenu.tsx
  packages/webb-ui-components/src/components/NagivationMenu/NavigationMenuContent.tsx
  packages/webb-ui-components/src/components/NagivationMenu/NavigationMenuTrigger.tsx
  packages/webb-ui-components/src/components/NagivationMenu/index.ts
  packages/webb-ui-components/src/components/NagivationMenu/types.d.ts
  packages/webb-ui-components/src/components/index.ts
  packages/webb-ui-components/src/icons/BookOpenLineIcon.tsx
  packages/webb-ui-components/src/icons/FlaskLineIcon.tsx
  packages/webb-ui-components/src/icons/HelpLineIcon.tsx
  packages/webb-ui-components/src/icons/ThreeDotsVerticalIcon.tsx
  packages/webb-ui-components/src/icons/index.ts
  packages/webb-ui-components/src/stories/molecules/TopNavigationMenu.stories.jsx
Labels: needs review 👓

#668 Fix Storybook With Mono Repo
  .storybook/main.js
  .storybook/tsconfig.json
  apps/bridge-dapp/postcss.config.js
  apps/bridge-dapp/webpack.base.js
  apps/stats-dapp/src/containers/ProposalDetail/ProposalDetail.tsx
  babel.config.json
  libs/webb-ui-components/.babelrc.json
  libs/webb-ui-components/.storybook/main.cjs
  libs/webb-ui-components/.storybook/main.js
  libs/webb-ui-components/.storybook/preview.js
  libs/webb-ui-components/.storybook/tsconfig.json
  libs/webb-ui-components/package.json
  libs/webb-ui-components/postcss.config.js
  libs/webb-ui-components/project.json
  libs/webb-ui-components/rollup.config.js
  libs/webb-ui-components/src/css/fonts/BreezeSans-Bold.ttf
  libs/webb-ui-components/src/css/fonts/BreezeSans-Medium.ttf
  libs/webb-ui-components/src/css/fonts/BreezeSans-Regular.ttf
  libs/webb-ui-components/src/css/fonts/Cousine-Bold.ttf
  libs/webb-ui-components/src/css/fonts/Cousine-Regular.ttf
  libs/webb-ui-components/src/stories/molecules/AmountMenu.stories.jsx
  libs/webb-ui-components/src/stories/molecules/Avatar.stories.jsx
  libs/webb-ui-components/src/stories/molecules/AvatarGroup.stories.jsx
  libs/webb-ui-components/src/stories/molecules/BridgeInputGroup.stories.jsx
  libs/webb-ui-components/src/stories/molecules/Card.stories.jsx
  libs/webb-ui-components/src/stories/molecules/CardTable.stories.jsx
  libs/webb-ui-components/src/stories/molecules/CheckBoxMenu.stories.jsx
  libs/webb-ui-components/src/stories/molecules/Collapsible.stories.jsx
  libs/webb-ui-components/src/stories/molecules/CopyWithToolTip.stories.jsx
  libs/webb-ui-components/src/stories/molecules/InfoItem.stories.jsx
  libs/webb-ui-components/src/stories/molecules/Input.stories.jsx
  libs/webb-ui-components/src/stories/molecules/KeyValueWithButton.stories.jsx
  libs/webb-ui-components/src/stories/molecules/Label.stories.jsx
  libs/webb-ui-components/src/stories/molecules/LabelWithValue.stories.jsx
  libs/webb-ui-components/src/stories/molecules/MenuItem.stories.jsx
  libs/webb-ui-components/src/stories/molecules/Progress.stories.jsx
  libs/webb-ui-components/src/stories/molecules/RecipientInput.stories.jsx
  libs/webb-ui-components/src/stories/molecules/RelayerInput.stories.jsx
  libs/webb-ui-components/src/stories/molecules/ShieldedAssetInput.stories.jsx
  libs/webb-ui-components/src/stories/molecules/Stats.stories.jsx
  libs/webb-ui-components/src/stories/molecules/Tabs.stories.jsx
  libs/webb-ui-components/src/stories/molecules/ThemeSwitcher.stories.jsx
  libs/webb-ui-components/src/stories/molecules/TitleWithInfo.stories.jsx
  libs/webb-ui-components/src/stories/molecules/TokenPair.stories.jsx
  libs/webb-ui-components/src/stories/molecules/TokenRing.stories.jsx
  libs/webb-ui-components/src/stories/molecules/TopNavigationMenu.stories.jsx
  libs/webb-ui-components/src/stories/organisms/NetworkThresholdCard.stories.jsx
  libs/webb-ui-components/src/stories/templates/DepositCard.stories.jsx
  libs/webb-ui-components/src/stories/templates/DepositConfirm.stories.jsx
  libs/webb-ui-components/src/stories/templates/TransferCard.stories.jsx
  libs/webb-ui-components/src/stories/templates/TransferConfirm.stories.jsx
  libs/webb-ui-components/src/stories/templates/WalletConnectionCard.stories.jsx
  libs/webb-ui-components/src/stories/templates/WithdrawCard.stories.jsx
  libs/webb-ui-components/src/stories/templates/WithdrawConfirm.stories.jsx
  nx.json
  package.json
  yarn.lock
Labels: needs review 👓

#670 Add GraphQL Type Generation Script With Mono Repo
  .graphqlconfig
  codegen.yml
  package.json
  yarn.lock
Labels: needs review 👓
