Repository tangle-network/dapp, pull requests merged in 2022-11, with the labels that each got.

#660 Implement Transaction processing card
  apps/bridge-dapp/src/types/index.ts
  apps/stats-dapp/src/containers/BridgeInputsShowCase/BridgeInputsShowCase.tsx
  apps/stats-dapp/src/containers/BridgeInputsShowCase/index.ts
  apps/stats-dapp/src/containers/BridgeInputsShowCase/types.ts
  apps/stats-dapp/src/containers/ListCardsShowcase/ListCardsShowcase.tsx
  apps/stats-dapp/src/containers/ListCardsShowcase/index.ts
  apps/stats-dapp/src/containers/index.ts
  apps/stats-dapp/src/hooks/useDonutColor.ts
  apps/stats-dapp/src/pages/BridgeControlShowcase.tsx
  apps/stats-dapp/src/pages/ComponentsShowcase.tsx
  apps/stats-dapp/src/routes/index.tsx
  libs/icons/src/Alert.tsx
  libs/icons/src/AlertFill.tsx
  libs/icons/src/PartyFill.tsx
  libs/icons/src/WalletLine.tsx
  libs/icons/src/index.ts
  libs/webb-ui-components/package.json
  libs/webb-ui-components/rollup.config.js
  libs/webb-ui-components/src/components/Disclaimer/Disclaimer.tsx
  libs/webb-ui-components/src/components/Disclaimer/index.ts
  libs/webb-ui-components/src/components/Disclaimer/types.d.ts
  libs/webb-ui-components/src/components/index.ts
  libs/webb-ui-components/src/containers/TransactionProgressCard/TransactionCardFooter.tsx
  libs/webb-ui-components/src/containers/TransactionProgressCard/TransactionProgressCard.tsx
  libs/webb-ui-components/src/containers/TransactionProgressCard/TransactionQueueCard.tsx
  libs/webb-ui-components/src/containers/TransactionProgressCard/index.ts
  libs/webb-ui-components/src/containers/TransactionProgressCard/success-tx.json
  libs/webb-ui-components/src/containers/TransactionProgressCard/types.ts
  libs/webb-ui-components/src/containers/index.ts
  libs/webb-ui-components/src/css/layer-components.css
  libs/webb-ui-components/src/stories/molecules/Disclaimer.stories.jsx
  libs/webb-ui-components/src/stories/organisms/KeyStatusCard.stories.jsx
  libs/webb-ui-components/src/stories/templates/TransactionProccessingCard.stories.jsx
  libs/webb-ui-components/src/stories/templates/TransactionQueueCard.stories.jsx
  package.json
  yarn.lock
Labels: needs review 👓, bridge

#654 Decode proposal data
  apps/bridge-dapp/package.json
  apps/stats-dapp/src/containers/ProposalDetail/ProposalDetail.tsx
  apps/stats-dapp/src/utils/getProposalsData.ts
  apps/stats-dapp/src/utils/index.ts
  libs/abstract-api-provider/package.json
  libs/api-provider-environment/package.json
  libs/browser-utils/package.json
  libs/evm-contracts/src/webb-vanchor.ts
  libs/polkadot-api-provider/src/webb-provider/vanchor-deposit.ts
  libs/polkadot-api-provider/src/webb-provider/vanchor-withdraw.ts
  libs/react-environment/package.json
  libs/webb-ui-components/package.json
  package.json
  yarn.lock
Labels: needs review 👓

#673 chore: update github ci and readme
  .github/workflows/deploy-bridge-dapp-dev.yml
  .github/workflows/deploy-stats-dapp-dev.yml
  .github/workflows/deploy-storybook-docs.yml
  README.md
Labels: needs review 👓

#656 Better GraphQL error handling
  apps/bridge-dapp/package.json
  apps/stats-dapp/src/components/Header/Header.tsx
  apps/stats-dapp/src/containers/AuthoritiesTable/AuthoritiesTable.tsx
  apps/stats-dapp/src/containers/AuthorityDetail/AuthorityDetail.tsx
  apps/stats-dapp/src/containers/KeyDetail/KeyDetail.tsx
  apps/stats-dapp/src/containers/KeygenTable/KeygenTable.tsx
  apps/stats-dapp/src/containers/Layout/Layout.tsx
  apps/stats-dapp/src/containers/ProposalDetail/ProposalDetail.tsx
  apps/stats-dapp/src/containers/ProposalsTable/ProposalsTable.tsx
  apps/stats-dapp/src/containers/ProposersTable/ProposersTable.tsx
  apps/stats-dapp/src/generated/graphql.tsx
  apps/stats-dapp/src/gql/metadata.graphql
  apps/stats-dapp/src/gql/proposals.graphql
  apps/stats-dapp/src/pages/AuthoritiesHistory.tsx
  apps/stats-dapp/src/pages/Keys.tsx
  apps/stats-dapp/src/pages/Proposals.tsx
  apps/stats-dapp/src/provider/hooks/mappers/thresholds.ts
  apps/stats-dapp/src/provider/hooks/useAuthorities.ts
  apps/stats-dapp/src/provider/hooks/useProposals.ts
  apps/stats-dapp/src/utils/getChipColorByProposalType.ts
  apps/stats-dapp/src/utils/getProposalsData.ts
  apps/stats-dapp/src/utils/index.ts
  apps/stats-dapp/src/utils/mapChainIdToCurrencyName.ts
  apps/stats-dapp/webpack.config.js
  graphql.schema.json
  libs/dapp-config/src/chains/chain-config.interface.ts
  libs/dapp-config/src/chains/evm/index.tsx
  libs/dapp-config/src/chains/substrate/index.tsx
  libs/webb-ui-components/package.json
  libs/webb-ui-components/src/components/Accordion/Accordion.tsx
  libs/webb-ui-components/src/components/Accordion/AccordionButton.tsx
  libs/webb-ui-components/src/components/Accordion/AccordionContent.tsx
  libs/webb-ui-components/src/components/Accordion/AccordionItem.tsx
  libs/webb-ui-components/src/components/Accordion/index.ts
  libs/webb-ui-components/src/components/Accordion/types.ts
  libs/webb-ui-components/src/components/KeyValueWithButton/KeyValueWithButton.tsx
  libs/webb-ui-components/src/components/Progress/Progress.tsx
  libs/webb-ui-components/src/components/TitleWithInfo/TitleWithInfo.tsx
  libs/webb-ui-components/src/components/index.ts
  libs/webb-ui-components/src/stories/molecules/Accordion.stories.jsx
  schema.graphql
  yarn.lock
Labels: needs review 👓

#690 Integrate Account Creation Flow
  apps/bridge-dapp/src/assets/privacy.gif
  apps/bridge-dapp/src/components/Header/ChainSwitcherButton.tsx
  apps/bridge-dapp/src/components/Header/Header.tsx
  apps/bridge-dapp/src/containers/CreateAccountModal/CreateAccountModal.tsx
  apps/bridge-dapp/src/containers/CreateAccountModal/index.ts
  apps/bridge-dapp/src/containers/CreateAccountModal/types.d.ts
  apps/bridge-dapp/src/containers/DepositContainer/DepositContainer.tsx
  apps/bridge-dapp/src/containers/ShieldedAssetsTableContainer/ShieldedAssetsTableContainer.tsx
  apps/bridge-dapp/src/containers/SpendNotesTableContainer/SpendNotesTableContainer.tsx
  apps/bridge-dapp/src/containers/index.ts
  apps/bridge-dapp/src/hooks/index.ts
  apps/bridge-dapp/src/hooks/useShieldedAssets.ts
  apps/bridge-dapp/src/hooks/useSpendNotes.ts
  apps/bridge-dapp/src/pages/PageBridge.tsx
  libs/evm-contracts/src/webb-vanchor.ts
  libs/icons/src/TimeLineIcon.tsx
  libs/icons/src/index.ts
  libs/web3-api-provider/src/webb-provider/vanchor-deposit.ts
  libs/webb-ui-components/src/components/Button/Button.tsx
  libs/webb-ui-components/src/components/CheckBox/Checkbox.tsx
  libs/webb-ui-components/src/components/CheckBox/types.ts
  libs/webb-ui-components/src/components/Modal/ModalFooter.tsx
  libs/webb-ui-components/src/components/Modal/ModalHeader.tsx
  libs/webb-ui-components/src/components/Modal/index.ts
  libs/webb-ui-components/src/components/Modal/types.d.ts
  libs/webb-ui-components/src/containers/TransactionProgressCard/types.ts
Labels: wip 🚧

#694 Setup Notification And Note Upload Flow
  apps/bridge-dapp/src/components/Header/ClearDataModal.tsx
  apps/bridge-dapp/src/components/Header/WalletButton.tsx
  apps/bridge-dapp/src/containers/CreateAccountModal/CreateAccountModal.tsx
  apps/bridge-dapp/src/containers/CreateAccountModal/congrat.json
  apps/bridge-dapp/src/containers/CreateAccountModal/privacy-security.json
  apps/bridge-dapp/src/containers/DepositContainer/DepositConfirmContainer.tsx
  apps/bridge-dapp/src/containers/ShieldedAssetsTableContainer/ShieldedAssetsTableContainer.tsx
  apps/bridge-dapp/src/containers/ShieldedAssetsTableContainer/types.d.ts
  apps/bridge-dapp/src/containers/SpendNotesTableContainer/SpendNotesTableContainer.tsx
  apps/bridge-dapp/src/containers/SpendNotesTableContainer/types.d.ts
  apps/bridge-dapp/src/containers/UploadSpendNoteModal/PasteModalContent.tsx
  apps/bridge-dapp/src/containers/UploadSpendNoteModal/UploadModalContent.tsx
  apps/bridge-dapp/src/containers/UploadSpendNoteModal/UploadSpendNoteModal.tsx
  apps/bridge-dapp/src/containers/UploadSpendNoteModal/index.ts
  apps/bridge-dapp/src/containers/UploadSpendNoteModal/types.d.ts
  apps/bridge-dapp/src/containers/index.ts
  apps/bridge-dapp/src/hooks/useConnectWallet.ts
  apps/bridge-dapp/src/pages/PageBridge.tsx
  apps/bridge-dapp/src/public/index.html
  apps/bridge-dapp/tsconfig.app.json
  libs/icons/src/FileUploadLine.tsx
  libs/icons/src/LoginBoxLineIcon.tsx
  libs/icons/src/chains/substrate.svg
  libs/icons/src/chains/tangle.svg
  libs/icons/src/index.ts
  libs/icons/src/tokens/webb.svg
  libs/icons/src/tokens/webb^2.svg
  libs/icons/src/tokens/webbdev.svg
  libs/note-manager/src/note-manager.ts
  libs/webb-ui-components/src/components/Button/utils.ts
  libs/webb-ui-components/src/components/FileUploads/FileUploadArea.tsx
  libs/webb-ui-components/src/components/FileUploads/FileUploadField.tsx
  libs/webb-ui-components/src/components/FileUploads/FileUploadItem.tsx
  libs/webb-ui-components/src/components/FileUploads/FileUploadList.tsx
  libs/webb-ui-components/src/components/FileUploads/index.ts
  libs/webb-ui-components/src/components/FileUploads/types.d.ts
  libs/webb-ui-components/src/components/Notification/NotificationContext.tsx
  libs/webb-ui-components/src/components/Notification/NotificationItem.tsx
  libs/webb-ui-components/src/components/Notification/NotificationProvider.tsx
  libs/webb-ui-components/src/components/Notification/NotificationStacked.tsx
  libs/webb-ui-components/src/components/Notification/index.ts
  libs/webb-ui-components/src/components/Notification/types.d.ts
  libs/webb-ui-components/src/components/TokenPairIcons/TokenPairIcons.tsx
  libs/webb-ui-components/src/components/TokenPairIcons/index.ts
  libs/webb-ui-components/src/components/TokenPairIcons/types.d.ts
  libs/webb-ui-components/src/components/index.ts
  libs/webb-ui-components/src/containers/TransactionProgressCard/TransactionProgressCard.tsx
  libs/webb-ui-components/src/provider/index.tsx
  libs/webb-ui-components/src/provider/types.ts
  libs/webb-ui-components/src/utils/getHumanFileSize.ts
  libs/webb-ui-components/src/utils/index.ts
  libs/webb-ui-components/tsconfig.json
  package.json
  yarn.lock
Labels: needs review 👓

#696 Update DKG authority uptime integration
  apps/stats-dapp/src/generated/graphql.tsx
  apps/stats-dapp/src/provider/hooks/useAuthorities.ts
  apps/stats-dapp/src/provider/hooks/useKeys.ts
  graphql.schema.json
  schema.graphql
Labels: wip 🚧

#700 Handle error when insufficient balance and add spend notes table data
  apps/bridge-dapp/src/components/Header/ClearDataModal.tsx
  apps/bridge-dapp/src/components/Header/Header.tsx
  apps/bridge-dapp/src/components/Header/WalletButton.tsx
  apps/bridge-dapp/src/containers/DepositContainer/DepositConfirmContainer.tsx
  apps/bridge-dapp/src/containers/DepositContainer/DepositContainer.tsx
  apps/bridge-dapp/src/containers/ShieldedAssetsTableContainer/ShieldedAssetsTableContainer.tsx
  apps/bridge-dapp/src/containers/ShieldedAssetsTableContainer/types.d.ts
  apps/bridge-dapp/src/containers/SpendNotesTableContainer/SpendNotesTableContainer.tsx
  apps/bridge-dapp/src/containers/SpendNotesTableContainer/types.d.ts
  apps/bridge-dapp/src/hooks/useSpendNotes.ts
  apps/bridge-dapp/src/pages/PageBridge.tsx
  libs/icons/src/ChainIcon.tsx
  libs/icons/src/tokens/dev.svg
  libs/react-hooks/src/currency/useCurrenciesBalances.tsx
  libs/react-hooks/src/deposit/useBridgeDeposit.tsx
  yarn.lock
Labels: needs review 👓

#715 Update to latest networks
  apps/bridge-dapp/src/assets/privacy.gif
  apps/bridge-dapp/src/containers/CreateAccountModal/CreateAccountModal.tsx
  libs/api-provider-environment/src/WebbProvider.tsx
  libs/api-provider-environment/src/error/interactive-errors/unsupported-chain.ts
  libs/dapp-config/src/chains/evm/index.tsx
  libs/dapp-config/src/currencies/currency-config.ts
  libs/dapp-config/src/wallets/wallets-config.tsx
  libs/dapp-types/src/ChainId.ts
  libs/react-hooks/src/currency/useCurrencyBalance.tsx
  libs/webb-ui-components/src/components/Notification/NotificationItem.tsx
Labels: needs review 👓

#718 Populated the shielded assets data
  apps/bridge-dapp/src/containers/ShieldedAssetsTableContainer/ShieldedAssetsTableContainer.tsx
  apps/bridge-dapp/src/containers/ShieldedAssetsTableContainer/types.d.ts
  apps/bridge-dapp/src/containers/SpendNotesTableContainer/SpendNotesTableContainer.tsx
  apps/bridge-dapp/src/containers/SpendNotesTableContainer/types.d.ts
  apps/bridge-dapp/src/hooks/useShieldedAssets.ts
  apps/bridge-dapp/src/hooks/useSpendNotes.ts
  libs/react-hooks/src/currency/useCurrencies.tsx
Labels: needs review 👓

#701 Update authority location query and handle unknown authority location
  apps/stats-dapp/src/components/CountryIcon/CountryIcon.tsx
  apps/stats-dapp/src/containers/AuthoritiesTable/AuthoritiesTable.tsx
  apps/stats-dapp/src/containers/AuthorityDetail/AuthorityDetail.tsx
  apps/stats-dapp/src/generated/graphql.tsx
  apps/stats-dapp/src/gql/authorites.graphql
  apps/stats-dapp/src/gql/fragments.graphql
  apps/stats-dapp/src/provider/hooks/mappers/index.ts
  apps/stats-dapp/src/provider/hooks/useAuthorities.ts
  graphql.schema.json
Labels: needs changes 🔧

#721 Chain rings component
  apps/bridge-dapp/src/containers/DepositContainer/DepositConfirmContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawConfirmContainer.tsx
  libs/webb-ui-components/src/components/ChainsRing/ChainsRing.tsx
  libs/webb-ui-components/src/components/ChainsRing/index.ts
  libs/webb-ui-components/src/components/ChainsRing/types.d.ts
  libs/webb-ui-components/src/components/index.ts
  libs/webb-ui-components/src/containers/ConfirmationCard/DepositConfirm.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/TransferConfirm.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/WithdrawConfirm.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/types.ts
Labels: needs review 👓

#722 The Withdraw Flow
  apps/bridge-dapp/src/containers/CreateAccountModal/CreateAccountModal.tsx
  apps/bridge-dapp/src/containers/DepositContainer/DepositContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawConfirmContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/types.d.ts
  apps/bridge-dapp/src/hooks/index.ts
  apps/bridge-dapp/src/hooks/useShieldedAssets.ts
  apps/bridge-dapp/src/hooks/useSpendNotes.ts
  apps/bridge-dapp/src/hooks/useTransactionProgressValue.ts
  apps/bridge-dapp/src/hooks/useTransactionStage.ts
  apps/bridge-dapp/src/pages/PageBridge.tsx
  libs/abstract-api-provider/src/vanchor/vanchor-withdraw.ts
  libs/dapp-config/src/currencies/currency-config.ts
  libs/evm-contracts/src/webb-vanchor.ts
  libs/note-manager/src/note-manager.ts
  libs/polkadot-api-provider/src/webb-provider/vanchor-withdraw.ts
  libs/react-hooks/src/bridge/useBridge.tsx
  libs/react-hooks/src/relayer/useRelayers.ts
  libs/react-hooks/src/transfer/useTransfer.tsx
  libs/react-hooks/src/withdraw/useWithdraw.tsx
  libs/react-hooks/tsconfig.lib.json
  libs/web3-api-provider/src/webb-provider.ts
  libs/web3-api-provider/src/webb-provider/vanchor-deposit.ts
  libs/web3-api-provider/src/webb-provider/vanchor-withdraw.ts
  libs/webb-ui-components/src/components/BridgeInputs/AmountInput.tsx
  libs/webb-ui-components/src/components/BridgeInputs/FixedAmount.tsx
  libs/webb-ui-components/src/components/BridgeInputs/RelayerInput.tsx
  libs/webb-ui-components/src/components/BridgeInputs/types.ts
  libs/webb-ui-components/src/components/ListCard/RelayerListCard.tsx
  libs/webb-ui-components/src/components/ListCard/types.ts
  libs/webb-ui-components/src/containers/ConfirmationCard/DepositConfirm.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/WithdrawConfirm.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/WrapperSection.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/types.ts
  libs/webb-ui-components/src/containers/WithdrawCard/WithdrawCard.tsx
  libs/webb-ui-components/src/containers/WithdrawCard/types.ts
Labels: needs review 👓

#734 Adding tooltips and dropdown for the note account table
  apps/bridge-dapp/package.json
  apps/bridge-dapp/src/containers/ShieldedAssetsTableContainer/ShieldedAssetsTableContainer.tsx
  apps/bridge-dapp/src/containers/SpendNotesTableContainer/SpendNotesTableContainer.tsx
  apps/stats-dapp/package.json
  libs/tailwind-preset/package.json
  libs/webb-ui-components/src/components/IconWithTooltip/IconWithTooltip.tsx
  libs/webb-ui-components/src/components/IconWithTooltip/index.ts
  libs/webb-ui-components/src/components/IconWithTooltip/types.d.ts
  libs/webb-ui-components/src/components/Table/TData.tsx
  libs/webb-ui-components/src/components/Table/Table.tsx
  libs/webb-ui-components/src/components/TokenPairIcons/TokenPairIcons.tsx
  libs/webb-ui-components/src/components/index.ts
  package.json
  yarn.lock
Labels: needs review 👓
