Repository tangle-network/dapp, pull requests merged in 2022-07, with the labels that each got.

#447 Mockup UI for DKG/Eggnet Statistics Page
  packages/apps/public/index.html
  packages/apps/src/sidebar-config.tsx
  packages/page-statistics/package.json
  packages/page-statistics/src/DKGStatistics.tsx
  packages/page-statistics/src/DKGStatistics/DKGStatistics.tsx
  packages/page-statistics/src/DKGStatistics/DescriptionIcon/DescriptionIcon.tsx
  packages/page-statistics/src/DKGStatistics/DescriptionIcon/index.ts
  packages/page-statistics/src/DKGStatistics/DescriptionIcon/styled/DescriptionText.styled.tsx
  packages/page-statistics/src/DKGStatistics/DescriptionIcon/styled/index.ts
  packages/page-statistics/src/DKGStatistics/StatisticCard/StatisticCard.tsx
  packages/page-statistics/src/DKGStatistics/StatisticCard/index.ts
  packages/page-statistics/src/DKGStatistics/StatisticCard/styled/StatisticCardWrapper.styled.tsx
  packages/page-statistics/src/DKGStatistics/StatisticCard/styled/index.ts
  packages/page-statistics/src/DKGStatistics/index.ts
  packages/page-statistics/src/DKGStatistics/styled/ChartLabelsWrapper.styled.tsx
  packages/page-statistics/src/DKGStatistics/styled/ChartWrapper.styled.tsx
  packages/page-statistics/src/DKGStatistics/styled/DKGEggnetStatisticsWrapper.styled.tsx
  packages/page-statistics/src/DKGStatistics/styled/DKGSignerWrapper.styled.tsx
  packages/page-statistics/src/DKGStatistics/styled/GridWrapper.styled.tsx
  packages/page-statistics/src/DKGStatistics/styled/StatisticCardsList.styled.tsx
  packages/page-statistics/src/DKGStatistics/styled/index.ts
  packages/page-statistics/src/DKGStatistics/styled/shared/CardWrapper.styled.tsx
  packages/page-statistics/src/DKGStatistics/styled/shared/index.ts
  packages/page-statistics/src/DKGStatistics/useDKGEggnetStats.ts
  packages/page-statistics/src/index.tsx
  packages/react-components/src/AppBar/AppBar.tsx
  packages/react-components/src/Sidebar/Products.tsx
  packages/ui-components/src/assets/InformationIcon/InformationIcon.tsx
  packages/ui-components/src/assets/InformationIcon/index.ts
  yarn.lock
Labels: approved ✅, needs changes 🔧

#455 Re-style tabs
  packages/bridge/src/components/Deposit/Deposit.tsx
  packages/bridge/src/components/Withdraw/Withdraw.tsx
  packages/mixer/src/components/Deposit/Deposit.tsx
  packages/mixer/src/components/Withdraw/Withdraw.tsx
  packages/page-wrap-unwrap/src/index.tsx
  packages/ui-components/src/Inputs/WalletSelect/WalletSelect.tsx
  packages/ui-components/src/Tabs/MixerTabs.tsx
  packages/ui-components/src/assets/DepositIcon.tsx
  packages/ui-components/src/assets/WithdrawIcon.tsx
  packages/vbridge/src/components/Deposit/Deposit.tsx
  packages/vbridge/src/components/Withdraw/Withdraw.tsx
Labels: needs review 👓

#449 Add VAnchor 8sided EVM testnet bridge
  package.json
  packages/api-providers/package.json
  packages/api-providers/src/chains/chain-id.enum.ts
  packages/api-providers/src/chains/chain-utils.ts
  packages/api-providers/src/contracts/wrappers/webb-vanchor.ts
  packages/api-providers/src/enums/webb-currency-id.enum.ts
  packages/api-providers/src/ext-providers/web3/web3-provider.ts
  packages/api-providers/src/utils/storage.ts
  packages/api-providers/src/web3/vanchor-deposit.ts
  packages/apps/src/configs/anchors/anchor-config.ts
  packages/apps/src/configs/chains/evm/index.ts
  packages/apps/src/configs/currencies/currency-config.ts
  packages/apps/src/configs/logos/chains/MoonbeamLogo.tsx
  packages/apps/src/configs/storage/app-storage.ts
  packages/apps/src/configs/storages/EvmChainStorage.ts
  packages/apps/src/configs/storages/bridge-storage.ts
  packages/apps/src/configs/storages/index.ts
  packages/apps/src/configs/wallets/wallets-config.ts
  packages/bridge/package.json
  packages/mixer/package.json
  packages/page-bridge/package.json
  packages/page-mixer/package.json
  packages/react-components/package.json
  packages/react-environment/package.json
  packages/react-environment/src/WebbProvider.tsx
  packages/react-hooks/package.json
  packages/vbridge/package.json
  packages/vbridge/src/components/Withdraw/Withdraw.tsx
  yarn.lock
Labels: needs review 👓

#458 Add the change note and standardize note amounts
  packages/api-providers/__test__/utils/mock-config.ts
  packages/api-providers/src/abstracts/anchor/vanchor-deposit.ts
  packages/api-providers/src/enums/webb-currency-id.enum.ts
  packages/api-providers/src/polkadot/mixer-deposit.ts
  packages/api-providers/src/polkadot/mixer-withdraw.ts
  packages/api-providers/src/polkadot/vanchor-deposit.ts
  packages/api-providers/src/polkadot/vanchor-withdraw.ts
  packages/api-providers/src/types/currency-config.interface.ts
  packages/api-providers/src/web3/anchor-withdraw.ts
  packages/api-providers/src/web3/vanchor-deposit.ts
  packages/api-providers/src/web3/vanchor-withdraw.ts
  packages/apps/src/configs/anchors/anchor-config.ts
  packages/apps/src/configs/bridges/bridge-config.ts
  packages/apps/src/configs/chains/evm/index.ts
  packages/apps/src/configs/currencies/currency-config.ts
  packages/bridge/src/components/DepositConfirm/DepositConfirm.tsx
  packages/bridge/src/components/Withdraw/Withdraw.tsx
  packages/mixer/src/components/DepositConfirm/DepositConfirm.tsx
  packages/mixer/src/components/Withdraw/Withdraw.tsx
  packages/react-components/src/NoteDisplay/ModalNoteDisplay.tsx
  packages/react-components/src/Withdraw/WithdrawSuccessModal.tsx
  packages/react-components/src/Withdraw/WithdrawingModal.tsx
  packages/vbridge/src/components/DepositConfirm/DepositConfirm.tsx
  packages/vbridge/src/components/NoteInput/NoteInput.tsx
  packages/vbridge/src/components/Withdraw/Withdraw.tsx
  packages/vbridge/src/hooks/withdraw/useWithdraw.tsx
Labels: approved ✅, needs review 👓

#452 VAnchor relaying transaction
  packages/api-providers/src/abstracts/relayer/types.ts
  packages/api-providers/src/abstracts/relayer/webb-relayer.ts
  packages/api-providers/src/contracts/wrappers/webb-vanchor.ts
  packages/api-providers/src/polkadot/mixer-withdraw.ts
  packages/api-providers/src/polkadot/vanchor-withdraw.ts
  packages/api-providers/src/web3/anchor-withdraw.ts
  packages/api-providers/src/web3/relayer-manager.ts
  packages/api-providers/src/web3/vanchor-deposit.ts
  packages/api-providers/src/web3/vanchor-withdraw.ts
  packages/apps/src/configs/anchors/anchor-config.ts
  packages/apps/src/configs/currencies/currency-config.ts
Labels: needs review 👓, wip 🚧
