Repository tangle-network/dapp, pull requests merged in 2022-08, with the labels that each got.

#477 chore: update pr template and add codeowners
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
Labels: needs review 👓

#475 Fix substrate native token not showing
  packages/api-providers/src/polkadot/anchor-api.ts
Labels: needs review 👓

#473 Fix balance display and disable the deposit button
  packages/api-providers/src/polkadot/anchor-api.ts
  packages/api-providers/src/polkadot/chain-query.ts
  packages/react-environment/src/WebbProvider.tsx
  packages/ui-components/src/utils/index.ts
  packages/vbridge/src/components/Deposit/Deposit.tsx
Labels: needs review 👓

#483 Aborting API calls
  packages/api-providers/src/abstracts/cancelation-token.ts
  packages/api-providers/src/abstracts/relayer/webb-relayer.ts
  packages/api-providers/src/contracts/wrappers/webb-vanchor.ts
  packages/api-providers/src/ipfs/evm/anchors.ts
  packages/api-providers/src/ipfs/substrate/vanchor.ts
  packages/api-providers/src/polkadot/vanchor-deposit.ts
  packages/api-providers/src/polkadot/vanchor-withdraw.ts
  packages/api-providers/src/utils/retry-promise.ts
  packages/api-providers/src/web3/relayer-manager.ts
  packages/api-providers/src/web3/vanchor-deposit.ts
  packages/api-providers/src/web3/vanchor-withdraw.ts
  packages/api-providers/src/web3/webb-provider.ts
  yarn.lock
Labels: needs review 👓

#485 EVM proofs in workers
  package.json
  packages/api-providers/__test__/web3.spec.ts
  packages/api-providers/package.json
  packages/api-providers/src/contracts/wrappers/webb-vanchor.ts
  packages/api-providers/src/polkadot/transaction.ts
  packages/api-providers/src/web3/vanchor-deposit.ts
  packages/api-providers/src/web3/vanchor-withdraw.ts
  packages/api-providers/src/web3/webb-provider.ts
  packages/mixer/package.json
  packages/page-mixer/package.json
  packages/react-components/package.json
  packages/react-environment/package.json
  packages/react-environment/src/WebbProvider.tsx
  packages/react-environment/src/circom-proving-manager.worker.ts
  packages/react-hooks/package.json
  packages/vbridge/package.json
  yarn.lock
Labels: needs review 👓

#492 Fix balance label
  packages/react-hooks/src/currency/useCurrencies.tsx
  packages/react-hooks/src/currency/useCurrencyBalance.tsx
Labels: needs review 👓

#491 Implemention of wrap/unwrap + wrap&deposit for substrate apis
  packages/api-providers/src/abstracts/currency/currency.ts
  packages/api-providers/src/abstracts/state/index.ts
  packages/api-providers/src/enums/webb-currency-id.enum.ts
  packages/api-providers/src/polkadot/bridge-api.ts
  packages/api-providers/src/polkadot/transaction.ts
  packages/api-providers/src/polkadot/vanchor-deposit.ts
  packages/api-providers/src/polkadot/vanchor-withdraw.ts
  packages/api-providers/src/polkadot/webb-provider.ts
  packages/api-providers/src/polkadot/wrap-unwrap.md
  packages/api-providers/src/polkadot/wrap-unwrap.ts
  packages/api-providers/src/web3/webb-provider.ts
  packages/apps/src/configs/anchors/anchor-config.ts
  packages/apps/src/configs/bridges/bridge-config.ts
  packages/apps/src/configs/currencies/currency-config.ts
  packages/page-wrap-unwrap/src/index.tsx
  packages/react-environment/src/WebbProvider.tsx
Labels: needs review 👓

#500 Register accounts on deposit and enable registration with MetaMask.
  packages/api-providers/src/abstracts/anchor/vanchor-registration.ts
  packages/api-providers/src/abstracts/webb-provider.interface.ts
  packages/api-providers/src/contracts/wrappers/webb-vanchor.ts
  packages/api-providers/src/notes/note-manager.ts
  packages/api-providers/src/polkadot/chain-query.ts
  packages/api-providers/src/polkadot/vanchor-registration.ts
  packages/api-providers/src/polkadot/webb-provider.ts
  packages/api-providers/src/utils/storage.ts
  packages/api-providers/src/web3/vanchor-deposit.ts
  packages/api-providers/src/web3/vanchor-registration.ts
  packages/api-providers/src/web3/webb-provider.ts
  packages/api-providers/src/web3/wrap-unwrap.ts
  packages/react-components/src/NoteAccount/NoteAccountDetails.tsx
  packages/react-components/src/PermissionedAccess/CreateNoteAccount.tsx
  packages/react-components/src/PermissionedAccess/RequiredNoteAccount.tsx
  packages/vbridge/src/VBridge.tsx
  packages/vbridge/src/components/Deposit/Deposit.tsx
  packages/vbridge/src/components/Withdraw/Withdraw.tsx
  packages/vbridge/src/hooks/deposit/useBridgeDeposit.tsx
Labels: needs review 👓

#496 ECDSA Claims page
  packages/api-providers/src/abstracts/ecdsa-claims/index.ts
  packages/api-providers/src/abstracts/webb-provider.interface.ts
  packages/api-providers/src/ext-providers/web3/web3-provider.ts
  packages/api-providers/src/polkadot/ecdsa-claims.ts
  packages/api-providers/src/polkadot/transaction.ts
  packages/api-providers/src/polkadot/vanchor-deposit.ts
  packages/api-providers/src/polkadot/webb-provider.ts
  packages/api-providers/src/web3/webb-provider.ts
  packages/apps/src/router-config.tsx
  packages/apps/src/sidebar-config.tsx
  packages/page-claims/README.md
  packages/page-claims/package.json
  packages/page-claims/src/hooks/index.ts
  packages/page-claims/src/hooks/useClaims.ts
  packages/page-claims/src/i18n/en.json
  packages/page-claims/src/i18n/zh.json
  packages/page-claims/src/index.tsx
  packages/ui-components/src/types.ts
  tsconfig.paths.json
Labels: needs review 👓

#498 Optimize leaf fetching
  package.json
  packages/api-providers/package.json
  packages/api-providers/src/web3/vanchor-withdraw.ts
  packages/mixer/package.json
  packages/page-mixer/package.json
  packages/react-components/package.json
  packages/react-environment/package.json
  packages/react-hooks/package.json
  packages/vbridge/package.json
  yarn.lock
Labels: approved ✅

#497 Integrate WeareTalisman wallet into the dApp
  packages/api-providers/src/ext-providers/polkadot/polkadot-accounts.ts
  packages/api-providers/src/ext-providers/polkadot/polkadot-provider.ts
  packages/api-providers/src/polkadot/mixer-withdraw.ts
  packages/api-providers/src/polkadot/transaction.ts
  packages/api-providers/src/polkadot/webb-provider.ts
  packages/api-providers/src/types/wallet-config.interface.ts
  packages/api-providers/src/webb-error/webb-error.class.ts
  packages/apps/src/configs/logos/wallets/TalismanLogo.tsx
  packages/apps/src/configs/logos/wallets/index.ts
  packages/apps/src/configs/wallets/wallet-id.enum.ts
  packages/apps/src/configs/wallets/wallets-config.ts
  packages/mixer/src/components/Deposit/Deposit.tsx
  packages/react-components/src/BottomWalletSelection/BottomWalletSelection.tsx
  packages/react-environment/src/WebbProvider.tsx
  packages/react-environment/src/error/interactive-errors/extension-not-installed.tsx
  packages/react-hooks/src/currency/useCurrencyBalance.tsx
  packages/react-hooks/src/currency/useNativeCurrencyBalance.tsx
  packages/ui-components/src/Inputs/WalletSelect/DisconnectedWalletView.tsx
  packages/ui-components/src/Inputs/WalletSelect/WalletDetails.tsx
  packages/ui-components/src/Inputs/WalletSelect/WalletSelect.tsx
  packages/ui-components/src/NetworkManager/NetworkManager.tsx
Labels: needs changes 🔧

#523 Integrate SubWallet into the dApp
  packages/api-providers/src/ext-providers/polkadot/polkadot-provider.ts
  packages/api-providers/src/webb-error/webb-error.class.ts
  packages/apps/src/configs/logos/wallets/SubWalletLogo.svg
  packages/apps/src/configs/logos/wallets/SubWalletLogo.tsx
  packages/apps/src/configs/logos/wallets/index.ts
  packages/apps/src/configs/wallets/wallet-id.enum.ts
  packages/apps/src/configs/wallets/wallets-config.ts
  packages/apps/src/react-app-env.d.ts
  packages/react-environment/src/WebbProvider.tsx
  packages/react-environment/src/error/interactive-errors/extension-not-installed.tsx
  packages/ui-components/src/Icon.tsx
Labels: needs review 👓

#494 Implement the NoteAccount and NoteManager
  packages/api-providers/__test__/web3.spec.ts
  packages/api-providers/src/abstracts/anchor/vanchor-registration.ts
  packages/api-providers/src/abstracts/webb-provider.interface.ts
  packages/api-providers/src/chains/chain-id.enum.ts
  packages/api-providers/src/contracts/wrappers/webb-vanchor.ts
  packages/api-providers/src/ext-providers/polkadot/polkadot-provider.ts
  packages/api-providers/src/notes/index.ts
  packages/api-providers/src/notes/note-manager.ts
  packages/api-providers/src/polkadot/chain-query.ts
  packages/api-providers/src/polkadot/mixer-deposit.ts
  packages/api-providers/src/polkadot/mixer-withdraw.ts
  packages/api-providers/src/polkadot/mt-utils.ts
  packages/api-providers/src/polkadot/vanchor-deposit.ts
  packages/api-providers/src/polkadot/vanchor-registration.ts
  packages/api-providers/src/polkadot/vanchor-withdraw.ts
  packages/api-providers/src/polkadot/webb-provider.ts
  packages/api-providers/src/utils/storage.ts
  packages/api-providers/src/web3/relayer-manager.ts
  packages/api-providers/src/web3/vanchor-deposit.ts
  packages/api-providers/src/web3/vanchor-registration.ts
  packages/api-providers/src/web3/vanchor-withdraw.ts
  packages/api-providers/src/web3/webb-provider.ts
  packages/api-providers/src/web3/wrap-unwrap.ts
  packages/apps/src/configs/chains/substrate/index.ts
  packages/apps/src/configs/currencies/currency-config.ts
  packages/apps/src/configs/relayer-config.ts
  packages/apps/src/configs/wallets/wallets-config.ts
  packages/mixer/src/components/Withdraw/Withdraw.tsx
  packages/react-components/src/AppBar/AppBar.tsx
  packages/react-components/src/ChainNotesSwitcher/ChainNotesSwitcher.tsx
  packages/react-components/src/NoteAccount/ChainNotesList.tsx
  packages/react-components/src/NoteAccount/NoteAccount.tsx
  packages/react-components/src/NoteAccount/NoteAccountDetails.tsx
  packages/react-components/src/NoteDisplay/ItemNoteDisplay.tsx
  packages/react-components/src/PermissionedAccess/CreateNoteAccount.tsx
  packages/react-components/src/PermissionedAccess/PermissionedAccess.tsx
  packages/react-components/src/PermissionedAccess/RequiredNoteAccount.tsx
  packages/react-components/src/Withdraw/WithdrawSuccessModal.tsx
  packages/react-environment/src/WebbProvider.tsx
  packages/react-environment/src/webb-context/index.ts
  packages/react-environment/src/webb-context/networks-storage.ts
  packages/react-environment/src/webb-context/webb-context.ts
  packages/ui-components/src/Inputs/InputTitle/InputTitle.tsx
  packages/ui-components/src/Inputs/WalletSelect/WalletSelect.tsx
  packages/utils/src/index.ts
  packages/utils/src/storage/index.ts
  packages/utils/src/storage/storage.ts
  packages/vbridge/src/VBridge.tsx
  packages/vbridge/src/components/Deposit/Deposit.tsx
  packages/vbridge/src/components/DepositConfirm/DepositConfirm.tsx
  packages/vbridge/src/components/Withdraw/Withdraw.tsx
  packages/vbridge/src/hooks/deposit/useBridgeDeposit.tsx
  packages/vbridge/src/hooks/withdraw/useWithdraw.tsx
  tsconfig.json
Labels: approved ✅

#524 Fix provider not working after cancel a transaction
  packages/api-providers/src/abstracts/anchor/vanchor-deposit.ts
  packages/api-providers/src/web3/vanchor-deposit.ts
  packages/react-components/src/Transact/TransactionProcessingModal.tsx
  packages/vbridge/src/components/Deposit/Deposit.tsx
Labels: needs review 👓

#533 UI bug Fixes, and fix tangle token
  packages/api-providers/src/polkadot/transaction.ts
Labels: wip 🚧

#530 Setup new color pallet
  packages/apps/package.json
  packages/apps/postcss.config.js
  packages/apps/src/App.tsx
  packages/apps/src/index.tsx
  packages/apps/tailwind.config.js
  packages/apps/webpack.base.js
  packages/apps/webpack.dev.js
  packages/react-components/src/AppBar/AppBar.tsx
  packages/webb-ui-components/README.md
  packages/webb-ui-components/package.json
  packages/webb-ui-components/src/components/ThemeSwitcher/ThemeSwitcher.tsx
  packages/webb-ui-components/src/components/ThemeSwitcher/index.ts
  packages/webb-ui-components/src/components/index.ts
  packages/webb-ui-components/src/hooks/index.ts
  packages/webb-ui-components/src/hooks/useDarkMode.ts
  packages/webb-ui-components/src/hooks/useWebbUI.ts
  packages/webb-ui-components/src/index.tsx
  packages/webb-ui-components/src/provider/index.tsx
  packages/webb-ui-components/src/tailwind.css
  packages/webb-ui-components/tsconfig.json
  tsconfig.paths.json
  yarn.lock
Labels: needs review 👓
