Repository tangle-network/dapp, pull requests merged in 2023-06, with the labels that each got.

#1286 Updates proposals query's fetch policy to always fetch latest data
  apps/stats-dapp/src/provider/hooks/useProposals.ts
Labels: needs review 👓, statistics

#1279 Fix Bridge Hanging Issue
  apps/bridge-dapp/src/containers/DepositContainer/DepositConfirmContainer.tsx
  apps/bridge-dapp/src/containers/DepositContainer/DepositContainer.tsx
  apps/bridge-dapp/src/containers/DepositContainer/types.d.ts
  apps/bridge-dapp/src/containers/TransferContainer/TransferConfirmContainer.tsx
  apps/bridge-dapp/src/containers/TransferContainer/TransferContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawConfirmContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
  apps/bridge-dapp/src/hooks/useLatestTransactionStage.ts
  apps/bridge-dapp/src/hooks/useTransactionProgressValue.ts
  apps/bridge-dapp/src/pages/PageBridge.tsx
  apps/bridge-dapp/src/types/index.ts
  apps/bridge-dapp/webpack.base.js
  apps/stats-dapp/webpack.config.js
  libs/abstract-api-provider/src/transaction.ts
  libs/api-provider-environment/src/transaction/useTransactionQueue.tsx
  libs/react-hooks/src/index.ts
  libs/react-hooks/src/transaction/index.ts
  libs/react-hooks/src/transaction/useTransactionQueue.tsx
  libs/react-hooks/src/vanchor/useVAnchor.tsx
  libs/web3-api-provider/src/utils/calculateProvingLeavesAndCommitmentIndex.ts
  libs/web3-api-provider/src/utils/handleVAnchorTxState.ts
  libs/web3-api-provider/src/utils/index.ts
  libs/web3-api-provider/src/utils/worker/calculateProvingLeavesAndCommitmentIndex.ts
  libs/web3-api-provider/src/webb-provider.ts
  libs/web3-api-provider/src/webb-provider/relayer-manager.ts
  libs/web3-api-provider/src/webb-provider/vanchor-actions.ts
  libs/web3-api-provider/tsconfig.json
  libs/webb-ui-components/src/components/Button/ButtonSpinner.tsx
  libs/webb-ui-components/src/containers/TransactionProgressCard/TransactionCardFooter.tsx
  package.json
  yarn.lock
Labels: needs review 👓

#1289 Remove graph gradient colors and updates legend
  apps/stats-dapp/src/containers/StackedAreaChartContainer/StackedAreaChartContainer.tsx
Labels: needs review 👓, statistics

#1292 [Hot Fix] Stats Proposal Page Crashes
  apps/stats-dapp/src/containers/StackedAreaChartContainer/StackedAreaChartContainer.tsx
  yarn.lock
Labels: needs review 👓

#1293 Sync develop branch with master branch
  .lycheeignore
  apps/bridge-dapp/CHANGELOG.md
  apps/bridge-dapp/package.json
  apps/faucet/CHANGELOG.md
  apps/faucet/package.json
  apps/stats-dapp/CHANGELOG.md
  apps/stats-dapp/package.json
  apps/stats-dapp/src/containers/StackedAreaChartContainer/StackedAreaChartContainer.tsx
  apps/tangle-website/CHANGELOG.md
  apps/tangle-website/package.json
  apps/tangle-website/src/components/sections/FAQSection.tsx
  apps/tangle-website/src/components/sections/FeaturesSection.tsx
  apps/tangle-website/src/components/sections/HeroSection.tsx
  apps/tangle-website/src/components/sections/ParticipationMechanicsSection.tsx
  apps/tangle-website/src/components/sections/UseCasesSection.tsx
  apps/webbsite/CHANGELOG.md
  apps/webbsite/package.json
  apps/webbsite/src/components/brandkit/BrandKitHeroSection.tsx
  apps/webbsite/src/components/brandkit/ColorPalettesSection.tsx
  apps/webbsite/src/components/brandkit/IconographySection.tsx
  apps/webbsite/src/components/brandkit/PressInquiriesSection.tsx
  apps/webbsite/src/components/brandkit/TypographySection.tsx
  apps/webbsite/src/components/brandkit/WebbLogoSection.tsx
  libs/webb-ui-components/src/components/BridgeInputs/RefundInput.tsx
  libs/webb-ui-components/src/components/CheckBox/Checkbox.tsx
Labels: needs review 👓

#1310 Fixes proposal table buggy pagination
  apps/stats-dapp/src/containers/ProposalsTable/ProposalsTable.tsx
  apps/stats-dapp/src/pages/Proposals.tsx
Labels: needs review 👓, statistics

#1315 Adds estimated transaction fee tooltip
  apps/bridge-dapp/src/containers/TransferContainer/TransferContainer.tsx
  apps/bridge-dapp/src/containers/TransferContainer/shared.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
  libs/webb-ui-components/src/components/TitleWithInfo/TitleWithInfo.tsx
Labels: needs review 👓, bridge

#1316 UI updates for improved transaction flow on bridge
  libs/webb-ui-components/src/components/ListCard/TokenListCard.tsx
  libs/webb-ui-components/src/containers/DepositCard/DepositCard.tsx
  libs/webb-ui-components/src/containers/TransferCard/TransferCard.tsx
  libs/webb-ui-components/src/containers/WithdrawCard/WithdrawCard.tsx
Labels: needs review 👓, bridge

#1327 Integrates Faucet App with Faucet Backend
  .github/workflows/check-build.yml
  .github/workflows/deploy-faucet.yml
  .github/workflows/release.yml
  apps/bridge-dapp/src/components/Header/WalletModal.tsx
  apps/faucet/.env.local.example
  apps/faucet/src/components/ContractAddressInput.tsx
  apps/faucet/src/components/Header.tsx
  apps/faucet/src/components/ProcessingModal.tsx
  apps/faucet/src/components/RecipientAddressInput.tsx
  apps/faucet/src/components/TwitterLink.tsx
  apps/faucet/src/config/shared.ts
  apps/faucet/src/config/tokens.ts
  apps/faucet/src/containers/LoginWithTwitter.tsx
  apps/faucet/src/containers/MintButtonContainer.tsx
  apps/faucet/src/errors/FaucetError.ts
  apps/faucet/src/lottie/failed.json
  apps/faucet/src/provider/index.tsx
  apps/faucet/src/styles/globals.css
  apps/faucet/src/types/index.ts
  apps/faucet/src/utils/loginWithTwitter.ts
  libs/dapp-config/src/chains/evm/index.tsx
  libs/dapp-config/src/chains/substrate/index.tsx
  libs/dapp-types/src/ChainId.ts
  libs/webb-ui-components/src/components/Input/Input.tsx
  package.json
  yarn.lock
Labels: needs review 👓

#1328 [RELEASE] Release dApps `2023-06-09`
  .lycheeignore
  apps/bridge-dapp/CHANGELOG.md
  apps/bridge-dapp/package.json
  apps/bridge-dapp/src/containers/Layout/Layout.tsx
  apps/bridge-dapp/src/pages/PageBridge.tsx
  apps/faucet/CHANGELOG.md
  apps/faucet/package.json
  apps/faucet/src/pages/index.tsx
  apps/stats-dapp/CHANGELOG.md
  apps/stats-dapp/package.json
  apps/tangle-website/CHANGELOG.md
  apps/tangle-website/package.json
  apps/tangle-website/src/components/sections/GovernanceSystemSection.tsx
  apps/tangle-website/src/components/sections/ParticipationMechanicsSection.tsx
  apps/tangle-website/src/components/sections/SupportedBySection.tsx
  apps/webbsite/CHANGELOG.md
  apps/webbsite/package.json
  libs/webb-ui-components/src/constants/index.ts
  libs/webb-ui-components/src/css/layer-components.css
Labels: needs review 👓

#1333 Fixes bridge header component
  apps/bridge-dapp/src/components/Header/Header.tsx
Labels: needs review 👓, bridge

#1332 Adds alert component to webb-ui-components
  apps/bridge-dapp/src/containers/DepositContainer/DepositContainer.tsx
  apps/bridge-dapp/src/containers/TransferContainer/TransferContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
  libs/icons/src/AlertFill.tsx
  libs/icons/src/CheckboxCircleFill.tsx
  libs/icons/src/InformationLineFill.tsx
  libs/icons/src/index.ts
  libs/webb-ui-components/src/components/Alert/Alert.tsx
  libs/webb-ui-components/src/components/Alert/index.ts
  libs/webb-ui-components/src/components/Alert/types.ts
  libs/webb-ui-components/src/components/Alert/utils.ts
  libs/webb-ui-components/src/components/ListCard/ChainListCard.tsx
  libs/webb-ui-components/src/components/ListCard/TokenListCard.tsx
  libs/webb-ui-components/src/components/ListCard/types.ts
  libs/webb-ui-components/src/components/index.ts
  libs/webb-ui-components/src/containers/DepositCard/DepositCard.tsx
  libs/webb-ui-components/src/containers/TransactionProgressCard/TransactionQueueCard.tsx
  libs/webb-ui-components/src/stories/molecules/Alert.stories.jsx
  yarn.lock
Labels: bridge, design-system 🎨

#1334 Fixes wallet connect loading state
  apps/bridge-dapp/src/components/Header/Header.tsx
Labels: needs review 👓, bridge

#1338 Fixes stats keys table pagination
  apps/stats-dapp/src/containers/KeygenTable/KeygenTable.tsx
  apps/stats-dapp/src/provider/hooks/mappers/index.ts
  apps/stats-dapp/src/provider/hooks/useKeys.ts
Labels: needs review 👓, statistics

#1335 Webbsite Shielded Pool Protocols page
  apps/tangle-website/src/components/Navbar.tsx
  apps/webbsite/public/static/assets/green.png
  apps/webbsite/public/static/assets/multiasset-vanchor.png
  apps/webbsite/public/static/assets/shielded-pool-hero.png
  apps/webbsite/public/static/svgs/shielded-pool-illustration-1.svg
  apps/webbsite/public/static/svgs/shielded-pool-illustration-2.svg
  apps/webbsite/public/static/svgs/shielded-pool-illustration-3.svg
  apps/webbsite/public/static/svgs/shielded-pool-illustration-4.svg
  apps/webbsite/public/static/svgs/shielded-pool-illustration-5.svg
  apps/webbsite/public/static/svgs/shielded-pool-step-1.svg
  apps/webbsite/public/static/svgs/shielded-pool-step-2.svg
  apps/webbsite/public/static/svgs/shielded-pool-step-3.svg
  apps/webbsite/public/static/svgs/shielded-pool-step-4.svg
  apps/webbsite/public/static/svgs/shielded-pool-step-5.svg
  apps/webbsite/src/components/Header.tsx
  apps/webbsite/src/components/PrivacyScaleIllustration.tsx
  apps/webbsite/src/components/PrivacyScaleSwiper.tsx
  apps/webbsite/src/components/index.ts
  apps/webbsite/src/components/sections/ApplicationsAndInfrastructureSection.tsx
  apps/webbsite/src/components/sections/PrivacyScaleSection.tsx
  apps/webbsite/src/components/shielded-pool/HowShieldedPoolWorksSection.tsx
  apps/webbsite/src/components/shielded-pool/ShieldedPoolExtensionsSection.tsx
  apps/webbsite/src/components/shielded-pool/ShieldedPoolHeroSection.tsx
  apps/webbsite/src/components/shielded-pool/ShieldedPoolUseCasesSection.tsx
  apps/webbsite/src/components/shielded-pool/index.ts
  apps/webbsite/src/components/svgs/ShieldedPoolUseCase1.tsx
  apps/webbsite/src/components/svgs/ShieldedPoolUseCase2.tsx
  apps/webbsite/src/components/svgs/ShieldedPoolUseCase3.tsx
  apps/webbsite/src/components/svgs/index.ts
  apps/webbsite/src/components/swipers/PrivacyScaleSwiper.tsx
  apps/webbsite/src/components/swipers/ShieldedPoolSwiper.tsx
  apps/webbsite/src/components/swipers/SwiperTemplate.tsx
  apps/webbsite/src/components/swipers/index.ts
  apps/webbsite/src/pages/404.tsx
  apps/webbsite/src/pages/shielded-pool-protocols.tsx
  apps/webbsite/src/styles/globals.css
  apps/webbsite/tailwind.config.js
  libs/dapp-config/src/links.ts
  libs/webb-ui-components/src/components/BridgeInputs/AmountInput.tsx
  libs/webb-ui-components/src/components/BridgeInputs/FixedAmount.tsx
  libs/webb-ui-components/src/components/Dropdown/DropdownBody.tsx
  libs/webb-ui-components/src/components/Dropdown/types.ts
  libs/webb-ui-components/src/components/Navbar/Navbar.tsx
  libs/webb-ui-components/src/css/layer-components.css
  yarn.lock
Labels: needs changes 🔧

#1341 Add token to wallet
  apps/bridge-dapp/src/containers/DepositContainer/DepositContainer.tsx
  apps/bridge-dapp/src/containers/TransferContainer/TransferContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
  apps/bridge-dapp/src/hooks/useAddCurrency.ts
  libs/webb-ui-components/src/components/ListCard/AssetListItem.tsx
  libs/webb-ui-components/src/components/ListCard/TokenListCard.tsx
  libs/webb-ui-components/src/components/ListCard/types.ts
Labels: needs review 👓, bridge

#1344 Tangle Leaderboard UI
  apps/tangle-website/public/static/svgs/webbAddress.svg
  apps/tangle-website/src/components/FAQAccordion.tsx
  apps/tangle-website/src/components/index.ts
  apps/tangle-website/src/components/leaderboard/CountdownSection.tsx
  apps/tangle-website/src/components/leaderboard/FAQSection.tsx
  apps/tangle-website/src/components/leaderboard/RankingTableSection.tsx
  apps/tangle-website/src/components/leaderboard/index.ts
  apps/tangle-website/src/components/leaderboard/tableComponents/AddressCell.tsx
  apps/tangle-website/src/components/leaderboard/tableComponents/BadgesCell.tsx
  apps/tangle-website/src/components/leaderboard/tableComponents/HeaderCell.tsx
  apps/tangle-website/src/components/leaderboard/tableComponents/index.ts
  apps/tangle-website/src/components/leaderboard/tableComponents/types.ts
  apps/tangle-website/src/components/sections/FAQSection.tsx
  apps/tangle-website/src/pages/leaderboard.tsx
  libs/webb-ui-components/src/components/Pagination/Pagination.tsx
  libs/webb-ui-components/src/components/Pagination/types.ts
  nx.json
Labels: needs review 👓

#1354 Update FAQSection.tsx
  apps/tangle-website/src/components/FAQAccordion.tsx
  apps/tangle-website/src/components/leaderboard/FAQSection.tsx
Labels: needs review 👓

#1355 Add Faucet link in navigation menu
  apps/bridge-dapp/src/components/Header/Header.tsx
  libs/webb-ui-components/src/components/NavigationMenu/NavigationMenuContent.tsx
  libs/webb-ui-components/src/components/NavigationMenu/types.ts
Labels: needs review 👓

#1359 Fixes inconsistent stats background image
  apps/stats-dapp/src/containers/Layout/Layout.tsx
Labels: needs review 👓, statistics

#1362 Close confirm containers when txn is dismissed
  apps/bridge-dapp/src/containers/DepositContainer/DepositContainer.tsx
  apps/bridge-dapp/src/containers/TransferContainer/TransferContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
Labels: needs review 👓, bridge

#1361 Utilizing Circom Proving for Substrate
  .github/workflows/check-build.yml
  .github/workflows/release.yml
  apps/bridge-dapp/postcss.config.js
  apps/bridge-dapp/scripts/localSubstrate.ts
  apps/bridge-dapp/scripts/localTangle.ts
  apps/bridge-dapp/webpack.base.js
  apps/bridge-dapp/webpack.dev.js
  apps/webbsite/.env.example
  libs/abstract-api-provider/src/utils/utxoFromVAnchorNote.ts
  libs/abstract-api-provider/src/webb-provider.interface.ts
  libs/abstract-api-provider/tsconfig.lib.json
  libs/api-provider-environment/project.json
  libs/api-provider-environment/src/types.ts
  libs/api-provider-environment/tsconfig.lib.json
  libs/dapp-config/src/types.ts
  libs/dapp-types/src/WebbError.ts
  libs/note-manager/src/note-manager.ts
  libs/polkadot-api-provider/src/types.ts
  libs/polkadot-api-provider/src/utils/ensureHex.ts
  libs/polkadot-api-provider/src/utils/getVAnchorExtDataHash.ts
  libs/polkadot-api-provider/src/utils/groth16ProofToBytes.ts
  libs/polkadot-api-provider/src/utils/index.ts
  libs/polkadot-api-provider/src/utils/substrateProviderFactory.ts
  libs/polkadot-api-provider/src/webb-provider.ts
  libs/polkadot-api-provider/src/webb-provider/vanchor-actions.ts
  libs/polkadot-api-provider/tsconfig.lib.json
  libs/react-hooks/tsconfig.lib.json
  libs/web3-api-provider/src/typings.ts
  libs/web3-api-provider/src/webb-provider.ts
  libs/web3-api-provider/tsconfig.lib.json
  package.json
  tools/scripts/fetchingOnChainConfig.ts
  tools/scripts/utils/on-chain-utils/fetchAnchorMetadata.ts
  tools/scripts/utils/on-chain-utils/getViemClient.ts
  tools/scripts/utils/on-chain-utils/mergeConfig.ts
  tsconfig.base.json
  types/global.d.ts
  yarn.lock
Labels: needs review 👓

#1371 Fixes keys table real-time update & progress bar reset
  apps/stats-dapp/src/containers/KeyStatusCardContainer/KeyStatusCardContainer.tsx
  apps/stats-dapp/src/provider/hooks/useKeys.ts
  apps/stats-dapp/src/provider/stats-provider.tsx
Labels: statistics

#1375 Privacy Policy and Terms Conditions pages for the Tangle Website
  apps/faucet/src/components/Header.tsx
  apps/tangle-website/src/pages/_app.tsx
  apps/tangle-website/src/pages/privacy-policy.tsx
  apps/tangle-website/src/pages/terms-and-conditions.tsx
  apps/tangle-website/src/styles/globals.css
  libs/dapp-config/src/links.ts
Labels: needs review 👓

#1380 [RELEASE] Relayer URL and Disable Radio When No Chains To Select
  apps/bridge-dapp/CHANGELOG.md
  apps/bridge-dapp/src/containers/TransferContainer/TransferContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
  libs/abstract-api-provider/src/relayer/webb-relayer.ts
  libs/webb-ui-components/src/components/ListCard/ChainListCard.tsx
Labels: needs review 👓

#1381 Change to font Satoshi for marketing sites
  apps/tangle-website/src/pages/_document.tsx
  apps/webbsite/src/pages/_document.tsx
Labels: needs review 👓

#1385 feat: add Key Metrics table
  apps/bridge-dapp/src/containers/TransferContainer/TransferConfirmContainer.tsx
  apps/bridge-dapp/src/containers/TransferContainer/TransferContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawConfirmContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
  apps/hubble-stats/app/layout.tsx
  apps/hubble-stats/app/page.tsx
  apps/hubble-stats/components/KeyMetricsTable/KeyMetricsTable.tsx
  apps/hubble-stats/components/KeyMetricsTable/MetricItem.tsx
  apps/hubble-stats/components/KeyMetricsTable/index.ts
  apps/hubble-stats/components/index.ts
  apps/hubble-stats/public/static/assets/bg-dark.png
  apps/hubble-stats/public/static/assets/bg.png
  apps/hubble-stats/tailwind.config.js
  libs/webb-ui-components/src/components/ListCard/WrapAssetListCard.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/DepositConfirm.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/TransferConfirm.tsx
  libs/webb-ui-components/src/containers/DepositCard/DepositCard.tsx
  libs/webb-ui-components/src/utils/getRoundedAmountString.ts
Labels: needs review 👓

#1388 Adding GA workflow for hubble-stats dapp
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy-hubble-stats.yml
  .github/workflows/release.yml
Labels: needs review 👓
