Repository tangle-network/dapp, pull requests merged in 2023-10, with the labels that each got.

#1734 Adds faucet banner link to bridge dapp
  apps/bridge-dapp/src/containers/Layout/Layout.tsx
  libs/webb-ui-components/src/components/Banner/Banner.tsx
  libs/webb-ui-components/src/components/SideBar/SideBar.tsx
Labels: needs review 👓, ui-components, bridge

#1731 Adding Support For Multiple Note Accounts
  apps/bridge-dapp/src/components/Header/Header.tsx
  apps/bridge-dapp/src/components/Header/WalletDropdown.tsx
  apps/bridge-dapp/src/components/Header/WalletDropdown/ClearDataModal.tsx
  apps/bridge-dapp/src/components/Header/WalletDropdown/NoteAccountAction.tsx
  apps/bridge-dapp/src/components/Header/WalletDropdown/NoteAccountKey.tsx
  apps/bridge-dapp/src/components/Header/WalletDropdown/index.tsx
  apps/bridge-dapp/src/containers/CreateAccountModal/CreateAccountModal.tsx
  apps/bridge-dapp/src/hooks/useConnectButtonProps.ts
  apps/bridge-dapp/src/pages/Hubble/Bridge/Deposit/private/useDepositButtonProps.tsx
  apps/bridge-dapp/src/pages/Hubble/Bridge/Transfer/private/useTransferButtonProps.tsx
  apps/bridge-dapp/src/pages/Hubble/Bridge/Withdraw/private/useWithdrawButtonProps.tsx
  apps/bridge-dapp/src/utils/downloadNotes.ts
  apps/hubble-stats/app/layout.tsx
  apps/hubble-stats/app/pool/[slug]/page.tsx
  apps/hubble-stats/containers/PoolInfoCardContainer/PoolInfoCardContainer.tsx
  apps/hubble-stats/containers/PoolOverviewChartsContainer/PoolOverviewChartsContainer.tsx
  apps/hubble-stats/containers/PoolWrappingChartsContainer/PoolWrappingChartsContainer.tsx
  libs/abstract-api-provider/src/vanchor/vanchor-actions.ts
  libs/abstract-api-provider/src/webb-provider.interface.ts
  libs/api-provider-environment/src/WebbProvider.tsx
  libs/api-provider-environment/src/webb-context/webb-context.ts
  libs/browser-utils/src/storage.ts
  libs/dapp-types/src/WebbError.ts
  libs/note-manager/src/note-manager.ts
  libs/polkadot-api-provider/src/ext-provider/polkadot-accounts.ts
  libs/polkadot-api-provider/src/webb-provider/vanchor-actions.ts
  libs/react-hooks/src/useNoteAccount.tsx
  libs/web3-api-provider/src/ext-provider/web3-accounts.ts
  libs/web3-api-provider/src/webb-provider.ts
  libs/web3-api-provider/src/webb-provider/vanchor-actions.ts
  libs/webb-ui-components/src/components/NavigationMenu/NavigationMenuContent.tsx
  libs/webb-ui-components/src/components/NavigationMenu/types.ts
Labels: needs review 👓

#1735 Substrate Support on Faucet
  apps/faucet/src/components/ProcessingModal.tsx
  apps/faucet/src/components/RecipientAddressInput.tsx
  apps/faucet/src/containers/InputsContainer.tsx
  apps/faucet/src/containers/MintButtonContainer.tsx
  apps/faucet/src/pages/api/auth/signin/twitter.ts
  apps/faucet/src/provider/index.tsx
  apps/faucet/src/utils/isAllowSubstrateAddress.ts
  apps/faucet/src/utils/isTwitterRateLimitError.ts
  libs/dapp-types/src/utils/index.ts
  libs/dapp-types/src/utils/isSubstrateAddress.ts
  libs/dapp-types/src/utils/isValidAddress.ts
  libs/webb-ui-components/src/constants/index.ts
  libs/webb-ui-components/src/css/layer-components.css
Labels: needs review 👓

#1738 Fixes hubble bridge layout issues
  apps/bridge-dapp/src/containers/Layout/Layout.tsx
  libs/webb-ui-components/src/components/Footer/Footer.tsx
Labels: needs review 👓, bridge

#1732 Improve Hubble Stats Timeout
  apps/hubble-stats/app/pool/[slug]/page.tsx
  apps/hubble-stats/containers/HeaderChipsContainer/HeaderChipsContainer.tsx
  apps/hubble-stats/containers/KeyMetricsTableContainer/KeyMetricsTableContainer.tsx
  apps/hubble-stats/containers/PoolInfoCardContainer/PoolInfoCardContainer.tsx
  apps/hubble-stats/containers/PoolMetadataTableContainer/PoolMetadataTableContainer.tsx
  apps/hubble-stats/containers/PoolOverviewTableContainer/PoolOverviewTableContainer.tsx
  apps/hubble-stats/containers/PoolTransactionsTableContainer/PoolTransactionsTableContainer.tsx
  apps/hubble-stats/containers/PoolWrappingChartsContainer/PoolWrappingChartsContainer.tsx
  apps/hubble-stats/containers/PoolWrappingTableContainer/PoolWrappingTableContainer.tsx
  apps/hubble-stats/containers/ShieldedTablesContainer/ShieldedTablesContainer.tsx
  apps/hubble-stats/containers/charts/OverviewTvlChartContainer.tsx
  apps/hubble-stats/containers/charts/OverviewVolumeChartContainer.tsx
  apps/hubble-stats/containers/charts/PoolRelayerEarningsChartContainer.tsx
  apps/hubble-stats/containers/charts/PoolTvlChartContainer.tsx
  apps/hubble-stats/containers/charts/PoolTwlChartContainer.tsx
  apps/hubble-stats/containers/charts/PoolVolumeChartContainer.tsx
  apps/hubble-stats/containers/charts/PoolWrappingFeesChartContainer.tsx
  apps/hubble-stats/data/shieldedTables/getShieldedAssetsTableData.ts
  apps/hubble-stats/data/shieldedTables/getShieldedPoolsTableData.ts
  package.json
  yarn.lock
Labels: needs review 👓

#1739 Disable amount input for destination accross flows
  apps/bridge-dapp/src/pages/Hubble/Bridge/Deposit/index.tsx
  apps/bridge-dapp/src/pages/Hubble/Bridge/Transfer/index.tsx
  apps/bridge-dapp/src/pages/Hubble/Bridge/Withdraw/index.tsx
Labels: needs review 👓

#1743 Fixes incorrect threshold values in key detail page
  apps/stats-dapp/src/containers/KeyDetail/KeyDetail.tsx
Labels: needs review 👓, dkg-stats-dapp

#1745 [RELEASE] 2023 Oct 05 - Hubble Bridge, Hubble Stats and DKG Stats
  .lycheeignore
  apps/bridge-dapp/CHANGELOG.md
  apps/bridge-dapp/package.json
  apps/bridge-dapp/src/hooks/useConnectButtonProps.ts
  apps/faucet/CHANGELOG.md
  apps/faucet/package.json
  apps/faucet/src/pages/_app.tsx
  apps/hubble-stats/CHANGELOG.md
  apps/hubble-stats/package.json
  apps/stats-dapp/CHANGELOG.md
  apps/stats-dapp/package.json
  libs/dapp-config/src/anchors/anchor-config.ts
  libs/note-manager/src/note-manager.ts
Labels: needs review 👓

#1765 Fix bridge mobile view
  apps/bridge-dapp/src/components/Header/Header.tsx
  apps/bridge-dapp/src/components/Header/WalletDropdown/index.tsx
  apps/bridge-dapp/src/components/Header/WalletModal.tsx
  apps/bridge-dapp/src/components/tables/EmptyTable.tsx
  apps/bridge-dapp/src/containers/BridgeTabsContainer/BridgeTabsContainer.tsx
  apps/bridge-dapp/src/containers/Layout/Layout.tsx
  libs/browser-utils/src/platform/getPlatformMetaData.ts
  libs/webb-ui-components/src/components/FeeDetails/FeeDetails.tsx
  libs/webb-ui-components/src/components/Input/Input.tsx
  libs/webb-ui-components/src/components/TableAndChartTabs/TableAndChartTabs.tsx
  libs/webb-ui-components/src/components/TextField/TextField.tsx
  libs/webb-ui-components/src/components/TokenSelector/TokenSelector.tsx
  libs/webb-ui-components/src/components/TransactionInputCard/TransactionInputCard.tsx
  libs/webb-ui-components/src/components/buttons/ChainButton.tsx
  libs/webb-ui-components/src/components/buttons/WalletButton.tsx
  libs/webb-ui-components/src/components/buttons/types.ts
  libs/webb-ui-components/src/hooks/useCheckMobile.ts
Labels: needs review 👓, bridge

#1771 Fix Hubble Bridge QA Checklist 2
  apps/bridge-dapp/src/components/RelayerFeeDetails.tsx
  apps/bridge-dapp/src/components/index.ts
  apps/bridge-dapp/src/components/tables/FilterButton.tsx
  apps/bridge-dapp/src/containers/note-account-tables/ShieldedAssetsTableContainer/ShieldedAssetsTableContainer.tsx
  apps/bridge-dapp/src/containers/note-account-tables/SpendNotesTableContainer/SpendNotesTableContainer.tsx
  apps/bridge-dapp/src/pages/Hubble/Bridge/SelectPool.tsx
  apps/bridge-dapp/src/pages/Hubble/Bridge/SelectRelayer.tsx
  apps/bridge-dapp/src/pages/Hubble/Bridge/SelectToken.tsx
  apps/bridge-dapp/src/pages/Hubble/Bridge/Transfer/index.tsx
  apps/bridge-dapp/src/pages/Hubble/Bridge/Transfer/private/useFeeCalculation.ts
  apps/bridge-dapp/src/pages/Hubble/Bridge/Withdraw/index.tsx
  apps/bridge-dapp/src/pages/Hubble/Bridge/Withdraw/private/useFeeCalculation.ts
  apps/bridge-dapp/src/utils/getRelayerFeePercentage.ts
  apps/bridge-dapp/src/utils/index.ts
  apps/hubble-stats/components/PoolMetadataTable/PoolMetadataTable.tsx
  apps/hubble-stats/components/PoolOverviewTable/PoolOverviewTable.tsx
  apps/hubble-stats/components/PoolTransactionsTable/PoolTransactionsTable.tsx
  apps/hubble-stats/components/PoolWrappingTable/PoolWrappingTable.tsx
  apps/hubble-stats/components/ShieldedAssetsTable/ShieldedAssetsTable.tsx
  apps/hubble-stats/components/ShieldedPoolsTable/ShieldedPoolsTable.tsx
  apps/stats-dapp/src/containers/AuthoritiesTable/AuthoritiesTable.tsx
  apps/stats-dapp/src/containers/AuthorityDetail/AuthorityDetail.tsx
  apps/stats-dapp/src/containers/KeyDetail/KeyDetail.tsx
  apps/stats-dapp/src/containers/KeygenTable/KeygenTable.tsx
  apps/stats-dapp/src/containers/ProposalsTable/ProposalsTable.tsx
  apps/stats-dapp/src/pages/Authorities.tsx
  libs/abstract-api-provider/src/relayer/types.ts
  libs/relayer-manager-factory/src/relayer-manager-factory.ts
  libs/webb-ui-components/src/components/FeeDetails/FeeDetails.tsx
  libs/webb-ui-components/src/components/FeeDetails/types.ts
  libs/webb-ui-components/src/components/ListCard/TokenListItem.tsx
  libs/webb-ui-components/src/components/ListCard/types.ts
  libs/webb-ui-components/src/components/Table/Table.tsx
  libs/webb-ui-components/src/components/Table/types.ts
  libs/webb-ui-components/src/components/TransactionInputCard/TransactionInputCard.tsx
Labels: needs review 👓

#1774 Add Tangle Sidebar to Faucet
  apps/faucet/src/components/Header.tsx
  apps/faucet/src/constants/sidebar.ts
  apps/faucet/src/pages/_app.tsx
  apps/faucet/src/pages/_document.tsx
  apps/faucet/src/pages/index.tsx
  apps/hubble-stats/app/layout.tsx
  apps/hubble-stats/components/sideBar/sideBarActions.ts
  apps/tangle-website/src/components/Header.tsx
  libs/api-provider-environment/src/NextThemeProvider.tsx
  libs/api-provider-environment/src/index.ts
  libs/icons/src/AppsLine.tsx
  libs/icons/src/FundsLine.tsx
  libs/icons/src/GlobalLine.tsx
  libs/icons/src/TangleIcon.tsx
  libs/icons/src/index.ts
  libs/webb-ui-components/src/components/SideBar/Footer.tsx
  libs/webb-ui-components/src/components/SideBar/Item.tsx
  libs/webb-ui-components/src/components/SideBar/Items.tsx
  libs/webb-ui-components/src/components/SideBar/SideBar.tsx
  libs/webb-ui-components/src/components/SideBar/SideBarMenu.tsx
  libs/webb-ui-components/src/components/TangleLogo/TangleLogo.tsx
  libs/webb-ui-components/src/components/TangleLogo/types.ts
  libs/webb-ui-components/src/constants/index.ts
Labels: needs review 👓

#1780 Bump Netlify Next.js Runtime
  package.json
  yarn.lock
Labels: needs review 👓

#1781 EVM Staking - Breadcrumbs & Header chips
  apps/tangle-dapp/app/page.tsx
  apps/tangle-dapp/components/Breadcrumbs/Breadcrumbs.tsx
  apps/tangle-dapp/components/Breadcrumbs/index.ts
  apps/tangle-dapp/components/Breadcrumbs/types.ts
  apps/tangle-dapp/components/HeaderChip/HeaderChip.tsx
  apps/tangle-dapp/components/HeaderChip/index.ts
  apps/tangle-dapp/components/HeaderChip/types.ts
  apps/tangle-dapp/components/index.ts
  apps/tangle-dapp/components/sideBar/sideBarProps.ts
  apps/tangle-dapp/constants/index.ts
  apps/tangle-dapp/constants/polkadot.ts
  apps/tangle-dapp/containers/HeaderChipsContainer/HeaderChipsContainer.tsx
  apps/tangle-dapp/containers/HeaderChipsContainer/index.ts
  apps/tangle-dapp/containers/Layout/Layout.tsx
  apps/tangle-dapp/data/HeaderChips/getEra.ts
  apps/tangle-dapp/data/HeaderChips/getSession.ts
  apps/tangle-dapp/data/HeaderChips/index.ts
  apps/tangle-dapp/data/index.ts
  libs/webb-ui-components/src/constants/index.ts
Labels: needs review 👓, tangle-dapp

#1782 Faucet Responsive + Fix Flicker
  apps/faucet/src/components/ProcessingModal.tsx
  apps/faucet/src/pages/_app.tsx
  apps/faucet/src/pages/index.tsx
  apps/faucet/src/utils/sidebar.ts
  package.json
  yarn.lock
Labels: needs review 👓

#1786 EVM Staking - Top Level Stats
  apps/tangle-dapp/app/page.tsx
  apps/tangle-dapp/components/HeaderChip/HeaderChip.tsx
  apps/tangle-dapp/components/InfoIconWithTooltip/InfoIconWithTooltip.tsx
  apps/tangle-dapp/components/InfoIconWithTooltip/index.ts
  apps/tangle-dapp/components/InfoIconWithTooltip/types.ts
  apps/tangle-dapp/components/KeyMetricItem/KeyMetricItem.tsx
  apps/tangle-dapp/components/KeyMetricItem/index.ts
  apps/tangle-dapp/components/KeyMetricItem/types.ts
  apps/tangle-dapp/components/index.ts
  apps/tangle-dapp/components/sideBar/SideBar.tsx
  apps/tangle-dapp/components/sideBar/sideBarProps.ts
  apps/tangle-dapp/containers/HeaderChipsContainer/HeaderChipsContainer.tsx
  apps/tangle-dapp/containers/KeyMetricsTableContainer/KeyMetricsTableContainer.tsx
  apps/tangle-dapp/containers/KeyMetricsTableContainer/index.ts
  apps/tangle-dapp/containers/index.ts
  apps/tangle-dapp/data/HeaderChips/getEraCount.ts
  apps/tangle-dapp/data/HeaderChips/getSessionCount.ts
  apps/tangle-dapp/data/HeaderChips/index.ts
  apps/tangle-dapp/data/TopLevelStats/getActiveAndDelegationCount.ts
  apps/tangle-dapp/data/TopLevelStats/getIdealStakedPercentage.ts
  apps/tangle-dapp/data/TopLevelStats/getInflationPercentage.ts
  apps/tangle-dapp/data/TopLevelStats/getValidatorsCount.ts
  apps/tangle-dapp/data/TopLevelStats/getWaitingCount.ts
  apps/tangle-dapp/data/TopLevelStats/index.ts
  apps/tangle-dapp/data/index.ts
  apps/tangle-dapp/tailwind.config.js
  apps/tangle-dapp/types/index.ts
  apps/tangle-dapp/utils/calculateInflation.ts
  apps/tangle-dapp/utils/getRoundedDownNumberWith2Decimals.ts
  apps/tangle-dapp/utils/index.ts
  package.json
  tsconfig.base.json
  yarn.lock
Labels: needs review 👓, tangle-dapp

#1787 Client Side Fetching for Hubble Stats
  apps/bridge-dapp/package.json
  apps/faucet/package.json
  apps/hubble-stats/app/layout.tsx
  apps/hubble-stats/app/page.tsx
  apps/hubble-stats/app/pool/[slug]/page.tsx
  apps/hubble-stats/app/providers.tsx
  apps/hubble-stats/components/Breadcrumbs/Breadcrumbs.tsx
  apps/hubble-stats/components/HeaderChipItem/HeaderChipItem.tsx
  apps/hubble-stats/components/HeaderChipItem/types.ts
  apps/hubble-stats/components/KeyMetricItem/KeyMetricItem.tsx
  apps/hubble-stats/components/KeyMetricItem/types.ts
  apps/hubble-stats/components/PoolInfoCardItem/PoolInfoCardItem.tsx
  apps/hubble-stats/components/PoolInfoCardItem/types.ts
  apps/hubble-stats/containers/HeaderChipsContainer/HeaderChipsContainer.tsx
  apps/hubble-stats/containers/KeyMetricsTableContainer/KeyMetricsTableContainer.tsx
  apps/hubble-stats/containers/PoolInfoCardContainer/ItemsContainer.tsx
  apps/hubble-stats/containers/PoolInfoCardContainer/PoolInfoCardContainer.tsx
  apps/hubble-stats/containers/PoolMetadataTableContainer/PoolMetadataTableContainer.tsx
  apps/hubble-stats/containers/PoolOverviewTableContainer/PoolOverviewTableContainer.tsx
  apps/hubble-stats/containers/PoolTransactionsTableContainer/PoolTransactionsTableContainer.tsx
  apps/hubble-stats/containers/PoolTransactionsTableContainer/TransactionsTable.tsx
  apps/hubble-stats/containers/PoolTransactionsTableContainer/tabs.ts
  apps/hubble-stats/containers/PoolWrappingTableContainer/PoolWrappingTableContainer.tsx
  apps/hubble-stats/containers/ShieldedTablesContainer/ShieldedAssetsTableContainer.tsx
  apps/hubble-stats/containers/ShieldedTablesContainer/ShieldedPoolsTableContainer.tsx
  apps/hubble-stats/containers/ShieldedTablesContainer/ShieldedTablesContainer.tsx
  apps/hubble-stats/containers/charts/OverviewTvlChartContainer.tsx
  apps/hubble-stats/containers/charts/OverviewVolumeChartContainer.tsx
  apps/hubble-stats/containers/charts/PoolRelayerEarningsChartContainer.tsx
  apps/hubble-stats/containers/charts/PoolTvlChartContainer.tsx
  apps/hubble-stats/containers/charts/PoolTwlChartContainer.tsx
  apps/hubble-stats/containers/charts/PoolVolumeChartContainer.tsx
  apps/hubble-stats/containers/charts/PoolWrappingFeesChartContainer.tsx
  apps/hubble-stats/package.json
  apps/stats-dapp/package.json
  apps/tangle-dapp/package.json
  apps/tangle-website/package.json
  apps/webbsite/package.json
  libs/webb-ui-components/package.json
  libs/webb-ui-components/src/components/Table/Table.tsx
  package.json
  yarn.lock
Labels: needs review 👓

#1794 [RELEASE] 2023 Oct 24 - Hubble Bridge, Hubble Stats and Faucet
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/deploy-tangle-website.yml
  .github/workflows/deploy-webbsite-dev.yml
  .github/workflows/release.yml
  .lycheeignore
  apps/bridge-dapp/CHANGELOG.md
  apps/bridge-dapp/package.json
  apps/faucet/CHANGELOG.md
  apps/faucet/package.json
  apps/hubble-stats/CHANGELOG.md
  apps/hubble-stats/package.json
Labels: needs review 👓

#1798 Fix Decimal input in amount field gets auto-deleted
  apps/bridge-dapp/src/hooks/useAmountWithRoute.ts
Labels: needs review 👓

#1797 Minor bugs on Faucet and Hubble Stats (Shielded Pool Table + Header Chip + Sidebar)
  apps/faucet/src/utils/sidebar.ts
  apps/hubble-stats/components/HeaderChipItem/HeaderChipItem.tsx
  apps/hubble-stats/containers/ShieldedTablesContainer/ShieldedTablesContainer.tsx
  libs/webb-ui-components/src/components/SideBar/SideBar.tsx
  libs/webb-ui-components/src/next-utils/sideBarState.ts
  libs/webb-ui-components/src/utils/getCookieItem.ts
  libs/webb-ui-components/src/utils/index.ts
Labels: needs review 👓

#1795 Align Margins and Width in Hubble Bridge and Hubble Statistics
  apps/bridge-dapp/src/components/Header/Header.tsx
  apps/bridge-dapp/src/containers/Layout/Layout.tsx
  apps/bridge-dapp/src/pages/Hubble/Bridge/index.tsx
  apps/hubble-stats/containers/Layout/Layout.tsx
Labels: needs review 👓

#1802 EVM Staking - Active & Waiting Validator List Tables
  apps/tangle-dapp/app/page.tsx
  apps/tangle-dapp/components/ValidatorTable/ValidatorTable.tsx
  apps/tangle-dapp/components/ValidatorTable/index.ts
  apps/tangle-dapp/components/ValidatorTable/types.ts
  apps/tangle-dapp/components/index.ts
  apps/tangle-dapp/components/skeleton/ContainerSkeleton.tsx
  apps/tangle-dapp/components/skeleton/index.ts
  apps/tangle-dapp/components/skeleton/types.ts
  apps/tangle-dapp/components/tableCells/HeaderCell.tsx
  apps/tangle-dapp/components/tableCells/StringCell.tsx
  apps/tangle-dapp/components/tableCells/index.ts
  apps/tangle-dapp/components/tableCells/types.ts
  apps/tangle-dapp/constants/polkadot.ts
  apps/tangle-dapp/containers/ValidatorTablesContainer/ValidatorTableContainer.tsx
  apps/tangle-dapp/containers/ValidatorTablesContainer/ValidatorTablesContainer.tsx
  apps/tangle-dapp/containers/ValidatorTablesContainer/index.ts
  apps/tangle-dapp/containers/index.ts
  apps/tangle-dapp/data/ValidatorTables/getActiveValidators.ts
  apps/tangle-dapp/data/ValidatorTables/getWaitingValidators.ts
  apps/tangle-dapp/data/ValidatorTables/index.ts
  apps/tangle-dapp/data/index.ts
  apps/tangle-dapp/types/index.ts
  libs/webb-ui-components/src/constants/index.ts
  package.json
Labels: needs review 👓, tangle-dapp

#1803 Implement Mobile Variant for Connect Wallet Modal
  apps/bridge-dapp/src/components/Header/ChainButton.tsx
  apps/bridge-dapp/src/components/Header/Header.tsx
  apps/bridge-dapp/src/components/Header/WalletDropdown/index.tsx
  libs/webb-ui-components/src/components/ListCard/ListItem.tsx
  libs/webb-ui-components/src/components/WalletConnectionCard/WalletConnectionCard.tsx
Labels: needs review 👓

#1808 Adding `feature` Branch to Github CI
  .github/workflows/check-build.yml
  .github/workflows/check-lint.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy-bridge-dapp-dev.yml
  .github/workflows/deploy-faucet.yml
  .github/workflows/deploy-stats-dapp-dev.yml
  .github/workflows/deploy-storybook-docs.yml
  .github/workflows/ui-review.yml
Labels: needs review 👓
