Repository tangle-network/dapp, pull requests merged in 2023-07, with the labels that each got.

#1390 Enable Fetching On-Chain Config Regardless of Multicall3 Availability
  .env.example
  .github/workflows/check-build.yml
  .github/workflows/deploy-bridge-dapp-dev.yml
  .github/workflows/release.yml
  apps/bridge-dapp/.env.example
  apps/bridge-dapp/README.md
  apps/bridge-dapp/webpack.base.js
  libs/dapp-config/src/anchors/anchor-config.ts
  libs/dapp-config/src/chains/evm/index.tsx
  libs/dapp-config/src/chains/index.ts
  libs/dapp-config/src/constants.ts
  libs/dapp-config/src/currencies/index.ts
  libs/dapp-config/src/on-chain-config/evm/on-chain-config.ts
  libs/dapp-config/src/on-chain-config/on-chain-config-base.ts
  libs/dapp-config/src/on-chain-config/substrate/on-chain-config.ts
  libs/dapp-config/src/types.ts
  libs/dapp-config/src/utils/addCurrencyToConfig.ts
  libs/dapp-config/src/utils/parseOnChainData.ts
  tools/scripts/fetchingOnChainConfig.ts
  tools/scripts/utils/on-chain-utils/fetchAnchorMetadata.ts
  tools/scripts/utils/on-chain-utils/fetchNative.ts
  tools/scripts/utils/on-chain-utils/getViemClient.ts
  tools/scripts/utils/on-chain-utils/shared.ts
Labels: needs review 👓

#1395 Adding missing hubble-stats netlify config
  apps/hubble-stats/netlify.toml
Labels: needs review 👓

#1394 Adds header component to hubble-stats
  apps/hubble-stats/app/layout.tsx
  apps/hubble-stats/app/page.tsx
  apps/hubble-stats/components/Header/Header.tsx
  apps/hubble-stats/components/Header/index.ts
Labels: needs review 👓

#1376 Sidebar webb-ui Component
  apps/bridge-dapp/src/components/Header/Header.tsx
  apps/bridge-dapp/src/containers/Layout/Layout.tsx
  apps/bridge-dapp/src/pages/Account.tsx
  apps/bridge-dapp/src/pages/Ecosystem.tsx
  apps/bridge-dapp/src/pages/Hubble/Bridge.tsx
  apps/bridge-dapp/src/pages/Hubble/WrapAndUnwrap.tsx
  apps/bridge-dapp/src/routes/index.tsx
  apps/hubble-stats/app/layout.tsx
  libs/icons/src/BillFill.tsx
  libs/icons/src/ContrastTwoLine.tsx
  libs/icons/src/DocumentationIcon.tsx
  libs/icons/src/GridFillIcon.tsx
  libs/icons/src/MoonLine.tsx
  libs/icons/src/SunLine.tsx
  libs/icons/src/Tangle.tsx
  libs/icons/src/index.ts
  libs/webb-ui-components/src/components/Footer/Footer.tsx
  libs/webb-ui-components/src/components/Link/Link.tsx
  libs/webb-ui-components/src/components/Link/index.ts
  libs/webb-ui-components/src/components/Link/types.ts
  libs/webb-ui-components/src/components/Logo/Logo.tsx
  libs/webb-ui-components/src/components/LogoWithoutName/LogoWithoutName.tsx
  libs/webb-ui-components/src/components/LogoWithoutName/index.ts
  libs/webb-ui-components/src/components/LogoWithoutName/types.ts
  libs/webb-ui-components/src/components/SideBar/Item.tsx
  libs/webb-ui-components/src/components/SideBar/SideBar.tsx
  libs/webb-ui-components/src/components/SideBar/SubItem.tsx
  libs/webb-ui-components/src/components/SideBar/index.ts
  libs/webb-ui-components/src/components/SideBar/types.ts
  libs/webb-ui-components/src/components/ThemeToggle/ThemeToggle.tsx
  libs/webb-ui-components/src/components/ThemeToggle/index.ts
  libs/webb-ui-components/src/components/index.ts
  libs/webb-ui-components/src/constants/index.ts
  libs/webb-ui-components/src/stories/molecules/ThemeToggle.stories.jsx
  libs/webb-ui-components/src/stories/organisms/Sidebar.stories.jsx
  yarn.lock
Labels: needs review 👓, ui-components

#1392 Add Shielded Tables for the Hubble Stats (no Filter and Back-end)
  apps/bridge-dapp/src/components/Header/Header.tsx
  apps/bridge-dapp/src/containers/Layout/Layout.tsx
  apps/bridge-dapp/src/containers/note-account-tables/ShieldedAssetsTableContainer/ShieldedAssetsTableContainer.tsx
  apps/bridge-dapp/src/containers/note-account-tables/SpendNotesTableContainer/SpendNotesTableContainer.tsx
  apps/bridge-dapp/src/pages/Hubble/Bridge.tsx
  apps/hubble-stats/app/page.tsx
  apps/hubble-stats/components/Header/Header.tsx
  apps/hubble-stats/components/KeyMetricItem/KeyMetricItem.tsx
  apps/hubble-stats/components/KeyMetricItem/index.ts
  apps/hubble-stats/components/KeyMetricItem/types.ts
  apps/hubble-stats/components/KeyMetricsTable/index.ts
  apps/hubble-stats/components/ShieldedAssetsTable/ShieldedAssetsTable.tsx
  apps/hubble-stats/components/ShieldedAssetsTable/index.ts
  apps/hubble-stats/components/ShieldedAssetsTable/types.ts
  apps/hubble-stats/components/ShieldedPoolsTable/ShieldedPoolsTable.tsx
  apps/hubble-stats/components/ShieldedPoolsTable/index.ts
  apps/hubble-stats/components/ShieldedPoolsTable/types.ts
  apps/hubble-stats/components/index.ts
  apps/hubble-stats/components/table/HeaderCell.tsx
  apps/hubble-stats/components/table/NumberCell.tsx
  apps/hubble-stats/components/table/PoolTypeCell.tsx
  apps/hubble-stats/components/table/ShieldedCell.tsx
  apps/hubble-stats/components/table/index.ts
  apps/hubble-stats/components/table/types.ts
  apps/hubble-stats/containers/KeyMetricsTableContainer/KeyMetricsTableContainer.tsx
  apps/hubble-stats/containers/KeyMetricsTableContainer/index.ts
  apps/hubble-stats/containers/ShieldedTablesContainer/ShieldedTablesContainer.tsx
  apps/hubble-stats/containers/ShieldedTablesContainer/index.ts
  apps/hubble-stats/containers/index.ts
  libs/icons/src/ShieldedAssetDark.tsx
  libs/icons/src/ShieldedAssetLight.tsx
  libs/icons/src/index.ts
  libs/icons/src/utils.ts
  libs/webb-ui-components/src/components/Breadcrumbs/BreadcrumbsItem.tsx
  libs/webb-ui-components/src/components/IconsGroup/IconsGroup.tsx
  libs/webb-ui-components/src/components/IconsGroup/index.ts
  libs/webb-ui-components/src/components/IconsGroup/types.ts
  libs/webb-ui-components/src/components/IconsGroup/utils.ts
  libs/webb-ui-components/src/components/Table/Table.tsx
  libs/webb-ui-components/src/components/Table/types.ts
  libs/webb-ui-components/src/components/TableAndChartTabs/TableAndChartTabs.tsx
  libs/webb-ui-components/src/components/TableAndChartTabs/index.ts
  libs/webb-ui-components/src/components/TableAndChartTabs/types.ts
  libs/webb-ui-components/src/components/index.ts
  libs/webb-ui-components/src/stories/molecules/IconsGroup.stories.jsx
  libs/webb-ui-components/src/stories/molecules/TableAndChartTabs.stories.jsx
Labels: needs review 👓

#1397 Fix: progress bar reset & remove proposals chart
  apps/stats-dapp/src/containers/KeyStatusCardContainer/KeyStatusCardContainer.tsx
  apps/stats-dapp/src/pages/Proposals.tsx
Labels: needs review 👓, statistics

#1424 Linh/hubble stats pool tables
  apps/hubble-stats/app/layout.tsx
  apps/hubble-stats/app/pool/[slug]/page.tsx
  apps/hubble-stats/components/PoolMetadataTable/PoolMetadataTable.tsx
  apps/hubble-stats/components/PoolMetadataTable/index.ts
  apps/hubble-stats/components/PoolMetadataTable/types.ts
  apps/hubble-stats/components/PoolTransactionsTable/PoolTransactionsTable.tsx
  apps/hubble-stats/components/PoolTransactionsTable/index.ts
  apps/hubble-stats/components/PoolTransactionsTable/types.ts
  apps/hubble-stats/components/ShieldedAssetsTable/ShieldedAssetsTable.tsx
  apps/hubble-stats/components/ShieldedPoolsTable/ShieldedPoolsTable.tsx
  apps/hubble-stats/components/index.ts
  apps/hubble-stats/components/table/ActivityCell.tsx
  apps/hubble-stats/components/table/DestinationCell.tsx
  apps/hubble-stats/components/table/FilterButton.tsx
  apps/hubble-stats/components/table/NumberCell.tsx
  apps/hubble-stats/components/table/TimeCell.tsx
  apps/hubble-stats/components/table/index.ts
  apps/hubble-stats/components/table/types.ts
  apps/hubble-stats/containers/PoolMetadataTableContainer/PoolMetadataTableContainer.tsx
  apps/hubble-stats/containers/PoolMetadataTableContainer/index.ts
  apps/hubble-stats/containers/PoolTransactionsTableContainer/PoolTransactionsTableContainer.tsx
  apps/hubble-stats/containers/PoolTransactionsTableContainer/index.ts
  apps/hubble-stats/containers/index.ts
  apps/hubble-stats/next.config.js
  libs/webb-ui-components/src/components/CheckBoxMenu/CheckBoxMenu.tsx
  libs/webb-ui-components/src/components/CheckBoxMenu/CheckBoxMenuGroup.tsx
  libs/webb-ui-components/src/components/CheckBoxMenu/types.d.ts
  libs/webb-ui-components/src/components/SideBar/SideBar.tsx
  libs/webb-ui-components/src/components/SideBar/types.ts
  yarn.lock
Labels: needs review 👓

#1432 Update Anchor Addresses and Faucet Tokens Addresses
  apps/faucet/src/config/tokens.ts
  libs/dapp-config/src/anchors/anchor-config.ts
Labels: needs review 👓

#1433 Add `dependabot`
  .github/dependabot.yml
Labels: needs review 👓

#1454 Faucet UI Improvements
  apps/faucet/src/components/ChainDropdown.tsx
  apps/faucet/src/components/ContractAddressInput.tsx
  apps/faucet/src/components/Header.tsx
  apps/faucet/src/components/ProcessingModal.tsx
  apps/faucet/src/components/TokenDropdown.tsx
  apps/faucet/src/containers/InputsContainer.tsx
  apps/faucet/src/containers/LoginWithTwitter.tsx
  apps/faucet/src/containers/MintButtonContainer.tsx
  apps/faucet/src/errors/FaucetError.ts
  apps/faucet/src/errors/FaucetErrorCode.ts
  apps/faucet/src/errors/FaucetErrorPayload.ts
  apps/faucet/src/pages/_app.tsx
  apps/faucet/src/pages/index.tsx
  apps/faucet/src/provider/index.tsx
  apps/faucet/src/styles/globals.css
  apps/faucet/src/types/index.ts
  apps/faucet/src/utils/isTooManyClaimResponse.ts
  apps/faucet/src/utils/parseErrorFromResult.ts
  libs/icons/src/types.ts
  libs/icons/src/utils.ts
  libs/webb-ui-components/src/components/BridgeInputs/TokenInput.tsx
  libs/webb-ui-components/src/components/Button/Button.tsx
  libs/webb-ui-components/src/components/Button/types.ts
  libs/webb-ui-components/src/components/Button/utils.ts
  libs/webb-ui-components/src/utils/shortenHex.ts
Labels: needs review 👓

#1463 Add Adjust Amount component & Fixed Tailwind Dark Mode on Storybook
  .github/workflows/check-build.yml
  .github/workflows/check-lint.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/deploy-storybook-docs.yml
  .github/workflows/ui-review.yml
  .storybook/main.js
  libs/icons/src/AddCircleFillIcon.tsx
  libs/icons/src/AddCircleLineIcon.tsx
  libs/icons/src/IndeterminateCircleFillIcon.tsx
  libs/icons/src/IndeterminateCircleLineIcon.tsx
  libs/icons/src/index.ts
  libs/webb-ui-components/.storybook/main.js
  libs/webb-ui-components/.storybook/preview.js
  libs/webb-ui-components/src/components/BridgeInputs/AdjustAmount.tsx
  libs/webb-ui-components/src/components/BridgeInputs/FixedAmount.tsx
  libs/webb-ui-components/src/components/BridgeInputs/index.ts
  libs/webb-ui-components/src/components/BridgeInputs/types.ts
  libs/webb-ui-components/src/stories/Introduction.stories.mdx
  libs/webb-ui-components/src/stories/molecules/AdjustAmount.stories.jsx
  libs/webb-ui-components/tailwind.config.js
  package.json
  tailwind.config.js
  yarn.lock
Labels: needs review 👓

#1452 Add network tables for Hubble Stats
  .github/workflows/deploy-hubble-stats.yml
  apps/hubble-stats/app/pool/[slug]/page.tsx
  apps/hubble-stats/components/NetworkPoolTable/NetworkPoolTable.tsx
  apps/hubble-stats/components/NetworkPoolTable/index.ts
  apps/hubble-stats/components/NetworkPoolTable/types.ts
  apps/hubble-stats/components/NetworkTokenTable/NetworkTokenTable.tsx
  apps/hubble-stats/components/NetworkTokenTable/index.ts
  apps/hubble-stats/components/NetworkTokenTable/types.ts
  apps/hubble-stats/components/index.ts
  apps/hubble-stats/containers/NetworkTablesContainer/NetworkTablesContainer.tsx
  apps/hubble-stats/containers/NetworkTablesContainer/index.ts
  apps/hubble-stats/containers/PoolMetadataTableContainer/PoolMetadataTableContainer.tsx
  apps/hubble-stats/containers/index.ts
  apps/hubble-stats/utils/getSortedTypedChainIds.ts
  apps/hubble-stats/utils/index.ts
  libs/dapp-config/src/chains/chain-config.interface.ts
  libs/icons/src/CornerDownRightLine.tsx
  libs/icons/src/index.ts
Labels: needs review 👓

#1465 Fix Environment Variables Issue
  .env.example
  .github/workflows/check-build.yml
  .github/workflows/deploy-bridge-dapp-dev.yml
  .github/workflows/deploy-faucet.yml
  .github/workflows/deploy-hubble-stats.yml
  .github/workflows/deploy-stats-dapp-dev.yml
  .github/workflows/deploy-tangle-website.yml
  .github/workflows/deploy-webbsite-dev.yml
  .github/workflows/release.yml
  apps/bridge-dapp/.env.example
  apps/bridge-dapp/scripts/localSubstrate.ts
  apps/bridge-dapp/scripts/localTangle.ts
  apps/bridge-dapp/src/constants/signIn.ts
  apps/bridge-dapp/webpack.base.js
  apps/faucet/.env.local.example
  libs/dapp-config/src/anchors/anchor-config.ts
  libs/dapp-config/src/chains/evm/index.tsx
  libs/dapp-config/src/wagmi-config.ts
  libs/dapp-config/src/wallets/wallets-config.tsx
Labels: needs review 👓

#1468 V2 ToggleCard component
  libs/icons/src/GasStationFill.tsx
  libs/icons/src/index.ts
  libs/webb-ui-components/src/components/ToggleCard/ToggleCard.tsx
  libs/webb-ui-components/src/components/ToggleCard/index.ts
  libs/webb-ui-components/src/components/ToggleCard/types.ts
  libs/webb-ui-components/src/components/index.ts
  libs/webb-ui-components/src/stories/molecules/ToggleCard.stories.tsx
Labels: needs review 👓

#1455 Migrate WSS to HTTP for Relayer
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
  apps/bridge-dapp/src/hooks/useMaxFeeInfo.ts
  apps/bridge-dapp/src/utils/getTokenURI.ts
  libs/abstract-api-provider/src/relayer/types.ts
  libs/abstract-api-provider/src/relayer/webb-relayer.ts
  libs/dapp-config/src/gasLimitConfig.ts
  libs/dapp-types/src/EVMChainId.ts
  libs/dapp-types/src/WebbError.ts
  libs/icons/src/chains/athena.svg
  libs/icons/src/chains/demeter.svg
  libs/icons/src/chains/hermes.svg
  libs/polkadot-api-provider/src/webb-provider/vanchor-actions.ts
  libs/web3-api-provider/src/utils/evmProviderFactory.ts
  libs/web3-api-provider/src/webb-provider.ts
  libs/web3-api-provider/src/webb-provider/relayer-manager.ts
  libs/web3-api-provider/src/webb-provider/vanchor-actions.ts
  libs/web3-api-provider/src/webb-provider/wrap-unwrap.ts
  libs/webb-ui-components/src/components/ChainChip/utils.ts
  tools/scripts/fetchingOnChainConfig.ts
Labels: needs review 👓

#1469 Adding StatusIndicator Component to `webb-ui-kit`
  libs/webb-ui-components/src/components/StatusIndicator/StatusIndicator.tsx
  libs/webb-ui-components/src/components/StatusIndicator/index.ts
  libs/webb-ui-components/src/components/StatusIndicator/types.ts
  libs/webb-ui-components/src/components/index.ts
  libs/webb-ui-components/src/stories/atoms/StatusIndicator.stories.tsx
Labels: needs review 👓

#1470 Hubble Stats Breadcrumbs
  apps/hubble-stats/app/layout.tsx
  apps/hubble-stats/components/Header/Header.tsx
  apps/hubble-stats/components/Header/index.ts
  apps/hubble-stats/components/Header/types.ts
  libs/icons/src/ContrastLine.tsx
  libs/icons/src/index.ts
  libs/webb-ui-components/src/components/Breadcrumbs/BreadcrumbsItem.tsx
  libs/webb-ui-components/src/components/Breadcrumbs/BreadcrumbsSeparator.tsx
Labels: needs review 👓, hubble-stats
