Repository tangle-network/dapp, pull requests merged in 2023-04, with the labels that each got.

#1093 Adds social links to every blog page
  apps/webbsite/src/pages/blog/posts/[slug].tsx
  libs/icons/src/CopyLinkFill.tsx
  libs/icons/src/LinkedIn.tsx
  libs/icons/src/index.ts
Labels: approved ✅, webbsite 🕸️

#1091 adds tangle website introduction section
  apps/tangle-website/public/static/assets/body-bg.jpg
  apps/tangle-website/public/static/assets/hero-image.png
  apps/tangle-website/public/static/assets/hero-section.jpg
  apps/tangle-website/src/components/Heading.tsx
  apps/tangle-website/src/components/Heading1.tsx
  apps/tangle-website/src/components/IntroducingTangleSVG.tsx
  apps/tangle-website/src/components/SectionDescription.tsx
  apps/tangle-website/src/components/SectionHeader.tsx
  apps/tangle-website/src/components/SectionTitle.tsx
  apps/tangle-website/src/components/Socials.tsx
  apps/tangle-website/src/components/SubHeading1.tsx
  apps/tangle-website/src/components/index.ts
  apps/tangle-website/src/components/sections/HeroSection.tsx
  apps/tangle-website/src/components/sections/IntroducingSection.tsx
  apps/tangle-website/src/components/sections/index.ts
  apps/tangle-website/src/libs/notion/notion.ts
  apps/tangle-website/src/libs/notion/server-constants.ts
  apps/tangle-website/src/pages/index.tsx
  apps/tangle-website/src/styles/globals.css
  apps/tangle-website/tailwind.config.js
Labels: approved ✅

#1095 Max Fee Calculation for Deposit, Transfer and Withdraw flows
  apps/bridge-dapp/src/containers/DepositContainer/DepositConfirmContainer.tsx
  apps/bridge-dapp/src/containers/DepositContainer/DepositContainer.tsx
  apps/bridge-dapp/src/containers/DepositContainer/types.d.ts
  apps/bridge-dapp/src/containers/TransferContainer/TransferConfirmContainer.tsx
  apps/bridge-dapp/src/containers/TransferContainer/TransferContainer.tsx
  apps/bridge-dapp/src/containers/TransferContainer/types.d.ts
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawConfirmContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/types.d.ts
  apps/bridge-dapp/src/hooks/index.ts
  apps/bridge-dapp/src/hooks/useMaxFeeInfo.ts
  apps/bridge-dapp/src/hooks/useWIthdrawFee.ts
  libs/abstract-api-provider/src/chain-query/index.ts
  libs/abstract-api-provider/src/relayer/webb-relayer.ts
  libs/abstract-api-provider/src/vanchor/vanchor-actions.ts
  libs/dapp-config/src/gasLimit-config.ts
  libs/polkadot-api-provider/src/webb-provider/chain-query.ts
  libs/polkadot-api-provider/src/webb-provider/relayer-manager.ts
  libs/react-hooks/src/currency/useBalancesFromNotes.tsx
  libs/react-hooks/src/currency/useCurrencyBalance.tsx
  libs/relayer-manager-factory/src/relayer-manager-factory.ts
  libs/web3-api-provider/src/webb-provider.ts
  libs/web3-api-provider/src/webb-provider/chain-query.ts
  libs/web3-api-provider/src/webb-provider/relayer-manager.ts
  libs/web3-api-provider/src/webb-provider/vanchor-actions.ts
  libs/webb-ui-components/src/components/BridgeInputs/AmountInput.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/DepositConfirm.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/TransferConfirm.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/WithdrawConfirm.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/types.ts
  libs/webb-ui-components/src/containers/DepositCard/DepositCard.tsx
  libs/webb-ui-components/src/containers/TransferCard/TransferCard.tsx
  libs/webb-ui-components/src/containers/TransferCard/types.ts
Labels: needs review 👓

#1096 adds tangle website features section
  apps/tangle-website/public/static/assets/tangle-features-1.png
  apps/tangle-website/public/static/assets/tangle-features-2.png
  apps/tangle-website/public/static/assets/tangle-features-3.png
  apps/tangle-website/src/components/Header.tsx
  apps/tangle-website/src/components/TangleFeatureCard.tsx
  apps/tangle-website/src/components/index.ts
  apps/tangle-website/src/components/sections/FeaturesSection.tsx
  apps/tangle-website/src/components/sections/HeroSection.tsx
  apps/tangle-website/src/components/sections/index.ts
  apps/tangle-website/src/pages/index.tsx
  libs/webb-ui-components/src/components/ErrorFallback/ErrorFallback.tsx
  libs/webb-ui-components/src/components/Socials/Socials.tsx
  libs/webb-ui-components/src/components/Socials/types.ts
  libs/webb-ui-components/src/constants/index.ts
Labels: needs changes 🔧

#1101 Adds footer & newsletter form to tangle-website
  .github/workflows/deploy-tangle-website.yml
  apps/tangle-website/src/libs/notion/index.ts
  apps/tangle-website/src/pages/_app.tsx
  apps/tangle-website/src/pages/api/subscribers/index.ts
  apps/tangle-website/src/pages/privacy-policy.tsx
  apps/tangle-website/src/pages/terms-and-conditions.tsx
  apps/tangle-website/src/utils/index.ts
  apps/tangle-website/src/utils/isValidEmail.ts
  apps/webbsite/src/components/index.ts
  apps/webbsite/src/pages/_app.tsx
  libs/webb-ui-components/src/components/TangleLogo/TangleLogo.tsx
  libs/webb-ui-components/src/components/WebsiteFooter/WebsiteFooter.tsx
  libs/webb-ui-components/src/components/WebsiteFooter/index.ts
  libs/webb-ui-components/src/components/WebsiteNewsLetterForm/WebsiteNewsLetterForm.tsx
  libs/webb-ui-components/src/components/WebsiteNewsLetterForm/index.ts
  libs/webb-ui-components/src/components/index.ts
Labels: needs review 👓, tangle-website 🪢

#1106 add tangle website governance system
  apps/tangle-website/public/static/assets/governance-system.png
  apps/tangle-website/src/components/LinkButton.tsx
  apps/tangle-website/src/components/Navbar.tsx
  apps/tangle-website/src/components/SectionHeader.tsx
  apps/tangle-website/src/components/TangleFeatureCard.tsx
  apps/tangle-website/src/components/index.ts
  apps/tangle-website/src/components/sections/FeaturesSection.tsx
  apps/tangle-website/src/components/sections/GovernanceSystemSection.tsx
  apps/tangle-website/src/components/sections/HeroSection.tsx
  apps/tangle-website/src/components/sections/IntroducingSection.tsx
  apps/tangle-website/src/components/sections/index.ts
  apps/tangle-website/src/components/svgs/HowTssWorksSvg.tsx
  apps/tangle-website/src/components/svgs/IntroducingTangleSvg.tsx
  apps/tangle-website/src/components/svgs/WhatIsTssSvg.tsx
  apps/tangle-website/src/components/svgs/index.tsx
  apps/tangle-website/src/constants/index.ts
  apps/tangle-website/src/pages/index.tsx
  apps/tangle-website/src/styles/globals.css
  apps/tangle-website/tailwind.config.js
Labels: needs review 👓

#1107 Liquidity Check
  apps/bridge-dapp/src/containers/DepositContainer/DepositContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
  libs/react-hooks/src/currency/useCurrencyBalance.tsx
Labels: approved ✅

#1110 Tangle Website - Use cases Section
  apps/tangle-website/src/components/SectionTitle2.tsx
  apps/tangle-website/src/components/index.ts
  apps/tangle-website/src/components/sections/UseCasesSection.tsx
  apps/tangle-website/src/components/sections/index.ts
  apps/tangle-website/src/components/svgs/UseCase1Svg.tsx
  apps/tangle-website/src/components/svgs/UseCase2Svg.tsx
  apps/tangle-website/src/components/svgs/UseCase3Svg.tsx
  apps/tangle-website/src/components/svgs/UseCase4Svg.tsx
  apps/tangle-website/src/components/svgs/index.tsx
  apps/tangle-website/src/pages/index.tsx
Labels: needs review 👓, tangle-website 🪢

#1111 Tangle Website - Supported By Section
  apps/tangle-website/public/static/svgs/commonwealth.svg
  apps/tangle-website/public/static/svgs/substrateBuildersProgram.svg
  apps/tangle-website/public/static/svgs/web3Foundation.svg
  apps/tangle-website/src/components/Header.tsx
  apps/tangle-website/src/components/Navbar.tsx
  apps/tangle-website/src/components/sections/SupportedBySection.tsx
  apps/tangle-website/src/components/sections/index.ts
  apps/tangle-website/src/constants/index.ts
  apps/tangle-website/src/pages/index.tsx
Labels: needs changes 🔧, needs review 👓, tangle-website 🪢

#1108 Tangle website - Participation Mechanics Section
  apps/tangle-website/src/components/ParticipationTabTrigger.tsx
  apps/tangle-website/src/components/index.ts
  apps/tangle-website/src/components/sections/FeaturesSection.tsx
  apps/tangle-website/src/components/sections/ParticipationMechanicsSection.tsx
  apps/tangle-website/src/components/sections/index.ts
  apps/tangle-website/src/constants/index.ts
  apps/tangle-website/src/pages/index.tsx
  apps/tangle-website/src/styles/globals.css
Labels: needs changes 🔧

#1121 Adds SEO, plausible, and favicon to Tangle website
  .github/assets/new-webb-icon-dark.svg
  apps/tangle-website/public/static/assets/favicon.png
  apps/tangle-website/src/components/svgs/UseCase1Svg.tsx
  apps/tangle-website/src/components/svgs/UseCase2Svg.tsx
  apps/tangle-website/src/components/svgs/UseCase3Svg.tsx
  apps/tangle-website/src/components/svgs/UseCase4Svg.tsx
  apps/tangle-website/src/pages/_app.tsx
  apps/tangle-website/src/pages/index.tsx
  libs/logos/src/chains/EthLogo.tsx
  libs/logos/src/chains/HarmonyLogo.tsx
  libs/logos/src/wallets/SubWalletLogo.tsx
Labels: needs review 👓, tangle-website 🪢

#1048 8-sided Bridge with DKG Deployment
  apps/bridge-dapp/src/components/ChainListCardWrapper/ChainListCardWrapper.tsx
  apps/bridge-dapp/src/containers/DepositContainer/DepositContainer.tsx
  apps/bridge-dapp/src/containers/TransferContainer/TransferConfirmContainer.tsx
  apps/bridge-dapp/src/containers/TransferContainer/TransferContainer.tsx
  apps/bridge-dapp/src/containers/TransferContainer/types.d.ts
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawConfirmContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/shared.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/types.d.ts
  apps/bridge-dapp/src/hooks/useMaxFeeInfo.ts
  apps/bridge-dapp/src/pages/PageBridge.tsx
  apps/bridge-dapp/src/utils/getAcitveSourceChains.ts
  libs/abstract-api-provider/src/relayer/types.ts
  libs/abstract-api-provider/src/relayer/webb-relayer.ts
  libs/abstract-api-provider/src/vanchor/vanchor-actions.ts
  libs/api-provider-environment/src/WebbProvider.tsx
  libs/api-provider-environment/src/error/index.ts
  libs/api-provider-environment/src/error/parseError.ts
  libs/dapp-config/src/anchors/anchor-config.ts
  libs/dapp-config/src/chains/chain-config.interface.ts
  libs/dapp-config/src/chains/evm/index.tsx
  libs/dapp-config/src/chains/substrate/index.tsx
  libs/dapp-config/src/gasLimit-config.ts
  libs/dapp-config/src/on-chain-config/evm/on-chain-config.ts
  libs/dapp-config/src/wallets/wallets-config.tsx
  libs/dapp-types/src/ChainId.ts
  libs/dapp-types/src/EVMChainId.ts
  libs/icons/src/chains/athena-orbit.svg
  libs/icons/src/chains/demeter-orbit.svg
  libs/icons/src/chains/hermes-orbit.svg
  libs/web3-api-provider/src/ext-provider/web3-provider.ts
  libs/web3-api-provider/src/webb-provider.ts
  libs/web3-api-provider/src/webb-provider/vanchor-actions.ts
  libs/webb-ui-components/src/components/BridgeInputs/RecipientInput.tsx
  libs/webb-ui-components/src/components/Notification/NotificationItem.tsx
  libs/webb-ui-components/src/components/TokenWithAmount/TokenWithAmount.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/DepositConfirm.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/TransferConfirm.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/WithdrawConfirm.tsx
  libs/webb-ui-components/src/containers/DepositCard/DepositCard.tsx
  libs/webb-ui-components/src/containers/TransferCard/TransferCard.tsx
  libs/webb-ui-components/src/containers/TransferCard/types.ts
  libs/webb-ui-components/src/containers/WithdrawCard/WithdrawCard.tsx
  libs/webb-ui-components/src/utils/getRoundedAmountString.ts
  package.json
  yarn.lock
Labels: needs review 👓

#1126 [RELEASE]: Fixes authorities table in authorities page
  apps/stats-dapp/CHANGELOG.md
  apps/stats-dapp/package.json
  apps/stats-dapp/src/provider/hooks/useAuthorities.ts
Labels: statistics

#1118 Adds website launch phases section to Tangle website
  apps/tangle-website/src/components/Header.tsx
  apps/tangle-website/src/components/ParticipationTabTrigger.tsx
  apps/tangle-website/src/components/SectionDescription2.tsx
  apps/tangle-website/src/components/SectionHeader.tsx
  apps/tangle-website/src/components/SectionTitle2.tsx
  apps/tangle-website/src/components/Socials.tsx
  apps/tangle-website/src/components/TangleFeatureCard.tsx
  apps/tangle-website/src/components/index.ts
  apps/tangle-website/src/components/sections/CommunitySection.tsx
  apps/tangle-website/src/components/sections/FeaturesSection.tsx
  apps/tangle-website/src/components/sections/GovernanceSystemSection.tsx
  apps/tangle-website/src/components/sections/HeroSection.tsx
  apps/tangle-website/src/components/sections/IntroducingSection.tsx
  apps/tangle-website/src/components/sections/LaunchPhasesSection.tsx
  apps/tangle-website/src/components/sections/ParticipationMechanicsSection.tsx
  apps/tangle-website/src/components/sections/SupportedBySection.tsx
  apps/tangle-website/src/components/sections/UseCasesSection.tsx
  apps/tangle-website/src/components/sections/index.ts
  apps/tangle-website/src/pages/index.tsx
  apps/tangle-website/src/styles/globals.css
Labels: needs changes 🔧, needs review 👓

#1145 Updates proposal chart to show data from first available data point
  apps/stats-dapp/src/containers/StackedAreaChartContainer/StackedAreaChartContainer.tsx
Labels: needs review 👓, statistics

#1144 Update/fix stats-dapp UI discrepancies Part 1
  apps/stats-dapp/src/containers/ProposalDetail/ProposalDetail.tsx
  apps/stats-dapp/src/containers/ProposalsTable/ProposalsTable.tsx
  apps/stats-dapp/src/pages/Proposals.tsx
  apps/stats-dapp/src/provider/hooks/useProposals.ts
  apps/stats-dapp/src/utils/mapChainIdToCurrencyName.ts
  libs/icons/src/utils.ts
Labels: needs review 👓, statistics

#1146 [RELEASE] release of stats-dapp v0.0.5
  .lycheeignore
  apps/faucet/src/pages/index.tsx
  apps/stats-dapp/CHANGELOG.md
  apps/stats-dapp/package.json
  apps/stats-dapp/src/containers/ProposalDetail/ProposalDetail.tsx
  apps/stats-dapp/src/containers/ProposalsTable/ProposalsTable.tsx
  apps/stats-dapp/src/containers/StackedAreaChartContainer/StackedAreaChartContainer.tsx
  apps/stats-dapp/src/pages/Proposals.tsx
  apps/stats-dapp/src/provider/hooks/useProposals.ts
  apps/stats-dapp/src/utils/mapChainIdToCurrencyName.ts
  apps/tangle-website/src/pages/_app.tsx
  libs/icons/src/utils.ts
Labels: statistics

#1147 Quick action prompts a chain switch
  apps/bridge-dapp/src/containers/DepositContainer/DepositContainer.tsx
  apps/bridge-dapp/src/containers/note-account-tables/ShieldedAssetsTableContainer/ShieldedAssetsTableContainer.tsx
Labels: needs review 👓, bridge

#1149 Show proposer details in proposal details drawer
  .github/workflows/check-build.yml
  .github/workflows/deploy-stats-dapp-dev.yml
  .gitignore
  .graphqlconfig
  apps/stats-dapp/.gitignore
  apps/stats-dapp/.graphqlconfig
  apps/stats-dapp/codegen.yml
  apps/stats-dapp/src/containers/ProposalsTable/ProposalsTable.tsx
  apps/stats-dapp/src/containers/ProposersTable/ProposersTable.tsx
  apps/stats-dapp/src/generated/graphql.tsx
  apps/stats-dapp/src/gql/proposals.graphql
  apps/stats-dapp/src/provider/hooks/mappers/index.ts
  apps/stats-dapp/src/provider/hooks/useProposals.ts
  apps/stats-dapp/src/utils/getChipColorByProposalType.ts
  apps/stats-dapp/src/utils/getProposalsData.ts
  codegen.yml
  graphql.schema.json
  package.json
  schema.graphql
Labels: wip 🚧, statistics

#1151 [RELEASE] : minor releases of stats-dapp and bridge
  .github/workflows/check-build.yml
  .github/workflows/deploy-stats-dapp-dev.yml
  .gitignore
  .graphqlconfig
  .lycheeignore
  apps/bridge-dapp/CHANGELOG.md
  apps/bridge-dapp/package.json
  apps/bridge-dapp/src/containers/DepositContainer/DepositContainer.tsx
  apps/bridge-dapp/src/containers/note-account-tables/ShieldedAssetsTableContainer/ShieldedAssetsTableContainer.tsx
  apps/stats-dapp/.gitignore
  apps/stats-dapp/.graphqlconfig
  apps/stats-dapp/CHANGELOG.md
  apps/stats-dapp/codegen.yml
  apps/stats-dapp/package.json
  apps/stats-dapp/src/containers/ProposalsTable/ProposalsTable.tsx
  apps/stats-dapp/src/containers/ProposersTable/ProposersTable.tsx
  apps/stats-dapp/src/generated/graphql.tsx
  apps/stats-dapp/src/gql/proposals.graphql
  apps/stats-dapp/src/provider/hooks/mappers/index.ts
  apps/stats-dapp/src/provider/hooks/useProposals.ts
  apps/stats-dapp/src/utils/getChipColorByProposalType.ts
  apps/stats-dapp/src/utils/getProposalsData.ts
  codegen.yml
  graphql.schema.json
  package.json
  schema.graphql
Labels: needs review 👓

#1154 Fixes Proposal Timeline
  apps/stats-dapp/src/containers/ProposalDetail/ProposalDetail.tsx
  libs/webb-ui-components/src/components/TimeLine/TimeLineItem.tsx
Labels: needs review 👓, statistics

#1156 [RELEASE] Release of bridge-dapp v0.0.5 (#1146)
  apps/bridge-dapp/CHANGELOG.md
  apps/bridge-dapp/package.json
  libs/api-provider-environment/src/transaction/useTransactionQueue.tsx
  libs/web3-api-provider/src/webb-provider/vanchor-actions.ts
  libs/webb-ui-components/src/containers/TransactionProgressCard/TransactionProgressCard.tsx
  libs/webb-ui-components/src/containers/TransactionProgressCard/TransactionQueueCard.tsx
Labels: needs review 👓
