Repository tangle-network/dapp, pull requests merged in 2023-09, with the labels that each got.

#1576 Stats dApp fixes and adds rotated key status to key timeline
  apps/stats-dapp/src/containers/AuthoritiesTable/AuthoritiesTable.tsx
  apps/stats-dapp/src/containers/KeyDetail/KeyDetail.tsx
  apps/stats-dapp/src/provider/hooks/useAuthorities.ts
  libs/webb-ui-components/src/components/TitleWithInfo/TitleWithInfo.tsx
  libs/webb-ui-components/src/components/Tooltip/Tooltip.tsx
Labels: needs review 👓, statistics

#1579 [RELEASE] DKG Stats dApp - September 2, 2021
  .eslintignore
  .lycheeignore
  .prettierignore
  apps/stats-dapp/CHANGELOG.md
  apps/stats-dapp/package.json
Labels: needs review 👓

#1580 Fix Overflow Issue and Experiment GIF for Hero Animation on Webbsite
  .gitignore
  .vscode/settings.json
  .vscode/tailwind.json
  apps/webbsite/public/animations/hero-loop.gif
  apps/webbsite/src/components/Header.tsx
  apps/webbsite/src/components/sections/HeroSection.tsx
  apps/webbsite/src/components/sections/PrivacyConnectedSection.tsx
  apps/webbsite/src/pages/index.tsx
  apps/webbsite/src/styles/globals.css
  apps/webbsite/src/styles/variables.css
Labels: needs review 👓

#1589 Update new Orbit deployment
  apps/faucet/src/config/tokens.ts
  libs/dapp-config/src/anchors/anchor-config.ts
  libs/dapp-config/src/signature-bridges/signature-bridge-config.ts
Labels: needs review 👓

#1592 Fix Small Amount Issue & Calculate Refund Fee Correctly
  apps/bridge-dapp/src/containers/DepositContainer/DepositContainer.tsx
  apps/bridge-dapp/src/containers/TransferContainer/TransferContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
  apps/bridge-dapp/src/hooks/useShieldedAssets.ts
  libs/dapp-config/src/chains/chain-config.interface.ts
  libs/dapp-config/src/chains/evm/index.tsx
  libs/note-manager/src/note-manager.ts
  libs/webb-ui-components/src/utils/index.ts
  libs/webb-ui-components/src/utils/numberToString.ts
Labels: needs review 👓

#1602 [HOTFIX] Leaf Index Checking & Relayer State
  apps/bridge-dapp/src/components/Header/Header.tsx
  apps/bridge-dapp/src/hooks/useMaxFeeInfo.ts
  apps/bridge-dapp/src/pages/Hubble/Bridge/SelectRelayer.tsx
  apps/bridge-dapp/src/pages/Hubble/Bridge/Transfer/private/useFeeCalculation.ts
  apps/bridge-dapp/src/pages/Hubble/Bridge/Transfer/private/useRelayerWithRoute.ts
  apps/bridge-dapp/src/pages/Hubble/Bridge/Transfer/private/useTransferButtonProps.tsx
  apps/bridge-dapp/src/pages/Hubble/Bridge/Withdraw/private/useFeeCalculation.ts
  apps/bridge-dapp/src/pages/Hubble/Bridge/Withdraw/private/useRelayerWithRoute.ts
  apps/bridge-dapp/src/pages/Hubble/Bridge/Withdraw/private/useWithdrawButtonProps.tsx
  apps/bridge-dapp/src/utils/validateNoteLeafIndex.ts
  libs/abstract-api-provider/src/relayer/webb-relayer-manager.ts
  libs/polkadot-api-provider/src/webb-provider/relayer-manager.ts
  libs/react-hooks/src/relayer/useRelayers.ts
  libs/web3-api-provider/src/webb-provider/relayer-manager.ts
Labels: needs review 👓

#1614 Fix Hubble Stats Theme Flickering
  apps/hubble-stats/app/layout.tsx
  apps/hubble-stats/app/providers.tsx
  apps/hubble-stats/components/charts/AreaChart.tsx
  apps/hubble-stats/components/charts/BarChart.tsx
  apps/hubble-stats/components/charts/VolumeChart.tsx
  apps/hubble-stats/components/sideBar/sideBarProps.tsx
  apps/hubble-stats/containers/Layout/Layout.tsx
  apps/hubble-stats/containers/OverviewChipsContainer/OverviewChipsContainer.tsx
  libs/webb-ui-components/src/components/SideBar/Footer.tsx
  libs/webb-ui-components/src/components/SideBar/SideBar.tsx
  libs/webb-ui-components/src/components/SideBar/SideBarMenu.tsx
  libs/webb-ui-components/src/components/SideBar/types.ts
  libs/webb-ui-components/src/components/ThemeToggle/ThemeToggle.tsx
  libs/webb-ui-components/src/components/ThemeToggle/types.ts
  libs/webb-ui-components/src/hooks/useDarkMode.ts
  package.json
  yarn.lock
Labels: needs review 👓

#1613 Add TVL change rate + Add Explorer Urls
  apps/bridge-dapp/src/components/Header/TxProgressDropdown/TxItem.tsx
  apps/bridge-dapp/src/hooks/useEnqueueSubmittedTx.tsx
  apps/hubble-stats/app/pool/[slug]/page.tsx
  apps/hubble-stats/components/KeyMetricItem/KeyMetricItem.tsx
  apps/hubble-stats/components/PoolMetadataTable/ExplorerUrlsDropdown.tsx
  apps/hubble-stats/components/PoolMetadataTable/types.ts
  apps/hubble-stats/components/PoolOverviewCardItem/PoolOverviewCardItem.tsx
  apps/hubble-stats/components/PoolOverviewTable/PoolOverviewTable.tsx
  apps/hubble-stats/components/PoolTransactionsTable/PoolTransactionsTable.tsx
  apps/hubble-stats/components/ShieldedAssetsTable/ShieldedAssetsTable.tsx
  apps/hubble-stats/components/ShieldedPoolsTable/ShieldedPoolsTable.tsx
  apps/hubble-stats/components/table/ActivityCell.tsx
  apps/hubble-stats/components/table/NumberCell.tsx
  apps/hubble-stats/components/table/ShieldedCell.tsx
  apps/hubble-stats/components/table/types.ts
  apps/hubble-stats/containers/PoolOverviewChartsContainer/PoolOverviewChartsCmp.tsx
  apps/hubble-stats/data/getKeyMetricsData.ts
  apps/hubble-stats/data/getPoolMetadataData.ts
  apps/hubble-stats/data/getPoolOverviewCardData.ts
  apps/hubble-stats/tsconfig.json
  apps/hubble-stats/utils/date.ts
  apps/hubble-stats/utils/getExplorerUrlByAddressByChains.ts
  apps/hubble-stats/utils/getShortenChainName.ts
  apps/hubble-stats/utils/index.ts
  libs/abstract-api-provider/src/relayer/webb-relayer-manager.ts
  libs/abstract-api-provider/src/transaction.ts
  libs/abstract-api-provider/src/types.ts
  libs/abstract-api-provider/src/vanchor/vanchor-actions.ts
  libs/abstract-api-provider/src/webb-provider.interface.ts
  libs/api-provider-environment/src/transaction/useTransactionQueue.tsx
  libs/api-provider-environment/src/transaction/utils/getExplorerURI.ts
  libs/api-provider-environment/src/transaction/utils/index.ts
  libs/webb-ui-components/src/components/Table/Table.tsx
  libs/webb-ui-components/src/components/Table/types.ts
  package.json
  yarn.lock
Labels: needs review 👓

#1610 [REFACTOR] Adopt `use-query-params` Hook, Eliminate Excessive `useEffect` for Default State Handling
  apps/bridge-dapp/src/components/Header/TxProgressDropdown/index.tsx
  apps/bridge-dapp/src/containers/DepositConfirmContainer/DepositConfirmContainer.tsx
  apps/bridge-dapp/src/containers/Layout/Layout.tsx
  apps/bridge-dapp/src/containers/TransferConfirmContainer/TransferConfirmContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawConfirmContainer/WithdrawConfirmContainer.tsx
  apps/bridge-dapp/src/hooks/index.ts
  apps/bridge-dapp/src/hooks/useAmountWithRoute.ts
  apps/bridge-dapp/src/hooks/useChainsFromRoute.ts
  apps/bridge-dapp/src/hooks/useCurrenciesFromRoute.ts
  apps/bridge-dapp/src/hooks/useCurrentTx.ts
  apps/bridge-dapp/src/hooks/useDefaultChainAndPool.ts
  apps/bridge-dapp/src/hooks/useNavigateWithPersistParams.ts
  apps/bridge-dapp/src/hooks/useRelayerWithRoute.ts
  apps/bridge-dapp/src/hooks/useStateWithRoute.ts
  apps/bridge-dapp/src/hooks/useTxTabFromRoute.ts
  apps/bridge-dapp/src/pages/Hubble/Bridge/Deposit/index.tsx
  apps/bridge-dapp/src/pages/Hubble/Bridge/Deposit/private/useDepositButtonProps.tsx
  apps/bridge-dapp/src/pages/Hubble/Bridge/Deposit/private/useWatchSearchParams.ts
  apps/bridge-dapp/src/pages/Hubble/Bridge/SelectChain.tsx
  apps/bridge-dapp/src/pages/Hubble/Bridge/SelectRelayer.tsx
  apps/bridge-dapp/src/pages/Hubble/Bridge/Transfer/index.tsx
  apps/bridge-dapp/src/pages/Hubble/Bridge/Transfer/private/useFeeCalculation.ts
  apps/bridge-dapp/src/pages/Hubble/Bridge/Transfer/private/useInputs.ts
  apps/bridge-dapp/src/pages/Hubble/Bridge/Transfer/private/useRelayerWithRoute.ts
  apps/bridge-dapp/src/pages/Hubble/Bridge/Transfer/private/useTransferButtonProps.tsx
  apps/bridge-dapp/src/pages/Hubble/Bridge/Withdraw/index.tsx
  apps/bridge-dapp/src/pages/Hubble/Bridge/Withdraw/private/useFeeCalculation.ts
  apps/bridge-dapp/src/pages/Hubble/Bridge/Withdraw/private/useInputs.ts
  apps/bridge-dapp/src/pages/Hubble/Bridge/Withdraw/private/useRelayerWithRoute.ts
  apps/bridge-dapp/src/pages/Hubble/Bridge/Withdraw/private/useWithdrawButtonProps.tsx
  apps/bridge-dapp/src/routes/index.tsx
  apps/bridge-dapp/src/utils/getCardTitle.ts
  apps/bridge-dapp/src/utils/getMessageFromTransactionState.ts
  apps/bridge-dapp/src/utils/getParam.ts
  apps/bridge-dapp/src/utils/index.ts
  apps/bridge-dapp/src/utils/objectToSearchString.ts
  libs/abstract-api-provider/src/relayer/webb-relayer-manager.ts
  libs/abstract-api-provider/src/relayer/webb-relayer.ts
  libs/abstract-api-provider/src/utils/validateNoteLeafIndex.ts
  libs/abstract-api-provider/src/vanchor/vanchor-actions.ts
  libs/abstract-api-provider/src/webb-provider.interface.ts
  libs/dapp-config/src/anchors/anchor-config.interface.ts
  libs/dapp-config/src/api-config.ts
  libs/dapp-config/src/bridges/bridge-config.interface.ts
  libs/dapp-config/src/currencies/currency-config.interface.ts
  libs/dapp-config/src/wallets/wallet-config.interface.ts
  libs/dapp-types/src/WebbError.ts
  libs/polkadot-api-provider/src/webb-provider/relayer-manager.ts
  libs/polkadot-api-provider/src/webb-provider/vanchor-actions.ts
  libs/web3-api-provider/src/webb-provider/relayer-manager.ts
  libs/web3-api-provider/src/webb-provider/vanchor-actions.ts
  libs/webb-ui-components/src/components/SideBar/SideBar.tsx
  libs/webb-ui-components/src/components/ThemeSwitcher/ThemeSwitcherMenuItem.tsx
  libs/webb-ui-components/src/components/ThemeToggle/ThemeToggle.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/DepositConfirm.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/TransferConfirm.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/WithdrawConfirm.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/types.ts
  package.json
  yarn.lock
Labels: needs review 👓

#1640 Hubble Stats: Fix Bugs in Pool Wrapping Table
  apps/hubble-stats/components/Breadcrumbs/Breadcrumbs.tsx
  apps/hubble-stats/components/Breadcrumbs/types.ts
  apps/hubble-stats/components/PoolWrappingTable/PoolWrappingTable.tsx
  apps/hubble-stats/constants/subgraphs.ts
  apps/hubble-stats/constants/vanchor.ts
  apps/hubble-stats/data/getPoolOverviewTableData.ts
  apps/hubble-stats/data/getPoolTransactionsData.ts
  apps/hubble-stats/data/getPoolWrappingTableData.ts
  apps/hubble-stats/next.config.js
  apps/hubble-stats/utils/getVAnchorMapFromOnChainData.ts
Labels: needs review 👓

#1648 Fix Invalid BigNumber String on Tranfer flow
  apps/bridge-dapp/src/pages/Hubble/Bridge/SelectPool.tsx
  apps/bridge-dapp/src/pages/Hubble/Bridge/SelectToken.tsx
  libs/web3-api-provider/src/webb-provider/vanchor-actions.ts
Labels: needs review 👓

#1649 [RELEASE] 2023 Sep 19 - Hubble Bridge, Hubble Stats, Faucet and DKG Stats
  .lycheeignore
  apps/bridge-dapp/CHANGELOG.md
  apps/bridge-dapp/package.json
  apps/faucet/CHANGELOG.md
  apps/faucet/package.json
  apps/hubble-stats/CHANGELOG.md
  apps/hubble-stats/package.json
  apps/stats-dapp/CHANGELOG.md
  apps/stats-dapp/package.json
Labels: needs review 👓

#1650 Adding SEO for Hubble Bridge & Update Orbit Deployments
  .env.example
  apps/bridge-dapp/src/public/index.html
  apps/faucet/src/config/tokens.ts
  libs/dapp-config/src/anchors/anchor-config.ts
  libs/dapp-config/src/chains/evm/index.tsx
  libs/dapp-config/src/currencies/index.ts
  libs/dapp-config/src/signature-bridges/signature-bridge-config.ts
Labels: needs review 👓

#1639 DKG stats-dapp QA (Sept 13, 2023) fixes part 1
  apps/stats-dapp/src/components/Header/Header.tsx
  apps/stats-dapp/src/containers/AuthoritiesTable/AuthoritiesTable.tsx
  apps/stats-dapp/src/containers/KeygenTable/KeygenTable.tsx
  apps/stats-dapp/src/containers/Layout/Layout.tsx
  apps/stats-dapp/src/containers/NavBlocksInfoContainer/NavBlocksInfoContainer.tsx
  apps/stats-dapp/src/containers/ProposalsTable/ProposalsTable.tsx
  apps/stats-dapp/src/index.tsx
  apps/stats-dapp/src/pages/Authorities.tsx
  apps/stats-dapp/src/provider/hooks/index.ts
  apps/stats-dapp/src/provider/hooks/types.ts
  apps/stats-dapp/src/provider/hooks/useAuthorities.ts
  apps/stats-dapp/src/provider/hooks/useKeys.ts
  apps/stats-dapp/src/provider/hooks/useReputation.ts
  apps/stats-dapp/src/public/index.html
  apps/stats-dapp/src/public/logo.png
  apps/stats-dapp/src/public/tangle-seo.jpg
  apps/stats-dapp/src/styles.css
  apps/stats-dapp/src/utils/getProposalsData.ts
  libs/icons/src/CheckboxBlankCircleLine.tsx
  libs/webb-ui-components/src/components/KeyValueWithButton/KeyValueWithButton.tsx
Labels: needs review 👓, dkg-stats-dapp

#1662 Iterative Improvement For Hubble Bridge
  apps/bridge-dapp/src/components/ChainListCardWrapper/ChainListCardWrapper.tsx
  apps/bridge-dapp/src/containers/BridgeTabsContainer/BridgeTabsContainer.tsx
  apps/bridge-dapp/src/containers/DepositConfirmContainer/DepositConfirmContainer.tsx
  apps/bridge-dapp/src/containers/TransferConfirmContainer/TransferConfirmContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawConfirmContainer/WithdrawConfirmContainer.tsx
  apps/bridge-dapp/src/hooks/index.ts
  apps/bridge-dapp/src/hooks/useInProgressTxInfo.ts
  apps/bridge-dapp/src/pages/Hubble/Bridge/SelectChain.tsx
  apps/bridge-dapp/src/utils/getActiveSourceChains.ts
  apps/faucet/src/containers/InputsContainer.tsx
  libs/dapp-config/src/chains/evm/index.tsx
  libs/icons/src/tokens/orbt.svg
  libs/webb-ui-components/src/components/TxProgressor/TxProgressor.tsx
  libs/webb-ui-components/src/constants/index.ts
Labels: p0 🔥, needs review 👓

#1684 Upgrade next apps to latest version to support adding features and fixing bugs
  apps/bridge-dapp/tsconfig.app.json
  apps/bridge-dapp/tsconfig.spec.json
  apps/faucet/next.config.js
  apps/faucet/project.json
  apps/faucet/src/pages/_app.tsx
  apps/hubble-stats/app/page.tsx
  apps/hubble-stats/app/pool/[slug]/page.tsx
  apps/hubble-stats/containers/Layout/Layout.tsx
  apps/hubble-stats/next.config.js
  apps/hubble-stats/project.json
  apps/stats-dapp/tsconfig.app.json
  apps/stats-dapp/tsconfig.spec.json
  apps/tangle-website/next.config.js
  apps/tangle-website/project.json
  apps/webbsite/next.config.js
  apps/webbsite/project.json
  libs/abstract-api-provider/project.json
  libs/api-provider-environment/project.json
  libs/browser-utils/project.json
  libs/dapp-config/project.json
  libs/dapp-types/project.json
  libs/icons/project.json
  libs/note-manager/project.json
  libs/polkadot-api-provider/project.json
  libs/react-hooks/project.json
  libs/relayer-manager-factory/project.json
  libs/tailwind-preset/project.json
  libs/web3-api-provider/project.json
  libs/webb-ui-components/.storybook/tsconfig.json
  libs/webb-ui-components/project.json
  libs/webb-ui-components/tsconfig.json
  libs/webb-ui-components/tsconfig.storybook.json
  migrations.json
  next.config.js
  nx.json
  package.json
  tools/scripts/fetchingOnChainConfig.ts
  yarn.lock
Labels: needs review 👓

#1689 Show chain name in proposal detail
  apps/stats-dapp/src/utils/getProposalsData.ts
Labels: needs review 👓, dkg-stats-dapp

#1701 Updates bridge header dropdown menu items
  apps/bridge-dapp/src/components/Header/Header.tsx
  libs/webb-ui-components/src/components/NavigationMenu/NavigationMenuContent.tsx
  libs/webb-ui-components/src/components/NavigationMenu/types.ts
Labels: bridge

#1709 Remove forced goerli connection on wallet reconnect
  apps/bridge-dapp/src/components/Header/WalletModal.tsx
  apps/bridge-dapp/src/constants/sidebar.ts
  libs/webb-ui-components/src/constants/index.ts
  yarn.lock
Labels: needs review 👓, bridge

#1713 Fix prev session's active period incorrect progress bar
  apps/stats-dapp/src/containers/KeyDetail/KeyDetail.tsx
  apps/stats-dapp/src/containers/KeygenTable/KeygenTable.tsx
Labels: needs review 👓, dkg-stats-dapp

#1688 Add metadata in layout in Hubble Stats
  apps/hubble-stats/app/layout.tsx
  libs/webb-ui-components/src/constants/index.ts
  package.json
  yarn.lock
Labels: needs changes 🔧

#1723 Fix Connect Wallet Modal When Connect Wallet Button Is Clicked
  apps/bridge-dapp/src/components/Header/WalletModal.tsx
  apps/bridge-dapp/src/constants/sidebar.ts
  apps/bridge-dapp/src/hooks/useTryAnotherWalletWithView.tsx
  libs/api-provider-environment/src/WebbProvider.tsx
  libs/api-provider-environment/src/error/interactive-errors/extension-not-installed.tsx
  libs/api-provider-environment/src/error/interactive-errors/index.ts
  libs/dapp-types/src/WebbError.ts
  libs/dapp-types/src/errors/WalletNotInstalledError.ts
  libs/webb-ui-components/src/components/WalletConnectionCard/WalletConnectionCard.tsx
  libs/webb-ui-components/src/components/WalletConnectionCard/types.ts
  libs/webb-ui-components/src/constants/index.ts
  libs/webb-ui-components/src/stories/organisms/Modal.stories.jsx
Labels: needs review 👓

#1725 Update DKG Stats favicon to match with Tangle Marketing favicon
  apps/stats-dapp/src/public/favicon.png
Labels: needs review 👓

#1724 Update Faucet API Routes to Edge Runtime
  package.json
  yarn.lock
Labels: needs review 👓
