Repository tangle-network/dapp, pull requests merged in 2023-05, with the labels that each got.

#1168 Stats Proposal Graph UI Fixes
  apps/stats-dapp/src/containers/StackedAreaChartContainer/StackedAreaChartContainer.tsx
Labels: needs review 👓, statistics

#1167 Webbsite brandkit
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  apps/webbsite/public/download/Webb-Color-Palettes.pdf.zip
  apps/webbsite/public/download/Webb-Logo.zip
  apps/webbsite/public/download/Webb-Typography.zip
  apps/webbsite/public/static/assets/brandkit-hero.png
  apps/webbsite/public/static/assets/brandkit-iconography-desktop.png
  apps/webbsite/public/static/assets/brandkit-iconography-mobile.png
  apps/webbsite/src/components/Header.tsx
  apps/webbsite/src/components/brandkit/BrandKitHeroSection.tsx
  apps/webbsite/src/components/brandkit/ColorPalettesSection.tsx
  apps/webbsite/src/components/brandkit/IconographySection.tsx
  apps/webbsite/src/components/brandkit/PressInquiriesSection.tsx
  apps/webbsite/src/components/brandkit/TypographySection.tsx
  apps/webbsite/src/components/brandkit/WebbLogoSection.tsx
  apps/webbsite/src/components/brandkit/index.ts
  apps/webbsite/src/components/index.ts
  apps/webbsite/src/pages/brand-kit.tsx
  apps/webbsite/tailwind.config.js
  libs/webb-ui-components/src/components/WebsiteFooter/WebsiteFooter.tsx
Labels: needs review 👓

#1175 Update Tangle according audit/review
  apps/tangle-website/src/components/Header.tsx
  apps/tangle-website/src/components/sections/FAQSection.tsx
  apps/tangle-website/src/components/sections/FeaturesSection.tsx
  apps/tangle-website/src/components/sections/GovernanceSystemSection.tsx
  apps/tangle-website/src/components/sections/HeroSection.tsx
  apps/tangle-website/src/components/sections/LaunchPhasesSection.tsx
  apps/tangle-website/src/components/sections/ParticipationMechanicsSection.tsx
  apps/tangle-website/src/components/sections/UseCasesSection.tsx
  apps/tangle-website/src/components/svgs/IntroducingTangleSvg.tsx
  libs/webb-ui-components/src/components/WebsiteCommunity/WebsiteCommunity.tsx
Labels: needs changes 🔧

#1198 Hot Fixes #2 for the Bridge
  apps/bridge-dapp/src/containers/TransferContainer/TransferContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/types.d.ts
  libs/web3-api-provider/src/webb-provider/vanchor-actions.ts
Labels: needs review 👓

#1199 [RELEASE] Bridge dApp `0.0.7` with Hot Fixes
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .lycheeignore
  apps/bridge-dapp/CHANGELOG.md
  apps/bridge-dapp/package.json
  apps/bridge-dapp/src/containers/TransferContainer/TransferContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/types.d.ts
  apps/bridge-dapp/src/hooks/useTransactionProgressValue.ts
  apps/faucet/CHANGELOG.md
  apps/faucet/src/components/ProcessingModal.tsx
  apps/faucet/src/types/index.ts
  apps/faucet/src/utils/addTokenToMetamask.ts
  apps/stats-dapp/src/containers/StackedAreaChartContainer/StackedAreaChartContainer.tsx
  apps/tangle-website/CHANGELOG.md
  apps/tangle-website/src/components/Header.tsx
  apps/tangle-website/src/components/sections/FAQSection.tsx
  apps/tangle-website/src/components/sections/FeaturesSection.tsx
  apps/tangle-website/src/components/sections/GovernanceSystemSection.tsx
  apps/tangle-website/src/components/sections/HeroSection.tsx
  apps/tangle-website/src/components/sections/LaunchPhasesSection.tsx
  apps/tangle-website/src/components/sections/ParticipationMechanicsSection.tsx
  apps/tangle-website/src/components/sections/UseCasesSection.tsx
  apps/tangle-website/src/components/svgs/IntroducingTangleSvg.tsx
  apps/webbsite/CHANGELOG.md
  apps/webbsite/public/download/Webb-Color-Palettes.pdf.zip
  apps/webbsite/public/download/Webb-Logo.zip
  apps/webbsite/public/download/Webb-Typography.zip
  apps/webbsite/public/static/assets/brandkit-hero.png
  apps/webbsite/public/static/assets/brandkit-iconography-desktop.png
  apps/webbsite/public/static/assets/brandkit-iconography-mobile.png
  apps/webbsite/src/components/Header.tsx
  apps/webbsite/src/components/brandkit/BrandKitHeroSection.tsx
  apps/webbsite/src/components/brandkit/ColorPalettesSection.tsx
  apps/webbsite/src/components/brandkit/IconographySection.tsx
  apps/webbsite/src/components/brandkit/PressInquiriesSection.tsx
  apps/webbsite/src/components/brandkit/TypographySection.tsx
  apps/webbsite/src/components/brandkit/WebbLogoSection.tsx
  apps/webbsite/src/components/brandkit/index.ts
  apps/webbsite/src/components/index.ts
  apps/webbsite/src/pages/brand-kit.tsx
  apps/webbsite/tailwind.config.js
  libs/abstract-api-provider/src/transaction.ts
  libs/api-provider-environment/src/transaction/useTransactionQueue.tsx
  libs/dapp-config/src/anchors/anchor-config.ts
  libs/dapp-config/src/chains/chain-config.interface.ts
  libs/dapp-config/src/gasLimit-config.ts
  libs/dapp-config/src/relayer-config.ts
  libs/dapp-config/src/types.ts
  libs/relayer-manager-factory/src/relayer-manager-factory.ts
  libs/web3-api-provider/src/webb-provider.ts
  libs/web3-api-provider/src/webb-provider/vanchor-actions.ts
  libs/webb-ui-components/src/components/WebsiteCommunity/WebsiteCommunity.tsx
  libs/webb-ui-components/src/components/WebsiteFooter/WebsiteFooter.tsx
Labels: needs review 👓

#1206 Stats Improvements and Fixes
  apps/stats-dapp/src/containers/AuthorityDetail/AuthorityDetail.tsx
  apps/stats-dapp/src/containers/KeyDetail/KeyDetail.tsx
  apps/stats-dapp/src/containers/ProposalDetail/ProposalDetail.tsx
  apps/stats-dapp/src/containers/ProposalsTable/ProposalsTable.tsx
  libs/webb-ui-components/src/components/Dropdown/DropdownButton.tsx
  libs/webb-ui-components/src/components/Filter/Filter.tsx
  libs/webb-ui-components/src/components/Input/Input.tsx
Labels: approved ✅, needs review 👓, statistics

#1205 Bridge Improvements #1
  apps/bridge-dapp/README.md
  apps/bridge-dapp/src/components/Header/WalletModal.tsx
  apps/bridge-dapp/src/hooks/useConnectWallet.ts
  apps/bridge-dapp/src/hooks/useMaxFeeInfo.ts
  libs/abstract-api-provider/src/relayer/webb-relayer.ts
  libs/api-provider-environment/src/WebbProvider.tsx
  libs/api-provider-environment/src/app-event/app-events.class.ts
  libs/api-provider-environment/src/utils.ts
  libs/browser-utils/src/index.ts
  libs/browser-utils/src/promise-utils.ts
  libs/browser-utils/src/storage.ts
  libs/browser-utils/tsconfig.json
  libs/dapp-config/src/anchors/anchor-config.ts
  libs/dapp-types/src/WebbError.ts
  libs/polkadot-api-provider/src/ext-provider/polkadot-provider.ts
  libs/polkadot-api-provider/src/index.ts
  libs/polkadot-api-provider/src/utils.ts
  libs/polkadot-api-provider/src/webb-provider/relayer-manager.ts
  libs/web3-api-provider/src/ext-provider/web3-provider.ts
  libs/web3-api-provider/src/index.ts
  libs/web3-api-provider/src/utils.ts
  libs/web3-api-provider/src/webb-provider/relayer-manager.ts
  libs/webb-ui-components/src/components/WalletConnectionCard/WalletConnectionCard.tsx
  libs/webb-ui-components/src/components/WalletConnectionCard/types.ts
  package.json
  tools/scripts/relayer.sh
  yarn.lock
Labels: needs review 👓

#1222 [RELEASE] Fixes theme switching in bridge-dapp
  .lycheeignore
  apps/bridge-dapp/CHANGELOG.md
  apps/bridge-dapp/package.json
  libs/webb-ui-components/src/components/BridgeInputs/RefundInput.tsx
  libs/webb-ui-components/src/components/CheckBox/Checkbox.tsx
  libs/webb-ui-components/src/hooks/useDarkMode.ts
Labels: needs review 👓, ui-components

#1224 Fixes Network Thresholds History Chart
  apps/stats-dapp/src/containers/Layout/Layout.tsx
  apps/stats-dapp/src/pages/AuthoritiesHistory.tsx
  libs/webb-ui-components/src/hooks/useDarkMode.ts
  yarn.lock
Labels: needs review 👓, ui-components, statistics

#1232 Unifying `dist` Dirs for all Apps
  .github/workflows/deploy-bridge-dapp-dev.yml
  .github/workflows/deploy-stats-dapp-dev.yml
  apps/bridge-dapp/project.json
  apps/bridge-dapp/webpack.base.js
  apps/stats-dapp/webpack.config.js
  nx.json
  yarn.lock
Labels: needs review 👓

#1235 Replaces swirl BG image in faucet app to include tangle token
  apps/faucet/public/static/assets/faucet-hero.png
  apps/faucet/src/components/Header.tsx
  apps/faucet/src/pages/_app.tsx
  apps/faucet/src/styles/globals.css
  libs/webb-ui-components/src/components/Footer/Footer.tsx
  package.json
Labels: needs review 👓, statistics

#1237 Adds SEO config to blog page
  apps/webbsite/.env.example
  apps/webbsite/src/pages/blog.tsx
  apps/webbsite/src/pages/blog/posts/[slug].tsx
Labels: webbsite 🕸️

#1233 chore: fix content and minor UI as requested
  apps/tangle-website/src/components/Header.tsx
  apps/tangle-website/src/pages/_app.tsx
  libs/webb-ui-components/src/components/WebsiteFooter/WebsiteFooter.tsx
Labels: needs review 👓

#1247 Fixes stats keys page refresh issue
  apps/stats-dapp/src/containers/KeyStatusCardContainer/KeyStatusCardContainer.tsx
  apps/stats-dapp/src/containers/KeygenTable/KeygenTable.tsx
  apps/stats-dapp/src/pages/Keys.tsx
  apps/stats-dapp/src/provider/hooks/useKeys.ts
  libs/webb-ui-components/src/components/KeyStatusCard/KeyStatusCard.tsx
Labels: needs review 👓, statistics

#1264 Bridge Improvements #2
  .prettierignore
  apps/bridge-dapp/src/components/ChainListCardWrapper/ChainListCardWrapper.tsx
  apps/bridge-dapp/src/components/ChainListCardWrapper/types.d.ts
  apps/bridge-dapp/src/containers/DepositContainer/DepositConfirmContainer.tsx
  apps/bridge-dapp/src/containers/DepositContainer/DepositContainer.tsx
  apps/bridge-dapp/src/containers/DepositContainer/types.d.ts
  apps/bridge-dapp/src/containers/TransferContainer/TransferConfirmContainer.tsx
  apps/bridge-dapp/src/containers/TransferContainer/TransferContainer.tsx
  apps/bridge-dapp/src/containers/TransferContainer/shared.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
  apps/bridge-dapp/src/containers/note-account-tables/ShieldedAssetsTableContainer/ShieldedAssetsTableContainer.tsx
  apps/bridge-dapp/src/containers/note-account-tables/SpendNotesTableContainer/SpendNotesTableContainer.tsx
  apps/bridge-dapp/src/hooks/useMaxFeeInfo.ts
  apps/bridge-dapp/src/hooks/useShieldedAssets.ts
  apps/bridge-dapp/src/hooks/useSpendNotes.ts
  apps/bridge-dapp/src/hooks/useStatesFromNotes.tsx
  apps/bridge-dapp/src/utils/errors.ts
  apps/bridge-dapp/webpack.dev.js
  libs/abstract-api-provider/src/currency/currency.ts
  libs/abstract-api-provider/src/relayer/types.ts
  libs/abstract-api-provider/src/relayer/webb-relayer.ts
  libs/api-provider-environment/src/WebbProvider.tsx
  libs/api-provider-environment/src/webb-context/webb-context.ts
  libs/browser-utils/src/download/cached-fetch.ts
  libs/dapp-config/src/anchors/anchor-config.ts
  libs/dapp-config/src/api-config.ts
  libs/dapp-config/src/on-chain-config/on-chain-config-base.ts
  libs/dapp-types/src/WebbError.ts
  libs/icons/src/tokens/eth.svg
  libs/note-manager/src/note-manager.ts
  libs/react-hooks/src/currency/useBalancesFromNotes.tsx
  libs/react-hooks/src/currency/useCurrencies.tsx
  libs/react-hooks/src/index.ts
  libs/react-hooks/src/useCurrentTypedChainId.ts
  libs/relayer-manager-factory/src/relayer-manager-factory.ts
  libs/web3-api-provider/src/webb-provider/relayer-manager.ts
  libs/webb-ui-components/src/components/ListCard/ChainListCard.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/DepositConfirm.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/TransferConfirm.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/WithdrawConfirm.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/types.ts
  libs/webb-ui-components/src/containers/DepositCard/DepositCard.tsx
  nx.json
Labels: needs review 👓

#1277 Update new Orbit Deployment
  libs/dapp-config/src/anchors/anchor-config.ts
Labels: needs review 👓

#1276 Deprecates Strapi blog Implementation and updates blog link to Ghost
  .env.example
  .github/workflows/check-build.yml
  .github/workflows/deploy-webbsite-dev.yml
  .github/workflows/release.yml
  apps/webbsite/.env.example
  apps/webbsite/src/components/BlogCard.tsx
  apps/webbsite/src/components/Header.tsx
  apps/webbsite/src/components/index.ts
  apps/webbsite/src/components/sections/BlogSection.tsx
  apps/webbsite/src/components/sections/FeaturedPostSection.tsx
  apps/webbsite/src/components/sections/index.ts
  apps/webbsite/src/libs/webb-cms/api.ts
  apps/webbsite/src/libs/webb-cms/constants.ts
  apps/webbsite/src/libs/webb-cms/index.ts
  apps/webbsite/src/libs/webb-cms/types.ts
  apps/webbsite/src/pages/blog.tsx
  apps/webbsite/src/pages/blog/posts/[slug].tsx
  apps/webbsite/src/pages/blog/posts/index.tsx
  apps/webbsite/src/pages/blog/videos.tsx
  libs/dapp-config/src/links.ts
Labels: needs review 👓, webbsite 🕸️

#1278 Adds a check for proposal data on proposal detail page to prevent from crashing
  apps/stats-dapp/src/containers/ProposalDetail/ProposalDetail.tsx
  apps/stats-dapp/src/utils/getProposalsData.ts
Labels: needs review 👓, statistics
