Repository tangle-network/dapp, pull requests merged in 2023-03, with the labels that each got.

#1029 32-bytes Fixing for Leaves and Roots
  apps/bridge-dapp/src/containers/TransferContainer/TransferConfirmContainer.tsx
  libs/web3-api-provider/src/webb-provider.ts
  libs/web3-api-provider/src/webb-provider/relayer-manager.ts
  libs/web3-api-provider/src/webb-provider/vanchor-actions.ts
Labels: needs review 👓

#1032 Bump Solidity Packages and Fix Webpack
  apps/bridge-dapp/webpack.base.js
  apps/bridge-dapp/webpack.dev.js
  libs/abstract-api-provider/tsconfig.json
  libs/api-provider-environment/tsconfig.json
  libs/api-provider-environment/tsconfig.lib.json
  libs/web3-api-provider/src/webb-provider.ts
  package.json
  yarn.lock
Labels: needs review 👓

#1033 Pad UTXO Before calling setupTransaction
  libs/web3-api-provider/src/webb-provider.ts
  libs/web3-api-provider/src/webb-provider/vanchor-actions.ts
Labels: needs review 👓

#1021 FEAT: Updated stats dApp backend selection
  apps/stats-dapp/src/components/Header/Header.tsx
  apps/stats-dapp/src/components/NetworkSelector/NetworkSelector.tsx
  apps/stats-dapp/src/components/NetworkSelector/types.ts
  apps/stats-dapp/src/constants/index.ts
  apps/stats-dapp/src/containers/Layout/Layout.tsx
  apps/stats-dapp/src/provider/stats-provider.tsx
  apps/stats-dapp/src/utils/index.ts
  apps/stats-dapp/src/utils/networkSelector.ts
  libs/icons/src/DeleteBinWithBg.tsx
  libs/icons/src/Save.tsx
  libs/icons/src/SaveWithBg.tsx
  libs/icons/src/TangleIcon.tsx
  libs/icons/src/index.ts
  libs/webb-ui-components/src/components/IconWithTooltip/IconWithTooltip.tsx
  libs/webb-ui-components/src/components/Input/Input.tsx
  libs/webb-ui-components/src/constants/index.ts
Labels: needs review 👓, statistics

#1028 Adding Currency to Metamask
  apps/bridge-dapp/src/containers/DepositContainer/DepositContainer.tsx
  apps/bridge-dapp/src/containers/TransferContainer/TransferContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
  apps/bridge-dapp/src/hooks/index.ts
  apps/bridge-dapp/src/hooks/useAddCurrency.ts
  libs/icons/src/TokenIcon.tsx
  libs/polkadot-api-provider/src/webb-provider.ts
  libs/webb-ui-components/src/components/BridgeInputs/TokenInput.tsx
  libs/webb-ui-components/src/components/BridgeInputs/types.ts
  libs/webb-ui-components/src/components/ListCard/AssetListItem.tsx
  libs/webb-ui-components/src/components/ListCard/TokenListCard.tsx
  libs/webb-ui-components/src/components/ListCard/types.ts
  libs/webb-ui-components/src/components/TokenSelector/TokenSelector.tsx
  libs/webb-ui-components/src/components/TokenSelector/types.ts
  libs/webb-ui-components/src/containers/DepositCard/DepositCard.tsx
Labels: approved ✅, bridge

#1036 Fix Withdraw Issue
  apps/bridge-dapp/src/components/Header/Header.tsx
  libs/note-manager/src/note-manager.ts
  libs/web3-api-provider/src/webb-provider.ts
  libs/web3-api-provider/src/webb-provider/vanchor-actions.ts
Labels: needs review 👓

#1016 FEAT: Adds Blog to Webbsite with Notion database
  .github/workflows/check-build.yml
  .github/workflows/deploy-webbsite-dev.yml
  apps/webbsite/public/static/svgs/play-button.svg
  apps/webbsite/src/components/BlogCard.tsx
  apps/webbsite/src/components/Footer.tsx
  apps/webbsite/src/components/Header.tsx
  apps/webbsite/src/components/Heading1.tsx
  apps/webbsite/src/components/Heading2.tsx
  apps/webbsite/src/components/Heading3.tsx
  apps/webbsite/src/components/Heading4.tsx
  apps/webbsite/src/components/InternalOrExternalLink.tsx
  apps/webbsite/src/components/Navbar.tsx
  apps/webbsite/src/components/NewletterForm.tsx
  apps/webbsite/src/components/PrivacyScaleIllustration.tsx
  apps/webbsite/src/components/PrivacyScaleSwiper.tsx
  apps/webbsite/src/components/SubHeading1.tsx
  apps/webbsite/src/components/SubHeading2.tsx
  apps/webbsite/src/components/index.ts
  apps/webbsite/src/components/sections/ApplicationsAndInfrastructureSection.tsx
  apps/webbsite/src/components/sections/BlogSection.tsx
  apps/webbsite/src/components/sections/FeaturedPostSection.tsx
  apps/webbsite/src/components/sections/HeroSection.tsx
  apps/webbsite/src/components/sections/InActionSection.tsx
  apps/webbsite/src/components/sections/PrivacyConnectedSection.tsx
  apps/webbsite/src/components/sections/PrivacyScaleSection.tsx
  apps/webbsite/src/components/sections/ResearchAndDevelopmentSection.tsx
  apps/webbsite/src/components/sections/index.ts
  apps/webbsite/src/libs/notion/getNotionClient.ts
  apps/webbsite/src/libs/notion/getNotionPage.ts
  apps/webbsite/src/libs/notion/index.ts
  apps/webbsite/src/libs/notion/notion.ts
  apps/webbsite/src/libs/notion/server-constants.ts
  apps/webbsite/src/libs/notion/types.ts
  apps/webbsite/src/pages/_app.tsx
  apps/webbsite/src/pages/api/subscribers/index.ts
  apps/webbsite/src/pages/blog.tsx
  apps/webbsite/src/pages/blog/posts/[slug].tsx
  apps/webbsite/src/pages/blog/posts/index.tsx
  apps/webbsite/src/pages/blog/videos.tsx
  apps/webbsite/src/pages/community.tsx
  apps/webbsite/src/pages/index.tsx
  apps/webbsite/src/pages/privacy-policy.tsx
  apps/webbsite/src/pages/terms-and-conditions.tsx
  apps/webbsite/src/styles/globals.css
  apps/webbsite/src/utils/formatDateTime.ts
  apps/webbsite/src/utils/index.ts
  apps/webbsite/src/utils/isValidEmail.ts
  libs/icons/src/CopyLinkFill.tsx
  libs/icons/src/index.ts
  libs/webb-ui-components/src/components/Notification/NotificationProvider.tsx
  package.json
  yarn.lock
Labels: approved ✅, webbsite 🕸️

#1038 Adds Terser Webpack plugin to drop console in production
  apps/bridge-dapp/project.json
  apps/bridge-dapp/webpack.base.js
  apps/bridge-dapp/webpack.prod.js
  apps/stats-dapp/project.json
  apps/stats-dapp/webpack.config.js
Labels: needs review 👓, bridge, statistics

#1040 chore: trial auto-reviewer bot
  .github/workflows/check-build.yml
  .github/workflows/check-lint.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/pr-reviewer.yml
Labels: needs review 👓

#1037 Remove spend notes from storage
  apps/bridge-dapp/src/containers/DeleteNotesModal/DeleteNotesModal.tsx
  libs/note-manager/src/note-manager.ts
  libs/storage/src/storage.ts
Labels: needs review 👓, bridge, codeball:needs-careful-review

#1042 Adjustments to Blog page
  .github/workflows/pr-reviewer.yml
  apps/webbsite/src/components/BlogCard.tsx
  apps/webbsite/src/components/sections/BlogSection.tsx
  apps/webbsite/src/components/sections/FeaturedPostSection.tsx
  apps/webbsite/src/libs/notion/notion.ts
  apps/webbsite/src/libs/notion/types.ts
  apps/webbsite/src/pages/blog/posts/index.tsx
  apps/webbsite/src/pages/blog/videos.tsx
  apps/webbsite/src/utils/getThumbnailURI.ts
  apps/webbsite/src/utils/index.ts
Labels: needs review 👓, webbsite 🕸️, codeball:needs-careful-review

#1051 Adds connecting chip in ChainListCard component
  apps/bridge-dapp/src/components/ChainListCardWrapper/ChainListCardWrapper.tsx
  libs/webb-ui-components/src/components/ListCard/ChainListCard.tsx
  libs/webb-ui-components/src/components/ListCard/types.ts
Labels: needs review 👓, bridge

#1047 Fetches session height using Polkadot.js API
  apps/stats-dapp/src/containers/Layout/Layout.tsx
  apps/stats-dapp/src/provider/hooks/useKeys.ts
  apps/stats-dapp/src/provider/stats-provider.tsx
Labels: needs review 👓, statistics

#1055 Updates featured post blog card
  apps/webbsite/src/components/BlogCard.tsx
  apps/webbsite/src/components/sections/FeaturedPostSection.tsx
Labels: needs review 👓, webbsite 🕸️

#1060 Filter Relayers by the Environment
  libs/dapp-config/src/relayer-config.ts
  libs/relayer-manager-factory/src/relayer-manager-factory.ts
Labels: needs review 👓

#1049 Relayer Fee and Refund Support
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawConfirmContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/shared.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/types.d.ts
  apps/bridge-dapp/src/hooks/useSpendNotes.ts
  apps/bridge-dapp/src/hooks/useWIthdrawFee.ts
  apps/bridge-dapp/src/utils/errors.ts
  libs/abstract-api-provider/src/relayer/webb-relayer.ts
  libs/abstract-api-provider/src/vanchor/vanchor-actions.ts
  libs/api-provider-environment/src/WebbProvider.tsx
  libs/api-provider-environment/src/transaction/useTransactionQueue.tsx
  libs/browser-utils/src/retry-promise.ts
  libs/dapp-config/src/anchors/anchor-config.ts
  libs/dapp-config/src/chains/evm/index.tsx
  libs/dapp-config/src/on-chain-config/evm/on-chain-config.ts
  libs/dapp-config/src/wallets/wallets-config.tsx
  libs/dapp-types/src/ChainId.ts
  libs/icons/src/chains/avalanche-fuji.svg
  libs/icons/src/chains/scroll-alpha.svg
  libs/icons/src/tokens/webbalpha.svg
  libs/react-hooks/src/useNoteAccount.tsx
  libs/web3-api-provider/src/typings.ts
  libs/web3-api-provider/src/webb-provider.ts
  libs/web3-api-provider/src/webb-provider/bridge-api.ts
  libs/web3-api-provider/src/webb-provider/chain-query.ts
  libs/web3-api-provider/src/webb-provider/relayer-manager.ts
  libs/web3-api-provider/src/webb-provider/vanchor-actions.ts
  libs/web3-api-provider/tsconfig.json
  libs/web3-api-provider/tsconfig.lib.json
  libs/webb-ui-components/.eslintrc.json
  libs/webb-ui-components/src/components/BridgeInputs/AmountInput.tsx
  libs/webb-ui-components/src/components/BridgeInputs/InfoItem.tsx
  libs/webb-ui-components/src/components/BridgeInputs/RefundInput.tsx
  libs/webb-ui-components/src/components/BridgeInputs/index.ts
  libs/webb-ui-components/src/components/BridgeInputs/types.ts
  libs/webb-ui-components/src/components/CheckBox/Checkbox.tsx
  libs/webb-ui-components/src/components/CheckBox/types.ts
  libs/webb-ui-components/src/components/ListCard/types.ts
  libs/webb-ui-components/src/components/TitleWithInfo/TitleWithInfo.tsx
  libs/webb-ui-components/src/components/TokenWithAmount/TokenWithAmount.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/WithdrawConfirm.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/types.ts
  libs/webb-ui-components/src/containers/DepositCard/DepositCard.tsx
  libs/webb-ui-components/src/containers/DepositCard/types.ts
  libs/webb-ui-components/src/containers/WithdrawCard/WithdrawCard.tsx
  libs/webb-ui-components/src/containers/WithdrawCard/types.ts
  libs/webb-ui-components/src/utils/getRoundedAmountString.ts
Labels: approved ✅

#1072 Capture user/transaction errors on Hubble Bridge dApp with Sentry
  apps/bridge-dapp/src/containers/DepositContainer/DepositConfirmContainer.tsx
  apps/bridge-dapp/src/containers/TransferContainer/TransferConfirmContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawConfirmContainer.tsx
  apps/bridge-dapp/src/utils/captureSentryException.ts
  apps/bridge-dapp/src/utils/index.ts
  package.json
  yarn.lock
Labels: needs review 👓, bridge

#1073 Feat: add website header
  apps/tangle-website/netlify.toml
  apps/tangle-website/src/components/Header.tsx
  apps/tangle-website/src/components/Heading1.tsx
  apps/tangle-website/src/components/InternalOrExternalLink.tsx
  apps/tangle-website/src/components/Navbar.tsx
  apps/tangle-website/src/components/SubHeading1.tsx
  apps/tangle-website/src/components/index.ts
  apps/tangle-website/src/components/sections/HeroSection.tsx
  apps/tangle-website/src/components/sections/index.ts
  apps/tangle-website/src/constants/index.ts
  apps/tangle-website/src/pages/_app.tsx
  apps/tangle-website/src/pages/index.module.css
  apps/tangle-website/src/pages/index.tsx
  apps/tangle-website/src/pages/styles.css
  apps/tangle-website/src/styles/globals.css
  apps/tangle-website/tsconfig.json
  libs/webb-ui-components/src/components/TangleLogo/TangleLogo.tsx
  libs/webb-ui-components/src/components/TangleLogo/index.tsx
  libs/webb-ui-components/src/components/TangleLogo/types.ts
  libs/webb-ui-components/src/components/index.ts
  libs/webb-ui-components/src/css/fonts/Satoshi-Black.ttf
  libs/webb-ui-components/src/css/fonts/Satoshi-BlackItalic.ttf
  libs/webb-ui-components/src/css/fonts/Satoshi-Bold.ttf
  libs/webb-ui-components/src/css/fonts/Satoshi-BoldItalic.ttf
  libs/webb-ui-components/src/css/fonts/Satoshi-Medium.ttf
  libs/webb-ui-components/src/css/typography.css
  libs/webb-ui-components/src/fonts/Satoshi-Black.ttf
  libs/webb-ui-components/src/fonts/Satoshi-BlackItalic.ttf
  libs/webb-ui-components/src/fonts/Satoshi-Bold.ttf
  libs/webb-ui-components/src/fonts/Satoshi-BoldItalic.ttf
  libs/webb-ui-components/src/fonts/Satoshi-Medium.ttf
  libs/webb-ui-components/src/stories/atoms/TangleLogo.stories.jsx
Labels: needs review 👓

#1083 chore: updates templates
  .github/CODEOWNERS
  .github/PULL_REQUEST_TEMPLATE.md
Labels: needs review 👓

#1082 chore: updates deployment flow
  .github/workflows/deploy-faucet.yml
  apps/faucet/netlify.toml
Labels: needs review 👓

#1077 chore: adds release workflows for apps
  .github/actions/create-release/action.yml
  .github/actions/create-release/gh-release-script.js
  .github/workflows/release.yml
  .lycheeignore
  apps/bridge-dapp/CHANGELOG.md
  apps/stats-dapp/CHANGELOG.md
  libs/webb-ui-components/CHANGELOG.md
  libs/webb-ui-components/package.json
  package.json
  yarn.lock
Labels: needs review 👓

#1087 chore: adds tangle website deployment with netlify
  .github/workflows/deploy-tangle-website.yml
Labels: needs review 👓

#1088 Calculating balances from notes in `transfer` and `withdraw` flows
  apps/bridge-dapp/src/containers/TransferContainer/TransferContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
  apps/faucet/tailwind.config.js
  libs/react-hooks/src/currency/index.ts
  libs/react-hooks/src/currency/useBalancesFromNotes.tsx
Labels: needs review 👓

#1089 Fixes current key progress bar in authorities page
  apps/stats-dapp/src/pages/Authorities.tsx
Labels: needs review 👓, statistics

#1081 Adds tangle website hero section
  apps/tangle-website/public/static/assets/hero-image.png
  apps/tangle-website/src/components/Header.tsx
  apps/tangle-website/src/components/Navbar.tsx
  apps/tangle-website/src/components/sections/HeroSection.tsx
  apps/tangle-website/src/constants/index.ts
  apps/tangle-website/src/pages/_app.tsx
  apps/tangle-website/src/pages/index.tsx
  apps/tangle-website/src/styles/globals.css
  apps/tangle-website/tailwind.config.js
  libs/webb-ui-components/src/components/Socials/Socials.tsx
  libs/webb-ui-components/src/components/Socials/index.ts
  libs/webb-ui-components/src/components/Socials/types.ts
  libs/webb-ui-components/src/components/index.ts
  libs/webb-ui-components/src/constants/index.ts
  libs/webb-ui-components/src/stories/molecules/Footer.stories.jsx
  libs/webb-ui-components/src/stories/molecules/Socials.stories.jsx
Labels: needs review 👓
