Repository tangle-network/dapp, pull requests merged in 2023-08, with the labels that each got.

#1480 Fix Token Approval Issue
  libs/web3-api-provider/src/VAnchor.ts
  libs/web3-api-provider/src/webb-provider/vanchor-actions.ts
Labels: needs review 👓, bridge

#1471 Add More Rpc Urls to Support Multiple Providers
  libs/api-provider-environment/src/WebbProvider.tsx
  libs/dapp-config/src/chains/evm/index.tsx
  libs/web3-api-provider/src/utils/getViemClient.ts
Labels: needs review 👓, bridge

#1492 chore: update privacy & policy page in mkt sites based on latest design
  apps/tangle-website/src/styles/globals.css
  apps/webbsite/src/pages/privacy-policy.tsx
  apps/webbsite/src/styles/globals.css
Labels: needs review 👓

#1494 Fee Detail component
  libs/webb-ui-components/.storybook/override.css
  libs/webb-ui-components/.storybook/preview.js
  libs/webb-ui-components/src/components/Accordion/AccordionButtonBase.tsx
  libs/webb-ui-components/src/components/Accordion/index.ts
  libs/webb-ui-components/src/components/Accordion/types.ts
  libs/webb-ui-components/src/components/BridgeInputs/ShieldedAssetInput.tsx
  libs/webb-ui-components/src/components/BridgeInputs/TokenInput.tsx
  libs/webb-ui-components/src/components/FeeDetails/FeeDetails.tsx
  libs/webb-ui-components/src/components/FeeDetails/index.ts
  libs/webb-ui-components/src/components/FeeDetails/types.ts
  libs/webb-ui-components/src/components/index.ts
  libs/webb-ui-components/src/containers/BridgeFeeDetails/BridgeFeeDetails.tsx
  libs/webb-ui-components/src/containers/BridgeFeeDetails/index.ts
  libs/webb-ui-components/src/containers/BridgeFeeDetails/types.ts
  libs/webb-ui-components/src/containers/index.ts
  libs/webb-ui-components/src/stories/molecules/BridgeFeeDetails.stories.tsx
  libs/webb-ui-components/tailwind.config.js
Labels: needs review 👓

#1497 Update TokenSelector component
  apps/hubble-stats/components/NetworkPoolTable/NetworkPoolTable.tsx
  apps/hubble-stats/components/table/DestinationCell.tsx
  apps/hubble-stats/components/table/ShieldedCell.tsx
  apps/hubble-stats/containers/PoolOverviewContainer/PoolOverviewContainer.tsx
  libs/icons/src/ShieldedAssetDark.tsx
  libs/icons/src/ShieldedAssetIcon.tsx
  libs/icons/src/ShieldedAssetLight.tsx
  libs/icons/src/TokenIcon.tsx
  libs/icons/src/hooks/useDynamicSVGImport.tsx
  libs/icons/src/index.ts
  libs/icons/src/tokens/placeholder.svg
  libs/icons/src/types.ts
  libs/webb-ui-components/src/components/ListCard/AssetListItem.tsx
  libs/webb-ui-components/src/components/ListCard/ChainListCard.tsx
  libs/webb-ui-components/src/components/ListCard/TokenListCard.tsx
  libs/webb-ui-components/src/components/ListCard/types.ts
  libs/webb-ui-components/src/components/TokenSelector/TokenSelector.tsx
  libs/webb-ui-components/src/components/TokenSelector/index.ts
  libs/webb-ui-components/src/components/TokenSelector/types.ts
  libs/webb-ui-components/src/components/index.ts
  libs/webb-ui-components/src/stories/molecules/Card.stories.jsx
  libs/webb-ui-components/src/stories/molecules/TokenSelector.stories.jsx
  libs/webb-ui-components/src/stories/molecules/TokenSelector.stories.tsx
Labels: needs review 👓

#1498 The `getViemChain` function should use chain in the chainsConfig
  libs/dapp-config/src/chains/evm/index.tsx
  libs/web3-api-provider/src/utils/getViemClient.ts
  tools/scripts/fetchingOnChainConfig.ts
Labels: needs review 👓

#1501 Removes proposal page and addresses bugs in keys and authorities page
  apps/stats-dapp/src/containers/DonutChartContainer/DonutChartContainer.tsx
  apps/stats-dapp/src/containers/DonutChartContainer/index.ts
  apps/stats-dapp/src/containers/DonutChartContainer/types.ts
  apps/stats-dapp/src/containers/KeyDetail/KeyDetail.tsx
  apps/stats-dapp/src/containers/KeyStatusCardContainer/KeyStatusCardContainer.tsx
  apps/stats-dapp/src/containers/KeygenTable/KeygenTable.tsx
  apps/stats-dapp/src/containers/ProposalDetail/ProposalDetail.tsx
  apps/stats-dapp/src/containers/ProposalsTable/ProposalsTable.tsx
  apps/stats-dapp/src/containers/ProposersTable/ProposersTable.tsx
  apps/stats-dapp/src/containers/StackedAreaChartContainer/StackedAreaChartContainer.tsx
  apps/stats-dapp/src/containers/index.ts
  apps/stats-dapp/src/gql/authorites.graphql
  apps/stats-dapp/src/gql/fragments.graphql
  apps/stats-dapp/src/gql/proposal-counters.graphql
  apps/stats-dapp/src/gql/proposals.graphql
  apps/stats-dapp/src/gql/public-keys.graphql
  apps/stats-dapp/src/gql/sessions.graphql
  apps/stats-dapp/src/hooks/index.ts
  apps/stats-dapp/src/hooks/useDonutColor.ts
  apps/stats-dapp/src/hooks/useProposalsSeedData.ts
  apps/stats-dapp/src/pages/Proposals.tsx
  apps/stats-dapp/src/provider/hooks/index.ts
  apps/stats-dapp/src/provider/hooks/mappers/index.ts
  apps/stats-dapp/src/provider/hooks/useAuthorities.ts
  apps/stats-dapp/src/provider/hooks/useKeys.ts
  apps/stats-dapp/src/provider/hooks/useProposals.ts
  apps/stats-dapp/src/utils/getChipColorByProposalType.ts
  apps/stats-dapp/src/utils/getProposalsData.ts
  apps/stats-dapp/src/utils/index.ts
  apps/stats-dapp/webpack.config.js
  libs/dapp-config/src/wagmi-config.ts
  libs/dapp-config/src/wallets/wallets-config.tsx
  libs/webb-ui-components/src/constants/index.ts
Labels: needs review 👓, statistics

#1500 Update New Orbit Deployments
  apps/faucet/src/config/tokens.ts
  libs/dapp-config/src/anchors/anchor-config.ts
  libs/dapp-config/src/wallets/wallets-config.tsx
Labels: needs review 👓

#1503 [RELEASE] Faucet, DKG Stats, Tangle Website, Webbsite - Aug 07, 2023
  .github/workflows/deploy-faucet.yml
  .github/workflows/deploy-hubble-stats.yml
  .github/workflows/deploy-tangle-website.yml
  apps/faucet/CHANGELOG.md
  apps/faucet/package.json
  apps/faucet/src/pages/_document.tsx
  apps/stats-dapp/CHANGELOG.md
  apps/stats-dapp/package.json
  apps/tangle-website/CHANGELOG.md
  apps/tangle-website/package.json
  apps/webbsite/CHANGELOG.md
  apps/webbsite/package.json
Labels: needs review 👓

#1508 Fix JS Heap Out Of Memory when Releasing Apps & Update Broken Links
  .github/workflows/check-build.yml
  .github/workflows/deploy-bridge-dapp-dev.yml
  .github/workflows/deploy-stats-dapp-dev.yml
  .github/workflows/release.yml
  apps/bridge-dapp/src/components/EducationCard/EducationCard.tsx
Labels: needs review 👓

#1509 [RELEASE] Hot Fix the Fixed Height on Stats dApp
  apps/faucet/CHANGELOG.md
  apps/stats-dapp/CHANGELOG.md
  apps/stats-dapp/src/containers/Layout/Layout.tsx
  apps/tangle-website/CHANGELOG.md
  apps/webbsite/CHANGELOG.md
Labels: needs review 👓

#1510 chore: add dummy data for Overview Charts
  apps/hubble-stats/app/page.tsx
  apps/hubble-stats/app/pool/[slug]/page.tsx
  apps/hubble-stats/components/BarChart/BarChart.tsx
  apps/hubble-stats/components/BarChart/types.ts
  apps/hubble-stats/components/Breadcrumbs/Breadcrumbs.tsx
  apps/hubble-stats/components/Breadcrumbs/types.ts
  apps/hubble-stats/components/NetworkPoolTable/NetworkPoolTable.tsx
  apps/hubble-stats/components/NetworkTokenTable/NetworkTokenTable.tsx
  apps/hubble-stats/components/PoolOverviewItem/PoolOverviewItem.tsx
  apps/hubble-stats/containers/OverviewChartsContainer/OverviewChartsCmp.tsx
  apps/hubble-stats/containers/OverviewChartsContainer/OverviewChartsContainer.tsx
  apps/hubble-stats/containers/PoolChartsContainer/PoolChartsCmp.tsx
  apps/hubble-stats/containers/PoolChartsContainer/PoolChartsContainer.tsx
  apps/hubble-stats/containers/PoolChartsContainer/index.ts
  apps/hubble-stats/containers/PoolOverviewContainer/PoolOverviewContainer.tsx
  apps/hubble-stats/containers/PoolTransactionsTableContainer/PoolTransactionsTableCmp.tsx
  apps/hubble-stats/containers/index.ts
  apps/hubble-stats/data/getOverviewChartsData.ts
  apps/hubble-stats/data/getPoolChartsData.ts
  apps/hubble-stats/data/getPoolTransactionsData.ts
  apps/hubble-stats/data/index.ts
  libs/webb-ui-components/src/components/Breadcrumbs/BreadcrumbsItem.tsx
  libs/webb-ui-components/src/components/Breadcrumbs/types.ts
  libs/webb-ui-components/src/components/ChartContainer/ChartContainer.tsx
Labels: needs review 👓

#1511 Adds proposal hooks in stats-dapp to fetch batched proposals
  apps/stats-dapp/src/gql/proposals.graphql
  apps/stats-dapp/src/pages/Proposals.tsx
  apps/stats-dapp/src/provider/hooks/index.ts
  apps/stats-dapp/src/provider/hooks/useProposals.ts
Labels: needs review 👓, statistics

#1515 Fix Relayer Status Polling Issue
  libs/abstract-api-provider/src/relayer/webb-relayer.ts
  libs/polkadot-api-provider/src/webb-provider/vanchor-actions.ts
  libs/web3-api-provider/src/webb-provider.ts
  libs/web3-api-provider/src/webb-provider/vanchor-actions.ts
  package.json
  yarn.lock
Labels: needs review 👓

#1526 Update New V2 List Card Items (Token, Shielded Pool, Chain & Relayer)
  apps/bridge-dapp/src/components/ChainListCardWrapper/ChainListCardWrapper.tsx
  apps/bridge-dapp/src/containers/DepositContainer/DepositContainer.tsx
  apps/bridge-dapp/src/containers/TransferContainer/TransferContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
  apps/stats-dapp/src/containers/NavBlocksInfoContainer/NavBlocksInfoContainer.tsx
  libs/icons/src/AlertFill.tsx
  libs/icons/src/CheckboxBlankCircleLine.tsx
  libs/icons/src/RefreshLineIcon.tsx
  libs/icons/src/ShieldedAssetIcon.tsx
  libs/icons/src/index.ts
  libs/webb-ui-components/src/components/Badge/Badge.tsx
  libs/webb-ui-components/src/components/Badge/index.ts
  libs/webb-ui-components/src/components/Badge/types.ts
  libs/webb-ui-components/src/components/ListCard/AssetListItem.tsx
  libs/webb-ui-components/src/components/ListCard/ChainListCard.tsx
  libs/webb-ui-components/src/components/ListCard/ListCardWrapper.tsx
  libs/webb-ui-components/src/components/ListCard/ListItem.tsx
  libs/webb-ui-components/src/components/ListCard/RelayerListCard.tsx
  libs/webb-ui-components/src/components/ListCard/TokenListCard.tsx
  libs/webb-ui-components/src/components/ListCard/TokenListItem.tsx
  libs/webb-ui-components/src/components/ListCard/WithdrawListCard.tsx
  libs/webb-ui-components/src/components/ListCard/WrapAssetListCard.tsx
  libs/webb-ui-components/src/components/ListCard/index.ts
  libs/webb-ui-components/src/components/ListCard/types.ts
  libs/webb-ui-components/src/components/MenuItem/MenuItem.tsx
  libs/webb-ui-components/src/components/Radio/RadioItem.tsx
  libs/webb-ui-components/src/components/Radio/types.d.ts
  libs/webb-ui-components/src/components/TokenSelector/types.ts
  libs/webb-ui-components/src/components/buttons/ChainButton.tsx
  libs/webb-ui-components/src/components/buttons/WalletButton.tsx
  libs/webb-ui-components/src/components/index.ts
  libs/webb-ui-components/src/stories/molecules/TokenListItem.stories.tsx
  libs/webb-ui-components/src/stories/templates/ChainListCard.stories.tsx
  libs/webb-ui-components/src/stories/templates/RelayerListCard.stories.tsx
  libs/webb-ui-components/src/types/index.ts
  libs/webb-ui-components/src/utils/getRoundedAmountString.ts
  yarn.lock
Labels: needs review 👓

#1525 Adds proposal table, proposal status container, fixes theme toggle and dropdown issue
  apps/stats-dapp/src/components/Header/Header.tsx
  apps/stats-dapp/src/components/NetworkSelector/NetworkSelector.tsx
  apps/stats-dapp/src/containers/ProposalsTable/ProposalsTable.tsx
  apps/stats-dapp/src/containers/ProposalsTable/index.ts
  apps/stats-dapp/src/containers/ProposalsTable/utils.ts
  apps/stats-dapp/src/gql/proposals.graphql
  apps/stats-dapp/src/pages/Proposals.tsx
  apps/stats-dapp/src/provider/hooks/useProposals.ts
  apps/stats-dapp/src/provider/stats-provider.tsx
  apps/stats-dapp/src/utils/ChainNameToLogo.ts
  apps/stats-dapp/src/utils/getChipColorByProposalType.ts
  apps/stats-dapp/src/utils/index.ts
  apps/stats-dapp/src/utils/mapChainIdToCurrencyName.ts
  libs/icons/src/ProposalBadge/ProposalBadge.tsx
  libs/icons/src/ProposalBadge/index.ts
  libs/icons/src/ProposalBadge/types.ts
  libs/icons/src/index.ts
  libs/tailwind-preset/index.js
  libs/webb-ui-components/src/components/CardTable/CardTable.tsx
  libs/webb-ui-components/src/components/ProposalsBadgeGroup/ProposalsBadgeGroup.tsx
  libs/webb-ui-components/src/components/ProposalsBadgeGroup/index.ts
  libs/webb-ui-components/src/components/ProposalsBadgeGroup/types.ts
  libs/webb-ui-components/src/components/ThemeSwitcher/ThemeSwitcherButton.tsx
  libs/webb-ui-components/src/components/index.ts
  libs/webb-ui-components/src/constants/index.ts
Labels: needs review 👓, statistics

#1531 Add New Stepped Progressor, Text Field Input, and Improve the Switch Component
  libs/icons/src/AccountCircleLineIcon.tsx
  libs/icons/src/ClipboardLineIcon.tsx
  libs/icons/src/index.ts
  libs/webb-ui-components/src/components/Progress/SteppedProgress.tsx
  libs/webb-ui-components/src/components/Progress/index.ts
  libs/webb-ui-components/src/components/Progress/types.ts
  libs/webb-ui-components/src/components/Switcher/Switcher.tsx
  libs/webb-ui-components/src/components/TextField/TextField.tsx
  libs/webb-ui-components/src/components/TextField/index.ts
  libs/webb-ui-components/src/components/TextField/types.ts
  libs/webb-ui-components/src/components/index.ts
  libs/webb-ui-components/src/stories/molecules/Progress.stories.jsx
  libs/webb-ui-components/src/stories/molecules/Switcher.stories.jsx
  libs/webb-ui-components/src/stories/molecules/TextField.stories.tsx
Labels: needs review 👓

#1542 Fix Netlify Build
  .github/workflows/deploy-bridge-dapp-dev.yml
  .github/workflows/deploy-faucet.yml
  .github/workflows/deploy-hubble-stats.yml
  .github/workflows/deploy-stats-dapp-dev.yml
  .github/workflows/deploy-tangle-website.yml
  .github/workflows/deploy-webbsite-dev.yml
  package.json
  yarn.lock
Labels: needs review 👓

#1521 Connect back-end with Overview Chips Component
  .github/workflows/deploy-hubble-stats.yml
  apps/hubble-stats/.vscode/settings.json
  apps/hubble-stats/app/api/hello/route.ts
  apps/hubble-stats/app/layout.tsx
  apps/hubble-stats/constants/index.ts
  apps/hubble-stats/containers/Layout/Layout.tsx
  apps/hubble-stats/containers/OverviewChipsContainer/OverviewChipsContainer.tsx
  apps/hubble-stats/data/getOverviewChipsData.ts
  package.json
  yarn.lock
Labels: needs review 👓

#1547 V2 Tx Progressor Component
  libs/webb-ui-components/src/components/ChainChip/ChainChip.tsx
  libs/webb-ui-components/src/components/StatusIndicator/StatusIndicator.tsx
  libs/webb-ui-components/src/components/StatusIndicator/index.ts
  libs/webb-ui-components/src/components/StatusIndicator/types.ts
  libs/webb-ui-components/src/components/TxProgressor/TxProgressor.tsx
  libs/webb-ui-components/src/components/TxProgressor/index.ts
  libs/webb-ui-components/src/components/TxProgressor/types.ts
  libs/webb-ui-components/src/components/index.ts
  libs/webb-ui-components/src/hooks/index.ts
  libs/webb-ui-components/src/hooks/useTimeAgo.ts
  libs/webb-ui-components/src/stories/molecules/TxProgressor.stories.tsx
Labels: needs review 👓

#1554 Stats dApp Fixes: footer, compressed key flex & proposal detail page color
  apps/stats-dapp/src/containers/KeyDetail/KeyDetail.tsx
  apps/stats-dapp/src/containers/Layout/Layout.tsx
  apps/stats-dapp/src/containers/ProposalDetail/ProposalDetail.tsx
  libs/webb-ui-components/src/components/Footer/Footer.tsx
  libs/webb-ui-components/src/components/KeyCard/KeyCard.tsx
Labels: needs review 👓, statistics

#1553 Fix Cropped Hero Image & Remove Requirement of `fetchOnChainConfig` When Running DKG Stats
  .github/workflows/check-build.yml
  .github/workflows/release.yml
  apps/stats-dapp/project.json
  apps/stats-dapp/webpack.config.js
  apps/webbsite/src/pages/index.tsx
  package.json
Labels: needs review 👓

#1562 Use Correct Package to Decode Proposals
  apps/stats-dapp/src/utils/getProposalsData.ts
  package.json
  yarn.lock
Labels: needs review 👓

#1560 DKG Stats UI Fixes/ Improvements
  apps/stats-dapp/src/components/Header/Header.tsx
  apps/stats-dapp/src/containers/AuthorityDetail/AuthorityDetail.tsx
  apps/stats-dapp/src/containers/KeyDetail/KeyDetail.tsx
  apps/stats-dapp/src/containers/ProposalDetail/ProposalDetail.tsx
  apps/stats-dapp/src/pages/Authorities.tsx
  apps/stats-dapp/src/pages/Proposals.tsx
  apps/stats-dapp/src/utils/getProposalsData.ts
  libs/webb-ui-components/src/components/Avatar/Avatar.tsx
  libs/webb-ui-components/src/components/Filter/Filter.tsx
  libs/webb-ui-components/src/components/KeyStatusCard/KeyStatusCard.tsx
  libs/webb-ui-components/src/components/TitleWithInfo/TitleWithInfo.tsx
  libs/webb-ui-components/src/components/Tooltip/Tooltip.tsx
  libs/webb-ui-components/src/constants/index.ts
Labels: needs review 👓, statistics

#1566 Use PolkadotAPI to show live chain data and Bug fixes in stats-dapp
  apps/stats-dapp/src/containers/AuthorityDetail/AuthorityDetail.tsx
  apps/stats-dapp/src/containers/KeyDetail/KeyDetail.tsx
  apps/stats-dapp/src/containers/KeyStatusCardContainer/KeyStatusCardContainer.tsx
  apps/stats-dapp/src/containers/NavBlocksInfoContainer/NavBlocksInfoContainer.tsx
  apps/stats-dapp/src/containers/ProposalsTable/ProposalsTable.tsx
  apps/stats-dapp/src/gql/metadata.graphql
  apps/stats-dapp/src/gql/sessions.graphql
  apps/stats-dapp/src/pages/Authorities.tsx
  apps/stats-dapp/src/provider/hooks/useAuthorities.ts
  apps/stats-dapp/src/provider/hooks/useBlocks.ts
  apps/stats-dapp/src/provider/hooks/useProposals.ts
  apps/stats-dapp/src/provider/stats-provider.tsx
  libs/webb-ui-components/src/components/KeyStatusCard/KeyStatusCard.tsx
  libs/webb-ui-components/src/components/KeyStatusCard/types.ts
  libs/webb-ui-components/src/components/TimeLine/TimeLineItem.tsx
  libs/webb-ui-components/src/components/TimeLine/types.ts
  libs/webb-ui-components/src/constants/index.ts
Labels: needs review 👓, bug 🪲, statistics
