Repository tangle-network/dapp, pull requests merged in 2023-02, with the labels that each got.

#968 Replaces action dropdown and removes deposit button in table
  apps/bridge-dapp/src/containers/ShieldedAssetsTableContainer/ShieldedAssetsTableContainer.tsx
  apps/bridge-dapp/src/containers/SpendNotesTableContainer/SpendNotesTableContainer.tsx
Labels: needs review 👓

#969 fixes invalid note upload error
  apps/bridge-dapp/src/containers/UploadSpendNoteModal/UploadModalContent.tsx
Labels: needs review 👓

#970 Fixes stats slider error
  apps/stats-dapp/src/containers/KeygenTable/KeygenTable.tsx
  libs/webb-ui-components/src/components/Slider/Slider.tsx
Labels: approved ✅

#963 Shielded assets table UI fixes
  apps/bridge-dapp/src/containers/ShieldedAssetsTableContainer/ShieldedAssetsTableContainer.tsx
  apps/bridge-dapp/src/containers/SpendNotesTableContainer/SpendNotesTableContainer.tsx
  apps/bridge-dapp/src/hooks/useShieldedAssets.ts
  apps/bridge-dapp/src/hooks/useSpendNotes.ts
Labels: approved ✅

#971 chore: update codeowners and remove outdated release job
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/config.yml
  .github/workflows/push-master.yml
Labels: needs review 👓

#973 Updates spend notes table column header
  apps/bridge-dapp/src/containers/SpendNotesTableContainer/SpendNotesTableContainer.tsx
Labels: needs review 👓

#977 Fixes keys page flicker issue
  apps/stats-dapp/src/containers/KeygenTable/KeygenTable.tsx
  apps/stats-dapp/src/containers/ProposalsTable/ProposalsTable.tsx
  apps/stats-dapp/src/pages/Keys.tsx
Labels: needs review 👓

#975 chore: update webb-ui-components readme
  libs/webb-ui-components/README.md
  libs/webb-ui-components/package.json
Labels: needs review 👓

#978 Updates navigation bar max width
  apps/bridge-dapp/src/components/Header/Header.tsx
Labels: needs review 👓

#980 Update links, add new pages
  .github/workflows/check-build.yml
  .github/workflows/landing-page-dapp-dev.yml
  apps/webbsite/src/components/Footer.tsx
  apps/webbsite/src/components/Header.tsx
  apps/webbsite/src/components/Heading1.tsx
  apps/webbsite/src/components/Heading2.tsx
  apps/webbsite/src/components/Heading3.tsx
  apps/webbsite/src/components/Heading4.tsx
  apps/webbsite/src/components/InternalOrExternalLink.tsx
  apps/webbsite/src/components/Navbar.tsx
  apps/webbsite/src/components/PrivacyScaleIllustration.tsx
  apps/webbsite/src/components/SubHeading.tsx
  apps/webbsite/src/components/SubHeading2.tsx
  apps/webbsite/src/components/sections/ApplicationsAndInfrastructureSection.tsx
  apps/webbsite/src/components/sections/InActionSection.tsx
  apps/webbsite/src/components/sections/PrivacyScaleSection.tsx
  apps/webbsite/src/constants/index.ts
  apps/webbsite/src/libs/notion/getNotionClient.ts
  apps/webbsite/src/libs/notion/getNotionPage.ts
  apps/webbsite/src/libs/notion/server-constants.ts
  apps/webbsite/src/pages/_app.tsx
  apps/webbsite/src/pages/privacy-policy.tsx
  apps/webbsite/src/pages/terms-and-conditions.tsx
  apps/webbsite/src/styles/globals.css
  package.json
  yarn.lock
Labels: needs review 👓

#923 chore: add chromatic visual review and testing
  .github/workflows/ui-review.yml
  package.json
Labels: needs review 👓

#988 Adds banner component
  apps/bridge-dapp/src/containers/Layout/Layout.tsx
  apps/webbsite/src/components/Footer.tsx
  apps/webbsite/src/components/sections/InActionSection.tsx
  libs/webb-ui-components/src/components/Banner/Banner.tsx
  libs/webb-ui-components/src/components/Banner/index.ts
  libs/webb-ui-components/src/components/Banner/types.ts
  libs/webb-ui-components/src/components/index.ts
  libs/webb-ui-components/src/stories/molecules/Banner.stories.jsx
Labels: needs review 👓, ui-components, bridge

#991 Adds docs link in navbar
  apps/webbsite/src/components/Navbar.tsx
  apps/webbsite/src/constants/index.ts
Labels: needs review 👓, webbsite 🕸️

#996 Adds community page to webbsite
  apps/webbsite/public/static/assets/community-texture.png
  apps/webbsite/src/components/Footer.tsx
  apps/webbsite/src/components/Navbar.tsx
  apps/webbsite/src/pages/community.tsx
  apps/webbsite/src/styles/globals.css
  apps/webbsite/tailwind.config.js
  libs/icons/src/DocumentationIcon.tsx
  libs/icons/src/ForumIcon.tsx
  libs/icons/src/index.ts
Labels: needs review 👓, webbsite 🕸️

#997 Adding SEO for Webbsite
  apps/webbsite/public/static/assets/og.png
  apps/webbsite/src/pages/_app.tsx
  apps/webbsite/src/pages/community.tsx
  apps/webbsite/src/pages/index.tsx
  apps/webbsite/src/pages/privacy-policy.tsx
  apps/webbsite/src/pages/terms-and-conditions.tsx
  package.json
  yarn.lock
Labels: needs review 👓

#999 Adding Optimzied OG Image for Marketing Page
  apps/webbsite/public/static/assets/og-optimize.png
  apps/webbsite/src/pages/_app.tsx
Labels: needs review 👓

#1000 [FIX] Preview link for webbsite on PRs
  .github/workflows/deploy-webbsite-dev.yml
Labels: needs review 👓

#1005 Fix signin message
  .github/workflows/check-build.yml
  .github/workflows/deploy-bridge-dapp-dev.yml
  apps/bridge-dapp/src/constants/signIn.ts
  apps/bridge-dapp/src/containers/CreateAccountModal/CreateAccountModal.tsx
  apps/bridge-dapp/src/containers/CreateAccountModal/congrats.json
  apps/bridge-dapp/src/pages/PageNoteAccount.tsx
  apps/bridge-dapp/webpack.base.js
Labels: approved ✅

#1003 Filter option for bridge tables and UI fixes
  README.md
  apps/bridge-dapp/src/components/tables/FilterButton.tsx
  apps/bridge-dapp/src/components/tables/index.ts
  apps/bridge-dapp/src/components/tables/types.d.ts
  apps/bridge-dapp/src/containers/UploadSpendNoteModal/PasteModalContent.tsx
  apps/bridge-dapp/src/containers/UploadSpendNoteModal/UploadSpendNoteModal.tsx
  apps/bridge-dapp/src/containers/note-account-tables/ShieldedAssetsTableContainer/ShieldedAssetsTableContainer.tsx
  apps/bridge-dapp/src/containers/note-account-tables/SpendNotesTableContainer/SpendNotesTableContainer.tsx
  apps/bridge-dapp/src/containers/note-account-tables/types.d.ts
  apps/bridge-dapp/src/hooks/useShieldedAssets.ts
  apps/bridge-dapp/src/hooks/useSpendNotes.ts
  apps/bridge-dapp/src/pages/PageBridge.tsx
  apps/bridge-dapp/src/utils/index.ts
  apps/bridge-dapp/src/utils/isValidNote.ts
  libs/icons/src/FilterIcon2.tsx
  libs/icons/src/index.ts
  libs/webb-ui-components/README.md
  libs/webb-ui-components/src/components/BridgeInputs/FixedAmount.tsx
  libs/webb-ui-components/src/components/Button/Button.tsx
  libs/webb-ui-components/src/components/Button/utils.ts
  libs/webb-ui-components/src/components/ChainsRing/ChainsRing.tsx
  libs/webb-ui-components/src/components/Dropdown/DropdownBody.tsx
  libs/webb-ui-components/src/utils/formatTokenAmount.ts
  libs/webb-ui-components/src/utils/index.ts
Labels: needs changes 🔧, bridge

#1008 chore: adds local network setup scripts and Sentry integration
  .gitignore
  README.md
  apps/bridge-dapp/src/App.tsx
  apps/bridge-dapp/src/index.tsx
  package.json
  tools/scripts/bridge.sh
  tools/scripts/contracts.sh
  tools/scripts/local-bridge-network.sh
  tools/scripts/relayer.sh
  yarn.lock
Labels: needs review 👓, do not merge 🛑

#1011 Education Card & UI Updates
  .github/workflows/deploy-webbsite-dev.yml
  .vscode/settings.json
  apps/bridge-dapp/src/assets/bridge-bg.png
  apps/bridge-dapp/src/assets/bridge-dark-bg.png
  apps/bridge-dapp/src/components/ChainListCardWrapper/ChainListCardWrapper.tsx
  apps/bridge-dapp/src/components/EducationCard/EducationCard.tsx
  apps/bridge-dapp/src/components/EducationCard/index.ts
  apps/bridge-dapp/src/components/EducationCard/types.d.ts
  apps/bridge-dapp/src/components/index.ts
  apps/bridge-dapp/src/components/tables/EmptyTable.tsx
  apps/bridge-dapp/src/containers/DepositContainer/DepositContainer.tsx
  apps/bridge-dapp/src/containers/Layout/Layout.tsx
  apps/bridge-dapp/src/containers/TransferContainer/TransferContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
  apps/bridge-dapp/src/containers/note-account-tables/ShieldedAssetsTableContainer/ShieldedAssetsTableContainer.tsx
  apps/bridge-dapp/src/containers/note-account-tables/SpendNotesTableContainer/SpendNotesTableContainer.tsx
  apps/bridge-dapp/src/pages/PageBridge.tsx
  apps/webbsite/src/components/sections/HeroSection.tsx
  libs/dapp-config/src/chains/evm/index.tsx
  libs/icons/src/BellIcon.tsx
  libs/icons/src/UsageGuideIcon.tsx
  libs/icons/src/index.ts
  libs/webb-ui-components/src/containers/DepositCard/DepositCard.tsx
  libs/webb-ui-components/src/containers/TransactionProgressCard/TransactionQueueCard.tsx
Labels: needs changes 🔧

#1017 Error Fallback Component
  apps/bridge-dapp/src/constants/index.ts
  apps/bridge-dapp/src/pages/PageBridge.tsx
  libs/relayer-manager-factory/src/relayer-manager-factory.ts
  libs/webb-ui-components/src/components/ErrorFallback/ErrorFallback.tsx
  libs/webb-ui-components/src/components/ErrorFallback/index.ts
  libs/webb-ui-components/src/components/ErrorFallback/types.d.ts
  libs/webb-ui-components/src/components/index.ts
  libs/webb-ui-components/src/constants/index.ts
  libs/webb-ui-components/src/containers/WebbUIErrorBoudary/WebbUIErrorBoudary.tsx
  libs/webb-ui-components/src/stories/molecules/ErrorFallback.stories.jsx
Labels: needs review 👓

#985 Fixing Moonbase Alpha, Mumbai and Optimism Errors
  apps/bridge-dapp/src/components/ChainListCardWrapper/ChainListCardWrapper.tsx
  apps/bridge-dapp/src/components/EducationCard/EducationCard.tsx
  apps/bridge-dapp/src/components/tables/LoadingTable.tsx
  apps/bridge-dapp/src/containers/CreateAccountModal/CreateAccountModal.tsx
  apps/bridge-dapp/src/containers/DepositContainer/DepositConfirmContainer.tsx
  apps/bridge-dapp/src/containers/DepositContainer/DepositContainer.tsx
  apps/bridge-dapp/src/containers/Layout/Layout.tsx
  apps/bridge-dapp/src/containers/TransferContainer/TransferConfirmContainer.tsx
  apps/bridge-dapp/src/containers/TransferContainer/TransferContainer.tsx
  apps/bridge-dapp/src/containers/TransferContainer/types.d.ts
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawConfirmContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/types.d.ts
  apps/bridge-dapp/src/hooks/useShieldedAssets.ts
  apps/bridge-dapp/src/utils/errors.ts
  libs/abstract-api-provider/src/vanchor/vanchor-actions.ts
  libs/api-provider-environment/src/WebbProvider.tsx
  libs/api-provider-environment/src/index.ts
  libs/api-provider-environment/src/transaction/useTransactionQueue.tsx
  libs/api-provider-environment/src/types.ts
  libs/api-provider-environment/src/utils/getNativeTokenInfo.tsx
  libs/api-provider-environment/src/utils/index.ts
  libs/api-provider-environment/tsconfig.lib.json
  libs/browser-utils/src/download/cached-fetch.ts
  libs/dapp-config/src/anchors/anchor-config.ts
  libs/dapp-config/src/chains/evm/index.tsx
  libs/dapp-config/src/currencies/currency-config.ts
  libs/icons/src/TokenIcon.tsx
  libs/icons/src/chains/kovan.svg
  libs/icons/src/chains/rinkeby.svg
  libs/icons/src/chains/ropsten.svg
  libs/icons/src/chains/substrate.svg
  libs/icons/src/chains/tangle.svg
  libs/icons/src/tokens/dev.svg
  libs/icons/src/tokens/webb.svg
  libs/icons/src/tokens/webb^2.svg
  libs/icons/src/tokens/webbdev.svg
  libs/icons/src/tokens/webbeth.svg
  libs/polkadot-api-provider/src/webb-provider/relayer-manager.ts
  libs/polkadot-api-provider/src/webb-provider/vanchor-actions.ts
  libs/react-hooks/src/currency/useCurrencies.tsx
  libs/react-hooks/src/relayer/useRelayers.ts
  libs/web3-api-provider/src/webb-provider.ts
  libs/web3-api-provider/src/webb-provider/chain-query.ts
  libs/web3-api-provider/src/webb-provider/relayer-manager.ts
  libs/web3-api-provider/src/webb-provider/vanchor-actions.ts
  libs/webb-ui-components/src/components/FileUploads/FileUploadField.tsx
  libs/webb-ui-components/src/components/ListCard/ChainListCard.tsx
  libs/webb-ui-components/src/components/ListCard/types.ts
  libs/webb-ui-components/src/containers/ConfirmationCard/TransferConfirm.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/WithdrawConfirm.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/types.ts
  libs/webb-ui-components/src/utils/formatTokenAmount.ts
  package.json
  yarn.lock
Labels: do not merge 🛑, in qa 🧪

#1019 chore: add plausible script to marketing site
  apps/webbsite/src/pages/_app.tsx
Labels: needs review 👓

#1020 Adding Arbitrum and Indexing localStorage by `ResourceId`
  apps/bridge-dapp/src/containers/TransferContainer/TransferContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
  apps/bridge-dapp/src/hooks/useSpendNotes.ts
  libs/abstract-api-provider/src/webb-provider.interface.ts
  libs/api-provider-environment/src/WebbProvider.tsx
  libs/browser-utils/src/storage.ts
  libs/dapp-config/src/anchors/anchor-config.ts
  libs/dapp-config/src/chains/evm/index.tsx
  libs/dapp-config/src/currencies/currency-config.ts
  libs/note-manager/src/note-manager.ts
  libs/polkadot-api-provider/src/webb-provider.ts
  libs/react-hooks/src/index.ts
  libs/react-hooks/src/useCurrentResourceId.ts
  libs/web3-api-provider/src/webb-provider.ts
  libs/web3-api-provider/src/webb-provider/relayer-manager.ts
  libs/web3-api-provider/src/webb-provider/vanchor-actions.ts
  libs/webb-ui-components/src/containers/TransferCard/TransferCard.tsx
Labels: needs review 👓

#1022 update: remove parachain endpoint from stats dapp - only use standalone
  apps/bridge-dapp/src/components/Header/Header.tsx
  apps/stats-dapp/src/components/Header/Header.tsx
  apps/stats-dapp/src/constants/index.ts
  apps/stats-dapp/src/containers/Layout/Layout.tsx
  apps/stats-dapp/src/provider/hooks/useKeys.ts
  apps/stats-dapp/src/provider/stats-provider.tsx
  docs/config/RelayerConfig.png
  docs/config/RelayerConfig.signalling
  docs/overview/AccessStateThroughHooks.png
  docs/overview/AccessStateThroughHooks.signalling
  docs/overview/ProvidersInitialization.png
  docs/overview/ProvidersInitialization.signalling
  docs/pages/deposit/VBridgeTokensSelection.png
  docs/pages/deposit/VBridgeTokensSelection.signalling
  docs/pages/withdraw/relayer/NoteChangeState.png
  docs/pages/withdraw/relayer/NoteChangeState.signalling
  docs/pages/withdraw/relayer/PageLoadState.png
  docs/pages/withdraw/relayer/PageLoadState.signalling
  docs/pages/withdraw/relayer/SetActiveRelayerState.png
  docs/pages/withdraw/relayer/SetActiveRelayerState.signalling
  docs/state/DisplayAssets.png
  docs/state/DisplayAssets.signalling
  libs/webb-ui-components/src/constants/index.ts
Labels: needs review 👓

#1024 Dynamic Education Card Step
  apps/bridge-dapp/src/components/EducationCard/EducationCard.tsx
  apps/bridge-dapp/src/containers/DepositContainer/DepositContainer.tsx
  apps/bridge-dapp/src/containers/TransferContainer/TransferContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawContainer/WithdrawContainer.tsx
  apps/bridge-dapp/src/hooks/useEducationCardStep.ts
  libs/relayer-manager-factory/src/relayer-manager-factory.ts
  package.json
  yarn.lock
Labels: needs review 👓

#1026 Fixing Webpack Production Build
  apps/bridge-dapp/project.json
  apps/bridge-dapp/webpack.base.js
  apps/bridge-dapp/webpack.dev.js
  apps/stats-dapp/webpack.config.js
Labels: needs review 👓
