Repository tangle-network/dapp, pull requests merged in 2023-11, with the labels that each got.

#1812 Bridge Tx Confirmation V2
  apps/bridge-dapp/src/components/RelayerFeeDetails.tsx
  apps/bridge-dapp/src/components/index.ts
  apps/bridge-dapp/src/containers/DepositConfirmContainer/DepositConfirmContainer.tsx
  apps/bridge-dapp/src/containers/DepositConfirmContainer/types.ts
  apps/bridge-dapp/src/containers/TransferConfirmContainer/TransferConfirmContainer.tsx
  apps/bridge-dapp/src/containers/TxInfoContainer/TxInfoContainer.tsx
  apps/bridge-dapp/src/containers/WithdrawConfirmContainer/WithdrawConfirmContainer.tsx
  apps/bridge-dapp/src/hooks/index.ts
  apps/bridge-dapp/src/hooks/useTransferFeeCalculation.ts
  apps/bridge-dapp/src/hooks/useWithdrawFeeCalculation.ts
  apps/bridge-dapp/src/pages/Hubble/Bridge/Deposit/index.tsx
  apps/bridge-dapp/src/pages/Hubble/Bridge/Deposit/private/useDepositButtonProps.tsx
  apps/bridge-dapp/src/pages/Hubble/Bridge/Transfer/index.tsx
  apps/bridge-dapp/src/pages/Hubble/Bridge/Withdraw/index.tsx
  libs/dapp-config/src/utils/parseOnChainData.ts
  libs/icons/src/ChainIcon.tsx
  libs/icons/src/EyeClosedLine.tsx
  libs/icons/src/EyeLine.tsx
  libs/icons/src/FileShieldLine.tsx
  libs/icons/src/chains/athena.svg
  libs/icons/src/chains/demeter.svg
  libs/icons/src/chains/hermes.svg
  libs/icons/src/index.ts
  libs/webb-ui-components/src/components/AddressChip/AddressChip.tsx
  libs/webb-ui-components/src/components/AddressChip/index.ts
  libs/webb-ui-components/src/components/AddressChip/types.ts
  libs/webb-ui-components/src/components/CopyWithTooltip/CopyWithTooltip.tsx
  libs/webb-ui-components/src/components/CopyWithTooltip/types.ts
  libs/webb-ui-components/src/components/IconWithTooltip/IconWithTooltip.tsx
  libs/webb-ui-components/src/components/TitleWithInfo/TitleWithInfo.tsx
  libs/webb-ui-components/src/components/TokenWithAmount/types.ts
  libs/webb-ui-components/src/components/TokensRing/TokensRing.tsx
  libs/webb-ui-components/src/components/TokensRing/index.ts
  libs/webb-ui-components/src/components/TokensRing/types.ts
  libs/webb-ui-components/src/components/TxConfirmationRing/TxConfirmationRing.tsx
  libs/webb-ui-components/src/components/TxConfirmationRing/index.ts
  libs/webb-ui-components/src/components/TxConfirmationRing/types.ts
  libs/webb-ui-components/src/components/TxProgressor/TxProgressor.tsx
  libs/webb-ui-components/src/components/TxProgressor/types.ts
  libs/webb-ui-components/src/components/index.ts
  libs/webb-ui-components/src/containers/ConfirmationCard/AmountInfo.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/DepositConfirm.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/RefundAmount.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/SpendNoteInput.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/TransferConfirm.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/WithdrawConfirm.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/WrapperSection.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/index.ts
  libs/webb-ui-components/src/containers/ConfirmationCard/types.ts
  libs/webb-ui-components/src/containers/ConfirmationCard/utils.ts
  libs/webb-ui-components/src/stories/molecules/AddressChip.stories.jsx
  libs/webb-ui-components/src/stories/molecules/TokenRing.stories.jsx
  libs/webb-ui-components/src/stories/molecules/TxConfirmationRing.stories.jsx
Labels: needs review 👓

#1815 Display DKG best authorities in authorities table
  apps/stats-dapp/src/containers/AuthoritiesTable/AuthoritiesTable.tsx
  apps/stats-dapp/src/provider/hooks/useAuthorities.ts
Labels: needs review 👓, dkg-stats-dapp

#1827 Ready UI for Account page
  apps/bridge-dapp/src/components/ActionsDropdown.tsx
  apps/bridge-dapp/src/components/Header/Header.tsx
  apps/bridge-dapp/src/components/HiddenValueEye.tsx
  apps/bridge-dapp/src/components/index.ts
  apps/bridge-dapp/src/components/tables/index.ts
  apps/bridge-dapp/src/components/tables/types.d.ts
  apps/bridge-dapp/src/constants/paths.ts
  apps/bridge-dapp/src/containers/ClearTxHistoryModal/ClearTxHistoryModal.tsx
  apps/bridge-dapp/src/containers/ClearTxHistoryModal/index.ts
  apps/bridge-dapp/src/containers/DepositConfirmContainer/DepositConfirmContainer.tsx
  apps/bridge-dapp/src/containers/TransferConfirmContainer/TransferConfirmContainer.tsx
  apps/bridge-dapp/src/containers/TxDetailContainer/InputOrOutputNotes.tsx
  apps/bridge-dapp/src/containers/TxDetailContainer/SourceOrDestinationWalletInfo.tsx
  apps/bridge-dapp/src/containers/TxDetailContainer/TxBasicInfo.tsx
  apps/bridge-dapp/src/containers/TxDetailContainer/TxDetailContainer.tsx
  apps/bridge-dapp/src/containers/TxDetailContainer/Wrapper.tsx
  apps/bridge-dapp/src/containers/TxDetailContainer/index.ts
  apps/bridge-dapp/src/containers/TxDetailContainer/types.ts
  apps/bridge-dapp/src/containers/TxTableContainer/TxTableContainer.tsx
  apps/bridge-dapp/src/containers/TxTableContainer/index.ts
  apps/bridge-dapp/src/containers/TxTableContainer/types.ts
  apps/bridge-dapp/src/containers/UploadSpendNoteModal/UploadModalContent.tsx
  apps/bridge-dapp/src/containers/UploadSpendNoteModal/UploadSpendNoteModal.tsx
  apps/bridge-dapp/src/containers/UploadTxHistoryModal/UploadTxHistoryModal.tsx
  apps/bridge-dapp/src/containers/UploadTxHistoryModal/index.ts
  apps/bridge-dapp/src/containers/index.ts
  apps/bridge-dapp/src/pages/Account/AccountSummaryCard.tsx
  apps/bridge-dapp/src/pages/Account/NoTx.tsx
  apps/bridge-dapp/src/pages/Account/Transactions/TransactionDetail/index.tsx
  apps/bridge-dapp/src/pages/Account/Transactions/index.tsx
  apps/bridge-dapp/src/pages/Account/index.tsx
  apps/bridge-dapp/src/routes/index.tsx
  apps/bridge-dapp/src/utils/downloadTxHistory.ts
  apps/bridge-dapp/src/utils/formatDateTimeByTimestamp.ts
  apps/bridge-dapp/src/utils/index.ts
  apps/hubble-stats/data/poolTables/getPoolTransactionsTableData.ts
  apps/hubble-stats/utils/date.ts
  libs/icons/src/TimerLine.tsx
  libs/icons/src/UploadLine.tsx
  libs/icons/src/index.ts
  libs/webb-ui-components/src/components/FileUploads/FileUploadArea.tsx
  libs/webb-ui-components/src/components/FileUploads/types.d.ts
  libs/webb-ui-components/src/utils/getTimeDetailByEpoch.ts
  libs/webb-ui-components/src/utils/index.ts
Labels: needs review 👓

#1837 Tx Table History with IndexedDB + delete and download functionalities
  apps/bridge-dapp/src/components/Header/TxProgressDropdown/TxItem.tsx
  apps/bridge-dapp/src/components/Header/TxProgressDropdown/index.tsx
  apps/bridge-dapp/src/components/HiddenValueEye.tsx
  apps/bridge-dapp/src/components/RelayerFeeDetails.tsx
  apps/bridge-dapp/src/containers/ClearTxHistoryModal/ClearTxHistoryModal.tsx
  apps/bridge-dapp/src/containers/DepositConfirmContainer/DepositConfirmContainer.tsx
  apps/bridge-dapp/src/containers/TransferConfirmContainer/TransferConfirmContainer.tsx
  apps/bridge-dapp/src/containers/TxDetailContainer/InputOrOutputNotes.tsx
  apps/bridge-dapp/src/containers/TxDetailContainer/SourceOrDestinationWalletInfo.tsx
  apps/bridge-dapp/src/containers/TxDetailContainer/TxBasicInfo.tsx
  apps/bridge-dapp/src/containers/TxDetailContainer/TxDetailContainer.tsx
  apps/bridge-dapp/src/containers/TxDetailContainer/types.ts
  apps/bridge-dapp/src/containers/TxTableContainer/TxTableContainer.tsx
  apps/bridge-dapp/src/containers/TxTableContainer/types.ts
  apps/bridge-dapp/src/containers/WithdrawConfirmContainer/WithdrawConfirmContainer.tsx
  apps/bridge-dapp/src/hooks/useCurrentTx.ts
  apps/bridge-dapp/src/pages/Account/Transactions/TransactionDetail/index.tsx
  apps/bridge-dapp/src/pages/Account/Transactions/index.tsx
  apps/bridge-dapp/src/pages/Account/index.tsx
  apps/bridge-dapp/src/routes/index.tsx
  apps/bridge-dapp/src/utils/downloadTxHistory.ts
  apps/bridge-dapp/src/utils/getCurrentTimestamp.ts
  apps/bridge-dapp/src/utils/getNoteSerializations.ts
  apps/bridge-dapp/src/utils/index.ts
  libs/abstract-api-provider/src/relayer/webb-relayer-manager.ts
  libs/abstract-api-provider/src/transaction/index.ts
  libs/abstract-api-provider/src/transaction/transaction.ts
  libs/abstract-api-provider/src/transaction/transactionExecutor.ts
  libs/abstract-api-provider/src/vanchor/vanchor-actions.ts
  libs/abstract-api-provider/src/webb-provider.interface.ts
  libs/api-provider-environment/src/transaction/client-storage/db.ts
  libs/api-provider-environment/src/transaction/index.ts
  libs/api-provider-environment/src/transaction/useTransactionClientStorage.tsx
  libs/api-provider-environment/src/transaction/useTransactionQueue.tsx
  libs/api-provider-environment/src/webb-context/webb-context.ts
  libs/polkadot-api-provider/src/webb-provider.ts
  libs/polkadot-api-provider/src/webb-provider/relayer-manager.ts
  libs/polkadot-api-provider/src/webb-provider/vanchor-actions.ts
  libs/web3-api-provider/src/utils/handleVAnchorTxState.ts
  libs/web3-api-provider/src/webb-provider.ts
  libs/web3-api-provider/src/webb-provider/relayer-manager.ts
  libs/web3-api-provider/src/webb-provider/vanchor-actions.ts
  package.json
  yarn.lock
Labels: needs review 👓

#1839 Tx History management for Account Page
  apps/bridge-dapp/src/components/ActionsDropdown.tsx
  apps/bridge-dapp/src/containers/ClearTxHistoryModal/ClearTxHistoryModal.tsx
  apps/bridge-dapp/src/containers/DepositConfirmContainer/DepositConfirmContainer.tsx
  apps/bridge-dapp/src/containers/TransferConfirmContainer/TransferConfirmContainer.tsx
  apps/bridge-dapp/src/containers/TransferConfirmContainer/types.ts
  apps/bridge-dapp/src/containers/UploadSpendNoteModal/UploadModalContent.tsx
  apps/bridge-dapp/src/containers/UploadTxHistoryModal/UploadTxHistoryModal.tsx
  apps/bridge-dapp/src/containers/UploadTxHistoryModal/types.ts
  apps/bridge-dapp/src/containers/WithdrawConfirmContainer/WithdrawConfirmContainer.tsx
  apps/bridge-dapp/src/pages/Hubble/Bridge/Transfer/private/useTransferButtonProps.tsx
  apps/bridge-dapp/src/utils/index.ts
  apps/bridge-dapp/src/utils/safeParseJson.ts
  libs/api-provider-environment/src/transaction/useTransactionClientStorage.tsx
  package.json
  yarn.lock
Labels: needs review 👓

#1843 EVM Staking - Adds wallet balance & total staked info container
  apps/tangle-dapp/app/layout.tsx
  apps/tangle-dapp/app/page.tsx
  apps/tangle-dapp/components/KeyMetricItem/KeyMetricItemValueClient.tsx
  apps/tangle-dapp/components/KeyMetricItem/dataHooks.ts
  apps/tangle-dapp/components/StatsMetricItem/StatsMetricItem.tsx
  apps/tangle-dapp/components/StatsMetricItem/index.ts
  apps/tangle-dapp/components/StatsMetricItem/types.ts
  apps/tangle-dapp/components/ValidatorTable/ValidatorTable.tsx
  apps/tangle-dapp/components/index.ts
  apps/tangle-dapp/constants/evm.ts
  apps/tangle-dapp/constants/index.ts
  apps/tangle-dapp/constants/polkadot.ts
  apps/tangle-dapp/containers/Layout/Layout.tsx
  apps/tangle-dapp/containers/NominatorStatsContainer/NominatorStatsContainer.tsx
  apps/tangle-dapp/containers/NominatorStatsContainer/index.ts
  apps/tangle-dapp/containers/index.ts
  apps/tangle-dapp/data/NominatorStats/getTokenWalletBalance.ts
  apps/tangle-dapp/data/NominatorStats/getTotalStakedAmount.ts
  apps/tangle-dapp/data/NominatorStats/index.ts
  apps/tangle-dapp/data/index.ts
  apps/tangle-dapp/tailwind.config.js
  apps/tangle-dapp/types/index.ts
  apps/tangle-dapp/utils/convertEthereumToSubstrateAddress.ts
  apps/tangle-dapp/utils/index.ts
  apps/tangle-dapp/utils/splitTokenValueAndSymbol.ts
  libs/webb-ui-components/src/components/SideBar/SideBar.tsx
  libs/webb-ui-components/src/constants/index.ts
  yarn.lock
Labels: needs review 👓, tangle-dapp

#1847 EVM Staking - Remove minimum stake column from validator tables
  README.md
  apps/tangle-dapp/components/ValidatorTable/ValidatorTable.tsx
  apps/tangle-dapp/constants/polkadot.ts
  apps/tangle-dapp/data/ValidatorTables/getActiveValidators.ts
  apps/tangle-dapp/data/ValidatorTables/getWaitingValidators.ts
  apps/tangle-dapp/types/index.ts
Labels: needs review 👓, tangle-dapp

#1848 Governance Template UI
  libs/webb-ui-components/src/components/ChainsRing/ChainsRing.tsx
  libs/webb-ui-components/src/components/ChainsRing/index.ts
  libs/webb-ui-components/src/components/ChainsRing/types.d.ts
  libs/webb-ui-components/src/components/ChainsRing/types.ts
  libs/webb-ui-components/src/components/GovernanceForm/FunctionInputs.tsx
  libs/webb-ui-components/src/components/GovernanceForm/GovernanceForm.tsx
  libs/webb-ui-components/src/components/GovernanceForm/index.ts
  libs/webb-ui-components/src/components/GovernanceForm/types.ts
  libs/webb-ui-components/src/components/GovernanceForm/utils.ts
  libs/webb-ui-components/src/components/TxConfirmationRing/TxConfirmationRing.tsx
  libs/webb-ui-components/src/components/index.ts
  libs/webb-ui-components/src/stories/molecules/ChainsRing.stories.tsx
  libs/webb-ui-components/src/stories/templates/GovernanceForm.stories.tsx
Labels: needs review 👓

#1856 Initialize Testnet Leaderboard App
  .github/PULL_REQUEST_TEMPLATE.md
  apps/testnet-leaderboard/.eslintrc.json
  apps/testnet-leaderboard/app/api/hello/route.ts
  apps/testnet-leaderboard/app/layout.tsx
  apps/testnet-leaderboard/app/page.tsx
  apps/testnet-leaderboard/app/providers.tsx
  apps/testnet-leaderboard/components/Footer.tsx
  apps/testnet-leaderboard/components/Header.tsx
  apps/testnet-leaderboard/components/Navbar.tsx
  apps/testnet-leaderboard/index.d.ts
  apps/testnet-leaderboard/jest.config.ts
  apps/testnet-leaderboard/next-env.d.ts
  apps/testnet-leaderboard/next.config.js
  apps/testnet-leaderboard/postcss.config.js
  apps/testnet-leaderboard/project.json
  apps/testnet-leaderboard/public/.gitkeep
  apps/testnet-leaderboard/public/assets/favicon.png
  apps/testnet-leaderboard/public/favicon.ico
  apps/testnet-leaderboard/tailwind.config.js
  apps/testnet-leaderboard/tsconfig.json
  apps/testnet-leaderboard/tsconfig.spec.json
  libs/webb-ui-components/src/components/WebsiteFooter/WebsiteFooter.tsx
  libs/webb-ui-components/src/constants/index.ts
  package.json
  yarn.lock
Labels: needs review 👓

#1852 feat: OFAC provider
  libs/api-provider-environment/src/OFACFilterProvider.tsx
  libs/api-provider-environment/src/index.ts
  libs/webb-ui-components/src/components/OFACModal/OFACModal.tsx
  libs/webb-ui-components/src/components/OFACModal/index.ts
  libs/webb-ui-components/src/components/index.ts
  libs/webb-ui-components/src/stories/molecules/OFACModal.stories.tsx
Labels: needs review 👓

#1858 Integrate Leaderboad Backend
  .env.example
  apps/testnet-leaderboard/app/layout.tsx
  apps/testnet-leaderboard/app/page.tsx
  apps/testnet-leaderboard/components/CountdownSection/Badges.tsx
  apps/testnet-leaderboard/components/CountdownSection/CTAButtons.tsx
  apps/testnet-leaderboard/components/CountdownSection/TimeRemaining.tsx
  apps/testnet-leaderboard/components/CountdownSection/index.tsx
  apps/testnet-leaderboard/components/FAQSection/FAQAccordion.tsx
  apps/testnet-leaderboard/components/FAQSection/index.tsx
  apps/testnet-leaderboard/components/RankingTableSection/AddressCell.tsx
  apps/testnet-leaderboard/components/RankingTableSection/BadgesCell.tsx
  apps/testnet-leaderboard/components/RankingTableSection/HeaderCell.tsx
  apps/testnet-leaderboard/components/RankingTableSection/ParseReponseErrorView.tsx
  apps/testnet-leaderboard/components/RankingTableSection/RankingTableView.tsx
  apps/testnet-leaderboard/components/RankingTableSection/SWRProvider.tsx
  apps/testnet-leaderboard/components/RankingTableSection/fetchLeaderboardData.ts
  apps/testnet-leaderboard/components/RankingTableSection/index.tsx
  apps/testnet-leaderboard/components/RankingTableSection/types.ts
  apps/testnet-leaderboard/constants/index.ts
  apps/testnet-leaderboard/hooks/useTimeRemaining.ts
  apps/testnet-leaderboard/next.config.js
  apps/testnet-leaderboard/types/index.ts
  libs/webb-ui-components/src/components/Avatar/Avatar.tsx
  libs/webb-ui-components/src/components/Avatar/types.ts
  libs/webb-ui-components/src/components/Avatar/utils.ts
  libs/webb-ui-components/src/constants/index.ts
  libs/webb-ui-components/src/hooks/useDarkMode.ts
Labels: needs review 👓

#1863 EVM Staking - Initial Delegations & Payouts Table
  apps/tangle-dapp/app/page.tsx
  apps/tangle-dapp/components/DelegatorTable/DelegatorTable.tsx
  apps/tangle-dapp/components/DelegatorTable/index.ts
  apps/tangle-dapp/components/DelegatorTable/types.ts
  apps/tangle-dapp/components/TableStatus/TableStatus.tsx
  apps/tangle-dapp/components/TableStatus/index.ts
  apps/tangle-dapp/components/TableStatus/types.ts
  apps/tangle-dapp/components/index.ts
  apps/tangle-dapp/containers/DelegationsPayoutsContainer/DelegationsPayoutsContainer.tsx
  apps/tangle-dapp/containers/DelegationsPayoutsContainer/DelegatorTableContainer.tsx
  apps/tangle-dapp/containers/DelegationsPayoutsContainer/index.ts
  apps/tangle-dapp/containers/Layout/Layout.tsx
  apps/tangle-dapp/containers/ValidatorTablesContainer/ValidatorTablesContainer.tsx
  apps/tangle-dapp/containers/index.ts
  apps/tangle-dapp/data/DelegationsPayouts/useDelegations.ts
  apps/tangle-dapp/types/index.ts
  package.json
  tools/tsconfig.json
Labels: needs review 👓, tangle-dapp

#1862 Governance Page components
  libs/webb-ui-components/src/components/ChainsRing/ChainsRing.tsx
  libs/webb-ui-components/src/components/ChainsRing/types.ts
  libs/webb-ui-components/src/components/GovernanceForm/GovernanceForm.tsx
  libs/webb-ui-components/src/components/GovernanceForm/index.ts
  libs/webb-ui-components/src/components/GovernanceForm/types.ts
  libs/webb-ui-components/src/components/GovernanceForm/utils.ts
  libs/webb-ui-components/src/components/ListCard/ContractListCard.tsx
  libs/webb-ui-components/src/components/ListCard/ListCardWrapper.tsx
  libs/webb-ui-components/src/components/ListCard/index.ts
  libs/webb-ui-components/src/components/ListCard/types.ts
  libs/webb-ui-components/src/components/index.ts
  libs/webb-ui-components/src/containers/GovernanceContractDetailCard/GovernanceContractDetailCard.tsx
  libs/webb-ui-components/src/containers/GovernanceContractDetailCard/GovernanceFncCaller.tsx
  libs/webb-ui-components/src/containers/GovernanceContractDetailCard/index.ts
  libs/webb-ui-components/src/containers/GovernanceContractDetailCard/types.ts
  libs/webb-ui-components/src/containers/index.ts
  libs/webb-ui-components/src/stories/molecules/ContractListCard.stories.tsx
  libs/webb-ui-components/src/stories/templates/GovernanceContractDetailCard.stories.tsx
  libs/webb-ui-components/src/stories/templates/GovernanceForm.stories.tsx
Labels: needs review 👓

#1864 Leaderboard - Adding Sessions and Identity Info, Support Search Functionality
  apps/testnet-leaderboard/app/page.tsx
  apps/testnet-leaderboard/components/CountdownSection/Badges.tsx
  apps/testnet-leaderboard/components/RankingTableSection/AddressCell.tsx
  apps/testnet-leaderboard/components/RankingTableSection/BadgeWithTooltip.tsx
  apps/testnet-leaderboard/components/RankingTableSection/BadgesCell.tsx
  apps/testnet-leaderboard/components/RankingTableSection/IdentityCell.tsx
  apps/testnet-leaderboard/components/RankingTableSection/RankingTableView.tsx
  apps/testnet-leaderboard/components/RankingTableSection/SessionsCell.tsx
  apps/testnet-leaderboard/components/RankingTableSection/SocialLinksCell.tsx
  apps/testnet-leaderboard/components/RankingTableSection/fetchLeaderboardData.ts
  apps/testnet-leaderboard/components/RankingTableSection/index.tsx
  apps/testnet-leaderboard/components/RankingTableSection/types.ts
  apps/testnet-leaderboard/components/RankingTableSection/utils.ts
  apps/testnet-leaderboard/constants/index.ts
  apps/testnet-leaderboard/types/index.ts
  libs/webb-ui-components/src/hooks/useCopyable.ts
  tools/scripts/fetchingOnChainConfig.ts
  yarn.lock
Labels: needs review 👓
