Repository tangle-network/dapp, pull requests merged in 2024-05, with the labels that each got.

#2283 feat(tangle-dapp): Add # of Active Services and Restake Amount to Validators Table in Nomination
  apps/tangle-dapp/app/nomination/[validatorAddress]/page.tsx
  apps/tangle-dapp/components/ValidatorTable/ValidatorTable.tsx
  apps/tangle-dapp/components/tableCells/HeaderCell.tsx
  apps/tangle-dapp/constants/env.ts
  apps/tangle-dapp/containers/Layout/Layout.tsx
  apps/tangle-dapp/data/NominationsPayouts/useNominations.ts
  apps/tangle-dapp/data/ValidatorTables/useValidators.ts
  apps/tangle-dapp/types/index.ts
Labels: needs review 👓

#2289 fix(tangle-dapp): Improve Balance Display
  apps/tangle-dapp/components/account/Balance.tsx
  apps/tangle-dapp/utils/polkadot/tokens.ts
Labels: needs review 👓

#2291 fix(tangle-dapp): Slow Rendering of Checkboxes When Clicked
  apps/tangle-dapp/components/ValidatorList/ValidatorList.tsx
  apps/tangle-dapp/components/ValidatorList/types.ts
  apps/tangle-dapp/containers/DelegateTxContainer/DelegateTxContainer.tsx
  apps/tangle-dapp/containers/UpdateNominationsTxContainer/SelectValidators.tsx
  apps/tangle-dapp/containers/UpdateNominationsTxContainer/UpdateNominationsTxContainer.tsx
  apps/tangle-dapp/containers/UpdateNominationsTxContainer/types.ts
  libs/webb-ui-components/src/components/Table/TData.tsx
  libs/webb-ui-components/src/components/Table/THeader.tsx
  libs/webb-ui-components/src/components/Table/Table.tsx
  libs/webb-ui-components/src/components/Table/types.ts
Labels: needs review 👓

#2285 feat(tangle-dapp): Backend Integration for Service Info Card and Participants table
  apps/tangle-dapp/app/nomination/[validatorAddress]/InfoCard.tsx
  apps/tangle-dapp/app/nomination/[validatorAddress]/NodeSpecificationsTable.tsx
  apps/tangle-dapp/app/nomination/[validatorAddress]/ServiceTableTabs.tsx
  apps/tangle-dapp/app/nomination/[validatorAddress]/page.tsx
  apps/tangle-dapp/app/services/ActiveServicesTable.tsx
  apps/tangle-dapp/app/services/[serviceId]/InfoCard.tsx
  apps/tangle-dapp/app/services/[serviceId]/JobsListTable.tsx
  apps/tangle-dapp/app/services/[serviceId]/ParticipantsTable.tsx
  apps/tangle-dapp/app/services/[serviceId]/SigningRules.tsx
  apps/tangle-dapp/app/services/[serviceId]/layout.tsx
  apps/tangle-dapp/app/services/[serviceId]/page.tsx
  apps/tangle-dapp/components/ServiceTable/ServiceTable.tsx
  apps/tangle-dapp/containers/BalancesTableContainer/LockedBalanceDetails/DemocracyUnlockingAt.tsx
  apps/tangle-dapp/containers/BalancesTableContainer/LockedBalanceDetails/VestingSchedulesUnlockingAt.tsx
  apps/tangle-dapp/context/ServiceDetailsContext.tsx
  apps/tangle-dapp/data/ServiceDetails/getServiceDetailsInfo.ts
  apps/tangle-dapp/data/ServiceDetails/useServiceParticipants.ts
  apps/tangle-dapp/data/ServiceTables/getActiveServices.ts
  apps/tangle-dapp/data/ServiceTables/index.ts
  apps/tangle-dapp/data/serviceDetails/getSigningRules.ts
  apps/tangle-dapp/data/serviceDetails/index.ts
  apps/tangle-dapp/data/serviceDetails/useServiceDetails.ts
  apps/tangle-dapp/data/serviceDetails/useServiceInfoCard.ts
  apps/tangle-dapp/data/serviceDetails/useServiceJobs.ts
  apps/tangle-dapp/data/serviceDetails/useServiceParticipants.ts
  apps/tangle-dapp/data/serviceOverview/index.ts
  apps/tangle-dapp/data/serviceOverview/useActiveServices.ts
  apps/tangle-dapp/data/useJobIdAndTypeLookupByValidator.ts
  apps/tangle-dapp/data/validatorDetails/useActiveServicesByValidator.ts
  apps/tangle-dapp/data/validatorDetails/useNodeSpecifications.ts
  apps/tangle-dapp/data/validatorDetails/useValidatorInfoCard.ts
  apps/tangle-dapp/hooks/useLocalStorage.ts
  apps/tangle-dapp/types/index.ts
  apps/tangle-dapp/utils/calculateTimeRemaining.ts
  apps/tangle-dapp/utils/getBlockDate.ts
  apps/tangle-dapp/utils/polkadot/identity.ts
  apps/tangle-dapp/utils/polkadot/index.ts
  apps/tangle-dapp/utils/polkadot/nominators.ts
  apps/tangle-dapp/utils/polkadot/services.ts
Labels: needs review 👓

#2294 fix(tangle-dapp): Iterate Tangle dApp May 04 2024
  apps/tangle-dapp/components/KeyStatsItem/KeyStatsItem.tsx
  apps/tangle-dapp/components/ValidatorTable/ValidatorTable.tsx
  apps/tangle-dapp/components/ValidatorTable/types.ts
  apps/tangle-dapp/containers/KeyStatsContainer/ActiveValidatorsKeyStat.tsx
  apps/tangle-dapp/containers/KeyStatsContainer/IdealStakedPercentageKeyStat.tsx
  apps/tangle-dapp/containers/KeyStatsContainer/ValidatorCountKeyStat.tsx
  apps/tangle-dapp/containers/KeyStatsContainer/WaitingValidatorsKeyStat.tsx
  apps/tangle-dapp/containers/ValidatorTablesContainer/ValidatorTablesContainer.tsx
  apps/tangle-dapp/data/KeyStats/useActiveAndDelegationCountSubscription.ts
  apps/tangle-dapp/data/KeyStats/useIdealStakePercentage.ts
  apps/tangle-dapp/data/KeyStats/useValidatorsCountSubscription.ts
  apps/tangle-dapp/data/KeyStats/useWaitingCountSubscription.ts
  apps/tangle-dapp/data/ValidatorTables/useValidators.ts
  apps/tangle-dapp/data/ValidatorTables/useWaitingValidators.ts
  apps/tangle-dapp/data/staking/useActualStakedPercentage.ts
  apps/tangle-dapp/types/index.ts
  libs/dapp-config/src/constants/tangle.ts
  libs/webb-ui-components/src/components/Dropdown/DropdownBody.tsx
  libs/webb-ui-components/src/components/ThemeToggle/ThemeToggle.tsx
  libs/webb-ui-components/src/tailwind.css
  package.json
  yarn.lock
Labels: needs review 👓

#2300 feat(tangle-dapp): Added Loading Account Page
  apps/tangle-dapp/app/loading.tsx
  apps/tangle-dapp/app/page.tsx
  libs/webb-ui-components/src/components/SkeletonLoader/SkeletonLoader.tsx
  libs/webb-ui-components/src/components/SkeletonLoader/utils.ts
  libs/webb-ui-components/src/typography/Typography/Typography.tsx
  libs/webb-ui-components/src/typography/types.ts
Labels: needs review 👓

#2299 style(webb-ui): Remove BreezeSans font and replace by Satoshi by default
  apps/tangle-dapp/containers/Layout/Layout.tsx
  libs/webb-ui-components/src/constants/index.ts
  libs/webb-ui-components/src/css/fonts/BreezeSans-Bold.ttf
  libs/webb-ui-components/src/css/fonts/BreezeSans-Medium.ttf
  libs/webb-ui-components/src/css/fonts/BreezeSans-Regular.ttf
  libs/webb-ui-components/src/css/typography.css
  libs/webb-ui-components/src/fonts/BreezeSans-Bold.ttf
  libs/webb-ui-components/src/fonts/BreezeSans-Medium.ttf
  libs/webb-ui-components/src/fonts/BreezeSans-Regular.ttf
Labels: needs review 👓

#2303 feat(tangle-dapp): Get Permitted Caller for Tangle Dapp
  apps/tangle-dapp/app/services/[serviceId]/DetailTabs.tsx
  apps/tangle-dapp/app/services/[serviceId]/PermittedCaller.tsx
  apps/tangle-dapp/app/services/[serviceId]/SigningRules.tsx
  apps/tangle-dapp/app/services/[serviceId]/page.tsx
  apps/tangle-dapp/data/serviceDetails/getSigningRules.ts
  apps/tangle-dapp/data/serviceDetails/index.ts
  apps/tangle-dapp/data/serviceDetails/usePermittedCaller.ts
  apps/zk-explorer/containers/ProjectDetailTabs/Circuits/client/index.tsx
  libs/webb-ui-components/src/components/CodeFile/CodeFile.tsx
  libs/webb-ui-components/src/components/CodeFile/types.ts
  libs/webb-ui-components/src/components/TableAndChartTabs/TableAndChartTabs.tsx
  libs/webb-ui-components/src/stories/molecules/CodeFile.stories.tsx
  package.json
  yarn.lock
Labels: needs review 👓

#2308 fix(bridge-dapp): Updated Local Chain Ids & Rpc Ports
  apps/bridge-dapp/src/pages/Hubble/Bridge/SelectChain.tsx
  libs/dapp-config/src/chains/evm/index.tsx
  libs/dapp-types/src/EVMChainId.ts
Labels: needs review 👓

#2307 feat(tangle-dapp): Bridge UI on Tangle Dapp
  apps/bridge-dapp/src/components/Header/ActiveChainDropdown.tsx
  apps/bridge-dapp/src/pages/Account/AccountSummaryCard.tsx
  apps/tangle-dapp/app/bridge/AmountAndTokenInput.tsx
  apps/tangle-dapp/app/bridge/BridgeContainer.tsx
  apps/tangle-dapp/app/bridge/ChainSelectors.tsx
  apps/tangle-dapp/app/bridge/layout.tsx
  apps/tangle-dapp/app/bridge/page.tsx
  apps/tangle-dapp/app/bridge/useActionButton.tsx
  apps/tangle-dapp/components/AmountInput/AmountInput.tsx
  apps/tangle-dapp/components/Breadcrumbs/Breadcrumbs.tsx
  apps/tangle-dapp/components/Sidebar/sidebarProps.ts
  apps/tangle-dapp/constants/bridge.ts
  apps/tangle-dapp/context/BridgeContext.tsx
  apps/tangle-dapp/context/RestakeContext.tsx
  apps/tangle-dapp/types/index.ts
  libs/webb-ui-components/src/components/MenuItem/MenuItem.tsx
  libs/webb-ui-components/src/components/buttons/ChainOrTokenButton.tsx
  libs/webb-ui-components/src/components/buttons/index.ts
  libs/webb-ui-components/src/components/buttons/types.ts
  libs/webb-ui-components/src/stories/molecules/ChainButton.stories.tsx
  libs/webb-ui-components/src/stories/molecules/ChainOrTokenButton.stories.tsx
Labels: needs review 👓

#2241 chore(tangle-dapp): Payouts rework
  apps/tangle-dapp/components/NominatorStatsItem/dataHooks.ts
  apps/tangle-dapp/components/PayoutTable/PayoutTable.tsx
  apps/tangle-dapp/components/PayoutTable/types.ts
  apps/tangle-dapp/components/ValidatorList/types.ts
  apps/tangle-dapp/containers/KeyStatsContainer/ActualStakedPercentageKeyStat.tsx
  apps/tangle-dapp/containers/NominationsPayoutsContainer/NominationsPayoutsContainer.tsx
  apps/tangle-dapp/containers/NominatorStatsContainer/NominatorStatsContainer.tsx
  apps/tangle-dapp/data/NominationsPayouts/usePayouts.ts
  apps/tangle-dapp/data/NominatorStats/useTotalPayoutRewards.ts
  apps/tangle-dapp/data/payouts/usePayouts2.ts
  apps/tangle-dapp/data/payouts/usePayoutsAvailability.ts
  apps/tangle-dapp/data/staking/useActualStakedPercentage.ts
  apps/tangle-dapp/data/staking/useHistoryDepth.ts
  apps/tangle-dapp/hooks/usePolkadotApi.ts
  apps/tangle-dapp/types/index.ts
  apps/tangle-dapp/utils/getExposureMap.ts
  libs/dapp-config/src/constants/tangle.ts
  libs/webb-ui-components/src/constants/networks.ts
  package.json
  yarn.lock
Labels: tangle-dapp

#2315 chore(tangle-dapp): add payouts loading state & use TokenAmountCell
  apps/tangle-dapp/components/PayoutTable/PayoutTable.tsx
  apps/tangle-dapp/containers/NominationsPayoutsContainer/NominationsPayoutsContainer.tsx
  apps/tangle-dapp/data/NominationsPayouts/usePayouts.ts
  apps/tangle-dapp/data/payouts/usePayouts2.ts
  apps/tangle-dapp/types/index.ts
Labels: tangle-dapp

#2311 feat(tangle-dapp): Switch chains in EVM wallets when switching networks
  apps/tangle-dapp/app/services/[serviceId]/JobsListTable.tsx
  apps/tangle-dapp/components/NetworkSelector/NetworkSelectorDropdown.tsx
  apps/tangle-dapp/hooks/useNetworkState.ts
Labels: tangle-dapp

#2322 chore (tangle-dapp): Fix console error
  libs/icons/src/TangleIcon.tsx
Labels: needs review 👓

#2314 feat(tangle-dapp): Update Substrate wallet metadata when appropriate
  apps/tangle-dapp/components/NetworkSelector/CustomRpcEndpointInput.tsx
  apps/tangle-dapp/components/UpdateMetadataButton.tsx
  apps/tangle-dapp/containers/BalancesTableContainer/BalancesTableContainer.tsx
  apps/tangle-dapp/containers/Layout/FeedbackBanner.tsx
  apps/tangle-dapp/containers/Layout/Layout.tsx
  apps/tangle-dapp/containers/NominationsPayoutsContainer/NominationsPayoutsContainer.tsx
  apps/tangle-dapp/containers/WalletAndChainContainer/WalletAndChainContainer.tsx
  apps/tangle-dapp/data/KeyStats/useActiveAndDelegationCountSubscription.ts
  apps/tangle-dapp/data/KeyStats/useIdealStakePercentage.ts
  apps/tangle-dapp/data/KeyStats/useValidatorsCountSubscription.ts
  apps/tangle-dapp/data/KeyStats/useWaitingCountSubscription.ts
  apps/tangle-dapp/data/NominationsPayouts/usePayouts.ts
  apps/tangle-dapp/data/NominatorStats/useTotalPayoutRewards.ts
  apps/tangle-dapp/data/payouts/usePayoutsAvailability.ts
  apps/tangle-dapp/data/staking/useActualStakedPercentage.ts
  apps/tangle-dapp/data/staking/useHistoryDepth.ts
  apps/tangle-dapp/hooks/useActiveAccountAddress.ts
  apps/tangle-dapp/hooks/useAgnosticTx.ts
  apps/tangle-dapp/hooks/useLocalStorage.ts
  apps/tangle-dapp/hooks/useNetworkState.ts
  apps/tangle-dapp/hooks/usePolkadotApi.ts
  apps/tangle-dapp/hooks/useSubstrateTx.ts
  apps/tangle-dapp/hooks/useTxNotification.tsx
  apps/tangle-dapp/utils/Optional.ts
  apps/tangle-dapp/utils/polkadot/api.ts
Labels: tangle-dapp

#2324 feat(tangle-dapp): Show longest vesting schedule info
  apps/tangle-dapp/containers/BalancesTableContainer/BalancesTableContainer.tsx
  apps/tangle-dapp/containers/BalancesTableContainer/useLongestVestingScheduleTime.ts
  apps/tangle-dapp/data/vesting/useVestingInfo.ts
Labels: tangle-dapp

#2323 docs(tangle-dapp): Update OpenGraph metadata and images
  apps/tangle-dapp/constants/openGraph.ts
  apps/tangle-dapp/containers/BalancesTableContainer/BalancesTableContainer.tsx
  apps/tangle-dapp/containers/Layout/FeedbackBanner.tsx
  apps/tangle-dapp/hooks/useNetworkState.ts
  apps/tangle-dapp/hooks/useSubstrateTx.ts
  apps/tangle-dapp/public/static/opengraph/claim-airdrop.png
  apps/tangle-dapp/public/static/opengraph/default.png
  apps/tangle-dapp/public/static/opengraph/nomination.png
Labels: tangle-dapp

#2329 feat(tangle-dapp): Setup the code logic to handle different scenarios of bridging
  apps/tangle-dapp/app/bridge/AmountAndTokenInput.tsx
  apps/tangle-dapp/app/bridge/ChainSelectors.tsx
  apps/tangle-dapp/app/bridge/hooks/useBridgeType.ts
  apps/tangle-dapp/constants/bridge.ts
  apps/tangle-dapp/context/BridgeContext.tsx
  apps/tangle-dapp/types/bridge.ts
  apps/tangle-dapp/types/index.ts
  libs/webb-ui-components/src/components/buttons/ChainOrTokenButton.tsx
Labels: needs review 👓

#2335 fix(tangle-dapp): Payouts reward calculation & Readme updates
  .github/assets/tangle-banner.png
  apps/hubble-stats/README.md
  apps/tangle-dapp/README.md
  apps/tangle-dapp/components/PayoutTable/PayoutTable.tsx
  apps/tangle-dapp/components/tableCells/TokenAmountCell.tsx
  apps/tangle-dapp/containers/NominationsPayoutsContainer/NominationsPayoutsContainer.tsx
  apps/tangle-dapp/containers/NominatorStatsContainer/NominatorStatsContainer.tsx
  apps/tangle-dapp/data/KeyStats/useInflationPercentage.ts
  apps/tangle-dapp/data/NominationsPayouts/usePayouts.ts
  apps/tangle-dapp/data/NominatorStats/useTotalPayoutRewards.ts
  apps/tangle-dapp/data/payouts/usePayoutsAvailability.ts
  apps/tangle-dapp/data/staking/useActualStakedPercentage.ts
  apps/tangle-dapp/hooks/useLocalStorage.ts
  apps/zk-explorer/README.md
  yarn.lock
Labels: tangle-dapp

#2350 fix(tangle-dapp): sorting fix & payout dest modal layout update
  .yarnrc
  apps/tangle-dapp/components/ValidatorSelectionTable/ValidatorSelectionTable.tsx
  apps/tangle-dapp/containers/UpdatePayeeTxContainer/UpdatePayee.tsx
  apps/tangle-dapp/containers/UpdatePayeeTxContainer/UpdatePayeeTxContainer.tsx
  apps/tangle-dapp/containers/UpdatePayeeTxContainer/types.ts
  libs/webb-ui-components/src/components/DropdownField/DropdownField.tsx
  libs/webb-ui-components/src/components/DropdownField/types.ts
  yarn.lock
Labels: needs review 👓, tangle-dapp
