Repository tangle-network/dapp, pull requests merged in 2024-01, with the labels that each got.

#1930 Implement ZK Explorer's user dashboard page design
  .gitignore
  apps/zk-explorer/app/dashboard/page.tsx
  apps/zk-explorer/app/page.tsx
  apps/zk-explorer/app/providers.tsx
  apps/zk-explorer/components/DashboardOverviewTab.tsx
  apps/zk-explorer/components/DashboardSettingsTab.tsx
  apps/zk-explorer/components/DashboardTabs.tsx
  apps/zk-explorer/components/FilterAndSortBy.tsx
  apps/zk-explorer/components/Filters/Filters.tsx
  apps/zk-explorer/components/GitHubOAuthButton/GitHubOAuthButton.tsx
  apps/zk-explorer/components/Header.tsx
  apps/zk-explorer/components/HeaderControls.tsx
  apps/zk-explorer/components/HomepageInteractiveContents.tsx
  apps/zk-explorer/components/ItemGrid.tsx
  apps/zk-explorer/components/LargeSquareAvatar.tsx
  apps/zk-explorer/components/LinkCard.tsx
  apps/zk-explorer/components/OverlayMask.tsx
  apps/zk-explorer/components/ProjectSubmissionControls.tsx
  apps/zk-explorer/components/SearchInput.tsx
  apps/zk-explorer/components/SidebarCloseButton.tsx
  apps/zk-explorer/components/SmallChip.tsx
  apps/zk-explorer/components/SubmitPageControls.tsx
  apps/zk-explorer/components/Tabs.tsx
  apps/zk-explorer/constants/index.ts
  apps/zk-explorer/constants/mock.ts
  apps/zk-explorer/hooks/useAuth.tsx
  apps/zk-explorer/hooks/useTabs.ts
  apps/zk-explorer/utils/api.ts
  apps/zk-explorer/utils/index.ts
  apps/zk-explorer/utils/utils.ts
Labels: needs review 👓

#1928 Circuit Sidebar for Project Detail page on ZK Explorer
  apps/zk-explorer/containers/ProjectDetailTabsContainer/Circuits/client/CodeFile.tsx
  apps/zk-explorer/containers/ProjectDetailTabsContainer/Circuits/client/Header.tsx
  apps/zk-explorer/containers/ProjectDetailTabsContainer/Circuits/client/NavSideBar.tsx
  apps/zk-explorer/containers/ProjectDetailTabsContainer/Circuits/client/index.tsx
  apps/zk-explorer/containers/ProjectDetailTabsContainer/ProjectDetailTabsContainer.tsx
  apps/zk-explorer/server/getProjectCircuitsData.ts
  apps/zk-explorer/server/index.ts
  apps/zk-explorer/styles/globals.css
  libs/icons/src/FileLine.tsx
  libs/icons/src/FolderFill.tsx
  libs/icons/src/FolderOpenFill.tsx
  libs/icons/src/SideBarLine.tsx
  libs/icons/src/index.ts
  package.json
  yarn.lock
Labels: needs review 👓

#1929 EVM Staking - Validator Tables & Selection updates
  apps/tangle-dapp/components/DelegatorTable/DelegatorTable.tsx
  apps/tangle-dapp/components/ValidatorList/ValidatorList.tsx
  apps/tangle-dapp/constants/polkadot.ts
  apps/tangle-dapp/containers/DelegateTxContainer/DelegateTxContainer.tsx
  apps/tangle-dapp/containers/DelegateTxContainer/SelectDelegates.tsx
  apps/tangle-dapp/containers/UpdateNominationsTxContainer/SelectValidators.tsx
  apps/tangle-dapp/containers/UpdateNominationsTxContainer/UpdateNominationsTxContainer.tsx
  apps/tangle-dapp/containers/ValidatorTablesContainer/ValidatorTablesContainer.tsx
  apps/tangle-dapp/data/ValidatorTables/getActiveValidators.ts
  apps/tangle-dapp/data/ValidatorTables/getWaitingValidators.ts
  apps/tangle-dapp/hooks/useAllValidatorsData.ts
  apps/tangle-dapp/hooks/useMaxNominationQuota.ts
  apps/tangle-dapp/types/index.ts
  libs/dapp-config/src/chains/evm/index.tsx
  libs/dapp-types/src/ChainId.ts
  libs/dapp-types/src/EVMChainId.ts
Labels: needs review 👓, tangle-dapp

#1932 Code Area Section for Project Detail page on ZK Explorer
  apps/zk-explorer/containers/ProjectDetailTabsContainer/Circuits/client/CodeFile.tsx
  apps/zk-explorer/containers/ProjectDetailTabsContainer/Circuits/client/Header.tsx
  apps/zk-explorer/containers/ProjectDetailTabsContainer/Circuits/client/index.tsx
  apps/zk-explorer/containers/ProjectDetailTabsContainer/ProjectDetailTabsContainer.tsx
  apps/zk-explorer/server/getProjectCircuitsData.ts
  apps/zk-explorer/styles/globals.css
  package.json
  yarn.lock
Labels: needs review 👓

#1933 EVM Staking - Stop (Staking.chill) nomination flow
  apps/tangle-dapp/constants/evm.ts
  apps/tangle-dapp/containers/DelegationsPayoutsContainer/DelegationsPayoutsContainer.tsx
  apps/tangle-dapp/containers/StopNominationTxContainer/StopNominationTxContainer.tsx
  apps/tangle-dapp/containers/StopNominationTxContainer/index.ts
  apps/tangle-dapp/containers/StopNominationTxContainer/types.ts
  libs/icons/src/ProhibitedLineIcon.tsx
  libs/icons/src/index.ts
  yarn.lock
Labels: needs review 👓, tangle-dapp

#1940 Update testnet RPC endpoints and opt out data cache
  apps/testnet-leaderboard/components/RankingTableSection/fetchLeaderboardData.ts
  libs/dapp-config/src/chains/evm/index.tsx
  libs/dapp-config/src/chains/substrate/index.tsx
  libs/webb-ui-components/src/constants/index.ts
Labels: needs review 👓

#1944 feat(tangle-dapp): Withdraw Unbonded Token Flow, UI Changes & Minor Fixes
  apps/tangle-dapp/components/BondedTokensBalanceInfo/BondedTokensBalanceInfo.tsx
  apps/tangle-dapp/components/BondedTokensBalanceInfo/index.ts
  apps/tangle-dapp/components/BondedTokensBalanceInfo/types.ts
  apps/tangle-dapp/components/DelegatorTable/DelegatorTable.tsx
  apps/tangle-dapp/components/InfoIconWithTooltip/InfoIconWithTooltip.tsx
  apps/tangle-dapp/components/ValidatorTable/ValidatorTable.tsx
  apps/tangle-dapp/components/index.ts
  apps/tangle-dapp/components/sideBar/sideBarProps.ts
  apps/tangle-dapp/constants/evm.ts
  apps/tangle-dapp/constants/polkadot.ts
  apps/tangle-dapp/containers/BondMoreTxContainer/BondMoreTxContainer.tsx
  apps/tangle-dapp/containers/BondMoreTxContainer/BondTokens.tsx
  apps/tangle-dapp/containers/BondMoreTxContainer/types.ts
  apps/tangle-dapp/containers/DelegateTxContainer/DelegateTxContainer.tsx
  apps/tangle-dapp/containers/NominatorStatsContainer/NominatorStatsContainer.tsx
  apps/tangle-dapp/containers/RebondTxContainer/RebondTokens.tsx
  apps/tangle-dapp/containers/RebondTxContainer/RebondTxContainer.tsx
  apps/tangle-dapp/containers/RebondTxContainer/types.ts
  apps/tangle-dapp/containers/UnbondTxContainer/UnbondTokens.tsx
  apps/tangle-dapp/containers/UnbondTxContainer/UnbondTxContainer.tsx
  apps/tangle-dapp/containers/UnbondTxContainer/types.ts
  apps/tangle-dapp/containers/UpdatePayeeTxContainer/UpdatePayeeTxContainer.tsx
  apps/tangle-dapp/containers/WithdrawUnbondedTxContainer/WithdrawUnbonded.tsx
  apps/tangle-dapp/containers/WithdrawUnbondedTxContainer/WithdrawUnbondedTxContainer.tsx
  apps/tangle-dapp/containers/WithdrawUnbondedTxContainer/index.ts
  apps/tangle-dapp/containers/WithdrawUnbondedTxContainer/types.ts
  apps/tangle-dapp/containers/index.ts
  apps/tangle-dapp/data/KeyStats/useInflationPercentage.ts
  apps/tangle-dapp/data/NominatorStats/useTotalUnbondedAndUnbondingAmount.ts
  apps/tangle-dapp/utils/calculateInflation.ts
  libs/dapp-config/src/chains/evm/index.tsx
  libs/dapp-config/src/chains/substrate/index.tsx
  libs/dapp-types/src/ChainId.ts
  libs/dapp-types/src/EVMChainId.ts
  libs/icons/src/LockUnlockLineIcon.tsx
  libs/icons/src/index.ts
  libs/webb-ui-components/src/constants/index.ts
Labels: needs review 👓, tangle-dapp

#1945 GitHub section collapsible on Project Detail Page on Zk Explorer
  apps/zk-explorer/app/layout.tsx
  apps/zk-explorer/app/project/[owner]/[name]/page.tsx
  apps/zk-explorer/constants/index.ts
  apps/zk-explorer/containers/ProjectGitHubInfoContainer/ProjectGitHubInfoContainer.tsx
  apps/zk-explorer/containers/ProjectGitHubInfoContainer/client/index.tsx
  apps/zk-explorer/server/getProjectGitHubInfoContainerData.ts
  apps/zk-explorer/server/index.ts
Labels: needs review 👓

#1942 feat(zk-explorer): Implement design and functionality of Proof Generation page
  apps/zk-explorer/app/project/[owner]/[name]/[circuit]/page.tsx
  apps/zk-explorer/app/providers.tsx
  apps/zk-explorer/app/submit/page.tsx
  apps/zk-explorer/components/DashboardOverviewTab.tsx
  apps/zk-explorer/components/FeedbackCard.tsx
  apps/zk-explorer/components/HeaderControls.tsx
  apps/zk-explorer/components/LinkCard.tsx
  apps/zk-explorer/components/ProofGenerationInteractiveContents.tsx
  apps/zk-explorer/components/ProofGenerationStepCards/index.tsx
  apps/zk-explorer/components/ProofGenerationStepCards/types.ts
  apps/zk-explorer/components/RadioCard.tsx
  apps/zk-explorer/components/RunCircuitServiceModalTrigger.tsx
  apps/zk-explorer/components/SocialChip.tsx
  apps/zk-explorer/components/StepTrackerSidebar.tsx
  apps/zk-explorer/constants/index.ts
  apps/zk-explorer/constants/mock.ts
  apps/zk-explorer/containers/ProjectHeaderContainer/ProjectHeaderContainer.tsx
  apps/zk-explorer/hooks/useAuth.tsx
  apps/zk-explorer/utils/api.ts
  apps/zk-explorer/utils/utils.ts
Labels: feature ➕, needs review 👓

#1947 chore: Re-integrate `husky` and `commitlint` which were accidentally deleted
  .github/CONTRIBUTING.md
  .husky/commit-msg
  .husky/pre-push
  README.md
  commitlint.config.js
  package.json
  yarn.lock
Labels: needs review 👓

#1954 feat(zk-explorer): Link `Run Service` modal to Proof Generation page
  .github/PULL_REQUEST_TEMPLATE.md
  apps/zk-explorer/components/CardTabs.tsx
  apps/zk-explorer/components/Header.tsx
  apps/zk-explorer/components/HeaderControls.tsx
  apps/zk-explorer/components/HomepageInteractiveContents.tsx
  apps/zk-explorer/components/ItemGrid.tsx
  apps/zk-explorer/components/ProofGenerationInteractiveContents.tsx
  apps/zk-explorer/components/ProofGenerationStepCards/index.tsx
  apps/zk-explorer/components/RadioCard.tsx
  apps/zk-explorer/components/RunCircuitServiceModalTrigger.tsx
  apps/zk-explorer/components/SearchInput.tsx
  apps/zk-explorer/components/SubmitPageControls.tsx
  apps/zk-explorer/constants/mock.ts
  apps/zk-explorer/containers/ProjectHeaderContainer/ProjectHeaderContainer.tsx
  apps/zk-explorer/hooks/useFilterConstraints.ts
  apps/zk-explorer/utils/api.ts
  apps/zk-explorer/utils/index.ts
  apps/zk-explorer/utils/utils.ts
  package.json
  yarn.lock
Labels: needs review 👓

#1963 refactor(testnet-leaderboard): Refactor to Server-side Pagination & Filtering
  apps/testnet-leaderboard/components/RankingTableSection/IdentityCell.tsx
  apps/testnet-leaderboard/components/RankingTableSection/RankingTableView.tsx
  apps/testnet-leaderboard/components/RankingTableSection/SWRProvider.tsx
  apps/testnet-leaderboard/components/RankingTableSection/index.tsx
  apps/testnet-leaderboard/components/RankingTableSection/utils.ts
  apps/testnet-leaderboard/constants/index.ts
Labels: needs review 👓

#1965 Connect substrate wallet in tangle-dapp
  apps/tangle-dapp/app/page.tsx
  apps/tangle-dapp/components/KeyStatsItem/KeyStatsText.tsx
  apps/tangle-dapp/components/WalletDropdown/WalletDropdown.tsx
  apps/tangle-dapp/containers/DelegateTxContainer/DelegateTxContainer.tsx
  apps/tangle-dapp/containers/DelegationsPayoutsContainer/DelegationsPayoutsContainer.tsx
  apps/tangle-dapp/containers/NominatorStatsContainer/NominatorStatsContainer.tsx
  apps/tangle-dapp/containers/RebondTxContainer/RebondTxContainer.tsx
  apps/tangle-dapp/containers/StopNominationTxContainer/StopNominationTxContainer.tsx
  apps/tangle-dapp/containers/UnbondTxContainer/UnbondTxContainer.tsx
  apps/tangle-dapp/containers/UpdatePayeeTxContainer/UpdatePayeeTxContainer.tsx
  apps/tangle-dapp/containers/WalletAndChainContainer/WalletAndChainContainer.tsx
  apps/tangle-dapp/containers/WalletModalContainer/WalletModalContainer.tsx
  apps/tangle-dapp/containers/WithdrawUnbondedTxContainer/WithdrawUnbondedTxContainer.tsx
  apps/tangle-dapp/data/NominatorStats/useTokenWalletBalance.ts
  apps/tangle-dapp/utils/convertEthereumToSubstrateAddress.ts
  apps/tangle-dapp/utils/convertToSubstrateAddress.ts
  apps/tangle-dapp/utils/index.ts
  libs/api-provider-environment/src/ConnectWallet/index.ts
  libs/dapp-config/src/wallets/wallets-config.tsx
  libs/webb-ui-components/src/components/WalletModal/WalletModal.tsx
  libs/webb-ui-components/src/components/WalletModal/types.ts
Labels: needs review 👓

#1962 feat(zk-explorer): Implement breadcrumbs
  apps/zk-explorer/components/ComputedBreadcrumbs.tsx
  apps/zk-explorer/components/Header.tsx
  apps/zk-explorer/components/SearchInput.tsx
  apps/zk-explorer/containers/ProjectHeader.tsx
  apps/zk-explorer/hooks/useAuth.tsx
  apps/zk-explorer/utils/index.ts
Labels: feature ➕, needs review 👓
