Repository tangle-network/dapp, pull requests merged in 2024-07, with the labels that each got.

#2399 feat(tangle-dapp): Tx from Substrate Chains + showing Tx Progress
  apps/bridge-dapp/src/components/Header/TxProgressDropdown/TxItem.tsx
  apps/tangle-dapp/app/bridge/BridgeConfirmationModal.tsx
  apps/tangle-dapp/app/bridge/ChainSelectors.tsx
  apps/tangle-dapp/app/bridge/hooks/useActionButton.ts
  apps/tangle-dapp/app/bridge/hooks/useAmountInDecimals.ts
  apps/tangle-dapp/app/bridge/hooks/useBridgeFee.ts
  apps/tangle-dapp/app/bridge/hooks/useBridgeTransfer.ts
  apps/tangle-dapp/app/bridge/hooks/useEstimatedGasFee.ts
  apps/tangle-dapp/app/bridge/hooks/useFormattedAmountForSygmaTx.ts
  apps/tangle-dapp/app/providers.tsx
  apps/tangle-dapp/components/AmountInput/AmountInput.tsx
  apps/tangle-dapp/components/BridgeTxQueueDropdown/BridgeTxQueueItem.tsx
  apps/tangle-dapp/components/BridgeTxQueueDropdown/index.tsx
  apps/tangle-dapp/components/LiquidStaking/LiquidStakingInput.tsx
  apps/tangle-dapp/components/UpdateMetadataButton.tsx
  apps/tangle-dapp/components/index.ts
  apps/tangle-dapp/constants/bridge.ts
  apps/tangle-dapp/containers/Layout/Layout.tsx
  apps/tangle-dapp/context/BridgeContext.tsx
  apps/tangle-dapp/context/BridgeTxQueueContext.tsx
  apps/tangle-dapp/data/balances/useTransferTx.ts
  apps/tangle-dapp/hooks/useInputAmount.ts
  apps/tangle-dapp/hooks/useLocalStorage.ts
  apps/tangle-dapp/hooks/useSubstrateInjectedExtension.ts
  apps/tangle-dapp/hooks/useSubstrateTx.ts
  apps/tangle-dapp/types/bridge.ts
  libs/api-provider-environment/src/transaction/useTransactionQueue.tsx
  libs/dapp-config/src/chains/evm/index.tsx
  libs/webb-ui-components/src/components/ChainChip/utils.ts
  libs/webb-ui-components/src/components/Input/Input.tsx
  libs/webb-ui-components/src/components/TxProgressor/TxProgressor.tsx
  libs/webb-ui-components/src/components/TxProgressor/types.ts
Labels: needs changes 🔧

#2413 fix(tangle-dapp): Fix Amount Input
  apps/tangle-dapp/hooks/useInputAmount.ts
Labels: needs review 👓

#2416 feat(tangle-dapp): Add `robots.txt` to optimzie SEO
  apps/tangle-dapp/app/robots.txt
Labels: needs review 👓

#2420 [RELEASE] tangle-dapp v0.0.10
  .github/actions/create-release/gh-release-script.js
  apps/tangle-dapp/CHANGELOG.md
  apps/tangle-dapp/package.json
Labels: needs review 👓

#2427 fix(tangle-dapp): Fix Timed Out Error
  apps/tangle-dapp/app/api/hello/route.ts
  apps/tangle-dapp/app/claim/layout.tsx
  apps/tangle-dapp/app/claim/page.tsx
  apps/tangle-dapp/app/layout.tsx
  apps/tangle-dapp/app/nomination/[validatorAddress]/page.tsx
  apps/tangle-dapp/app/nomination/layout.tsx
  apps/tangle-dapp/app/nomination/page.tsx
  apps/tangle-dapp/app/page.tsx
Labels: needs review 👓

#2432 [RELEASE] tangle-dapp v0.0.11
  apps/tangle-dapp/CHANGELOG.md
  apps/tangle-dapp/package.json
Labels: needs review 👓

#2419 feat(tangle-dapp): Implementation of Bridge from EVM chain
  apps/bridge-dapp/src/components/Header/TxProgressDropdown/TxItem.tsx
  apps/tangle-dapp/app/bridge/AmountAndTokenInput.tsx
  apps/tangle-dapp/app/bridge/BridgeConfirmationModal.tsx
  apps/tangle-dapp/app/bridge/BridgeContainer.tsx
  apps/tangle-dapp/app/bridge/FeeDetails.tsx
  apps/tangle-dapp/app/bridge/hooks/useActionButton.ts
  apps/tangle-dapp/app/bridge/hooks/useAmountInDecimals.ts
  apps/tangle-dapp/app/bridge/hooks/useBridgeFee.ts
  apps/tangle-dapp/app/bridge/hooks/useBridgeTransfer.ts
  apps/tangle-dapp/app/bridge/hooks/useEstimatedGasFee.ts
  apps/tangle-dapp/app/bridge/lib/transfer/sygmaEvm.ts
  apps/tangle-dapp/components/BridgeTxQueueDropdown/BridgeTxQueueItem.tsx
  apps/tangle-dapp/components/BridgeTxQueueDropdown/index.tsx
  apps/tangle-dapp/components/NetworkSelector/NetworkSelectionButton.tsx
  apps/tangle-dapp/containers/Layout/Layout.tsx
  apps/tangle-dapp/containers/WalletModalContainer/WalletModalContainer.tsx
  apps/tangle-dapp/context/BridgeContext.tsx
  apps/tangle-dapp/context/BridgeTxQueueContext.tsx
  apps/tangle-dapp/hooks/useNetworkSwitcher.ts
  apps/tangle-dapp/index.d.ts
  apps/tangle-dapp/tsconfig.json
  apps/tangle-dapp/types/bridge.ts
  libs/dapp-types/src/SubstrateChainId.ts
  libs/icons/src/Alert.tsx
  libs/webb-ui-components/src/components/FeeDetails/FeeDetails.tsx
  libs/webb-ui-components/src/components/TxProgressor/TxProgressor.tsx
  libs/webb-ui-components/src/components/TxProgressor/types.ts
  libs/webb-ui-components/src/constants/networks.ts
  libs/webb-ui-components/src/containers/ConfirmationCard/DepositConfirm.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/TransferConfirm.tsx
  libs/webb-ui-components/src/containers/ConfirmationCard/WithdrawConfirm.tsx
  libs/webb-ui-components/src/next-utils/index.ts
  libs/webb-ui-components/src/next-utils/useLayoutBgClassName.ts
Labels: needs review 👓

#2406 feat(tangle-dapp): Stake Operation Table UI & Logic
  apps/tangle-dapp/app/liquid-staking/[tokenSymbol]/page.tsx
  apps/tangle-dapp/app/services/[serviceId]/JobsListTable.tsx
  apps/tangle-dapp/components/LiquidStaking/LiquidStakeCard.tsx
  apps/tangle-dapp/components/LiquidStaking/LiquidStakingSelectionTable.tsx
  apps/tangle-dapp/components/LiquidStaking/StakingItemExternalLinkButton.tsx
  apps/tangle-dapp/components/LiquidStaking/UnstakeRequestsTable.tsx
  apps/tangle-dapp/components/tableCells/HeaderCell.tsx
  apps/tangle-dapp/constants/liquidStaking.ts
  apps/tangle-dapp/data/liquidStaking/helper.ts
  apps/tangle-dapp/data/liquidStaking/store.ts
  apps/tangle-dapp/data/liquidStaking/useLiquidStakingItems.ts
  apps/tangle-dapp/hooks/LiquidStaking/useLiquidStakingSelectionTableColumns.tsx
  apps/tangle-dapp/hooks/useLSTokenSVGs.ts
  apps/tangle-dapp/hooks/useLocalStorage.ts
  apps/tangle-dapp/tailwind.config.js
  apps/tangle-dapp/types/astarDappStaking.ts
  apps/tangle-dapp/types/liquidStaking.ts
  libs/icons/src/LineChartIcon.tsx
  libs/icons/src/index.ts
  libs/webb-ui-components/src/assets/body-bg-dark-large.jpeg
  libs/webb-ui-components/src/assets/body-bg-dark.jpeg
  libs/webb-ui-components/src/assets/body-bg-dark.jpg
  libs/webb-ui-components/src/assets/body-bg-large.jpeg
  libs/webb-ui-components/src/assets/body-bg.jpeg
  libs/webb-ui-components/src/assets/body-bg.jpg
  libs/webb-ui-components/src/assets/ls-bg-dark.jpeg
  libs/webb-ui-components/src/assets/ls-bg.jpeg
  libs/webb-ui-components/src/components/Table/Table.tsx
  libs/webb-ui-components/src/tailwind.css
Labels: tangle-dapp

#2462 perf(repo): Disabled Unused Targets
  apps/bridge-dapp/project.json
  apps/zk-explorer/project.json
Labels: needs review 👓

#2461 fix(tangle-dapp): Fix payout modal overflowing
  apps/tangle-dapp/containers/PayoutAllTxContainer/PayoutAllTxContainer.tsx
Labels: needs review 👓

#2456 [RELEASE] tangle-dapp v0.0.12
  apps/tangle-dapp/CHANGELOG.md
  apps/tangle-dapp/package.json
Labels: needs review 👓

#2481 [RELEASE] tangle-dapp v0.0.13 released to fix CI issues
  apps/tangle-dapp/CHANGELOG.md
  apps/tangle-dapp/app/restake/_layout.tsx
  apps/tangle-dapp/app/restake/_page.tsx
  apps/tangle-dapp/app/restake/deposit/_page.tsx
  apps/tangle-dapp/app/restake/stake/_page.tsx
  apps/tangle-dapp/package.json
Labels: needs review 👓

#2453 feat(tangle-dapp): Implement unstake requests table
  apps/tangle-dapp/app/liquid-staking/[tokenSymbol]/page.tsx
  apps/tangle-dapp/app/liquid-staking/page.tsx
  apps/tangle-dapp/app/restake/TabListItem.tsx
  apps/tangle-dapp/components/Breadcrumbs/utils.tsx
  apps/tangle-dapp/components/LiquidStaking/AddressLink.tsx
  apps/tangle-dapp/components/LiquidStaking/AvailableWithdrawCard.tsx
  apps/tangle-dapp/components/LiquidStaking/LiquidStakeAndUnstakeCards.tsx
  apps/tangle-dapp/components/LiquidStaking/TableRowsSkeleton.tsx
  apps/tangle-dapp/components/LiquidStaking/UnstakeRequestsTable.tsx
  apps/tangle-dapp/components/LiquidStaking/stakeAndUnstake/ChainLogo.tsx
  apps/tangle-dapp/components/LiquidStaking/stakeAndUnstake/DetailItem.tsx
  apps/tangle-dapp/components/LiquidStaking/stakeAndUnstake/DropdownChevronIcon.tsx
  apps/tangle-dapp/components/LiquidStaking/stakeAndUnstake/ExchangeRateDetailItem.tsx
  apps/tangle-dapp/components/LiquidStaking/stakeAndUnstake/LiquidStakeCard.tsx
  apps/tangle-dapp/components/LiquidStaking/stakeAndUnstake/LiquidStakingInput.tsx
  apps/tangle-dapp/components/LiquidStaking/stakeAndUnstake/LiquidStakingTokenItem.tsx
  apps/tangle-dapp/components/LiquidStaking/stakeAndUnstake/LiquidUnstakeCard.tsx
  apps/tangle-dapp/components/LiquidStaking/stakeAndUnstake/MintAndRedeemFeeDetailItem.tsx
  apps/tangle-dapp/components/LiquidStaking/stakeAndUnstake/ParachainWalletBalance.tsx
  apps/tangle-dapp/components/LiquidStaking/stakeAndUnstake/SelectTokenModal.tsx
  apps/tangle-dapp/components/LiquidStaking/stakeAndUnstake/SelectValidatorsButton.tsx
  apps/tangle-dapp/components/LiquidStaking/stakeAndUnstake/TokenChip.tsx
  apps/tangle-dapp/components/LiquidStaking/stakeAndUnstake/UnstakePeriodDetailItem.tsx
  apps/tangle-dapp/components/LiquidStaking/stakeAndUnstake/UnstakeRequestSubmittedModal.tsx
  apps/tangle-dapp/components/LiquidStaking/unstakeRequestsTable/CancelUnstakeModal.tsx
  apps/tangle-dapp/components/LiquidStaking/unstakeRequestsTable/RebondLstUnstakeRequestButton.tsx
  apps/tangle-dapp/components/LiquidStaking/unstakeRequestsTable/UnstakeRequestsTable.tsx
  apps/tangle-dapp/components/LiquidStaking/unstakeRequestsTable/WithdrawLstUnstakeRequestButton.tsx
  apps/tangle-dapp/components/LiquidStaking/unstakeRequestsTable/WithdrawalConfirmationModal.tsx
  apps/tangle-dapp/components/LiquidStaking/unstakeRequestsTable/useLstUnlockRequestTableRows.ts
  apps/tangle-dapp/components/tableCells/TokenAmountCell.tsx
  apps/tangle-dapp/constants/index.ts
  apps/tangle-dapp/constants/liquidStaking.ts
  apps/tangle-dapp/containers/NominatorStatsContainer/NominatorStatsContainer.tsx
  apps/tangle-dapp/data/NominatorStats/useTotalPayoutRewards.ts
  apps/tangle-dapp/data/liquidStaking/getValueOfTangleCurrency.ts
  apps/tangle-dapp/data/liquidStaking/store.ts
  apps/tangle-dapp/data/liquidStaking/useDelegationsOccupiedStatus.ts
  apps/tangle-dapp/data/liquidStaking/useExchangeRate.ts
  apps/tangle-dapp/data/liquidStaking/useLiquidStakingItems.ts
  apps/tangle-dapp/data/liquidStaking/useLstRebondTx.ts
  apps/tangle-dapp/data/liquidStaking/useLstUnlockRequests.ts
  apps/tangle-dapp/data/liquidStaking/useLstWithdrawRedeemTx.ts
  apps/tangle-dapp/data/liquidStaking/useMintTx.ts
  apps/tangle-dapp/data/liquidStaking/useOngoingTimeUnits.ts
  apps/tangle-dapp/data/liquidStaking/useRedeemTx.ts
  apps/tangle-dapp/data/liquidStaking/useTokenUnlockLedger.ts
  apps/tangle-dapp/hooks/useSubstrateTx.ts
  apps/tangle-dapp/hooks/useTxNotification.tsx
  apps/tangle-dapp/utils/compareSubstrateAddresses.ts
  apps/tangle-dapp/utils/liquidStaking/getValueOfTangleTimeUnit.ts
  apps/tangle-dapp/utils/liquidStaking/performTimeUnitOp.ts
  apps/tangle-dapp/utils/liquidStaking/tangleTimeUnitToSimpleInstance.ts
  apps/tangle-dapp/utils/liquidStaking/timeUnitToMilliseconds.ts
  apps/tangle-dapp/utils/toSubstrateAddress.ts
  libs/api-provider-environment/src/OFACFilterProvider.tsx
Labels: tangle-dapp

#2490 fix(tangle-dapp): Fix payouts batch limit and SS58 prefix bugs
  apps/tangle-dapp/app/bridge/hooks/useActionButton.ts
  apps/tangle-dapp/app/claim/EligibleSection.tsx
  apps/tangle-dapp/app/claim/NotEligibleSection.tsx
  apps/tangle-dapp/app/claim/page.tsx
  apps/tangle-dapp/app/services/WhatIsRestakingCard.tsx
  apps/tangle-dapp/components/Breadcrumbs/utils.tsx
  apps/tangle-dapp/components/ServiceTable/ServiceTable.tsx
  apps/tangle-dapp/components/ValidatorTable/ValidatorTable.tsx
  apps/tangle-dapp/components/WalletDropdown/WalletDropdown.tsx
  apps/tangle-dapp/components/account/AccountAddress.tsx
  apps/tangle-dapp/components/account/AccountSummaryCard.tsx
  apps/tangle-dapp/containers/BondMoreTxContainer/BondMoreTxContainer.tsx
  apps/tangle-dapp/containers/DelegateTxContainer/AuthorizeTx.tsx
  apps/tangle-dapp/containers/DelegateTxContainer/BondTokens.tsx
  apps/tangle-dapp/containers/DelegateTxContainer/DelegateTxContainer.tsx
  apps/tangle-dapp/containers/NominationsPayoutsContainer/NominationsPayoutsContainer.tsx
  apps/tangle-dapp/containers/NominatorStatsContainer/NominatorStatsContainer.tsx
  apps/tangle-dapp/containers/PayoutAllTxContainer/PayoutAllTxContainer.tsx
  apps/tangle-dapp/containers/PayoutTxContainer/PayoutTxContainer.tsx
  apps/tangle-dapp/containers/RebondTxContainer/RebondTxContainer.tsx
  apps/tangle-dapp/containers/RecentTxContainer/RecentTxContainer.tsx
  apps/tangle-dapp/containers/StopNominationTxContainer/StopNominationTxContainer.tsx
  apps/tangle-dapp/containers/TransferTxContainer/TransferTxContainer.tsx
  apps/tangle-dapp/containers/UnbondTxContainer/UnbondTxContainer.tsx
  apps/tangle-dapp/containers/UpdatePayeeTxContainer/UpdatePayeeTxContainer.tsx
  apps/tangle-dapp/containers/WalletAndChainContainer/WalletAndChainContainer.tsx
  apps/tangle-dapp/data/NominationsPayouts/usePayouts.ts
  apps/tangle-dapp/data/NominatorStats/useTotalPayoutRewards.ts
  apps/tangle-dapp/data/payouts/useNominationsUnclaimedRewards.ts
  apps/tangle-dapp/data/payouts/usePayoutsStore.ts
  apps/tangle-dapp/data/types.ts
  apps/tangle-dapp/hooks/useActiveAccountAddress.ts
  apps/tangle-dapp/hooks/useSubstrateAddress.ts
  apps/tangle-dapp/types/index.ts
  apps/tangle-dapp/utils/toSubstrateAddress.ts
  libs/webb-ui-components/src/components/Dropdown/AccountDropdownBody.tsx
  libs/webb-ui-components/src/components/Dropdown/types.ts
  libs/webb-ui-components/src/constants/index.ts
Labels: tangle-dapp
