Repository tangle-network/dapp, pull requests merged in 2024-08, with the labels that each got.

#2488 fix(tangle-dapp): Fix Static Page Generation on Netlify
  apps/tangle-dapp/app/restake/deposit/layout.tsx
  apps/tangle-dapp/app/restake/deposit/page.tsx
  apps/tangle-dapp/app/restake/layout.tsx
  apps/tangle-dapp/app/restake/page.tsx
  apps/tangle-dapp/app/restake/stake/layout.tsx
  apps/tangle-dapp/app/restake/stake/page.tsx
  apps/tangle-dapp/app/restake/unstake/UnstakeRequestTable.tsx
  apps/tangle-dapp/app/restake/unstake/UnstakeRequestTableActions.tsx
  apps/tangle-dapp/app/restake/unstake/page.tsx
  apps/tangle-dapp/data/restake/useRestakeConsts.ts
Labels: needs review 👓

#2501 ci: Bump deps; Temporary Remove Pages to Fix Netlify Issue
  apps/tangle-dapp/app/restake/_layout.tsx
  apps/tangle-dapp/app/restake/_page.tsx
  apps/tangle-dapp/app/restake/deposit/_layout.tsx
  apps/tangle-dapp/app/restake/deposit/_page.tsx
  apps/tangle-dapp/app/restake/stake/_layout.tsx
  apps/tangle-dapp/app/restake/stake/_page.tsx
  apps/tangle-dapp/app/restake/unstake/_page.tsx
  apps/tangle-dapp/app/services/[serviceId]/_page.tsx
  apps/tangle-dapp/app/services/_page.tsx
  package.json
  yarn.lock
Labels: needs review 👓

#2504 fix(webb-ui): Fix storybook Build & Publish
  .storybook/main.ts
  libs/webb-ui-components/.storybook/main.ts
  package.json
  yarn.lock
Labels: needs review 👓

#2491 chore(webb-ui-components): Update Radios component in UI Kit
  libs/webb-ui-components/src/components/Radio/RadioItem.tsx
  yarn.lock
Labels: ui-components

#2492 refactor(tangle-dapp): Integrate New Restake API
  .lycheeignore
  apps/tangle-dapp/app/restake/deposit/DepositForm.tsx
  apps/tangle-dapp/app/restake/deposit/TxDetails.tsx
  apps/tangle-dapp/app/restake/deposit/layout.tsx
  apps/tangle-dapp/app/restake/deposit/page.tsx
  apps/tangle-dapp/app/restake/layout.tsx
  apps/tangle-dapp/app/restake/page.tsx
  apps/tangle-dapp/app/restake/stake/layout.tsx
  apps/tangle-dapp/app/restake/stake/page.tsx
  apps/tangle-dapp/app/restake/unstake/UnstakeModal.tsx
  apps/tangle-dapp/app/restake/unstake/UnstakeRequestTable.tsx
  apps/tangle-dapp/app/restake/unstake/UnstakeRequestTableActions.tsx
  apps/tangle-dapp/app/restake/unstake/page.tsx
  apps/tangle-dapp/app/restake/unstake/types.ts
  apps/tangle-dapp/data/restake/RestakeTx/base.ts
  apps/tangle-dapp/data/restake/RestakeTx/evm.ts
  apps/tangle-dapp/data/restake/RestakeTx/substrate.ts
  apps/tangle-dapp/data/restake/useRestakeAssetIds.ts
  apps/tangle-dapp/data/restake/useRestakeAssetMap.ts
  apps/tangle-dapp/data/restake/useRestakeBalances.ts
  apps/tangle-dapp/data/restake/useRestakeDelegatorInfo.ts
  apps/tangle-dapp/data/restake/useRestakeOperatorMap.ts
  apps/tangle-dapp/data/restake/useRestakeRewardConfig.ts
  apps/tangle-dapp/data/restake/useRestakeRewardPoolMap.ts
  apps/tangle-dapp/data/restake/useRestakeTx.ts
  apps/tangle-dapp/types/restake.ts
  apps/tangle-dapp/utils/assertAnySubstrateAddress.ts
  apps/tangle-dapp/utils/restaking/filterNativeAsset.ts
  package.json
  tools/scripts/setupMultiAssetDelegationPallet.ts
  yarn.lock
Labels: needs review 👓

#2506 chore(tangle-dapp): Update modals (header, footer, body)
  apps/tangle-dapp/app/bridge/BridgeConfirmationModal.tsx
  apps/tangle-dapp/components/LiquidStaking/stakeAndUnstake/SelectTokenModal.tsx
  apps/tangle-dapp/components/LiquidStaking/stakeAndUnstake/UnstakeRequestSubmittedModal.tsx
  apps/tangle-dapp/components/LiquidStaking/unstakeRequestsTable/CancelUnstakeModal.tsx
  apps/tangle-dapp/components/LiquidStaking/unstakeRequestsTable/WithdrawalConfirmationModal.tsx
  apps/tangle-dapp/containers/BondMoreTxContainer/BondMoreTxContainer.tsx
  apps/tangle-dapp/containers/DelegateTxContainer/DelegateTxContainer.tsx
  apps/tangle-dapp/containers/ManageProfileModalContainer/ManageProfileModalContainer.tsx
  apps/tangle-dapp/containers/PayoutAllTxContainer/PayoutAllTxContainer.tsx
  apps/tangle-dapp/containers/PayoutTxContainer/PayoutTxContainer.tsx
  apps/tangle-dapp/containers/RebondTxContainer/RebondTxContainer.tsx
  apps/tangle-dapp/containers/StopNominationTxContainer/StopNominationTxContainer.tsx
  apps/tangle-dapp/containers/TransferTxContainer/TransferTxContainer.tsx
  apps/tangle-dapp/containers/UnbondTxContainer/UnbondTxContainer.tsx
  apps/tangle-dapp/containers/UpdateNominationsTxContainer/UpdateNominationsTxContainer.tsx
  apps/tangle-dapp/containers/UpdatePayeeTxContainer/UpdatePayeeTxContainer.tsx
  apps/tangle-dapp/containers/WithdrawUnbondedTxContainer/WithdrawUnbondedTxContainer.tsx
  apps/zk-explorer/components/RunCircuitServiceModalTrigger.tsx
  libs/webb-ui-components/src/components/Modal/ModalContent.tsx
  libs/webb-ui-components/src/components/Modal/ModalFooter.tsx
  libs/webb-ui-components/src/components/Modal/ModalHeader.tsx
  libs/webb-ui-components/src/components/WalletConnectionCard/WalletConnectionCard.tsx
  libs/webb-ui-components/src/stories/organisms/Modal.stories.jsx
Labels: needs review 👓, tangle-dapp

#2514 feat(tangle-dapp): Implement EVM Restaking
  apps/tangle-dapp/app/restake/stake/_page.tsx
  apps/tangle-dapp/app/restake/unstake/UnstakeRequestTableActions.tsx
  apps/tangle-dapp/app/restake/unstake/_page.tsx
  apps/tangle-dapp/app/restake/withdraw/TxInfo.tsx
  apps/tangle-dapp/app/restake/withdraw/WithdrawRequestTableActions.tsx
  apps/tangle-dapp/constants/restake.ts
  apps/tangle-dapp/data/restake/RestakeTx/abi.ts
  apps/tangle-dapp/data/restake/RestakeTx/base.ts
  apps/tangle-dapp/data/restake/RestakeTx/constants.ts
  apps/tangle-dapp/data/restake/RestakeTx/evm.ts
  apps/tangle-dapp/data/restake/RestakeTx/substrate.ts
  apps/tangle-dapp/data/restake/useRestakeTx.ts
  apps/tangle-dapp/hooks/useEvmPrecompileAbiCall.ts
  apps/tangle-dapp/utils/staking/createEvmBatchCallArgs.ts
  tools/scripts/setupMultiAssetDelegationPallet.ts
Labels: needs review 👓

#2518 chore(webb-ui): Clean up Legacy Storybook Components
  libs/abstract-api-provider/src/relayer/webb-relayer-manager.ts
  libs/abstract-api-provider/src/webb-provider.interface.ts
  libs/web3-api-provider/src/VAnchor.ts
  libs/web3-api-provider/src/webb-provider/relayer-manager.ts
  libs/web3-api-provider/src/webb-provider/vanchor-actions.ts
  libs/webb-ui-components/src/stories/atoms/StatusIndicator.stories.tsx
  libs/webb-ui-components/src/stories/molecules/AdjustAmount.stories.jsx
  libs/webb-ui-components/src/stories/molecules/AmountInput.stories.jsx
  libs/webb-ui-components/src/stories/molecules/AmountMenu.stories.jsx
  libs/webb-ui-components/src/stories/molecules/Banner.stories.jsx
  libs/webb-ui-components/src/stories/molecules/BridgeFeeDetails.stories.tsx
  libs/webb-ui-components/src/stories/molecules/BridgeInputGroup.stories.jsx
  libs/webb-ui-components/src/stories/molecules/CardTable.stories.jsx
  libs/webb-ui-components/src/stories/molecules/ChainInput.stories.jsx
  libs/webb-ui-components/src/stories/molecules/ChainOrTokenButton.stories.tsx
  libs/webb-ui-components/src/stories/molecules/CheckBoxMenu.stories.jsx
  libs/webb-ui-components/src/stories/molecules/CodeFile.stories.tsx
  libs/webb-ui-components/src/stories/molecules/Footer.stories.jsx
  libs/webb-ui-components/src/stories/molecules/Input.stories.jsx
  libs/webb-ui-components/src/stories/molecules/LoadingPill.stories.tsx
  libs/webb-ui-components/src/stories/molecules/Progress.stories.jsx
  libs/webb-ui-components/src/stories/molecules/RecipientInput.stories.jsx
  libs/webb-ui-components/src/stories/molecules/RelayerInput.stories.jsx
  libs/webb-ui-components/src/stories/molecules/ShieldedAssetInput.stories.jsx
  libs/webb-ui-components/src/stories/molecules/Switcher.stories.jsx
  libs/webb-ui-components/src/stories/molecules/TextField.stories.tsx
  libs/webb-ui-components/src/stories/molecules/TimeProgress.stories.jsx
  libs/webb-ui-components/src/stories/molecules/ToggleCard.stories.tsx
  libs/webb-ui-components/src/stories/molecules/TokenInput.stories.jsx
  libs/webb-ui-components/src/stories/molecules/TokenListItem.stories.tsx
  libs/webb-ui-components/src/stories/molecules/TokenSelector.stories.tsx
  libs/webb-ui-components/src/stories/molecules/TxConfirmationRing.stories.jsx
  libs/webb-ui-components/src/stories/molecules/TxProgressor.stories.tsx
  libs/webb-ui-components/src/stories/molecules/WalletButton.stories.tsx
  libs/webb-ui-components/src/stories/organisms/KeyCard.stories.jsx
  libs/webb-ui-components/src/stories/organisms/KeyStatusCard.stories.jsx
  libs/webb-ui-components/src/stories/organisms/NetworkThresholdCard.stories.jsx
  libs/webb-ui-components/src/stories/organisms/SideBarMenu.stories.jsx
  libs/webb-ui-components/src/stories/organisms/Sidebar.stories.jsx
  libs/webb-ui-components/src/stories/organisms/TransactionInputCard.stories.tsx
  libs/webb-ui-components/src/stories/templates/ChainListCard.stories.tsx
  libs/webb-ui-components/src/stories/templates/DepositCard.stories.jsx
  libs/webb-ui-components/src/stories/templates/DepositConfirm.stories.jsx
  libs/webb-ui-components/src/stories/templates/GovernanceContractDetailCard.stories.tsx
  libs/webb-ui-components/src/stories/templates/RelayerListCard.stories.tsx
  libs/webb-ui-components/src/stories/templates/TransferCard.stories.jsx
  libs/webb-ui-components/src/stories/templates/TransferConfirm.stories.jsx
  libs/webb-ui-components/src/stories/templates/WalletConnectionCard.stories.jsx
  libs/webb-ui-components/src/stories/templates/WithdrawCard.stories.jsx
  libs/webb-ui-components/src/stories/templates/WithdrawConfirm.stories.jsx
  package.json
  yarn.lock
Labels: needs review 👓
