Repository tangle-network/dapp, pull requests merged in 2025-02, with the labels that each got.

#2788 fix(tangle-dapp): Fix Missing Default Tab & Incorrect Balance
  apps/tangle-dapp/src/app/app.tsx
  apps/tangle-dapp/src/containers/VaultsAndBalancesTable.tsx
  apps/tangle-dapp/src/containers/restaking/WithdrawModal.tsx
  apps/tangle-dapp/src/context/RestakeContext/RestakeContext.ts
  apps/tangle-dapp/src/context/RestakeContext/RestakeContextProvider.tsx
  apps/tangle-dapp/src/context/RestakeContext/index.ts
  apps/tangle-dapp/src/context/RestakeContext/types.ts
  apps/tangle-dapp/src/context/RestakeContext/useRestakeContext.ts
  apps/tangle-dapp/src/data/points/useActivePoints.ts
  apps/tangle-dapp/src/data/rewards/useAccountRewardInfo.ts
  apps/tangle-dapp/src/hooks/useQueryState.ts
  apps/tangle-dapp/src/pages/blueprints/layout.tsx
  apps/tangle-dapp/src/pages/restake/RestakeTabs.tsx
  apps/tangle-dapp/src/pages/restake/delegate/StakeInput.tsx
  apps/tangle-dapp/src/pages/restake/delegate/index.tsx
  apps/tangle-dapp/src/pages/restake/deposit/DepositForm.tsx
  apps/tangle-dapp/src/pages/restake/index.tsx
  apps/tangle-dapp/src/pages/restake/withdraw/index.tsx
  apps/tangle-dapp/src/types/index.ts
  libs/tangle-shared-ui/src/components/ListModal.tsx
  libs/tangle-shared-ui/src/components/tables/TableStatus.tsx
  libs/tangle-shared-ui/src/context/RestakeContext/RestakeContext.ts
  libs/tangle-shared-ui/src/context/RestakeContext/RestakeContextProvider.tsx
  libs/tangle-shared-ui/src/context/RestakeContext/types.ts
  libs/tangle-shared-ui/src/data/restake/useRestakeBalances.ts
  libs/tangle-shared-ui/src/data/restake/useRestakeDelegatorInfo.ts
  libs/tangle-shared-ui/src/data/restake/useRestakeVaults.ts
  libs/tangle-shared-ui/src/hooks/useSubstrateAddress.ts
  libs/tangle-shared-ui/src/types/restake.ts
Labels: needs review 🔎

#2789 feat(tangle-dapp): Aggregate Vault Token and Display Self-Bonded
  apps/tangle-dapp/src/containers/restaking/OperatorsTable.tsx
  libs/dapp-config/src/chains/substrate/index.tsx
  libs/tangle-shared-ui/src/components/tables/Operators/VaultsDropdown.tsx
  libs/tangle-shared-ui/src/components/tables/Operators/index.tsx
  libs/tangle-shared-ui/src/data/restake/useBlueprintDetails.ts
  libs/tangle-shared-ui/src/data/restake/utils/randOperator.ts
  libs/tangle-shared-ui/src/types/index.ts
  libs/tangle-shared-ui/src/utils/restake/delegationsToVaultTokens.ts
Labels: needs review 🔎

#2795 feat(tangle-dapp): Add TNT Rewards, Fix TVL Calculation
  apps/tangle-dapp/src/components/StatItem.tsx
  apps/tangle-dapp/src/containers/AssetsAndBalancesTable.tsx
  apps/tangle-dapp/src/containers/restaking/OperatorsTable.tsx
  apps/tangle-dapp/src/containers/restaking/RestakeOverviewTabs.tsx
  apps/tangle-dapp/src/containers/restaking/SelectOperatorModal.tsx
  apps/tangle-dapp/src/containers/restaking/UnstakeRequestTable.tsx
  apps/tangle-dapp/src/containers/restaking/WithdrawModal.tsx
  apps/tangle-dapp/src/containers/restaking/WithdrawRequestTable.tsx
  apps/tangle-dapp/src/data/restake/useRestakeAsset.ts
  apps/tangle-dapp/src/pages/account.tsx
  apps/tangle-dapp/src/pages/restake/delegate/index.tsx
  apps/tangle-dapp/src/pages/restake/deposit/Details.tsx
  apps/tangle-dapp/src/pages/restake/operators/[address]/TVLTable.tsx
  apps/tangle-dapp/src/pages/restake/unstake/index.tsx
  libs/tangle-shared-ui/src/context/RestakeContext/RestakeContext.ts
  libs/tangle-shared-ui/src/context/RestakeContext/RestakeContextProvider.tsx
  libs/tangle-shared-ui/src/context/RestakeContext/types.ts
  libs/tangle-shared-ui/src/data/blueprints/useBlueprintListing.ts
  libs/tangle-shared-ui/src/data/restake/useBlueprintDetails.ts
  libs/tangle-shared-ui/src/data/restake/useDelegatorTVL.ts
  libs/tangle-shared-ui/src/data/restake/useOperatorTVL.ts
  libs/tangle-shared-ui/src/data/restake/useRestakeAssets.ts
  libs/tangle-shared-ui/src/data/restake/useRestakeAssetsTvl.ts
  libs/tangle-shared-ui/src/data/restake/useRestakeDeposits.ts
  libs/tangle-shared-ui/src/data/restake/useRestakeTVL.ts
  libs/tangle-shared-ui/src/data/rewards/useVaultPotAccount.ts
  libs/tangle-shared-ui/src/data/rewards/useVaultRewards.ts
  libs/tangle-shared-ui/src/queries/restake/assetDetails.ts
  libs/tangle-shared-ui/src/types/restake.ts
  libs/tangle-shared-ui/src/utils/restake/delegationsToVaultTokens.ts
  package.json
  yarn.lock
Labels: needs review 🔎

#2794 fix(tangle-dapp): Fix bridge transaction status not updating correctly in edge cases
  apps/tangle-dapp/src/components/KeyStatsItem/KeyStatsItem.tsx
  apps/tangle-dapp/src/components/bridge/BridgeConfirmationModal.tsx
  apps/tangle-dapp/src/components/bridge/BridgeTxQueueItem.tsx
  apps/tangle-dapp/src/components/bridge/FeeDetail.tsx
  apps/tangle-dapp/src/data/KeyStats/useWaitingCountSubscription.ts
  apps/tangle-dapp/src/data/ValidatorTables/useActiveValidators.ts
  apps/tangle-dapp/src/pages/restake/delegate/index.tsx
  apps/tangle-dapp/src/pages/restake/deposit/DepositForm.tsx
  apps/tangle-dapp/src/pages/restake/unstake/index.tsx
  apps/tangle-dapp/src/pages/restake/withdraw/index.tsx
  libs/tangle-shared-ui/src/constants/bridge.ts
  libs/tangle-shared-ui/src/hooks/useLocalStorage.ts
Labels: app: tangle-dapp

#2806 fix(tangle-dapp): Remove Heavy SVG, Use Shallow for Selectors
  apps/tangle-dapp/src/app/app.tsx
  apps/tangle-dapp/src/components/Lists/AssetList.tsx
  apps/tangle-dapp/src/containers/bridge/BridgeContainer.tsx
  apps/tangle-dapp/src/pages/bridge/layout.tsx
  libs/icons/src/chains/astar.svg
  libs/icons/src/chains/base.svg
  libs/icons/src/chains/bsc.svg
  libs/icons/src/chains/chainlink.svg
  libs/icons/src/chains/linea.svg
  libs/icons/src/chains/livepeer.svg
  libs/icons/src/chains/manta.svg
  libs/icons/src/chains/optimism.svg
  libs/icons/src/chains/phala.svg
  libs/icons/src/chains/solana.svg
  libs/icons/src/chains/the-graph.svg
  libs/icons/src/tokens/arb.svg
  libs/icons/src/tokens/astr.svg
  libs/icons/src/tokens/avail.svg
  libs/icons/src/tokens/bnb.svg
  libs/icons/src/tokens/cbbtc.svg
  libs/icons/src/tokens/cbeth.svg
  libs/icons/src/tokens/crv.svg
  libs/icons/src/tokens/dot.svg
  libs/icons/src/tokens/ezeth.svg
  libs/icons/src/tokens/glmr.svg
  libs/icons/src/tokens/hyperlane.svg
  libs/icons/src/tokens/lbtc.svg
  libs/icons/src/tokens/ldo.svg
  libs/icons/src/tokens/lpt.svg
  libs/icons/src/tokens/manta.svg
  libs/icons/src/tokens/pha.svg
  libs/icons/src/tokens/pol.svg
  libs/icons/src/tokens/reth.svg
  libs/icons/src/tokens/router.svg
  libs/icons/src/tokens/solvbtc.svg
  libs/icons/src/tokens/stavail.svg
  libs/icons/src/tokens/sweth.svg
  libs/icons/src/tokens/tbtc.svg
  libs/icons/src/tokens/tnt.svg
  libs/icons/src/tokens/ttnt.svg
  libs/icons/src/tokens/uni.svg
  libs/icons/src/tokens/usdx.svg
  libs/icons/src/tokens/wbtc.svg
  libs/icons/src/tokens/webbttnt.svg
  libs/icons/src/tokens/wsteth.svg
  libs/icons/src/tokens/wtnt.svg
  package.json
Labels: needs review 🔎

#2801 chore(tangle-dapp): Replace Assets Table with Vaults Table
  .github/workflows/check-build.yml
  .github/workflows/check-lint.yml
  .github/workflows/check-pr-title.yml
  .github/workflows/deploy-storybook-docs.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  apps/tangle-dapp/src/components/account/RewardsAndPoints.tsx
  apps/tangle-dapp/src/components/tables/VaultAssets/index.tsx
  apps/tangle-dapp/src/components/tables/VaultAssets/types.ts
  apps/tangle-dapp/src/components/tables/Vaults/index.tsx
  apps/tangle-dapp/src/components/tables/Vaults/types.ts
  apps/tangle-dapp/src/containers/AssetsAndBalancesTable.tsx
  apps/tangle-dapp/src/containers/restaking/RestakeOverviewTabs.tsx
  apps/tangle-dapp/src/containers/restaking/UnstakeRequestTable.tsx
  apps/tangle-dapp/src/containers/restaking/VaultsOverview.tsx
  apps/tangle-dapp/src/containers/restaking/WithdrawModal.tsx
  apps/tangle-dapp/src/containers/restaking/WithdrawRequestTable.tsx
  apps/tangle-dapp/src/data/restake/useRestakeAsset.ts
  apps/tangle-dapp/src/data/restake/useRestakeRewardVaultMap.ts
  apps/tangle-dapp/src/hooks/useVaultTableData.tsx
  apps/tangle-dapp/src/pages/account.tsx
  apps/tangle-dapp/src/pages/restake/delegate/index.tsx
  apps/tangle-dapp/src/pages/restake/deposit/DepositForm.tsx
  apps/tangle-dapp/src/pages/restake/index.tsx
  apps/tangle-dapp/src/pages/restake/operators/[address]/TVLTable.tsx
  apps/tangle-dapp/src/pages/restake/operators/[address]/index.tsx
  apps/tangle-dapp/src/utils/calculateVaults.ts
  codegen.ts
  libs/tangle-shared-ui/src/components/tables/Operators/index.tsx
  libs/tangle-shared-ui/src/components/tables/TableCellWrapper.tsx
  libs/tangle-shared-ui/src/context/RestakeContext/RestakeContext.ts
  libs/tangle-shared-ui/src/context/RestakeContext/RestakeContextProvider.tsx
  libs/tangle-shared-ui/src/context/RestakeContext/types.ts
  libs/tangle-shared-ui/src/data/restake/useRestakeAssetIds.ts
  libs/tangle-shared-ui/src/data/restake/useRestakeAssets.ts
  libs/tangle-shared-ui/src/data/restake/useRestakeBalances.ts
  libs/tangle-shared-ui/src/data/rewards/useVaultPotAccount.ts
  libs/tangle-shared-ui/src/queries/restake/assetDetails.ts
  libs/tangle-shared-ui/src/queries/restake/rewardVault.ts
  libs/tangle-shared-ui/src/queries/restake/rewardVaultsPotAccounts.ts
  libs/tangle-shared-ui/src/types/restake.ts
  libs/tangle-shared-ui/src/utils/fetchErc20TokenMetadata.ts
  libs/tangle-shared-ui/src/utils/restake/filterNativeAsset.ts
  libs/webb-ui-components/src/components/Table/Table.tsx
  libs/webb-ui-components/src/components/Table/types.ts
  package.json
  yarn.lock
Labels: needs review 🔎

#2836 fix(tangle-dapp): Fix Incorrect Token Symbol on Unclaimed Reward
  apps/tangle-dapp/src/components/account/RewardsAndPoints.tsx
  tsconfig.base.json
Labels: needs review 🔎

#2838 feat(repo): Add Typecheck for dApps
  apps/tangle-cloud/project.json
  apps/tangle-cloud/tsconfig.app.json
  apps/tangle-dapp/project.json
  apps/tangle-dapp/tsconfig.app.json
  package.json
  yarn.lock
Labels: needs review 🔎

#2846 fix(tangle-shared-ui): Fix Talisman Keep Popping Up
  libs/dapp-config/src/types.ts
  libs/dapp-config/src/utils/findSubstrateWallet.ts
  libs/dapp-config/src/wallets/wallet-config.interface.ts
  libs/dapp-config/src/wallets/wallets-config.tsx
  libs/dapp-types/src/WalletId.ts
  libs/polkadot-api-provider/src/ext-provider/polkadot-provider.ts
  libs/polkadot-api-provider/src/webb-provider.ts
  libs/tangle-shared-ui/src/components/UpdateMetadataButton/UpdateMetadataButton.tsx
  libs/tangle-shared-ui/src/hooks/usePromise.ts
  libs/tangle-shared-ui/src/hooks/useSubstrateInjectedExtension.ts
  libs/tangle-shared-ui/src/hooks/useWallet.ts
  libs/tangle-shared-ui/src/utils/polkadot/api.ts
  types/global.d.ts
Labels: needs review 🔎

#2851 fix(tangle-shared-ui): Fix Table Issues, Resolve API Errors
  apps/tangle-dapp/src/components/PayoutTable.tsx
  apps/tangle-dapp/src/components/ValidatorSelectionTable.tsx
  apps/tangle-dapp/src/components/ValidatorTable.tsx
  apps/tangle-dapp/src/components/nomination/NominationsTable.tsx
  apps/tangle-dapp/src/components/tables/VaultAssets/index.tsx
  apps/tangle-dapp/src/components/tables/Vaults/index.tsx
  apps/tangle-dapp/src/containers/restaking/OperatorsTable.tsx
  apps/tangle-dapp/src/data/restake/useRestakeConsts.ts
  apps/tangle-dapp/src/hooks/useApi.ts
  apps/tangle-dapp/src/pages/restake/deposit/DepositForm.tsx
  apps/tangle-dapp/src/pages/restake/deposit/Details.tsx
  apps/tangle-dapp/src/utils/calculateVaults.ts
  apps/tangle-dapp/src/utils/sortByBn.ts
  libs/tangle-shared-ui/src/hooks/usePromise.ts
  libs/ui-components/src/components/Table/Table.tsx
  libs/ui-components/src/components/Table/types.ts
  libs/ui-components/src/containers/FAQSection/index.tsx
  libs/ui-components/src/utils/convertBnToDecimal.ts
  libs/ui-components/src/utils/sortByBnToDecimal.ts
  libs/ui-components/src/utils/sortByComparable.ts
Labels: needs review 🔎

#2859 fix(tangle-shared-ui): Fix Incorrect Instance Provider
  apps/tangle-dapp/src/hooks/useSubstrateInjectedExtension.ts
  apps/tangle-dapp/src/pages/restake/deposit/DepositForm.tsx
  libs/tangle-shared-ui/src/hooks/useSubstrateInjectedExtension.ts
Labels: needs review 🔎

#2854 perf(tangle-dapp): Optimize Bridge API Requests when fetching balances
  apps/tangle-dapp/src/containers/TopNavigationPanel.tsx
  apps/tangle-dapp/src/containers/bridge/BridgeContainer.tsx
  apps/tangle-dapp/src/data/bridge/useBridgeEvmBalances.ts
Labels: app: tangle-dapp, needs review 🔎
