Repository tangle-network/dapp, pull requests merged in 2025-03, with the labels that each got.

#2850 chore(tangle-dapp): Separate mainnet and testnet in bridge chain selection
  apps/tangle-dapp/src/containers/bridge/BridgeContainer.tsx
  apps/tangle-dapp/src/context/bridge/useBridgeStore.ts
Labels: app: tangle-dapp, needs review 🔎

#2849 fix(tangle-dapp): Fix token selector not working for Tangle mainnet
  apps/tangle-dapp/src/components/Lists/AssetList.tsx
  apps/tangle-dapp/src/containers/bridge/BridgeContainer.tsx
Labels: app: tangle-dapp, needs review 🔎

#2861 fix(ui-components): useDarkMode Resets on Page Refresh
  libs/ui-components/src/hooks/useDarkMode.ts
Labels: app: tangle-dapp, needs review 🔎

#2855 fix(tangle-dapp): Network Switching Improvements
  apps/tangle-dapp/src/components/NetworkSelectorButton/index.tsx
  apps/tangle-dapp/src/components/bridge/BridgeConfirmationModal.tsx
  apps/tangle-dapp/src/containers/TopNavigationPanel.tsx
  apps/tangle-dapp/src/containers/bridge/BridgeContainer.tsx
  apps/tangle-dapp/src/context/bridge/useBridgeStore.ts
  apps/tangle-dapp/src/data/bridge/useHyperlaneTransfer.ts
  apps/tangle-dapp/src/hooks/useIsBridgeNativeToken.ts
  libs/dapp-config/src/chains/evm/customChains/tangleMainnetEVM.ts
  libs/dapp-config/src/chains/evm/index.tsx
  libs/tangle-shared-ui/src/components/ConnectWalletButton/ConnectWalletButton.tsx
  libs/tangle-shared-ui/src/components/NetworkSelectorDropdown/index.tsx
  libs/ui-components/src/components/Dropdown/DropdownBasicButton.tsx
  libs/ui-components/src/components/buttons/ChainOrTokenButton.tsx
Labels: app: tangle-dapp

#2872 chore(tangle-dapp): Update Asset List Modal in Bridge
  apps/tangle-dapp/src/components/Lists/AssetList.tsx
Labels: app: tangle-dapp, needs review 🔎

#2873 fix(tangle-dapp): Network switching & other fixes
  apps/tangle-dapp/src/components/account/PromotionalBanner.tsx
  apps/tangle-dapp/src/containers/bridge/BridgeContainer.tsx
  libs/tangle-shared-ui/src/components/ConnectWalletButton/ConnectWalletButton.tsx
  libs/tangle-shared-ui/src/components/ConnectWalletButton/ConnectWalletModal.tsx
  libs/tangle-shared-ui/src/components/NetworkSelectorDropdown/NetworkSelectorDropdown.tsx
  libs/tangle-shared-ui/src/components/NetworkSelectorDropdown/index.tsx
Labels: app: tangle-dapp, needs review 🔎

#2866 feat(tangle-cloud): implement mock logic for Tangle Cloud Operator Home Page Instance section
  apps/tangle-cloud/src/components/TangleCloudCard.tsx
  apps/tangle-cloud/src/pages/instances/AccountStatsCard.tsx
  apps/tangle-cloud/src/pages/instances/BlueprintManagementSection.tsx
  apps/tangle-cloud/src/pages/instances/Instances/PendingInstanceTable.tsx
  apps/tangle-cloud/src/pages/instances/Instances/RunningInstanceTable.tsx
  apps/tangle-cloud/src/pages/instances/Instances/StoppedInstanceTable.tsx
  apps/tangle-cloud/src/pages/instances/Instances/index.tsx
  apps/tangle-cloud/src/pages/instances/Instances/type.ts
  apps/tangle-cloud/src/pages/instances/RegisteredBlueprints/RegisteredBlueprints.tsx
  apps/tangle-cloud/src/pages/instances/RegisteredBlueprints/index.tsx
  apps/tangle-cloud/src/pages/instances/RegisteredBlueprints/type.ts
  apps/tangle-cloud/src/pages/instances/TotalValueLocked/TotalValueLockedTable.tsx
  apps/tangle-cloud/src/pages/instances/TotalValueLocked/index.tsx
  apps/tangle-cloud/src/pages/instances/page.tsx
  apps/tangle-dapp/src/pages/restake/operators/[address]/index.tsx
  libs/tangle-shared-ui/src/data/blueprints/useFakeMonitoringBlueprints.ts
  libs/tangle-shared-ui/src/data/blueprints/useOperatorBlueprints.ts
  libs/tangle-shared-ui/src/data/blueprints/utils/randPrimitiveBlueprint.ts
  libs/tangle-shared-ui/src/data/blueprints/utils/randPrimitiveService.ts
  libs/tangle-shared-ui/src/data/blueprints/utils/type.ts
Labels: app: tangle-cloud ☁️

#2875 fix(tools): Update Tangle chains Info
  libs/dapp-config/src/chains/evm/customChains/tangleMainnetEVM.ts
  libs/dapp-config/src/chains/evm/customChains/tangleTestnetEVM.ts
Labels: needs review 🔎

#2874 feat(tangle-cloud): building UI deployer home page
  apps/tangle-cloud/src/components/NestedOperatorCell.tsx
  apps/tangle-cloud/src/pages/instances/BlueprintManagementSection.tsx
  apps/tangle-cloud/src/pages/instances/Instances/PendingInstanceTable.tsx
  apps/tangle-cloud/src/pages/instances/Instances/type.ts
  apps/tangle-cloud/src/pages/instances/InstructionCard.tsx
  apps/tangle-cloud/src/pages/instances/RegisteredBlueprints/RegisteredBlueprints.tsx
  apps/tangle-cloud/src/pages/instances/page.tsx
  libs/tangle-shared-ui/src/data/blueprints/useFakeMonitoringBlueprints.ts
  libs/tangle-shared-ui/src/data/blueprints/utils/randPrimitiveService.ts
  libs/tangle-shared-ui/src/data/blueprints/utils/type.ts
  libs/ui-components/src/components/Dropdown/DropdownButton.tsx
  libs/ui-components/src/components/Dropdown/types.ts
Labels: app: tangle-cloud ☁️

#2878 chore: Handle Empty Names for Assets and Pools
  apps/tangle-dapp/src/components/LiquidStaking/LstListItem.tsx
  apps/tangle-dapp/src/components/LiquidStaking/stakeAndUnstake/SelectedPoolIndicator.tsx
  apps/tangle-dapp/src/constants/liquidStaking/types.ts
  apps/tangle-dapp/src/containers/LsPoolsTable/LsPoolsTable.tsx
  apps/tangle-dapp/src/data/liquidStaking/useLsActivePoolDisplayName.ts
  apps/tangle-dapp/src/data/liquidStaking/useLsPools.ts
  apps/tangle-dapp/src/data/restake/useRestakeAsset.ts
  libs/tangle-shared-ui/src/data/restake/useRestakeAssets.ts
  libs/tangle-shared-ui/src/types/restake.ts
Labels: needs review 🔎

#2868 chore(tangle-dapp): BridgeContainer Refactor
  apps/tangle-dapp/src/app/providers.tsx
  apps/tangle-dapp/src/components/Lists/AssetList.tsx
  apps/tangle-dapp/src/containers/Layout.tsx
  apps/tangle-dapp/src/containers/TopNavigationPanel.tsx
  apps/tangle-dapp/src/containers/bridge/BridgeContainer.tsx
  apps/tangle-dapp/src/data/bridge/useRouterQuote.ts
  apps/tangle-dapp/src/data/bridge/useRouterTransfer.ts
  apps/tangle-dapp/src/features/bridge/components/BridgeActionButton.tsx
  apps/tangle-dapp/src/features/bridge/components/BridgeConfirmationModal.tsx
  apps/tangle-dapp/src/features/bridge/components/BridgeFeeDetail.tsx
  apps/tangle-dapp/src/features/bridge/components/BridgeTxQueueDropdown.tsx
  apps/tangle-dapp/src/features/bridge/components/BridgeTxQueueItem.tsx
  apps/tangle-dapp/src/features/bridge/containers/BridgeContainer.tsx
  apps/tangle-dapp/src/features/bridge/context/BridgeHyperlaneContext/BridgeHyperlaneContext.tsx
  apps/tangle-dapp/src/features/bridge/context/BridgeHyperlaneContext/BridgeHyperlaneProvider.tsx
  apps/tangle-dapp/src/features/bridge/context/BridgeTxQueueContext/BridgeTxQueueContext.ts
  apps/tangle-dapp/src/features/bridge/context/BridgeTxQueueContext/BridgeTxQueueProvider.tsx
  apps/tangle-dapp/src/features/bridge/context/BridgeTxQueueContext/index.ts
  apps/tangle-dapp/src/features/bridge/context/BridgeTxQueueContext/useBridgeTxQueue.ts
  apps/tangle-dapp/src/features/bridge/context/useBridgeStore.ts
  apps/tangle-dapp/src/features/bridge/hooks/useAssets.ts
  apps/tangle-dapp/src/features/bridge/hooks/useEthersSigner.ts
  apps/tangle-dapp/src/features/bridge/hooks/useEvmBalances.ts
  apps/tangle-dapp/src/features/bridge/hooks/useHyperlaneFeeDetails.ts
  apps/tangle-dapp/src/features/bridge/hooks/useHyperlaneQuote.ts
  apps/tangle-dapp/src/features/bridge/hooks/useHyperlaneQuoteParams.ts
  apps/tangle-dapp/src/features/bridge/hooks/useHyperlaneTransfer.ts
  apps/tangle-dapp/src/features/bridge/hooks/useIsNativeToken.ts
  apps/tangle-dapp/src/features/bridge/hooks/useTokenBalance.ts
  apps/tangle-dapp/src/features/bridge/hooks/useWalletClient.ts
  apps/tangle-dapp/src/features/bridge/utils/getHyperlaneChainName.ts
  apps/tangle-dapp/src/features/bridge/utils/getHyperlaneToken.ts
  apps/tangle-dapp/src/features/bridge/utils/hyperlaneAssembleChainMetadata.ts
  apps/tangle-dapp/src/features/bridge/utils/hyperlaneAssembleWarpCoreConfig.ts
  apps/tangle-dapp/src/hooks/useIsBridgeNativeToken.ts
  apps/tangle-dapp/src/pages/bridge/index.tsx
  apps/tangle-dapp/src/utils/bridge.ts
  libs/api-provider-environment/src/transaction/utils/makeExplorerUrl.ts
  libs/icons/src/wallets/MetaMaskIcon.tsx
  libs/tangle-shared-ui/src/constants/bridge.ts
  libs/tangle-shared-ui/src/hooks/useLocalStorage.ts
  libs/tangle-shared-ui/src/types/index.ts
Labels: app: tangle-dapp, needs review 🔎

#2876 fix(tangle-dapp): Fix Restake Data not Showing
  apps/tangle-dapp/src/components/tables/Vaults/index.tsx
  apps/tangle-dapp/src/containers/TransferTxModal.tsx
  apps/tangle-dapp/src/containers/restaking/VaultsOverview.tsx
  apps/tangle-dapp/src/hooks/useAgnosticTx.ts
  apps/tangle-dapp/src/hooks/useEvmCallPermitNonce.ts
  apps/tangle-dapp/src/hooks/useEvmTxRelayer.ts
  apps/tangle-dapp/src/hooks/useVaultTableData.tsx
  apps/tangle-dapp/src/hooks/useViemWalletClient.ts
  apps/tangle-dapp/src/pages/restake/deposit/DepositForm.tsx
  libs/tangle-shared-ui/src/components/ListModal.tsx
  libs/tangle-shared-ui/src/components/UpdateMetadataButton/UpdateMetadataButton.tsx
  libs/tangle-shared-ui/src/components/tables/Operators/index.tsx
  libs/tangle-shared-ui/src/data/blueprints/utils/blueprintHelpers.ts
  libs/tangle-shared-ui/src/data/blueprints/utils/toPrimitiveBlueprint.ts
  libs/tangle-shared-ui/src/data/restake/useBlueprintDetails.ts
  libs/tangle-shared-ui/src/data/restake/useErc20Balances.ts
  libs/tangle-shared-ui/src/data/restake/useRestakeAssetBalances.ts
  libs/tangle-shared-ui/src/data/restake/useRestakeAssetIds.ts
  libs/tangle-shared-ui/src/data/restake/useRestakeAssets.ts
  libs/tangle-shared-ui/src/hooks/useEvmChain.ts
  libs/tangle-shared-ui/src/hooks/usePromise.ts
  libs/tangle-shared-ui/src/utils/createRestakeAssetId.ts
  libs/ui-components/src/components/Table/Table.tsx
Labels: needs review 🔎

#2881 fix(tangle-dapp): Fix bridge page crash when connected to a Substrate account
  apps/tangle-dapp/src/features/bridge/hooks/useAssets.ts
Labels: needs review 🔎

#2882 fix(tangle-shared-ui): Fix Infinite Loading on Vault Table
  libs/tangle-shared-ui/src/data/restake/useRestakeAssetBalances.ts
  libs/tangle-shared-ui/src/types/error.ts
Labels: needs review 🔎

#2883 chore(tangle-dapp): Add switch wallet button for bridge
  apps/tangle-dapp/src/features/bridge/components/BridgeActionButton.tsx
  apps/tangle-dapp/src/features/bridge/containers/BridgeContainer.tsx
  libs/tangle-shared-ui/src/components/ConnectWalletButton/ConnectWalletButton.tsx
Labels: needs review 🔎

#2884 chore(tangle-dapp): Update Bridge Destination Address Input
  apps/tangle-dapp/src/features/bridge/containers/BridgeContainer.tsx
  libs/icons/src/WalletIcon.tsx
  libs/icons/src/index.ts
Labels: needs review 🔎

#2833 chore(tangle-dapp): Payouts v2
  apps/tangle-dapp/src/components/PayoutTable.tsx
  apps/tangle-dapp/src/components/PayoutsTable.tsx
  apps/tangle-dapp/src/components/nomination/NominationsTable.tsx
  apps/tangle-dapp/src/constants/index.ts
  apps/tangle-dapp/src/containers/NominationsPayoutsContainer.tsx
  apps/tangle-dapp/src/containers/NominatorStatsContainer.tsx
  apps/tangle-dapp/src/containers/PayoutAllTxModal.tsx
  apps/tangle-dapp/src/containers/PayoutTxContainer.tsx
  apps/tangle-dapp/src/containers/PayoutTxModal.tsx
  apps/tangle-dapp/src/data/nomination/useTotalPayoutRewards.ts
  apps/tangle-dapp/src/data/payouts/filterClaimedPayouts.ts
  apps/tangle-dapp/src/data/payouts/getPayouts.ts
  apps/tangle-dapp/src/data/payouts/useAllLedgers.ts
  apps/tangle-dapp/src/data/payouts/useClaimedRewards.ts
  apps/tangle-dapp/src/data/payouts/useEraTotalRewards.ts
  apps/tangle-dapp/src/data/payouts/useErasRewardsPoints.ts
  apps/tangle-dapp/src/data/payouts/useNominationsUnclaimedRewards.ts
  apps/tangle-dapp/src/data/payouts/usePayoutAllTx.ts
  apps/tangle-dapp/src/data/payouts/usePayoutStakersTx.ts
  apps/tangle-dapp/src/data/payouts/usePayouts.ts
  apps/tangle-dapp/src/data/payouts/usePayoutsAvailability.ts
  apps/tangle-dapp/src/data/payouts/usePayoutsStore.ts
  apps/tangle-dapp/src/data/types.ts
  apps/tangle-dapp/src/hooks/useClaimedEras.ts
  apps/tangle-dapp/src/hooks/useTxNotification.tsx
  apps/tangle-dapp/src/types/index.ts
  apps/tangle-dapp/src/utils/convertRewardPointsToReward.ts
  apps/tangle-dapp/src/utils/payout.ts
  apps/tangle-dapp/src/utils/sortByBn.ts
  libs/tangle-shared-ui/src/hooks/useLocalStorage.ts
  libs/tangle-shared-ui/src/types/index.ts
  libs/ui-components/src/components/InputField/InputField.tsx
Labels: needs review 🔎

#2894 fix(tangle-shared-ui): Fix Incorrect Vault Data Display
  apps/tangle-dapp/src/components/tables/Vaults/index.tsx
  libs/tangle-shared-ui/src/data/restake/useRestakeAssetIds.ts
  libs/tangle-shared-ui/src/data/restake/useRestakeAssets.ts
  libs/tangle-shared-ui/src/data/rewards/useVaultRewards.ts
  libs/tangle-shared-ui/src/data/rewards/useVaultsPotAccounts.ts
  libs/tangle-shared-ui/src/hooks/useApiRx.ts
  libs/tangle-shared-ui/src/hooks/usePromise.ts
  libs/tangle-shared-ui/src/types/error.ts
Labels: needs review 🔎

#2897 [RELEASE] Release Tangle dApp v0.1.1
  apps/tangle-dapp/CHANGELOG.md
  apps/tangle-dapp/package.json
  nx.json
Labels: needs review 🔎

#2899 refactor(repo): move graphql to common
  .gitignore
  apps/tangle-cloud/src/constants/swr.ts
  apps/tangle-dapp/src/data/points/useActivePoints.ts
  codegen.ts
  libs/tangle-shared-ui/src/types/index.ts
  libs/tangle-shared-ui/src/utils/executeGraphQL.ts
  tools/checkCodegen.js
Labels: needs review 🔎

#2900 chore(repo): bump `tangle-substrate-type` version
  libs/tangle-shared-ui/src/data/blueprints/utils/randPrimitiveService.ts
  libs/tangle-shared-ui/src/data/blueprints/utils/toPrimitiveBlueprint.ts
  libs/tangle-shared-ui/src/data/blueprints/utils/toPrimitiveService.ts
  libs/tangle-shared-ui/src/types/utils.ts
  libs/tangle-shared-ui/src/utils/polkadot/api.ts
  package.json
  yarn.lock
Labels: app: tangle-dapp

#2901 fix(tangle-dapp): Fix Incorrect Precompile Reward, Bump Types
  apps/tangle-dapp/src/constants/evmPrecompiles.ts
  libs/tangle-shared-ui/src/data/blueprints/utils/toPrimitiveBlueprint.ts
  libs/tangle-shared-ui/src/types/blueprint.ts
  package.json
  tools/checkCodegen.js
  yarn.lock
Labels: needs review 🔎

#2903 fix(libs/tangle-shared-ui): update the TVL calculation in use blueprint hook
  apps/tangle-cloud/src/pages/instances/AccountStatsCard.tsx
  apps/tangle-cloud/src/pages/instances/RegisteredBlueprints/RegisteredBlueprints.tsx
  apps/tangle-dapp/src/containers/restaking/OperatorsTable.tsx
  apps/tangle-dapp/src/containers/restaking/RestakeOverviewTabs.tsx
  apps/tangle-dapp/src/pages/restake/operators/[address]/OperatorInfoCard.tsx
  libs/tangle-shared-ui/src/data/blueprints/useBlueprintListing.ts
  libs/tangle-shared-ui/src/data/blueprints/useMonitoringBlueprints.ts
  libs/tangle-shared-ui/src/data/blueprints/utils/blueprintHelpers.ts
  libs/tangle-shared-ui/src/data/blueprints/utils/type.ts
  libs/tangle-shared-ui/src/data/restake/useBlueprintDetails.ts
  libs/tangle-shared-ui/src/data/restake/useOperatorConcentration.ts
  libs/tangle-shared-ui/src/data/restake/useOperatorTVL.ts
  libs/tangle-shared-ui/src/data/restake/useRestakeTVL.ts
Labels: needs review 🔎

#2910 feat(tangle-cloud): implement logic of pending service request table
  apps/tangle-cloud/src/pages/instances/BlueprintManagementSection.tsx
  apps/tangle-cloud/src/pages/instances/Instances/PendingInstanceTable.tsx
  apps/tangle-cloud/src/pages/instances/Instances/RunningInstanceTable.tsx
  apps/tangle-cloud/src/pages/instances/Instances/type.ts
  libs/tangle-shared-ui/src/data/blueprints/useBlueprintListing.ts
  libs/tangle-shared-ui/src/data/blueprints/useFakeMonitoringBlueprints.ts
  libs/tangle-shared-ui/src/data/blueprints/useMonitoringBlueprints.ts
  libs/tangle-shared-ui/src/data/blueprints/useOperatorBlueprints.ts
  libs/tangle-shared-ui/src/data/blueprints/usePendingServiceRequest.ts
  libs/tangle-shared-ui/src/data/blueprints/utils/blueprintHelpers.ts
  libs/tangle-shared-ui/src/data/blueprints/utils/randPrimitiveService.ts
  libs/tangle-shared-ui/src/data/blueprints/utils/toPrimitiveBlueprint.ts
  libs/tangle-shared-ui/src/data/blueprints/utils/toPrimitiveService.ts
  libs/tangle-shared-ui/src/data/blueprints/utils/type.ts
  libs/tangle-shared-ui/src/data/restake/useBlueprintDetails.ts
Labels: needs review 🔎, app: tangle-cloud ☁️

#2917 feat(tangle-cloud): implement logic update pending service request
  apps/tangle-cloud/src/components/ErrorMessage.tsx
  apps/tangle-cloud/src/constants/index.ts
  apps/tangle-cloud/src/data/base/BaseSubstrateApi.ts
  apps/tangle-cloud/src/data/blueprints/ServiceSubstrateApi.ts
  apps/tangle-cloud/src/data/blueprints/useServiceApi.ts
  apps/tangle-cloud/src/hooks/useTxNotification.tsx
  apps/tangle-cloud/src/pages/instances/BlueprintManagementSection.tsx
  apps/tangle-cloud/src/pages/instances/Instances/PendingInstanceTable.tsx
  apps/tangle-cloud/src/pages/instances/Instances/UpdateBlueprintModel/ApproveConfirmationModal.tsx
  apps/tangle-cloud/src/pages/instances/Instances/UpdateBlueprintModel/AssetCommitmentFormItem.tsx
  apps/tangle-cloud/src/pages/instances/Instances/UpdateBlueprintModel/RejectConfirmationModal.tsx
  apps/tangle-cloud/src/pages/instances/Instances/index.tsx
  apps/tangle-cloud/src/pages/instances/Instances/type.ts
  apps/tangle-cloud/src/pages/instances/page.tsx
  apps/tangle-cloud/src/stores/roleStore.tsx
  apps/tangle-cloud/src/types/index.ts
  apps/tangle-cloud/src/utils/validations/validateSecurityCommitment.ts
  apps/tangle-cloud/vite.config.ts
  apps/tangle-dapp/src/data/evm/useContractWrite.ts
  apps/tangle-dapp/src/data/payouts/usePayoutStakersTx.ts
  apps/tangle-dapp/src/data/restake/RestakeSubstrateApi.ts
  apps/tangle-dapp/src/data/restake/useNativeRestakeUnstakeCancelTx.ts
  apps/tangle-dapp/src/data/restake/useNativeRestakeUnstakeExecuteTx.ts
  apps/tangle-dapp/src/data/rewards/useClaimRewardsTx.ts
  apps/tangle-dapp/src/data/staking/useSetupNominatorTx.ts
  apps/tangle-dapp/src/data/staking/useUpdateNominatorTx.ts
  apps/tangle-dapp/src/hooks/useSubstrateTx.ts
  apps/tangle-dapp/src/hooks/useTxNotification.tsx
  libs/tangle-shared-ui/src/data/blueprints/usePendingServiceRequest.ts
  libs/tangle-shared-ui/src/data/blueprints/utils/blueprintHelpers.ts
  libs/tangle-shared-ui/src/data/blueprints/utils/toPrimitiveService.ts
  libs/tangle-shared-ui/src/data/blueprints/utils/type.ts
  libs/tangle-shared-ui/src/hooks/useAssetsMetadata.ts
  libs/tangle-shared-ui/src/hooks/useTxNotification.tsx
  libs/tangle-shared-ui/src/types/restake.ts
  libs/tangle-shared-ui/src/utils/extractErrorFromStatus.ts
  libs/tangle-shared-ui/src/utils/optimizeTxBatch.ts
Labels: needs review 🔎, app: tangle-cloud ☁️

#2919 refactor(repo): move evmPrecompiles to common
  apps/tangle-dapp/src/data/balances/useTransferTx.ts
  apps/tangle-dapp/src/data/liquidStaking/tangle/useLsCreatePoolTx.ts
  apps/tangle-dapp/src/data/liquidStaking/tangle/useLsPoolJoinTx.ts
  apps/tangle-dapp/src/data/liquidStaking/tangle/useLsPoolSetStateTx.ts
  apps/tangle-dapp/src/data/liquidStaking/tangle/useLsPoolUnbondTx.ts
  apps/tangle-dapp/src/data/liquidStaking/tangle/useLsPoolUpdateNominationsTx.ts
  apps/tangle-dapp/src/data/liquidStaking/tangle/useLsUpdateRolesTx.ts
  apps/tangle-dapp/src/data/liquidStaking/useLsWithdrawUnbondedTx.ts
  apps/tangle-dapp/src/data/payouts/usePayoutStakersTx.ts
  apps/tangle-dapp/src/data/restake/RestakeEvmApi.ts
  apps/tangle-dapp/src/data/restake/useNativeRestakeTx.ts
  apps/tangle-dapp/src/data/restake/useNativeRestakeUnstakeCancelTx.ts
  apps/tangle-dapp/src/data/restake/useNativeRestakeUnstakeExecuteTx.ts
  apps/tangle-dapp/src/data/restake/useNativeRestakeUnstakeTx.ts
  apps/tangle-dapp/src/data/rewards/useClaimRewardsTx.ts
  apps/tangle-dapp/src/data/staking/useBondExtraTx.ts
  apps/tangle-dapp/src/data/staking/useChillTx.ts
  apps/tangle-dapp/src/data/staking/useNominateTx.ts
  apps/tangle-dapp/src/data/staking/useRebondTx.ts
  apps/tangle-dapp/src/data/staking/useSetPayeeTx.ts
  apps/tangle-dapp/src/data/staking/useSetupNominatorTx.ts
  apps/tangle-dapp/src/data/staking/useUnbondTx.ts
  apps/tangle-dapp/src/data/staking/useUpdateNominatorTx.ts
  apps/tangle-dapp/src/data/staking/useWithdrawUnbondedTx.ts
  apps/tangle-dapp/src/data/vesting/useVestTx.ts
  apps/tangle-dapp/src/hooks/useAgnosticTx.ts
  apps/tangle-dapp/src/hooks/useEvmCallPermitNonce.ts
  apps/tangle-dapp/src/hooks/useEvmGasEstimate.ts
  apps/tangle-dapp/src/hooks/useEvmPrecompileCall.ts
  apps/tangle-dapp/src/hooks/useEvmPrecompileFee.ts
  apps/tangle-dapp/src/hooks/useEvmTxRelayer.ts
  apps/tangle-dapp/src/utils/staking/createEvmBatchCall.ts
  libs/icons/src/useDynamicSVGImport.tsx
  libs/tangle-shared-ui/src/abi/balancesErc20.ts
  libs/tangle-shared-ui/src/abi/batch.ts
  libs/tangle-shared-ui/src/abi/callPermit.ts
  libs/tangle-shared-ui/src/abi/lst.ts
  libs/tangle-shared-ui/src/abi/restaking.ts
  libs/tangle-shared-ui/src/abi/rewards.ts
  libs/tangle-shared-ui/src/abi/services.ts
  libs/tangle-shared-ui/src/abi/staking.ts
  libs/tangle-shared-ui/src/abi/vesting.ts
  libs/tangle-shared-ui/src/constants/evmPrecompiles.ts
Labels: needs review 🔎

#2922 fix(tangle-cloud): update services hook to use common hook
  apps/tangle-cloud/src/data/blueprints/ServiceSubstrateApi.ts
  apps/tangle-cloud/src/data/blueprints/useServiceApi.ts
  apps/tangle-cloud/src/data/services/useServicesApproveTx.ts
  apps/tangle-cloud/src/data/services/useServicesRejectTx.ts
  apps/tangle-cloud/src/hooks/useTxNotification.tsx
  apps/tangle-cloud/src/pages/instances/Instances/PendingInstanceTable.tsx
  apps/tangle-cloud/src/pages/instances/Instances/RunningInstanceTable.tsx
  apps/tangle-cloud/src/pages/instances/Instances/StoppedInstanceTable.tsx
  apps/tangle-cloud/src/pages/instances/Instances/UpdateBlueprintModel/ApproveConfirmationModal.tsx
  apps/tangle-cloud/src/pages/instances/Instances/UpdateBlueprintModel/RejectConfirmationModal.tsx
  apps/tangle-cloud/src/pages/instances/RegisteredBlueprints/RegisteredBlueprints.tsx
  libs/ui-components/src/components/Modal/ModalBody.tsx
Labels: needs review 🔎, app: tangle-cloud ☁️
